### ISSUE TITLE
SECURITY: Windows Installer is not signed

### ISSUE THREAD

**Issue by ericlaw1979** [github/git-lfs#1003]
Please apply an authenticode signature to https://github.com/github/git-lfs/releases/download/v1.1.1/git-lfs-windows-1.1.1.exe to avoid problems with SmartScreen/AV and the risk of compromise.

**Comment by shiftkey** [comment]
The team is in the process of obtaining new certificates - see the [v1.1.1](https://github.com/github/git-lfs/releases/tag/v1.1.1) release notes for more info.

**Comment by blackzackm** [comment]
@blackzackm +1

**Comment by blackzackm** [comment]
⬇

**Comment by technoweenie** [comment]
This was fixed in the v1.1.2 release. Please report back with details if you're still having problems.
