### ISSUE TITLE
Error on upload attempt to GitLab.

### ISSUE THREAD

**Issue by igormq** [github/git-lfs#1010]
Hi There,

I'm using GIT LFS v.1.1.1, GIT 2.7.1 on OS X El Capitain and my origin repo is the GITLAB. When I tried to push to remote I got the follow error:
```
codigo git:(master) ✗ GIT_TRACE=1 git lfs push origin master
20:03:52.515030 git.c:561               trace: exec: 'git-lfs' 'push' 'origin' 'master'
20:03:52.517440 run-command.c:343       trace: run_command: 'git-lfs' 'push' 'origin' 'master'
trace git-lfs: Upload refs origin to remote [master]
trace git-lfs: run_command: git rev-list --objects master --not --remotes=origin
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: run_command: 'git' config -l
trace git-lfs: tq: starting 3 transfer workers
trace git-lfs: tq: running as batched queue, batch size of 100
... some prepare uploads
trace git-lfs: tq: sending batch of size 100
... some prepare uploads
trace git-lfs: ssh: git@gitlab.com git-lfs-authenticate igormq/projeto-final-code-ufrj.git upload 
trace git-lfs: ssh: upload attempted with git@gitlab.com.  Error: exit status 1
trace git-lfs: tq: sending batch of size 76
trace git-lfs: ssh: git@gitlab.com git-lfs-authenticate igormq/projeto-final-code-ufrj.git upload 
trace git-lfs: ssh: upload attempted with git@gitlab.com.  Error: exit status 1
Git LFS: (0 of 176 files) 0 B / 77.88 MB                                                                                                                                            
exit status 1
exit status 1

```

Could anyone help me to understand what is happening?

Best regards,
Igor.

**Comment by technoweenie** [comment]
Your ssh command is erroring. Try running `git@gitlab.com git-lfs-authenticate igormq/projeto-final-code-ufrj.git upload`. It should spit out some json to STDOUT.

**Comment by ramccor** [comment]
It is an interaction between GIT-LFS 1.1.1 and GitLab, downgrading to git-lfs 1.1.0 works around the issue for now.

**Comment by moimael** [comment]
Same issue with 1.1.1 and Gitlab downgrading works for now.

**Comment by igormq** [comment]
I've updated to git-lfs to 1.1.1 because there was a bug on  MAC (see #920), so I can't downgrading to git-lfs 1.1.0.

**Comment by technoweenie** [comment]
If someone can run `ssh git@gitlab.com git-lfs-authenticate igormq/projeto-final-code-ufrj.git` (or whatever your repo name is), that would help me out.

**Comment by lorenz** [comment]
GitLab doesn't have `git-lfs-authenticate` yet, this is being tracked [here](https://gitlab.com/gitlab-org/gitlab-ce/issues/3589). Output is therefore `GitLab: Disallowed command`.

**Comment by igormq** [comment]
Thank you @lorenz  and @technoweenie. I think i'll have to wait until the GITLAB team solve this compatibility issue. :(

**Comment by technoweenie** [comment]
@igormq Have you tried using an HTTPS remote, instead of git?

**Comment by igormq** [comment]
@technoweenie I've tried and it worked.
