### ISSUE TITLE
Error when trying to push commit with delete file

### ISSUE THREAD

**Issue by vtchalakov** [github/git-lfs#1013]
I was able to get git-lfs running on my private git repo. And I was able to push a 300 or so MB .psd file without issue. Next I tried deleting the file locally, and pushing that delete, but now i'm getting the following error:

\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n

Any thoughts on what to do? I already deleted my HEAD branch to fix the fact that git lfs didn't know what to do with the ref.

**Comment by technoweenie** [comment]
> This repository is configured for Git LFS but 'git-lfs' was not found on your path.

Make sure that `git-lfs` is in the `$PATH` for whatever user is running the git command. You can see what script is running by looking at the `.git/hooks/pre-push` file.

**Comment by vtchalakov** [comment]
So seems if I do "git push origin master" through the terminal it will run properly, however running through sourcetree's UI (clicking push button) doesn't work. Seems to be a sourcetree issue.

**Comment by chocolim** [comment]
I delete .git/hooks/pre-push in my local repository and it worked for me

**Comment by hovox** [comment]
I'm getting this error when I'm running `git push` command in ruby script. Running `git push` from terminal works as expected.

**Comment by Raj-Accedo** [comment]
Thanks @chocolim It worked for me also
