### ISSUE TITLE
General comments and questions about git-media spec

### ISSUE THREAD

**Issue by mhagger** [github/git-lfs#102]
I made a bunch of notes while reading the git-media documentation, and I'm not really sure what to do with them. So I'm throwing them in this issue.

Some of these are general questions that were unanswered by the documentation. It would be nice if the docs were expanded to cover these topics.

Some are questions about the design, including points where I wonder if you've thought of this detail or the other. Probably most of these can just be waived away, but others might give you ideas for work that is needed.

I hope this is useful!

* Can `git media path add` and `git media path remove` handle fully general `.gitattributes` files?  Can they handle lines that have other (perhaps unrelated) attributes on them?

* What if `.gitattributes` files are present at lower levels in the tree?  Can `git media path add` and `git media path remove` still handle the situation somehow?

* What `.gitattributes` files are used?  Are they the ones in the working copy, or in the index, or HEAD, or what? I believe that this is determined by Git and not by `git-media`, but the answer could affect usability.

* How does `git media init` work? I imagine it adds configuration to the user's global Git config, because the docs show it being used before `git init` or `git clone`. Is this polite? E.g., will there be cases where the user wants different git-media configurations for different repositories?

* In `docs/spec.md`, section "The Server", the precedence of the three places where the Git Media server is sought should be specified explicitly (I think the order is currently incorrect).

* In the same section, the sample Git config file has a key `media.endpoint`. Should that be `media.url`?  (Maybe that is old nomenclature that has since been changed?) The term "endpoint" also appears in the text.

* It seems to me that the layout of `git-media`-related data in the local repository (i.e., the data under `$GIT_DIR`) needs to be documented to enable other Git implementations and tools to work with the data correctly.

* Is it always guaranteed that the media files are pushed to the server before commits that use them? Are media files only pushed if they are used in the specific commits being pushed, or are all media blobs pushed even if they are used in other commits that haven't been pushed yet? How is it determined whether a media blob is already present on the server? (Is this verified every time a commit referencing the asset is pushed to the server?) What happens if the server URI is changed? Is there a way to migrate the media assets to a different media server?

* Is it possible to un-media-ize a file in a later commit without confusing earlier history?

* Is it possible to discard media files from the local repo to save space (e.g., I only want the media assets associated with the current revision)? Is there a tool to help with this?

* Is it possible to GC media files from the remote media server if, for example, the commits referencing them have been discarded?  Would other clients handle this situation gracefully?

* Is there a tool analogous to `git cat-file blob` to access the contents of a media-ized file (downloading it if necessary) without having to check out the commit containing it? (I don't think that `git cat-file` respects smudge filters but I might be wrong.)

* Is there any provision for sharding the local media asset cache directory? (If the number of assets becomes large, the performance might suffer from too many files in a single directory.)

* Is there a reference implementation of a git media server?

* Is there provision to compress the media files somehow (e.g., on disk and on the wire), or are they assumed to be incompressible? Can they be stored as deltas somehow? (Some large file formats delta well.)

* Regarding the API: Is it standard practice to use the `Accept:` header to distinguish between fetching the blob and the JSON metadata?  (I would have expected that distinction to be encoded in the URI.)

**Comment by gitfoxi** [comment]
> There's no way to migrate assets, but that would be cool.

What happens when you fork a repository? Do the forks share a git-media path? Or does each fork needs to maintain a copy of all media files separately on the server? Can that work with pull requests?

**Comment by technoweenie** [comment]
@gitfoxi Git LFS itself doesn't really know about forks or how GitHub (or whatever Git host you're using) works.  However, GitHub's implementation of the Git LFS API shares objects across a GitHub repository network. Forking and pull requesting should work great :)

Also, this is a really old discussion about an ancient version of Git LFS.  I'm closing this issue, but you're very welcome to open a new one if you want to discuss further.
