### ISSUE TITLE
What happens to orphan lfs objects?

### ISSUE THREAD

**Issue by kilianc** [github/git-lfs#1020]
I had to contact support this week because we transferred a repo between organizations and all git LFS refs where lost, to be precise github ui wasn't even aware they were lfs references. This got me to think: What happens to orphaned objects? When you delete a branch or amend a commit for example? Do we delete them from storage? do we get back our storage space available?

Thanks

**Comment by technoweenie** [comment]
The OSS Git LFS client has nothing to do with this. GitHub _should_ be transferring your LFS objects. Though, it may take some time depending on how many and how large they are. Can you contact me at https://github.com/contact with the name of the old and new repository, so I can look into it?

**Comment by kilianc** [comment]
@technicalpickles I did already, someone answered my ticket. Where is it a good place to ask these questions?

**Comment by technoweenie** [comment]
Ask the owner of whatever LFS server you're using. https://github.com/contact for GitHub.

There's nothing in the Git LFS client concerning this. My recommendation is that servers should clean up the data if they go unreferenced, while [respecting git's `gc.pruneExpire` setting on the server](https://git-scm.com/docs/git-gc). Though, this requires a full scan of the repository history.

**Comment by kilianc** [comment]
@technoweenie so there is no specification on how to handle PR / Merge / Transfer / GC and it's implementation specific. Thanks.
