### ISSUE TITLE
Build fails with go 1.6

### ISSUE THREAD

**Issue by jacobmischka** [github/git-lfs#1021]
Running `./scripts/bootstrap` fails to build for me on x64 Arch, no `bin` directory is created afterward. 

Output: https://gist.github.com/jacobmischka/0bd07fc66bfded7cd1e2

`go version go1.6 linux/amd64`

**Comment by technoweenie** [comment]
Oh, they enabled the vendor stuff in 1.6. You'll have to use go 1.5.3, or use one of the precompiled ones in the release.

**Comment by rubyist** [comment]
FWIW, you can build with 1.6 if you set `GO15VENDOREXPERIMENT=0` to turn off the vendoring stuff.

**Comment by jacobmischka** [comment]
Okay, that works thank you. Will you be planning on updating the package to work with 1.6 by default soon, or should I expect to need to use that env variable for the foreseeable future?

**Comment by rubyist** [comment]
I think nut hardcodes `vendor` so we'd probably have to move away from that (or it'd have to change). We could also just set the var in the bootstrap script, though it might resurface again with 1.7 if they drop the env var entirely (I thought I saw that somewhere, but I could be mistaken).

**Comment by jacobmischka** [comment]
Okay, well this works for now, thanks again!

**Comment by technoweenie** [comment]
Builds should work on 1.6 without specifying any env vars now: #1025
