### ISSUE TITLE
How to force git lfs authentication

### ISSUE THREAD

**Issue by Mais316** [github/git-lfs#1022]
We have found that any one can push to the lfs server 
is there any way to force authentication so its not none as below

[user@test]$ git lfs env
git-lfs/1.1.1 (GitHub; linux amd64; go 1.5.3; git 7de0397)
git version 2.7.0

Endpoint=http://ip_address:port (auth=none)
LocalWorkingDir=

Kinldy help

**Comment by technoweenie** [comment]
If you configure your LFS server to require authentication, it should return a 401 response, causing the LFS client to retry with authentication. From then on, it should say `auth=basic`.

**Comment by Mais316** [comment]
to be honest i dont know how to configure server to require auth

as implementation i used said that it doesnt support authentication yet

https://github.com/artemkin/git-lfs-server/

at server
./lfs_server.sh -s ip address -p 1234 -verbose
2016-02-12 19:18:47.508593Z Listening for HTTP on ip_address:1234

I cant find Enterprise git lfs server configuration that support authentication

**Comment by technoweenie** [comment]
You'll have to ask in that repository. This repository is for the Git LFS client only.

**Comment by Mais316** [comment]
thanks :)
