### ISSUE TITLE
git push repeatedly asks for password despite git credential set...

### ISSUE THREAD

**Issue by perrette** [github/git-lfs#1031]
Hi !

I am aware of issues #203 and #858 , and it did help with `git-pull`, but unfortunately the problem remains when pushing:

```
$ git config -l | grep credential
credential.helper=cache --timeout=3600
$ git remote -v
origin git@gitlab.com:greenrise/sicopolis-rembo.git (fetch)
origin git@gitlab.com:greenrise/sicopolis-rembo.git (push)
$ git pull
Already up-to-date.
$ git push
Username for 'https://gitlab.com': xxxxxxxxxxxxx
Password for 'https://xxxxxxxxxxxxx@gitlab.com':
Username for 'https://gitlab.com': xxxxxxxxxxxxx
Password for 'https://xxxxxxxxxxxxx@gitlab.com':
Username for 'https://gitlab.com': ^C

Exiting because of "interrupt" signal.
```

Any idea what may be causing that / workaround?

**Comment by perrette** [comment]
PS: I am using Ubuntu LTS 14.04, version: `git-lfs/1.1.0 (GitHub; linux amd64; go 1.5.1; git 258acf1)`

**Comment by technoweenie** [comment]
Double check that your password is correct. You can run `GIT_CURL_VERBOSE=1 git push` to see the responses from the server. If it's returning 401 or 403, there's nothing to be done in the client.

**Comment by perrette** [comment]
... don't know what to say, beyond time to go to bed here. That was as simple as that. Thanks.
