### ISSUE TITLE
 rpm package git-lfs-1.1.0 source code.

### ISSUE THREAD

**Issue by unixnewbie** [github/git-lfs#1032]
Hello,

I am trying to rpm package git-lfs-1.1.0 using a custom SPEC file .  I get the following error during the build. I don’t know anything about go. Could you please help ?

Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.F57yah
+ umask 022
+ cd /home/rpmuser/rpmbuild/BUILD
+ cd git-lfs-1.1.0
+ GOARCH=amd64
++ pwd
+ GOPATH=/home/rpmuser/rpmbuild/BUILD/git-lfs-1.1.0
+ ./script/bootstrap
Using go1.4.2
# _/home/rpmuser/rpmbuild/BUILD/git-lfs-1.1.0
./git-lfs.go:23: cannot use lfs.ClearTempObjects (type func() error) as type func() in argument to once.Do
./git-lfs.go:36: cannot use lfs.ClearTempObjects (type func() error) as type func() in argument to once.Do

2016/02/24 09:10:31 exit status 2
exit status 1
error: Bad exit status from /var/tmp/rpm-tmp.F57yah (%build)

Thanks

**Comment by technoweenie** [comment]
What version of Go are you compiling with? It's possible it may require Go 1.4 or even 1.5.

**Comment by javabrett** [comment]
> Using go1.4.2

Try with Go 1.5, it is the documented minimum.

Suggest close. :no_entry_sign:

**Comment by ttaylorr** [comment]
Please try again with Go 1.5, or Go 1.6 😄
