### ISSUE TITLE
git lfs push fails

### ISSUE THREAD

**Issue by akhyansh13** [github/git-lfs#1035]
I installed and set up git-lfs. Tried pushing and it kept throwing a 301 Permanently moved error. Then I changed the remote url to 
https://github.com/akhyansh13/quablsource/
following https://github.com/github/git-lfs/issues/697#issuecomment-145598782. That didn't work, throws this error now:

Akhyanshs-MacBook-Pro:quablsource Akhyansh$ git push --set-upstream origin master
Git LFS: (0 of 1 files) 0 B / 507.66 MB                                        
Not Found
Docs: https://github.com/contact
error: failed to push some refs to 'https://github.com/akhyansh13/quablsource/'

**Comment by technoweenie** [comment]
Make sure you have a credential helper setup with the correct password. https://help.github.com/articles/caching-your-github-password-in-git/

You can also run the push command with either `GIT_TRACE=1` or `GIT_CURL_VERBOSE=1` to see what's returning 404. But I'm pretty sure it's an auth error.
