### ISSUE TITLE
Avoid prompt for password in https authentication

### ISSUE THREAD

**Issue by panjandrum** [github/git-lfs#1041]
Hi,

I use git-lfs 1.1.1 and as a server JFROG Artifactory 4.2.

Because that Artifactory version is not supporting SSH authentication, so we stack with https based one.

My question is how can I avoid asking for password (even first time), because I would like to use it from Jenkins.
I already tried:
~/.gitconfig:
```
[credential "https://example.com"]
    username = jondoe
    password = 123456
```
~/.netrc:
`machine https://example.com username jondoe password 123456`

Obviously I would like to avoid hardcoded username and password in url in .lfsconfig

I thought netrc support was already implemented in git-lfs.

Thanks in advance,
panjandrum

**Comment by technoweenie** [comment]
netrc support is nearly ready (#715). I plan on taking it across the finish line in Git LFS v1.2.

Until then, you could try storing it in `~/.git-credentials`: https://git-scm.com/docs/git-credential-store

**Comment by panjandrum** [comment]
Thanks! Works for me :)

I have one other question. Is git-lfs fully support SSH based authentication?

**Comment by technoweenie** [comment]
Sort of. It can execute a custom SSH command that the server needs to implement, which essentially returns a temporary token for the LFS HTTPS API.
