### ISSUE TITLE
Clone timeouts

### ISSUE THREAD

**Issue by panamafrancis** [github/git-lfs#1049]
Each time i try to clone our LFS repository from github it fails. 

I've seen a number of reasons over the past weeks, but they include:

TLS handshake timeout
Get https://... "EOF"
or just a random "smudge error"

Now if i do a clone from a machine nearer to your east coast amazon instances things work OK, so i'm assuming the fix for this you upgrading the LFS infrastructure to serve a global community or Git-LFS to support ssh as it's better at holding long-lived connections. 

We're giving up.

I really don't think it's acceptable to have released git lfs in it's current state. It's some of the worst software i've ever used, if anything you should rebrand it, I don't think the git brand should be associated with LFS in its current form.

**Comment by technoweenie** [comment]
Thanks for the feedback.
