### ISSUE TITLE
After git lfs pull all tracked files are listed as "modified"

### ISSUE THREAD

**Issue by englercj** [github/git-lfs#1062]
I have an existing repository that I converted to lfs with BFG. The repository now properly contains all the pointers.

When I clone this repository, git lfs does not checkout the actual binary files but instead leaves the pointers on disk. Running `git lfs pull` pulls the binary files and replaces the pointers but leaves me with a giant "modified" file list in `git status`. Committing any of these "modified" binary files and pushing will push the actual binary files into my repository. No messages from git-lfs.

I have run (a few times now) `git lfs install` in the working directory. Both before and after the pull, in multiple different attempts to get it working.

Additional info:

```
$ git lfs track
Listing tracked paths
    *.{gif,jpg,png,ogg,wav,mp3} (.gitattributes)
```

```
$ git lfs env
git-lfs/1.1.2 (GitHub; windows amd64; go 1.6; git bf6a6c9)
git version 2.5.2.windows.2

Endpoint=https://github.com/englercj/lttp-phaser.git/info/lfs (auth=none)
  SSH=git@github.com:englercj/lttp-phaser.git
LocalWorkingDir=C:\Users\Chad\repos\lttp-phaser
LocalGitDir=C:\Users\Chad\repos\lttp-phaser\.git
LocalGitStorageDir=C:\Users\Chad\repos\lttp-phaser\.git
LocalMediaDir=C:\Users\Chad\repos\lttp-phaser\.git\lfs\objects
TempDir=C:\Users\Chad\repos\lttp-phaser\.git\lfs\tmp
ConcurrentTransfers=3
BatchTransfer=true
git config filter.lfs.smudge = "git-lfs smudge %f"
git config filter.lfs.clean = "git-lfs clean %f"
```

```
$ git config --global -l
user.name=Chad Engler
user.email=englercj@live.com
push.default=matching
core.excludesfile=~/.gitignore
core.autocrlf=false
core.eol=lf
color.ui=auto
alias.co=checkout
alias.last=log -1
alias.lo=log --stat
alias.lm=log --stat --author=englercj@live.com --abbrev-commit
alias.ls=status
alias.lol=log --graph --decorate --pretty=oneline --abbrev-commit --date=relative --format=format:'%C(red)%h%C(reset) - %C(green)(%cr)%C(reset) %s - %C(dim cyan)%an%C(reset) %C(auto)%d%C(reset)'
alias.sha1=rev-parse HEAD
alias.sha=rev-parse HEAD
alias.ha=rev-parse --short HEAD
filter.lfs.clean=git-lfs clean %f
filter.lfs.smudge=git-lfs smudge %f
filter.lfs.required=true
```

I'm not sure what else to try, it seems like my filters are not running at all either during checkout or push. Any ideas?

**Comment by technoweenie** [comment]
> *.{gif,jpg,png,ogg,wav,mp3}

I don't think Git understands this.  There's more info here: https://github.com/rtyley/bfg-repo-cleaner/issues/116

Basically, BFG is writing your `.gitattributes` file incorrectly, so some things may not be stored in LFS properly.

**Comment by englercj** [comment]
That was the issue, after changing my attributes file to:

```
$ git lfs track
Listing tracked paths
    *.gif (.gitattributes)
    *.jpg (.gitattributes)
    *.png (.gitattributes)
    *.ogg (.gitattributes)
    *.wav (.gitattributes)
    *.mp3 (.gitattributes)
```

It works as expected. Thanks for the heads up, not sure how I didn't find that in all of my searching.
