### ISSUE TITLE
Git LFS quota release

### ISSUE THREAD

**Issue by mnonnenm** [github/git-lfs#1065]
Hello, 

I have an issue with the lfs storage quota. More specifically, I would like to understand the amount of data that lfs thinks I have currently stored on my repository, and what I need to do to force lfs to update this number.

I have set up a repository for sharing both data and results of a project.
(https://github.com/mackelab/critical_retina.git)
Initially, I had just uploaded a lot of files until the quota limit (hitting > 4 GB) stopped me. My bad. To be able to still work with the repository and get less important files back off the repo, my team account paid for a quota extension. With this, I could work on the repository again and use "git filter branch" to remove many excess files. The (single-branch) repository upon a new clone now is sized at < 1 GB (741.4 MB), and running "git lfs ls-files" on the repo confirms that none of the files I deleted using "git filter branch" are still tracked. Yet the git LFS quota shown to my team account is still > 4 GB. 

Is there something specific I have to do to free up the quota, or can I expect the lfs garbage collection to release it automatically at some point (as suggested in http://stackoverflow.com/questions/34579211/how-to-delete-a-file-tracked-by-git-lfs-and-release-the-storage-quota)? The "git filter branch" command had been run 5 weeks ago, so I'm starting to believe that I was too quick to rely on any form of garbage collection after what I had done so far. We would like to eventually cancel the extended quota agreement, now we should actually be back in the regime of free storage.

Regards, Marcel Nonnenmacher

**Comment by technoweenie** [comment]
Hi, you can contact us at https://github.com/contact, as this issue doesn't have anything to do with the Git LFS open source code.
