### ISSUE TITLE
Unable to sync commit with LFS files

### ISSUE THREAD

**Issue by mponce1** [github/git-lfs#1068]
OS: Windows 7/10

1) Created new repository
2) adding LFS filters to git attributes and synced commit
3) Commit LFS files locally
4) Attempt Sync

Received failed to sync error message. When trying to push through git shell, I received these error messages: 
>C:\Users\MIguel Ponce\Documents\GitHub\LFS-Filterless [master]> git push
>Di.png is an LFS pointer to af8e81e3089ad082f171266b4de154bd398de4df0d41c90dc592
>bb12ef5723a6, which does not exist in .git/lfs/objects.
>
>Run 'git lfs fsck' to verify Git LFS objects.
>error: failed to push some refs to 'https://github.com/MichaelClickalot/LFS-Filt
>erless.git'
>C:\Users\MIguel Ponce\Documents\GitHub\LFS-Filterless [master]> git lfs fsck
>Object Di.png (af8e81e3089ad082f171266b4de154bd398de4df0d41c90dc592bb12ef5723a6)
>could not be checked: The system cannot find the file specified.
>Object Diamonds.png (527757d3abf20082b55e9f7173cd24b4ebabfdbe84592c91658cd60a690
>27f62) could not be checked: The system cannot find the file specified.
>C:\Users\MIguel Ponce\Documents\GitHub\LFS-Filterless [master]>

![screen shot 2016-03-10 at 1 44 45 pm](https://cloud.githubusercontent.com/assets/6272408/13686323/178f0700-e6ca-11e5-9f31-bb9ba489eee3.png)

Log file: 
[TheLog.txt](https://github.com/github/git-lfs/files/168076/TheLog.txt)

Found a related issue here: #564

**Comment by technoweenie** [comment]
What commands did you run to create the repo? Here's the error message: 

> Di.png is an LFS pointer to af8e81e3089ad082f171266b4de154bd398de4df0d41c90dc592
bb12ef5723a6, which does not exist in .git/lfs/objects.

Assuming `.gitattributes` is setup, those files should be created after running `git add` on the file.

**Comment by mponce1** [comment]
I created the repo through the desktop client

**Comment by technoweenie** [comment]
What desktop client? What LFS filters did you add? What files were committed?

**Comment by mponce1** [comment]
Windows desktop client (tried with 2 different repositories in Windows 7 and Windows 10, on both the bump-lfs and production builds) 

LFS filters: *.png, *.txt
files: ![dice](https://cloud.githubusercontent.com/assets/6272408/13686905/1cff714a-e6cd-11e5-97b0-77eb54a944d6.png)
![diamonds](https://cloud.githubusercontent.com/assets/6272408/13686904/1cff589a-e6cd-11e5-9258-455f5ae330f8.png)

(text files are over 100mb in size, let me know if you want me to attach as well)

**Comment by mponce1** [comment]
Not sure if this is relevant, but this was working up until I switched from bump-lfs to production build, then stopped working thereafter.

**Comment by technoweenie** [comment]
Well, here's how it's supposed to work in Git LFS. Maybe this will help you troubleshoot in Desktop:

```bash
$ git init
Initialized empty Git repository in /Users/rick/p/foo/.git/
$ git lfs track "*.png"
Tracking *.png
$ git lfs track "*.txt"
Tracking *.txt
$ echo "png" > pseudo.png
$ echo "txt" > real.txt
$ tree .git/lfs/objects
.git/lfs/objects
└── logs

1 directory, 0 files
$ gs
## Initial commit on master
?? .gitattributes
?? pseudo.png
?? real.txt
```

At this point, the repo has been initialized. The patterns are in .gitattributes. The png and txt files are in the repo, but are still untracked. Nothing is in `.git/lfs/objects`.

```bash
$ git add .
$ tree .git/lfs/objects
.git/lfs/objects
├── 33
│   └── d8
│       └── 33d8344a7135c42aa3876706b908f95b702d83ff53e05e4aaff17c07bf67a98e
├── 7c
│   └── 4c
│       └── 7c4c231187cd4b75677c312faa7787da874bdbb7d71e1c9dc0619f3e27a53940
└── logs

5 directories, 2 files
```

Files are staged, but not committed. The files are now in `.git/lfs/objects`.

```bash
$ git commit -m "booya"
[master (root-commit) 06f96ed] booya
 3 files changed, 8 insertions(+)
 create mode 100644 .gitattributes
 create mode 100644 pseudo.png
 create mode 100644 real.txt
$ git show
commit 06f96edf35eed8fcd7bf75f343bf4caa22477c8b
Author: risk danger olson <technoweenie@gmail.com>
Date:   Thu Mar 10 15:42:18 2016 -0700

    booya

diff --git a/.gitattributes b/.gitattributes
new file mode 100644
index 0000000..7da20c6
--- /dev/null
+++ b/.gitattributes
@@ -0,0 +1,2 @@
+*.png filter=lfs diff=lfs merge=lfs -text
+*.txt filter=lfs diff=lfs merge=lfs -text
diff --git a/pseudo.png b/pseudo.png
new file mode 100644
index 0000000..84f2bee
--- /dev/null
+++ b/pseudo.png
@@ -0,0 +1,3 @@
+version https://git-lfs.github.com/spec/v1
+oid sha256:33d8344a7135c42aa3876706b908f95b702d83ff53e05e4aaff17c07bf67a98e
+size 4
diff --git a/real.txt b/real.txt
new file mode 100644
index 0000000..739557c
--- /dev/null
+++ b/real.txt
@@ -0,0 +1,3 @@
+version https://git-lfs.github.com/spec/v1
+oid sha256:7c4c231187cd4b75677c312faa7787da874bdbb7d71e1c9dc0619f3e27a53940
+size 4
```

The commit shows the LFS pointers for the png and txt files ^

It looks like this part isn't happening for some reason.

**Comment by shana** [comment]
@technoweenie Just fyi, the bump-lfs version of the Desktop app is a branch that includes git-lfs 1.1.2. Production includes git-lfs 1.1.0. From what I understand about this, it looks like if you ever use 1.1.2 and then for some reason use 1.1.0 on the same repo, it permanently corrupts it so that it stops working with any version. If this is indeed the case, then it's kinda bad because if for some reason we have to rollback a release or someone accidentally has the wrong git-lfs on the path, it's game over :-P

**Comment by mponce1** [comment]
Based on discussion with @shana, it's possible the switching between the git lfs versions (1.1.0 to 1.1.2, and vice versa several times) caused it to become permanently corrupt.

**Comment by technoweenie** [comment]
Can I get a detailed step by step reproduction? Nothing in the original steps mentioned that the LFS version was being rolled back anywhere.

**Comment by mponce1** [comment]
The problem started as a continuation of the issue mentioned on #5820. 
Prerequisite: Windows client installed with build speakeasy/bump-lfs.

1) create a repository and publish
2) add LFS filters to git attributes, and commit
3) push files through git LFS
4) switch to production build
5) create a subfolder within the repository, and copy the files from step 3 into it
6) create a commit and push

That's essentially when the problem started.

**Comment by technoweenie** [comment]
Keep in mind this is an OSS repo, and none of us work on Desktop. So the best I can do is try to replicate this with the command line, under the assumption Desktop is not doing anything special, and the system has the default git lfs config.

## 1) create a repository and publish

```bash
$ git init
Initialized empty Git repository in /Users/rick/p/foo/.git/
$ git remote add origin https://github.com/technoweenie/musical-octo-meme
$ git push origin master
error: src refspec master does not match any.
error: failed to push some refs to 'https://github.com/technoweenie/musical-octo-meme'
```

Not sure how desktop handles empty repos... 

## 2) add LFS filters to git attributes, and commit

First, I created an empty directory with the v1.1.2 and v1.1.0 LFS binaries. Here's the current lfs env:

```bash
$ git config filter.lfs.smudge "/Users/rick/p/foo/git-lfs-1.1.2/git-lfs smudge %f"
$ git config filter.lfs.clean "/Users/rick/p/foo/git-lfs-1.1.2/git-lfs clean %f"

$ git-lfs-1.1.2/git-lfs env
git-lfs/1.1.2 (GitHub; darwin amd64; go 1.6; git bf6a6c9)
git version 2.5.4 (Apple Git-61)

Endpoint=https://github.com/technoweenie/musical-octo-meme.git/info/lfs (auth=none)
LocalWorkingDir=/Users/rick/p/foo
LocalGitDir=/Users/rick/p/foo/.git
LocalGitStorageDir=/Users/rick/p/foo/.git
LocalMediaDir=/Users/rick/p/foo/.git/lfs/objects
TempDir=/Users/rick/p/foo/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
GIT_LFS_TEST_DIR=/Users/rick/p/git-lfs-temp
GIT_LFS_TEST_MAXPROCS=4
git config filter.lfs.smudge = "/Users/rick/p/foo/git-lfs-1.1.2/git-lfs smudge %f"
git config filter.lfs.clean = "/Users/rick/p/foo/git-lfs-1.1.2/git-lfs clean %f"
```

Now to actually track the files, and push just `.gitattributes`.

```bash
$ git-lfs-1.1.2/git-lfs track "*.png"
Tracking *.png
$ git-lfs-1.1.2/git-lfs track "*.txt"
Tracking *.txt
$ git add .gitattributes
$ git commit -m "gitattributes"
[master (root-commit) d57ee92] gitattributes
 1 file changed, 2 insertions(+)
 create mode 100644 .gitattributes
$ git push origin master
...
 * [new branch]      master -> master
```

## 3) push files through git LFS

```bash
$ echo "png" > fake.png
$ echo "txt" > real.txt
$ git add fake.png real.txt

# Now the objects are in .git/lfs/objects
$ tree .git/lfs/objects
.git/lfs/objects
├── 33
│   └── d8
│       └── 33d8344a7135c42aa3876706b908f95b702d83ff53e05e4aaff17c07bf67a98e
├── 7c
│   └── 4c
│       └── 7c4c231187cd4b75677c312faa7787da874bdbb7d71e1c9dc0619f3e27a53940
└── logs

5 directories, 2 files

$ git commit -m "add LFS files"
[master 5667ca0] add LFS files
 2 files changed, 6 insertions(+)
 create mode 100644 fake.png
 create mode 100644 real.txt

$ git push origin master
Git LFS: (2 of 2 files) 8 B / 8 B
...
   d57ee92..5667ca0  master -> master
```

## 4) switch to production build

```bash
$ git config filter.lfs.smudge "/Users/rick/p/foo/git-lfs-1.1.0/git-lfs smudge %f"
$ git config filter.lfs.clean "/Users/rick/p/foo/git-lfs-1.1.0/git-lfs clean %f"

$ git-lfs-1.1.0/git-lfs env
git-lfs/1.1.0 (GitHub; darwin amd64; go 1.5.1; git 258acf1)
git version 2.5.4 (Apple Git-61)

Endpoint=https://github.com/technoweenie/musical-octo-meme.git/info/lfs (auth=basic)
LocalWorkingDir=/Users/rick/p/foo
LocalGitDir=/Users/rick/p/foo/.git
LocalGitStorageDir=/Users/rick/p/foo/.git
LocalMediaDir=/Users/rick/p/foo/.git/lfs/objects
TempDir=/Users/rick/p/foo/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
GIT_LFS_TEST_DIR=/Users/rick/p/git-lfs-temp
GIT_LFS_TEST_MAXPROCS=4
git config filter.lfs.smudge = "/Users/rick/p/foo/git-lfs-1.1.0/git-lfs smudge %f"
git config filter.lfs.clean = "/Users/rick/p/foo/git-lfs-1.1.0/git-lfs clean %f"
```

Now it's reverted back to v1.1.0.

## 5) create a subfolder within the repository, and copy the files from step 3 into it

```bash
$ mkdir sub
$ cp fake.png sub
$ cp real.txt sub

$ gs
## master
?? git-lfs-1.1.0/
?? git-lfs-1.1.2/
?? git-lfs-darwin-amd64-1.1.0.tar.gz
?? git-lfs-darwin-amd64-1.1.2.tar.gz
?? sub/
```

## 6) create a commit and push

```bash
$ git add sub
$ git commit -m "add files in subdir"
[master c0372ff] add files in subdir
 2 files changed, 6 insertions(+)
 create mode 100644 sub/fake.png
 create mode 100644 sub/real.txt

# no LFS upload needed because those files were already uploaded in step 3.
$ git push origin master
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 341 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
To https://github.com/technoweenie/musical-octo-meme
   5667ca0..c0372ff  master -> master
```

Is Desktop wiping the `.git/lfs/objects` directory? The only LFS command that deletes files in `.git/lfs/objects` is `git lfs prune`. However, it only deletes old objects after they've been pushed, and if they're in commits older than 3 days.

Am I missing anything else?

**Comment by shiftkey** [comment]
@technoweenie thanks for digging into this

> Not sure how desktop handles empty repos...

We normally initialise a repo with a commit containing a `.gitattributes` file (and maybe a `.gitignore`).

I'll see if I can grab a log from @mponce1's install to see how we're following this behaviour in Desktop.

**Comment by shiftkey** [comment]
Looking at the logs we're trying to `git lfs push origin` with the new objects and then encounter the `.git/lfs/objects` issue:

```
Diamond PNG.png is an LFS pointer to 527757d3abf20082b55e9f7173cd24b4ebabfdbe84592c91658cd60a69027f62, which does not exist in .git/lfs/objects.

Run 'git lfs fsck' to verify Git LFS objects.
error: failed to push some refs to '[URL]'
```

This happened a couple of times - basically when we'd try to push - in that session. I'd just like to confirm whether this is related to switching releases on-the-fly, so I'll do another run-through as well before adjusting my internal DEFCON setting...

**Comment by shiftkey** [comment]
So I just ran through these steps with Git LFS 1.1.2 (without switching versions) and couldn't encounter this issue. @mponce1 I'll leave it to you how far you want to explore how much of an issue switching versions might be here...

**Comment by technoweenie** [comment]
I think the version switching is a red herring. There isn't a huge difference between v1.1.0 and v1.1.2. I'm just trying to figure out how the repository gets into this state.

> Diamond PNG.png is an LFS pointer to 527757d3abf20082b55e9f7173cd24b4ebabfdbe84592c91658cd60a69027f62, which does not exist in .git/lfs/objects.

Until v1.1.0, Git LFS didn't ever delete files from `.git/lfs/objects`. It does now, but only through [the `git lfs prune` command](https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-prune.1.ronn):

> Deletes local copies of LFS files which are old, thus freeing up disk space.
Prune operates by enumerating all the locally stored objects, and then deleting
any which are not referenced by at least ONE of the following:
>
> * the current checkout
* a 'recent branch'; see [RECENT FILES]
* a 'recent commit' on the current branch or recent branches; see [RECENT FILES]
* a commit which has not been pushed; see [UNPUSHED LFS FILES]
* any other worktree checkouts; see git-worktree(1)

This only happens when you run `git lfs prune`, or `git lfs fetch --prune`, which I don't think Desktop is doing. This is why I'm trying to get the exact sequence of commands to try and replicate the bug in LFS.

**Comment by mponce1** [comment]
Tried recreating with a new VM instance but didn't run into the same problem. I'll continue to look into this but will close it out in the meantime.
