### ISSUE TITLE
Trying to add large file and get: Size must be less than 2147483648

### ISSUE THREAD

**Issue by chriskinsman** [github/git-lfs#1073]
I can't find anything about max file size limits.  Is Git-LFS really limited to 2GB?

Thanks,

**Comment by technoweenie** [comment]
It depends on the server. 2GB is the limit on GitHub.com.

**Comment by metaf** [comment]
Sorry to post in a closed issue, but where would be the appropriate place to complain about this limitation/request the 'feature' of supporting files >2GB?

**Comment by technoweenie** [comment]
https://github.com/contact, since it's a github limitation and not an LFS one.

**Comment by amacneil** [comment]
Cold

**Comment by de-code** [comment]
Given that GitHub.com is very common and the first mentioned supported remote server, it would perhaps be good to add that to the documentation? Potentially somewhere where it mentions 'Version large files—even those as large as a couple GB in size'?

**Comment by hartator** [comment]
+1 

Yes, it will be great to add this to the documentation. I've gone through the process to install everything just to be blocked because my file is 2.4 GB.

**Comment by ttaylorr** [comment]
Hi everybody, this is totally something that I think we should address. In the meantime, this is also being discussed in https://github.com/git-lfs/git-lfs/issues/730, so I'm going to lock this and move discussion there. Thanks!
