### ISSUE TITLE
regression:  updating above v1.1.0 causes failure on travis

### ISSUE THREAD

**Issue by lbergelson** [github/git-lfs#1090]
I've been installing git-lfs on travis and using it successfully.  Updating from v1.1.0 has proven problematic though. 

I use this script to install git-lfs, which happens AFTER the git repo is cloned.

```
#!/bin/bash

GIT_LFS_VERSION="1.1.1"
GIT_LFS_LINK=https://github.com/github/git-lfs/releases/download/v${GIT_LFS_VERSION}/git-lfs-linux-amd64-${GIT_LFS_VERSION}.tar.gz
GIT_LFS="git-lfs-${GIT_LFS_VERSION}/git-lfs"
echo "downloading and untarring git-lfs binary"
wget -qO- $GIT_LFS_LINK | tar xvz

echo "ls"
ls

echo "resetting travis remote"
git remote set-url origin "git@github.com:broadinstitute/gatk.git"

echo "git lfs install"
GIT_TRACE=1 $GIT_LFS install

echo "fetch"
GIT_TRACE=1 $GIT_LFS fetch

echo "checkout"
GIT_TRACE=1 $GIT_LFS checkout

echo "ls-files"
GIT_TRACE=1 $GIT_LFS ls-files
ls -lah src/test/resources/large/
md5sum src/test/resources/large/*.*

echo "logs"
GIT_TRACE=1 $GIT_LFS logs last

echo "ls /home/travis/build/broadinstitute/gatk/.git/lfs/objects/logs/"
ls /home/travis/build/broadinstitute/gatk/.git/lfs/objects/logs/

echo "cat /home/travis/build/broadinstitute/gatk/.git/lfs/objects/logs/*"
cat /home/travis/build/broadinstitute/gatk/.git/lfs/objects/logs/
```

If I set `GIT_LFS_VERSION=1.1.0` then everything works fine, however if I use `1.1.1` or `1.1.2` I have a complete failure to download anything.

I can't reproduce it locally, although I tried using the setup that @larsxschneider used to debug #904.  

Here a build logs, the relevant portions are near the top, grep for  `git-lfs`:

- [v1.1.0 - success](https://s3.amazonaws.com/archive.travis-ci.org/jobs/116770417/log.txt)
- [v1.1.1 - failure](https://s3.amazonaws.com/archive.travis-ci.org/jobs/116912705/log.txt)
- [v1.1.2 - failure](https://s3.amazonaws.com/archive.travis-ci.org/jobs/116770373/log.txt)

I'm downloading the prebuilt jars, but I've also tried building from source with similar results, as well as trying different combinations of pull/checkout/fetch.

(I realized the statement to output the individual log files failed, I can rerun with that fixed if you think it would be helpful)

I could stay with 1.1.0, but I'm having a separate issue which I believe relates to #904 that I haven't been able to work around.

**Comment by sinbad** [comment]
```
trace git-lfs: ssh: git@github.com git-lfs-authenticate broadinstitute/gatk.git download 
trace git-lfs: ssh: download attempted with git@github.com.  Error: exit status 255
```
That looks to be the core of it, the SSH call to GitHub is failing, although I'm not sure why since it's a public repo, maybe @technoweenie can assist?

The reason it did not fail before 1.1.1 is that there was a bug that ignored SSH failure result codes in 1.1.0. Instead, it just fell back on a made-up https URL unrelated to the SSH output that just happened to work sometimes.

**Comment by lbergelson** [comment]
@sinbad Thanks for the insight!  This seems to have been the cause.  I didn't think that the ssh remote was the issue since I had seen those exact same error messages in the working build.  I didn't realize that it was falling back to http as an error.  

Changing to an http remote fixed my problem.  Is there any way this could produce a better error message in the future/ work with ssh remotes?

**Comment by sinbad** [comment]
LFS already works with SSH remotes (it's how I use it most of the time), so I don't know why you're getting that error. I think the issue is that you should be exiting your script on failure instead of ignoring errors, that would have halted right after the fetch and been much easier to spot. Maybe a `set -e` at the top?

**Comment by lbergelson** [comment]
I use ssh remotes locally, but I have a key registered with github.  Is it expected that ssh doesn't work for public repos without authentication?

**Comment by sinbad** [comment]
> Is it expected that ssh doesn't work for public repos without authentication?

It's not a git-lfs requirement but it's often a server requirement. I don't know the detail of GitHub's implementation but it's common because with SSH the authentication usually happens separately before access to the repo is resolved, so it's required that you have a key that can resolve to an account, before permissions are even checked. @technoweenie can probably confirm though.

**Comment by technoweenie** [comment]
I don't know much about this part of the system, but I have another LFS related thing to tackle anyway, so I'll dig in. It seems logical that a valid github key should work on public repos.

**Comment by technoweenie** [comment]
Turns out I can answer my own questions by hammering on the keyboard for about 10s. Seems to work fine:

```bash
$ git clone git@github.com:docker/docker.git
Cloning into 'docker'...
remote: Counting objects: 144986, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 144986 (delta 21), reused 7 (delta 7), pack-reused 144934
Receiving objects: 100% (144986/144986), 85.06 MiB | 10.31 MiB/s, done.
Resolving deltas: 100% (95481/95481), done.
Checking connectivity... done.
```

```bash
# this is what LFS actually runs
$ ssh git@github.com git-lfs-authenticate docker/docker download
{
  "href": "https://api.github.com/lfs/docker/docker",
  "header": {
    "Authorization": "RemoteAuth AAAAMONKEY==="
  },
  "expires_at": "2016-03-28T20:14:38Z"
}
```

@lbergelson What happens when you run this?

```bash
$ ssh git@github.com git-lfs-authenticate broadinstitute/gatk.git download
```

**Comment by sinbad** [comment]
Yeah the issue as I understand it is that his Travis build doesn't have a valid SSH key, and that you need to have *some* valid key to use an SSH clone URL regardless of the permissions on the repo.

**Comment by lbergelson** [comment]
@technoweenie I can definitely use git-lfs with an ssh remote if I have a key.  

I had thought you could use ssh without a key if it was a public repo.  That worked up until 1.1.1 but apparently was actually just falling back to http.  I was wondering if ssh remotes were expected to work without a key for public repos, or if they will never work.  (i.e. is there a bug or am I trying to do something impossible.)  If it will never work, an error message that says "you need a key to use an ssh remote" would be useful if it's practical.

**Comment by technoweenie** [comment]
Oh right, without _any_ key. For some reason I read that as "without any key that has push or organization access."

I agree that the error should be reported better. It's on my list. I should be better about posting things like this as bugs though :)

**Comment by lbergelson** [comment]
Thank you everyone for the help.
