### ISSUE TITLE
Broken link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by anatolyborodin** [github/git-lfs#1092]
The link https://github.com/github/git-lfs.github.com/blob/gh-pages/_config.yml#L4 "Update Git LFS website" is 404.

See also commit 0fb9c7b10f0cd204899214282a9d2913a94ed1a4 by @technoweenie

**Comment by technoweenie** [comment]
It's a valid link to the private repository for https://git-lfs.github.com, which is accessible to people that have access to make official Git LFS releases.

**Comment by anatolyborodin** [comment]
Wouldn't it be good to add a corresponding remark to that link?
