### ISSUE TITLE
Restriction of Adding maximum 5000 Files in the GIT Repository.

### ISSUE THREAD

**Issue by prashantakerkar** [github/git-lfs#1097]
After Trying to add multiple projects in the GIT created Repository, We got a message of  maximum limit of 5000 files can be added in the Repository.

Is there a solution for this?. Or we have to create new Repositories projects wise, which will not have more than 5000 files per Repository.

**Comment by whoisj** [comment]
Does that mean "5000 lfs tracked" files?

Because I'm certain that a repo can contain significantly more than 5,000 files.

**Comment by javabrett** [comment]
Can you post the exact output and message, together with any instructions on how to reproduce the problem?

**Comment by sinbad** [comment]
Maybe you got the message from git-gui? That has a limit of displaying 5000 files for performance but core git doesn't have that limitation.

**Comment by sinbad** [comment]
Or, perhaps it was a GitHub API rate limit that you hit? https://github.com/github/git-lfs/issues/466.

Closing this one until more detail is given.
