### ISSUE TITLE
Can't call method "get_deps" on an undefined value at /usr/bin/dh_golang line 114

### ISSUE THREAD

**Issue by jean-christophe-manciot** [github/git-lfs#1112]
Built with commit cc41ca541361372323ccafd9d4f14797151c421c

dpkg-buildpackage -m"Jean-Christophe Manciot <manciot.jeanchristophe@gmail.com>"

```make[1]: Leaving directory '/home/actionmystique/Program-Files/Ubuntu/Git/git-git-lfs'```
```   dh_makeshlibs -O--buildsystem=golang```
```   dh_shlibdeps -O--buildsystem=golang```
```   dh_installdeb -O--buildsystem=golang```
```   dh_golang -O--buildsystem=golang```
```Can't call method "get_deps" on an undefined value at /usr/bin/dh_golang line 114```.
```debian/rules:18: recipe for target 'binary' failed```
```make: *** [binary] Error 255```
```dpkg-buildpackage: error: debian/rules binary gave error exit status 2```

Whole log: 
[Can't call method get_deps.txt](https://github.com/github/git-lfs/files/190898/Can.t.call.method.get_deps.txt)

**Comment by technoweenie** [comment]
Ahh, paging @andyneff or @ssgelm :/

**Comment by ssgelm** [comment]
Works fine for me on both debian jessie and wheezy.  On what distro and release are you trying to build?  What version of dh-golang?

**Comment by jean-christophe-manciot** [comment]
**Ubuntu** 15.10 - 4.2.0-34 - dh-golang 1.12

**Comment by ssgelm** [comment]
I see the same issue when I install that version of dh-golang.  I'll see what I can do to fix.

**Comment by ssgelm** [comment]
Looks like it's blowing up as a result of this commit: 432e1fb876a29a915f171073aa197cbba0d7e6ff.  The error when parsing the build depends is:
```
-e: warning: can't parse dependency golang-go:native (>= 1.3.0)
```
@andyneff any ideas here?

**Comment by ssgelm** [comment]
Oh, it's a bug in dh-golang.  It calls dep_parse in Dpkg::Deps but does not pass the "build_dep" flag so it errors out.  From the Dpkg::Deps docs:
```
build_dep (defaults to 0)
    If set to 1, allow build-dep only arch qualifiers, that is “:native”.  This should be set whenever working with build-deps.
```
I will report the bug upstream.

**Comment by ssgelm** [comment]
Bug is reported upstream:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819596
The patch attached to that bug should fix the issue if you are interested.  I think this can be closed now.  What do you think @technoweenie?

**Comment by jean-christophe-manciot** [comment]
Where can I grab the patched sources to build dh-golang for Ubuntu?

**Comment by ssgelm** [comment]
You can find the patch at https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;msg=5;bug=819596;filename=fix-dh-golang-build-dep.patch which can be applied to the sources that you can retrieve with `apt-get source dh-golang`.

**Comment by jean-christophe-manciot** [comment]
I'm disappointed there is no github sources repo for dh-golang. It would be so convenient and would allow us to build the latest release, instead of depending on some downstream provider who happens to be always behind...
I'll let you know the result.

**Comment by technoweenie** [comment]
Closing this, as it looks like a dh-golang issue. Thanks for diving into it, @ssgelm :)

@jean-christophe-manciot: There are alternative ways of installing Go and Git LFS from source or pre-built binaries:

https://golang.org/dl/
https://github.com/github/git-lfs/releases

I can understand why you'd prefer to go through gh-golang, though. I'd like us to do more to make Git LFS easier to build and install, but these efforts on platforms I don't use rely heavily on contributors like @ssgelm. If you're interested in contributing, feel free to hop in our web chat room: https://gitter.im/github/git-lfs/installation. LFS has no forum or mailing list yet, other than these GitHub Issues, so feel free to go that route, or private email, if either are more preferable to you.

**Comment by ssgelm** [comment]
@jean-christophe-manciot If it makes things easier for you I went ahead and pushed a fork of the dh-golang repo with my patch committed.  You can find it at https://github.com/ssgelm/dh-golang.

**Comment by jean-christophe-manciot** [comment]
Thanks;
However, I'm experiencing another issue when building git-lfs with the patched dh-golang:
```
Converting man pages into code...
Failed to open man dir: <nil>
Converting man pages into code...
Failed to open man dir: <nil>
dh_installman: man --recode UTF-8 ./git\-lfs\-logs\.1 > git\-lfs\-logs\.1\.new returned exit code 2
debian/rules:18: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2
```
Whole log: 
[Man Pages Error.txt](https://github.com/github/git-lfs/files/198052/Man.Pages.Error.txt)
