### ISSUE TITLE
Smudge filter failed with a pull

### ISSUE THREAD

**Issue by TruJosh** [github/git-lfs#1116]
Similar to issue: (Smudge filter failed with a fresh new clone #911 / https://github.com/github/git-lfs/issues/911) but with a pull instead of a new clone.  

I'm seeing this:

git.exe pull --progress --no-rebase -v "e6" master

From https://github.com/TruGolf/e6
* branch            master     -> FETCH_HEAD
= [up to date]      master     -> e6/master
Downloading Code/BuildScripts/E61.6/PsExec.exe (387.19 KB)
Error downloading object: Code/BuildScripts/E61.6/PsExec.exe (3b08535b4add194f5661e1131c8e81af373ca322cf669674cf1272095e5cab95)

Errors logged to D:\dev\e6\.git\lfs\objects\logs\20160330T084938.5566214.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge %f failed 2
error: external filter git-lfs smudge %f failed
fatal: Code/BuildScripts/E61.6/PsExec.exe: smudge filter lfs failed

git did not exit cleanly (exit code 128) (46250 ms @ 3/30/2016 8:49:38 AM)

While 2 others pull without an issue, I cannot.

**Comment by technoweenie** [comment]
Hi @TruJosh, the actual error message is in `D:\dev\e6.git\lfs\objects\logs\20160330T084938.5566214.log`. Can you post that to a Gist, or email it to technoweenie@gmail.com?

**Comment by TruJosh** [comment]
Here is the log file.

**Comment by technoweenie** [comment]
Closing this until I can get some more details.
