### ISSUE TITLE
Continuous Password Request

### ISSUE THREAD

**Issue by PickySalamander** [github/git-lfs#1123]
Git LFS constantly asks our users for a password to upload or get from our storage. We use S3 to store our large files and an LFS server that gives the client back a signed url to upload to S3. When the put command is executed to S3 the headers and parameters are already signed so no username and password are needed. 

Unfortunately, it seems that Git assumes that the authorization is always basic and will ask for a username and password. If the user enters no username and password and hits enter the request will succeed, but then will be asked for the next file. This is a deal breaker for us as some of our projects have many large files.

Also, before anyone asks I've set the credential helper to anything I could think of and it has no effect.

Is there a work around for this? Is there a way I can change the server to tell my client to not send a username and password?

Thanks!

**Comment by technoweenie** [comment]
> When the put command is executed to S3 the headers and parameters are already signed so no username and password are needed.

Are you signing with uri query arguments, or an http `Authorization` header? Currently, LFS looks for the existence of an `Authorization` header to tell if the URI is already authenticated, or whether it should ask for the auth.

```json
# NOT AUTHENTICATED
{
  "objects": [
    {
      "oid": "d1c8fab51418ef587fcf5dd8e73c60b9700704e2f8f5292ea12ec27c285b23a3",
      "size": 25237,
      "actions": {
        "download": {
          "href": "https://some-bucket.s3.amazonaws.com/some-key?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=...",
          "expires_at": "2016-04-06T21:44:31Z"
        }
      }
    }
  ]
}

# AUTHENTICATED, YAY
{
  "objects": [
    {
      "oid": "d1c8fab51418ef587fcf5dd8e73c60b9700704e2f8f5292ea12ec27c285b23a3",
      "size": 25237,
      "actions": {
        "download": {
          "href": "https://some-bucket.s3.amazonaws.com/some-key",
          "header": {
            "Authorization": "...",
          },
          "expires_at": "2016-04-06T21:44:31Z"
        }
      }
    }
  ]
}
```

This doesn't work in cases where all of the authentication is passed through query parameters. Here's a future-proof workaround for your LFS server:

```
{
  "objects": [
    {
      "oid": "d1c8fab51418ef587fcf5dd8e73c60b9700704e2f8f5292ea12ec27c285b23a3",
      "size": 25237,
      "actions": {
        "download": {
          "href": "https://some-bucket.s3.amazonaws.com/some-key?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=...&token=1",
          "authenticated": true,
          "expires_at": "2016-04-06T21:44:31Z"
        }
      }
    }
  ]
}
```

This example adds two things:

1. Mysterious `token=1` hack will start working _today_. See https://github.com/github/git-lfs/issues/1088 for context.
2. The `authenticated` property is only a proposal, but I really want it for Git LFS v1.2 or 1.3. See #960.

@PickySalamander thanks for stopping by and reporting this. Let me know how else I can help :wave:

**Comment by PickySalamander** [comment]
Ah alright. Thanks for the help! We do send it all through query params, but I could possibly rework it to send through the header. I'll give it a try and reopen if it doesn't work.
