### ISSUE TITLE
What's the proper procedure for cloning a fresh repo with files tracked by `git-lfs`?

### ISSUE THREAD

**Issue by AdamCanady** [github/git-lfs#1124]
Is it necessary to run `git lfs install` on each new cloned repo? I've been running into the issue where files are marked as modified by `git` when I run `git lfs pull`.

**Comment by technoweenie** [comment]
> Is it necessary to run `git lfs install` on each new cloned repo?

Nope, just once per machine.

It sounds like your repo wasn't upgrade to LFS completely. LFS can't go back in history to retroactively apply settings like `git lfs track "*.psd"`. So you'll see `git status` changes on any existing PSD files that were added prior to LFS.

**Comment by AdamCanady** [comment]
Ah gotcha. So once that new "change" is committed (swapping it from being a normal file to being a file tracked in .gitattributes), the file will now be tracked by lfs with no additional changes recognized by `git status`?

**Comment by technoweenie** [comment]
Sort of. Git tracks changes in `git status` by comparing the current git blob to the git blob in the working directory. Normally, the git blob content matches the file exactly.

```bash
# update a file
$ echo "Hi" > hi.txt
$ git status
On branch master
Changes not staged for commit:

	modified:   hi.txt

no changes added to commit (use "git add" and/or "git commit -a")
$ git diff
diff --git a/hi.txt b/hi.txt
index 45b983b..b14df64 100644
--- a/hi.txt
+++ b/hi.txt
@@ -1 +1 @@
-hi
+Hi
```

Now, LFS inserts itself into internal filters that affect how Git adds a file to a repository. When you tell LFS to track a file pattern, all it does is adds it to `.gitattributes`. Here's what a diff looks like now:

```bash
$ git status
On branch master
nothing to commit, working directory clean

$ git lfs track "*.txt"
Tracking *.txt

# bump the file's modification time so `git status` will re-check it
$ touch hi.txt

$ git status
On branch master
Changes not staged for commit:

	modified:   hi.txt

Untracked files:

	.gitattributes

no changes added to commit (use "git add" and/or "git commit -a")

$ git diff
diff --git a/hi.txt b/hi.txt
index 45b983b..90353d7 100644
--- a/hi.txt
+++ b/hi.txt
@@ -1 +1,3 @@
-hi
+version https://git-lfs.github.com/spec/v1
+oid sha256:98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4
+size 3
```

Even though the contents of the file didn't change, adding it to LFS makes Git _think_ it changed. You can then commit it and move on.

Note: In Git LFS v1.2, you won't have to run `touch` yourself. This will happen automatically with #1104.

**Comment by AdamCanady** [comment]
Oh awesome, makes sense now! Thank you!
