### ISSUE TITLE
Use proxy settings from git config

### ISSUE THREAD

**Issue by csmager** [github/git-lfs#1125]
I'm using Windows and have the proxy set in Internet Options (which most apps will use) and in my git config (which git will use)... yet git lfs still tries to connect directly and fails when it times out.

It took me a while to track down where git lfs is getting its proxy configuration from. - it seems it uses [http.ProxyFromEnvironment](https://github.com/github/git-lfs/blob/8f90f594162d0a7e90e2f5785287f4327f097235/lfs/http.go#L118), which then led me [to the documentation](https://golang.org/pkg/net/http/#ProxyFromEnvironment) where I discover I need to add an `HTTP_PROXY` environment variable.   It now works.  Hopefully anyone else struggling with this will chance upon this issue!

I think given the integration with git the expectation would be that lfs would use the same proxy config as is configured for git in .gitconfig.

**Comment by technoweenie** [comment]
> I think given the integration with git the expectation would be that lfs would use the same proxy config as is configured for git in .gitconfig.

Good call, thanks for the report! It's probably too late for v1.2, but I'll put it on the list for v1.3.

**Comment by technoweenie** [comment]
This was shipped in Git LFS v1.3.
