### ISSUE TITLE
Custom GIT_SSH client not invoked correctly

### ISSUE THREAD

**Issue by mstrap** [github/git-lfs#1132]
When Git-LFS is invoking a custom `GIT_SSH` client, it passes the command as *separate* parameters, like `'git-lfs-authenticate', 'account/priv.git', 'upload'` however according to the [specification](https://git-scm.com/docs/git), the command must be passed in as exactly one parameter, like `'git-lfs-authenticate account/priv.git upload'`.

**Comment by sinbad** [comment]
Thanks for spotting this!
