### ISSUE TITLE
debug travis failure on test-credentials.sh

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#1140]
See #1136

**Comment by somi8462** [comment]
I needs neteller help me my first time money .neteller I'd:-451225122904.Nereller  gmail I'd:-asomi8462@gmail.com

**Comment by technoweenie** [comment]
Eventually fixed this a couple ways:

* [Added noop credential helper](https://github.com/github/git-lfs/blob/cf3dc4e5eb84cbc2dd6d0667a4b6762e3176cc56/test/cmd/git-credential-lfsnoop.go)
* [Skip credential tests if system credential helper is set](https://github.com/github/git-lfs/blob/ac301aa673124a7d85b547a8a66ec8a802b1c656/test/test-credentials-no-prompt.sh#L8-L14).
