### ISSUE TITLE
After installing 1.2.0 reported version is still 1.1.0

### ISSUE THREAD

**Issue by pascalberger** [github/git-lfs#1150]
I just installed 1.2.0 using the windows installer.

If I afterwards run `git lfs version` in a newly opened cmd shell the following is reported:

```
git-lfs/1.1.0 (GitHub; windows amd64; go 1.5.1; git 258acf1)
```
Control Panel reports that 1.2.0 is installed.

**Comment by sinbad** [comment]
The location that the installer places git-lfs.exe changed after 1.1.0, to install into its own area under Program Files and not under the Git install location like it used to. You probably still have an old version in your Git install folder which is taking precedence. Do a quick file search under your git install location for git-lfs.exe and delete any entries, leaving only the new version in Program Files\Git LFS.

**Comment by sinbad** [comment]
IIRC there may actually be an uninstaller placed in the old location too which you could use but deleting will work too. I don't believe the old installer created an entry in Control Panel, if it did you can uninstall from there.

**Comment by pascalberger** [comment]
Thanks @sinbad. Deleting git-lfs from the Git directory did the trick. Unfortunately like this it isn't possible to provide a smooth upgrade experience with the Chocolatey package (which always installs the new version above the older one)
