### ISSUE TITLE
Issues on Ubuntu 15.10

### ISSUE THREAD

**Issue by micahwalter** [github/git-lfs#1157]
Hi,
I'm having some issues with pulling data from a repository on Ubuntu 15.10. Below is a gist of the output from the git pull command and subsequent log messages. 

Has anyone else run into this problem ?

https://gist.github.com/micahwalter/7f71ee26b3798b02309e2120e1ae10f9

thanks
Micah

**Comment by technoweenie** [comment]
> Git LFS is disabled for this repository.

I checked, and your LFS access was disabled. My hunch is that you ran over last month, and then it rolled over without re-enabling access. I can look into that. Have your repo admin check for LFS emails from us about the limit. If you have more questions, hit me up at https://github.com/contact.

**Comment by micahwalter** [comment]
FYI this seems to work when I do 

    $ git lfs clone

vs. 

    $ git clone

Maybe that's just the way its supposed to be ?

**Comment by technoweenie** [comment]
@micahwalter: I wonder if it _just worked_ as I ninja-fixed the LFS usage issue that I described? Let me know if it's still a reproducible problem.
