### ISSUE TITLE
Adding Content-Length Header

### ISSUE THREAD

**Issue by PickySalamander** [github/git-lfs#1163]
I'm developing a GIT LFS server that returns a S3 put URL back to the client. Unfortunately, S3 requires requests contain a `Content-Length` header ([Even if a chunked request](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html)). I can't seem to get the LFS client to include this value even if I put it in the headers section (see below). Is there a way I can force this on?

JSON from GIT LFS Server:
```
  {
  	"objects": [{
  		"oid": "99a86d47165ef079873100c5db8d96b9d7abcb5f162ae24756d3097fa94d6930",
  		"actions": {
  			"upload": {
  				"href": "https://presigned-url.s3.amazonaws.com/data/99a86d47165ef079873100c5db8d96b9d7abcb5f162ae24756d3097fa94d6930",
  				"expires_at": "2016-04-20T19:11+0000",
  				"authenticated": true,
  				"header": {
  					"x-amz-content-sha256": "99a86d47165ef079873100c5db8d96b9d7abcb5f162ae24756d3097fa94d6930",
  					"Authorization": "...",
  					"X-Amz-Date": "20160420T190142Z",
  					"Host": "presigned-url.s3.amazonaws.com",
  					"Content-Type": "application/octet-stream",
  					"Content-Length": "496800"
  				}
  			},
  			"verify": {
  				"href": "http://localhost:8080/verify"
  			}
  		}
  	}]
  }
```

Also, here's the curl:
```
> PUT /data/99a86d47165ef079873100c5db8d96b9d7abcb5f162ae24756d3097fa94d6930 HTTP/1.1
> Host: presigned-url.s3.amazonaws.com
> Authorization: ...
> Content-Type: application/octet-stream
> User-Agent: git-lfs/1.2.0 (GitHub; windows amd64; go 1.6.1; git 386c5d8)
> X-Amz-Content-Sha256: 99a86d47165ef079873100c5db8d96b9d7abcb5f162ae24756d3097fa94d6930
> X-Amz-Date: 20160420T190142Z

```

Thanks for the help!

Picky

**Comment by technoweenie** [comment]
Ah, it's clobbering it [here](https://github.com/github/git-lfs/blob/db69cbdc8889f0b8ac4e8575e82da10f48c5d4d9/lfs/client.go#L352-L358), as it's finishing instantiating the request, so it can actually upload the body.

```go
	if req.Header.Get("Transfer-Encoding") == "chunked" {
		req.TransferEncoding = []string{"chunked"}
	} else {
		req.Header.Set("Content-Length", strconv.FormatInt(o.Size, 10))
	}

	req.ContentLength = o.Size
```

You're not returning a `size` property for the objects, so I'm guessing it's assuming `size = 0`. It is definitely [required in the API spec](https://github.com/github/git-lfs/blob/db69cbdc8889f0b8ac4e8575e82da10f48c5d4d9/docs/api/http-v1-batch-response-schema.json#L61).

**Comment by PickySalamander** [comment]
That worked, missed that in the schema. Thanks!
