### ISSUE TITLE
301 error on git lfs fetch

### ISSUE THREAD

**Issue by grwhumphries** [github/git-lfs#1166]
Here's my workflow. 

`git lfs install --skip-smudge`
I use --skip-smudge, otherwise I get the error...   
`error: external filter git-lfs smudge %f failed 2`
Next:   
`git clone https://www.github.com/CCheCastaldo/MAPPPD-Database.git`  
repository cloned... I get ALL files EXCEPT the .rda file I want to retrieve (RDA file is 300mb)  
`git lfs pull`  
Which gives me the error:   
`Git LFS: (0 of 1 files) 0 B / 288.91 MB
Invalid status for POST https://www.github.com/CCheCastaldo/MAPPPD-Database.git/info/lfs/objects/batch: 301  
Invalid status for POST https://www.github.com/CCheCastaldo/MAPPPD-Database.git/info/lfs/objects/batch: 301`

Why am I getting a 301 error?   
Same error when I try  

`git lfs fetch`

**Comment by javabrett** [comment]
Try dropping the `www.` from your clone.

**Comment by technoweenie** [comment]
Also, use https. This was reported in #1129.
