### ISSUE TITLE
git lfs clone for submodules

### ISSUE THREAD

**Issue by larsxschneider** [github/git-lfs#1172]
I realized that the `git lfs clone` [speed up](https://developer.atlassian.com/blog/2016/04/git-lfs-12-clone-faster/) does not work with Git Submodules and I wonder if anyone has a clever idea to approach this problem. Here is my first wrapper script attempt:

```bash
git-lfs clone $@
if [[ -z $2 ]]; then
    CLONE_PATH=$(basename ${1%.git});
else
    CLONE_PATH=$2;
fi
pushd "$CLONE_PATH"
    git submodule init
    wt_prefix=$(git rev-parse --show-prefix)
    git submodule--helper list --prefix "$wt_prefix" | {
        while read mode sha1 stage sm_path
        do
            name=$(git submodule--helper name "$sm_path") || exit
            url=$(git config submodule."$name".url)
            if ! test -d "$sm_path"/.git && ! test -f "$sm_path"/.git
            then
                git submodule--helper clone --prefix "$wt_prefix" --path "$sm_path" --name "$name" --url "$url"
                pushd "$sm_path"
                    git -c filter.lfs.smudge=cat checkout -q $sha1 || exit
                    git-lfs pull || exit
                popd
            fi
        done
    }
popd
```

This works by taking the relevant pieces from the [`git submodule`](https://github.com/git/git/blob/6a6636270fbaf74609cd3e1bd207dd2c420d640a/git-submodule.sh#L686-L731) command. However, this is probably a pretty fragile solution. I would prefer to use higher level Submodule commands. @sinbad @stefanbeller any better idea or do you think this is the way to go?

**Comment by larsxschneider** [comment]
I started a discussion on the Git core mailing list in addition: http://thread.gmane.org/gmane.comp.version-control.git/292466

**Comment by sinbad** [comment]
Man, submodules always throw a spanner in the works.

In 1.2.1 the `--recursive` option is supported which presumably means the submodules are cloned but the `-c` options are not passed along, meaning the submodules work but don't benefit from the speed-up, is that correct?

To support a manual cascade like this we'd firstly have to catch & suppress the `--recursive` and `--recurse-submodules` options in the call `git clone`. After that wouldn't a `git submodule update` with the same `-c filter.lfs...` options work instead of manually configuring? If so the remaining issue would be doubly (or more) nested submodules meaning some recursion. I'd need to test this but would maybe be more portable/future proof.

**Comment by larsxschneider** [comment]
Your 1.2.1 `--recursive` statement is correct. From my point of view that would be OK for now as it is just slow but not broken.

Your "catch & suppress `--recursive`" solution could work but @peff pointed me to an easier solution. We could just pass the `filter.lfs...` git config on to the submodule checkout:
http://thread.gmane.org/gmane.comp.version-control.git/292466/focus=292563

I will try to prepare a patch for Git core. If this gets accepted then `git lfs clone` could support fast submodule clones starting with Git 2.9 easily...

**Comment by sinbad** [comment]
That sounds ideal, thanks @larsxschneider!

**Comment by larsxschneider** [comment]
Look what landed in **next**: https://github.com/git/git/commit/89044baa8b8a14b48e78a42ebdc43cfcd144ce28

If this patch makes it into Git 2.9 then we can do this:
```
git -c filter.lfs.smudge= -c filter.lfs.required=false clone --recursive $URL $REPO_PATH
cd "$REPO_PATH"
git-lfs pull

git submodule--helper list |
while read mode sha1 stage sm_path
do
    if test -e "$sm_path"/.git
    then
        (
            cd "$sm_path"
            git-lfs pull
        )
    fi
done
```

Thanks to @gitster , @dscho , and @peff for making this work!

**Comment by sinbad** [comment]
Nice! Thanks so much for organising this.

**Comment by larsxschneider** [comment]
@sinbad: Do you have plans to update the `git lfs clone` code with the snipped above?

**Comment by sinbad** [comment]
Yeah, I was initially waiting to see if it made it into 2.9 and have been on vacation. I have some other transfer work to do first but it's on my list.

**Comment by sinbad** [comment]
Looking at this now, wouldn't it be better to use `git submodule foreach --recursive` instead of `git submodule--helper list`? That way nested submodules would work automatically.

**Comment by larsxschneider** [comment]
Nice idea! I haven't tested it but this should work, yes!

**Comment by sinbad** [comment]
Yeah, this is what I'm going with. PR soon.

**Comment by knight2010** [comment]
git lfs is not stable, but git submodule is much stable.
