### ISSUE TITLE
`git lfs install` returns zero exit code even when it doesn't install hooks

### ISSUE THREAD

**Issue by sinbad** [github/git-lfs#1174]
Reproduction:

```
> rm .git/lfs/pre-push
> touch .git/hooks/pre-push
> git lfs install
Hook already exists: pre-push



Run `git lfs update --force` to overwrite this hook.
Git LFS initialized.
> echo $?
0
```
This should return a non-zero exit code since currently this repository is not correctly initialised.

This also applies to `git lfs update`.

**Comment by technoweenie** [comment]
I guess I look at it as more "free gift with purchase", but I'd agree it's worth fixing :+1:

**Comment by sinbad** [comment]
Yeah, this particularly screws up SourceTree because it thinks it can rely on an exit code to detect failure in `git lfs install`.
