### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by Zitrax** [github/git-lfs#1184]
At https://git-lfs.github.com I tried the "Download" link, it links to https://github.com/github/git-lfs/releases/download/v1.2.0/git-lfs-windows-amd64-1.2.0.exe which is a 404. Switching .exe for .zip makes it work though.

**Comment by technoweenie** [comment]
Doh, thanks for the head's up. Try now!

If it doesn't work, here's the correct link https://github.com/github/git-lfs/releases/download/v1.2.0/git-lfs-windows-1.2.0.exe. The reason it changed is we have a single windows installer with both the 64bit and 32bit editions included.

**Comment by Zitrax** [comment]
Works now, thanks!
