### ISSUE TITLE
git push with LFS can stall on bad internet connections, and it will never notice and do something useful like retry

### ISSUE THREAD

**Issue by JonasT** [github/git-lfs#1220]
git push with LFS can stall on bad internet connections, and it will never notice and do something useful like retry (at least for me it never did). Since my internet connection is currently not the best, this means for large pushes I constantly need to abort it with CTRL+C and start again.

Due to the already uploaded files being "skipped" I manage to make actual progress like this so it's not a total showstopper, but it seems like an obvious thing for the client to do on its own: detect stalled uploads, and do a proper retry of that part/file (and eventually a fail after a few unsuccessful retries). Please note the default behavior should never be to entirely abort the push on first failure/stall, since that's just cruel for people with slower internet connections. I also suggest the amount of retries to be some configurable option.

Since git-lfs is meant for huge files specifically and this results in huge uploads naturally, it would be nice if this could be addressed in a future version!

**Comment by JonasT** [comment]
Just to be super clear: the stalling always happened to me during the Git LFS file upload part (since that's usually the really huge stuff, naturally) and never during the relatively quick regular git object transfer. So it would be nice if LFS did something about it without requiring my constant intervention..

**Comment by technoweenie** [comment]
Thanks for the feedback. It should retry failed transfers, but there are some failures that it can't come back from. That said, improving this situation is on our [roadmap](https://github.com/github/git-lfs/blob/master/ROADMAP.md). You can see some of the more fleshed out ideas (but not much code yet) [here](https://github.com/github/git-lfs/blob/ab1af11720f3a1b363f0bbf445504a4cc569b865/docs/proposals/transfer_adapters.md).

**Comment by JonasT** [comment]
What I mentioned doesn't seem to be covered by any of the things you linked:

The uploads aren't ever recognized as failed, they only **stall** and it just hangs there with git-lfs just assuming it is still uploading - hence this bug report ("it will never notice", see title).

Therefore what you would need is some mechanism that checks how large the *actual effective* upload speed is, and if it's 0 bytes per second for quite a while, treat the upload as failed.

**Comment by technoweenie** [comment]
Are you sure that's what's happening? What's it look like when you run the command with `GIT_TRACE=1`? 

We can setup connection timeouts to detect stalled transfers. IMO, that is a part of resumable uploading/downloading. If the transfer errors for any reason, restart from where you left off. We can achieve that with a HTTP Range header for downloads, and something like the [tus.io](http://tus.io/) api for uploads.

**Comment by JonasT** [comment]
I'm pretty sure, because at some point the  transferred data just stops climbing and I waited for a really long time with nothing advancing, but no error/automated abort happening either. When CTRL+C aborting and retrying it went fine and continued with visible progress again... and this happened multiple times.

My connection is better now so I cannot easily retest, my connection quality varies sporadically :-/ sorry

**Comment by JonasT** [comment]
@technoweenie happened again last night when I tried to do a larger upload. 10 minutes after I left the pc it just stalled and did nothing for the rest of the night because apparently why not... so now it's not uploaded as it should be. Would be very nice if this could be addressed so minor random connection hiccups don't stop a larger upload entirely

**Comment by gregbillock** [comment]
I'm observing what looks like this error, but extremely reproducibly after exactly 6 files every time. Is there a number-of-files-per-push limit or something that I need to adjust?

**Comment by ABaldwinHunter** [comment]
I'm not sure if this is the same or different, but I'm currently on a plane with very slow wifi - yet I can use internet in chrome successfully, including on github.com.

However when I try to push to github via the command line via ssh - the command just hangs forever and eventually get a no connection response:

```bash
GIT_TRACE=1 g push origin abh/my-branch
14:05:23.731527 git.c:465               trace: built-in: git push origin abh/my-branch
14:05:23.758661 run-command.c:657       trace: run_command: unset GIT_PREFIX; ssh git@github.com 'git-receive-pack '\''myorganization/repo.git'\'''

Connection closed by XXX.82.YYY.4 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

any suggestion?

**Comment by chrisd8088** [comment]
@ABaldwinHunter --

Without a full trace log, like one might get with `GIT_SSH_COMMAND="ssh -vvv" GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git push ...`, I don't think we can do more than speculate as to the cause, but I wouldn't be surprised if the plane's WiFi connection ran through some kind of proxy which was tuned for HTTP use and interfered with SSH connections in a way that prevented them from succeeding in your case.

I will also note that we prefer folks to open a new issue rather than comment on an old, closed one; in the future, if you have problems, please do just open a new discussion or a new issue.
