### ISSUE TITLE
hardening-no-relro: not found

### ISSUE THREAD

**Issue by jean-christophe-manciot** [github/git-lfs#1221]
Ubuntu 16.04 4.4.0-22
commit 1.2.0
```
	echo --------
	echo Cleaning
	echo --------
	cd $GOPATH/src/github.com/github/git-lfs
	git fetch --progress --prune origin
	git reset --hard
	git clean -fxd :/
	git checkout v1.2.0

	echo --------
	echo Building
	echo --------
	dpkg-buildpackage -m"Jean-Christophe Manciot <manciot.jeanchristophe@gmail.com>"
...
make[1]: Leaving directory '/home/actionmystique/Program-Files/Ubuntu/GO-Packages/src/github.com/github/git-lfs'
   dh_installdocs -O--buildsystem=golang
   dh_installchangelogs -O--buildsystem=golang
   dh_installman -O--buildsystem=golang
   dh_lintian -O--buildsystem=golang
debian/git-lfs.lintian-overrides: 2: debian/git-lfs.lintian-overrides: hardening-no-relro: not found
debian/git-lfs.lintian-overrides: 6: debian/git-lfs.lintian-overrides: unstripped-binary-or-object: not found
dh_lintian: debian/git-lfs.lintian-overrides returned exit code 127
debian/rules:19: recipe for target 'binary' failed
make: *** [binary] Error 127
dpkg-buildpackage: error: debian/rules binary gave error exit status 2
```
Whole log: 
[hardening-no-relro not found.txt](https://github.com/github/git-lfs/files/266040/hardening-no-relro.not.found.txt)

**Comment by technoweenie** [comment]
@ssgelm Any idea?

**Comment by ssgelm** [comment]
I'm spinning up a VM to test.

**Comment by ssgelm** [comment]
Other than the dh_golang issue that was fixed in #1112 I got no build errors on a clean 16.04 box.  The steps I followed on the new box were:

```
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install build-essential devscripts
git clone https://github.com/github/git-lfs
cd git-lfs/
git checkout v1.2.0
sudo apt-get install dh-golang golang-go ruby-ronn
(manually applied my dh_golang patch from #1112)
dpkg-buildpackage -us -uc
```

**Comment by jean-christophe-manciot** [comment]
Since your last patch, Ubuntu has a new iteration (16.04) & I have compiled & built dh_golang 1.16.
Unfortunately, applying your patch does not work anymore:
```
git apply ../fix-dh-golang-build-dep.patch
warning: script/dh_golang has type 100644, expected 100755
error: patch failed: script/dh_golang:106
error: script/dh_golang: patch does not apply
```
Also, are you planning on a pull request?

**Comment by ssgelm** [comment]
The patch should not be needed on anything higher than dh-golang 1.13.  The patch was accepted upstream. (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819596)  Having said that ubuntu 16.04 only has dh-golang 1.12 (http://packages.ubuntu.com/xenial/dh-golang).  Are you sure that you are running 16.04?

**Comment by jean-christophe-manciot** [comment]
See for yourself with dh-golang 1.16 that I have built [here](https://gitlab.com/jean-christophe-manciot/system-tools).

**Comment by jean-christophe-manciot** [comment]
Solved! :-)
I have just built the latest stable debhelper ([debhelper_9.20160403_all](https://gitlab.com/jean-christophe-manciot/system-tools/blob/master/Ubuntu/16.04/debhelper_9.20160403_all.deb)) and I can now build [git-lfs_1.2.0_amd64](https://gitlab.com/jean-christophe-manciot/system-tools/blob/master/Ubuntu/16.04/git-lfs_1.2.0_amd64.deb) with [dh-golang_1.16_all](https://gitlab.com/jean-christophe-manciot/system-tools/blob/master/Ubuntu/16.04/dh-golang_1.16_all.deb) on Ubuntu 16.04.
