### ISSUE TITLE
local changes present right after `git lfs clone`

### ISSUE THREAD

**Issue by vlsd** [github/git-lfs#1232]
This seems to be related to a known issue, but I can't seem to find good documentation as to what *should* be happening (or a link to the actual known issue).

I clone a repo with `git lfs clone`, I enter it and the status shows that all the `lfs` managed paths have local, uncommitted changes. There's a sentence in the documentation that says "this is known git issue and... well... deal with it by doing ______" so I assume it's safe to ignore. However, say I want to be working on a different branch. I cannot switch branches, because of my "local uncommitted changes", so I can't actually ignore it. 

Should I be committing those changes? If so, won't that end up with one extra commit from each person who clones the repo, all of them committing the same changes to the same files? If I'm not supposed to commit them, what should I do? 

Say I commit them, or stash them, or whatever... when I switch to the other branch (that I've been itching to switch to) I have to do `git lfs fetch` and `git lfs checkout .` in order to get my lfs files for that branch, but once that's done, yet again, there are "local uncommitted changes" that I have to deal with.

Am I doing something wrong or is this the way `git-lfs` is supposed to handle cloning repos?

**Comment by technoweenie** [comment]
Ideally, you won't see changes immediately after cloning. Can you see what the change is? Are these files that aren't using LFS, but match file paths in `.gitattributes` for LFS?

**Comment by vlsd** [comment]
They are definitely all the files that match `.gitattributes` (images) but I don't think they're not using LFS, since they only appear *after* running `git lfs fetch` and `git lfs checkout`, so they are certainly coming form the LFS server.

**Comment by technoweenie** [comment]
Try creating a temporary branch and committing. What's in the commit?

**Comment by vlsd** [comment]
Ok, I just did the following:
```
git checkout -b temp
git commit -am "test commit"
```

and the result was:
```
[temp 6e354b8] new commit
 998 files changed, 3122 insertions(+), 3 deletions(-)
 rewrite content/articles/blog/a-taxis-suspension-of-judgement/cab_thumbnail.jpg (100%)
 rewrite content/articles/blog/a-taxis-suspension-of-judgement/cab_thumbnail_big.jpg (100%)
 rewrite content/articles/blog/a-taxis-suspension-of-judgement/cab_thumbnail_bw.jpg (100%)
...
```

**Comment by javabrett** [comment]
Might be time to post your `.gitattributes` contents.

**Comment by technoweenie** [comment]
What does `git show` say?

**Comment by vlsd** [comment]
@javabrett there is one `.gitattributes` file in every folder that contains images (I believe this is the doing of `bfg -git-lfs`) and they all have the same content:
```
*.{jpg,png,gif,jpeg,psd,xcf,pdf} filter=lfs diff=lfs merge=lfs -text
```
@technoweenie `git show`, after the commit (I expect that's what you meant), is of this form:

```
commit 6e354b8402e76ca3c656a016a3a967691b0b15ad
Author: Vlad Seghete <vlad.seghete@gmail.com>
Date:   Thu May 19 18:27:36 2016 -0500

    new commit

diff --git a/content/articles/blog/a-taxis-suspension-of-judgement/cab_thumbnail.jpg b/content/articles/blog/a-taxis-suspension-of-judgement/cab_thumbnail.jpg
index 0019587..1ac3fef 100644
Binary files a/content/articles/blog/a-taxis-suspension-of-judgement/cab_thumbnail.jpg and b/content/articles/blog/a-taxis-suspension-of-judgement/cab_thumbnail.jpg differ
diff --git a/content/articles/blog/a-taxis-suspension-of-judgement/cab_thumbnail_big.jpg b/content/articles/blog/a-taxis-suspension-of-judgement/cab_thumbnail_big.jpg
index 89906fa..d3ca401 100644
...
```

**Comment by technoweenie** [comment]
Ah yes, the `.gitattributes` helps a lot (side note: this project sorely needs an issue template). That is an invalid file pattern that bfg writes. Here's an issue about it: https://github.com/rtyley/bfg-repo-cleaner/issues/116.

You may be better off trying https://github.com/bozaro/git-lfs-migrate to migrate your repository data.

**Comment by vlsd** [comment]
Hmm, so the issue is that `git` and/or `git-lfs` does not always deal with bracket globbing in the `.gitattributes` file? If that's the case I think that closes this and open a PR with the documentation for `bfg`

**Comment by technoweenie** [comment]
Git LFS doesn't use the file, only Git. Though, the issue is that bfg is creating invalid `.gitattributes` files.
