### ISSUE TITLE
Install from source / without sudo

### ISSUE THREAD

**Issue by ryan-williams** [github/git-lfs#1235]
[INSTALLING.md seems to require `sudo` for installing on Linux](https://github.com/github/git-lfs/blob/master/INSTALLING.md#installing-packages), but I'm interested in installing on a machine that I don't have `sudo` privileges on.

[The wiki "Installation" page says I can clone the repo and run `./scripts/bootstrap`](https://github.com/github/git-lfs/wiki/Installation#source). In the 1.2.0 release this file seems to actually be named `script/boostrap` (singular "script"). When I run it I get errors:

```
$ script/bootstrap
# command-line-arguments
script/build.go:99: undefined: lfs.Version
script/build.go:265: undefined: lfs.Version
```

I tried downloading with `go get` and get many errors like:

```
$ cd $GOPATH
$ go get github.com/github/git-lfs
package github.com/github/git-lfs
	imports github.com/github/git-lfs/commands
	imports github.com/github/git-lfs/config
	imports github.com/github/git-lfs/vendor/_nuts/github.com/ThomsonReutersEikon/go-ntlm/ntlm: must be imported as _nuts/github.com/ThomsonReutersEikon/go-ntlm/ntlm
package github.com/github/git-lfs
	imports github.com/github/git-lfs/commands
	imports github.com/github/git-lfs/config
	imports github.com/github/git-lfs/vendor/_nuts/github.com/ThomsonReutersEikon/go-ntlm/ntlm
	imports github.com/github/git-lfs/vendor/_nuts/github.com/ThomsonReutersEikon/go-ntlm/ntlm/md4: must be imported as _nuts/github.com/ThomsonReutersEikon/go-ntlm/ntlm/md4
…
```

Any ideas how to proceed?

**Comment by javabrett** [comment]
If you don't have root, help yourself to a tarball https://github.com/github/git-lfs/releases/download/v1.2.0/git-lfs-linux-amd64-1.2.0.tar.gz

**Comment by ryan-williams** [comment]
Great, I missed that on that page and went straight to the source tarball, thanks!

I'll close this out since I'm unblocked here but if you/anyone has thoughts on why the other two attempts to install from source failed I'd be curious to hear/document them as well. Thanks again.

**Comment by javabrett** [comment]
1.2.0 is known to FTBFS from source-tarball and requires a git clone, ref #1201, #1202 .  There are recent/unreleased improvements on master.

**Comment by ziyuhuang123** [comment]
How to install it? I am new to linux.....

**Comment by ziyuhuang123** [comment]
tar xvf git-lfs_3.3.0_amd64.deb
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

**Comment by bk2204** [comment]
A `.deb` file is not a tarball.  If you want a binary you can install, you can use the `git-lfs-linux-amd64-v3.3.0.tar.gz` file from the releases page and extract that, and that will contain the binary.  All you have to do is copy it somewhere in your `PATH`.

If you want to build from source, you can use the `git-lfs-v3.3.0.tar.gz` tarball and run `make` (after having installed it).

If you are able to run things with `sudo`, then you can install the `.deb` file with `sudo dpkg -i git-lfs_3.3.0_amd64.deb` and that should install the Git LFS package.  You're better off using the APT repository so it's updated automatically, though.
