### ISSUE TITLE
Can't git push

### ISSUE THREAD

**Issue by ryan-williams** [github/git-lfs#1237]
I typically develop on my laptop and `git push` to a server for compilation/deployment. 

Adding git-lfs to my repo has broken `git push` and I've gone in circles reading the many issues about SSH remotes and pushing/pulling/cloning/fetching not working as people expect:

- #1207:
  - [receiver of a `push` needs a server running](https://github.com/github/git-lfs/issues/1207#issuecomment-217455331),
  - [SSH remotes only work if the receiving remote has a `git-lfs-authenticate` command](https://github.com/github/git-lfs/issues/1207#issuecomment-218523052).
  - #1044: [you can write your own `git-lfs-authenticate` command to run on the receiving server](https://github.com/github/git-lfs/issues/1044#issuecomment-188893647)?
- #930: something about `pull` only working if the remote is called `origin`, not `upstream`.
- #754: SSH remote urls must include the user, i.e. `user@host:…` instead of just `host:…`
  - #798: same thing?
- #724: the `push`ing side [needs to set the "LFS URL" git config to the address of an HTTP server running on the receiving side](https://github.com/github/git-lfs/issues/724#issuecomment-146898843).
- #479: run an [lfs-test-server](https://github.com/github/lfs-test-server) on the receiving end of an SSH `push`.
- #295: [SSH URLs will be handled by LFS version 1.1](https://github.com/github/git-lfs/issues/295#issuecomment-104788283).
- [Wiki Tutorial](https://github.com/github/git-lfs/wiki/Tutorial): "Push: TODO"

It would be very beneficial to distill whatever bits of the above are correct/current into the docs.

My current state is:

- lfs-test-server running on `server` side:

  ```bash
$ export LFS_ADMINUSER=foo
$ export LFS_ADMINPASS=bar
$ export LFS_SCHEME=http
$ lfs-test-server
2016-05-21T03:54:17Z server lfs[9816] [proc.go:188]: fn=main msg=listening pid=9816 addr=tcp://:8080 version=0.3.0
  ```

- LFS URL set on `laptop` for the `server` remote:

  ```bash
$ git config remote.server.lfsurl http://server:8080
  ```

- credentials (`foo`/`bar`) on `laptop` being cached after the first time I entered them (when prompted during a `git push server`):

  ```bash
$ git config credential.helper cache
  ```

- `git push server` on `laptop` fails:

  ```bash
$ git push server
Git LFS: (22 of 11 files) 0 B / 145.35 MB
Put http://localhost:8080/objects/b51abcf9b1b59b4b5eeb9f516831a852aa23c17fac3b94130f28a8b3b3bc7fdf: dial tcp [::1]:8080: getsockopt: connection refused
Put http://localhost:8080/objects/b51abcf9b1b59b4b5eeb9f516831a852aa23c17fac3b94130f28a8b3b3bc7fdf: dial tcp [::1]:8080: getsockopt: connection refused
Put http://localhost:8080/objects/7d3137c0eb6fde817b0816f7acafc38e72625b31c3f7afe3d1618148bdcaacd3: dial tcp [::1]:8080: getsockopt: connection refused
Put http://localhost:8080/objects/7d3137c0eb6fde817b0816f7acafc38e72625b31c3f7afe3d1618148bdcaacd3: dial tcp [::1]:8080: getsockopt: connection refused
…
error: failed to push some refs to 'user@server:path'
  ```

[GitLab suggests](http://docs.gitlab.com/ce/workflow/lfs/manage_large_binaries_with_git_lfs.html#getsockopt-connection-refused) this could mean the client is speaking HTTPS to a server expecting HTTP, but afaict everything is `http` here, so I'm out of leads. Any help is much appreciated.

**Comment by javabrett** [comment]
Is your git-lfs from the 1.2.0 binary tarball per your other thread?  What does `./git-lfs version` return?

It is possible that there is some IPv4 versus IPv6 mismatch here similar to described in [this SO post](http://stackoverflow.com/questions/28376472/golang-http-post-error-connection-refused), although I thought Go 1.5+ would be clear of this problem.  The reference-server might be compiled with an older version of Go though.

To verify, can you run `netstat -anp` as root and note the listen protocols and ports for the server on port 8080.  Is it `tcp` or `tcp6`.  Then you might need to try and establish what the client is using - `tcpdump` might help.  If you find that the server is listening on IPv4, try using `127.0.0.1` as the hostname instead of something that might be resolving to an IPv6 address.

**Comment by ryan-williams** [comment]
Interesting idea about IPv4 vs. IPv6, thanks. I went down that path a bunch before realizing the error was elsewhere; details about both adventures follow.

### Setting `LFS_HOST` on `server`
The smoking gun turned out to be visible in the error lines from above, e.g.:

```
Put http://localhost:8080/objects/b51abcf9b1b59b4b5eeb9f516831a852aa23c17fac3b94130f28a8b3b3bc7fdf: dial tcp [::1]:8080: getsockopt: connection refused
```

That error was appearing on my laptop when attempting to `git push server`. Why would either machine be trying to `Put` things to `localhost`? Any `Put`s should presumably have been going from `laptop` to the `server` (the direction of the `git push`).

The crucial config setting turned out to be [`lfs-test-server`'s `LFS_HOST`](https://github.com/github/lfs-test-server/tree/v0.3.0#running):
> The host used when the server generates URLs, default: "localhost:8080".

`server` was sending `laptop` URLs to `Put` stuff to that pointed to `localhost`, which might be fine if they were on the same machine, but didn't make sense here.

I did not expect the flow to be:

1. `laptop` connects to `lfs-test-server` on `server` (as specified by `git config remote.<remote name>.lfsurl` on `laptop`).
2. `laptop` receives URL strings from `server` that must be configured, on `server`, to point back to `server` (but in a way that can be resolved on `laptop`, i.e. `localhost` / `127.0.0.1` not admissible).
3. `laptop` uses those URLs to contact same `server` it was already contacting via LFS URL.

I understand that this is designed assuming these things are running on github.com, out of the user's control, and clients are routed to api.github.com URLs or something for the files themselves, but this extra layer of indirection, when I'm just trying to `git push` between two machines that I control, is unexpected, not well documented, and apparently redundant.

It's still unclear to me, for example, whether I would be better served using `github.com/myteam/myrepo` as the base of one of the three kinds of URLs that is in play here (pusher, receiver, and large-file server).

Anyway, after sorting this out, `git push server` successfully shipped my 11 LFS-tracked files from `laptop` to `server`, and the worst was over. 

I still ran into a problem where I couldn't `git reset --hard` between commits straddling some LFS changes on `server` without another LFS error:

```
Downloading <some LFS-tracked file> (163.12 KB)
Error downloading object: <some LFS-tracked file> (b51abcf9b1b59b4b5eeb9f516831a852aa23c17fac3b94130f28a8b3b3bc7fdf)

Errors logged to /path/to/repo/.git/lfs/objects/logs/20160521T172328.122450407.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: <some LFS-tracked file>: smudge filter lfs failed
```

[This random JIRA](https://jira.atlassian.com/browse/BAM-17160) suggested temporarily removing this block from my .gitconfig:

```
[filter "lfs"]
        clean = git-lfs clean %f
        smudge = git-lfs smudge %f
        required = true
```

and that allowed me to `git reset --hard` on `server`; I restored the config block afterward.

So, I think I finally have a clean+working clone on `server`, though I don't know if pushing further LFS-related changes from `laptop` is going to work 😟.

### Answers to previous questions about IPv6 vs. IPv4
This turned out to be a red herring, I think, but is maybe useful to document anyway.

- Yes, I'm running `git-lfs` 1.2.0:

  ```
git-lfs/1.2.0 (GitHub; darwin amd64; go 1.6.1)
  ```

- lfs-test-server (`0.3.0`) seems to be built against Go 1.4:
  - [dockerfile](https://github.com/github/lfs-test-server/blob/v0.3.0/Dockerfile#L1)
  - [godeps](https://github.com/github/lfs-test-server/blob/v0.3.0/Godeps/Godeps.json#L3)

  which corroborates your hypothesis.
- However, `netstat -anp` on `server` (as the user running `lfs-test-server`, not `root`, though presumably both work) has this line:

  ```
tcp6       0      0 :::8080                 :::*                    LISTEN      48770/lfs-test-serv
  ```

  which implies the server is listening for IPv6.
- I wasn't able to determine whether the client is sending IPv4; I ran `tcpdump` as root on `laptop` while attempting a `git push server` but all I see is traffic over the VPN that I'm on (necessary for talking to `server` from my apt), e.g.:

  ```
16:35:27.071257 IP 192.168.0.15.63134 > vpn.domain.https: Flags [.], ack 182577, win 65535, options [nop,nop,TS val 1419950854 ecr 3559646500], length 0
  ```

  All such lines have `IP` in the second column, while other traffic (e.g. to AWS) has `IP6`.

So the new hypothesis might have been that my laptop was trying to speak IPv4 to an `lfs-test-server` listening for IPv6, but I think given the aforedescribed `LFS_HOST` resolution, this was probably not the issue.

Thanks again for your help.

**Comment by wvaughn409** [comment]
> Interesting idea about IPv4 vs. IPv6, thanks. I went down that path a bunch before realizing the error was elsewhere; details about both adventures follow.
> 
> ### Setting `LFS_HOST` on `server`
> The smoking gun turned out to be visible in the error lines from above, e.g.:
> 
> ```
> Put http://localhost:8080/objects/b51abcf9b1b59b4b5eeb9f516831a852aa23c17fac3b94130f28a8b3b3bc7fdf: dial tcp [::1]:8080: getsockopt: connection refused
> ```
> 
> That error was appearing on my laptop when attempting to `git push server`. Why would either machine be trying to `Put` things to `localhost`? Any `Put`s should presumably have been going from `laptop` to the `server` (the direction of the `git push`).
> 
> The crucial config setting turned out to be [`lfs-test-server`'s `LFS_HOST`](https://github.com/github/lfs-test-server/tree/v0.3.0#running):
> 
> > The host used when the server generates URLs, default: "localhost:8080".
> 
> `server` was sending `laptop` URLs to `Put` stuff to that pointed to `localhost`, which might be fine if they were on the same machine, but didn't make sense here.
> 
> I did not expect the flow to be:
> 
> 1. `laptop` connects to `lfs-test-server` on `server` (as specified by `git config remote.<remote name>.lfsurl` on `laptop`).
> 2. `laptop` receives URL strings from `server` that must be configured, on `server`, to point back to `server` (but in a way that can be resolved on `laptop`, i.e. `localhost` / `127.0.0.1` not admissible).
> 3. `laptop` uses those URLs to contact same `server` it was already contacting via LFS URL.
> 
> I understand that this is designed assuming these things are running on github.com, out of the user's control, and clients are routed to api.github.com URLs or something for the files themselves, but this extra layer of indirection, when I'm just trying to `git push` between two machines that I control, is unexpected, not well documented, and apparently redundant.
> 
> It's still unclear to me, for example, whether I would be better served using `github.com/myteam/myrepo` as the base of one of the three kinds of URLs that is in play here (pusher, receiver, and large-file server).
> 
> Anyway, after sorting this out, `git push server` successfully shipped my 11 LFS-tracked files from `laptop` to `server`, and the worst was over.
> 
> I still ran into a problem where I couldn't `git reset --hard` between commits straddling some LFS changes on `server` without another LFS error:
> 
> ```
> Downloading <some LFS-tracked file> (163.12 KB)
> Error downloading object: <some LFS-tracked file> (b51abcf9b1b59b4b5eeb9f516831a852aa23c17fac3b94130f28a8b3b3bc7fdf)
> 
> Errors logged to /path/to/repo/.git/lfs/objects/logs/20160521T172328.122450407.log
> Use `git lfs logs last` to view the log.
> error: external filter git-lfs smudge -- %f failed 2
> error: external filter git-lfs smudge -- %f failed
> fatal: <some LFS-tracked file>: smudge filter lfs failed
> ```
> 
> [This random JIRA](https://jira.atlassian.com/browse/BAM-17160) suggested temporarily removing this block from my .gitconfig:
> 
> ```
> [filter "lfs"]
>         clean = git-lfs clean %f
>         smudge = git-lfs smudge %f
>         required = true
> ```
> 
> and that allowed me to `git reset --hard` on `server`; I restored the config block afterward.
> 
> So, I think I finally have a clean+working clone on `server`, though I don't know if pushing further LFS-related changes from `laptop` is going to work 😟.
> 
> ### Answers to previous questions about IPv6 vs. IPv4
> This turned out to be a red herring, I think, but is maybe useful to document anyway.
> 
> * Yes, I'm running `git-lfs` 1.2.0:
>   ```
>   git-lfs/1.2.0 (GitHub; darwin amd64; go 1.6.1)
>   ```
> * lfs-test-server (`0.3.0`) seems to be built against Go 1.4:
>   
>   * [dockerfile](https://github.com/github/lfs-test-server/blob/v0.3.0/Dockerfile#L1)
>   * [godeps](https://github.com/github/lfs-test-server/blob/v0.3.0/Godeps/Godeps.json#L3)
>   
>   which corroborates your hypothesis.
> * However, `netstat -anp` on `server` (as the user running `lfs-test-server`, not `root`, though presumably both work) has this line:
>   ```
>   tcp6       0      0 :::8080                 :::*                    LISTEN      48770/lfs-test-serv
>   ```
>   
>   
>   which implies the server is listening for IPv6.
> * I wasn't able to determine whether the client is sending IPv4; I ran `tcpdump` as root on `laptop` while attempting a `git push server` but all I see is traffic over the VPN that I'm on (necessary for talking to `server` from my apt), e.g.:
>   ```
>   16:35:27.071257 IP 192.168.0.15.63134 > vpn.domain.https: Flags [.], ack 182577, win 65535, options [nop,nop,TS val 1419950854 ecr 3559646500], length 0
>   ```
>   
>   
>   All such lines have `IP` in the second column, while other traffic (e.g. to AWS) has `IP6`.
> 
> So the new hypothesis might have been that my laptop was trying to speak IPv4 to an `lfs-test-server` listening for IPv6, but I think given the aforedescribed `LFS_HOST` resolution, this was probably not the issue.
> 
> Thanks again for your help.

Could you please give specific step-by-step instructions on how you solved this?
I see these lines in gitlab.yml...

test:
  <<: *base
  gravatar:
    enabled: true
  lfs:
    enabled: false
  gitlab:
    host: localhost
    port: 80


..but when i change localhost to the correct url and fix the port, then save, i don't know how to restart the gitlab docker container and have the changes persist. it keeps resetting them back to the above
