### ISSUE TITLE
Support multiple git media endpoints

### ISSUE THREAD

**Issue by rubyist** [github/git-lfs#124]
After [smarter push](https://github.com/github/git-media/pull/122) lands, we'll be able to start building better support for pushing to different git media endpoints. The primary issues so far are:

Picking the endpoint to send to. The pre-push hook gets the remote name and url on its command line. We can look up or calculate a git media endpoint based on that.

If you make a fresh clone of a git media repository, you will only have `HEAD` versions of the git media files. If you then want to push the repo to a new remote / git media endpoint, we'll need a way to retrieve the historical git media files so they can be pushed, or otherwise notify the user.

Some things we'll probably need to do here:
- [ ] Grep the repo  for media pointer files
- [ ] Push all versions of every media file to a new endpoint

**Comment by technoweenie** [comment]
This is solved with `git lfs fetch` and `git lfs pull` now.
