### ISSUE TITLE
Push command succeed but no changes happend in the repository on github.com

### ISSUE THREAD

**Issue by Buzz2000** [github/git-lfs#1242]
Hi,
I cloned a repository, made some change like add a directory and move files into it and into other exsited dorectories.
Then I commited the changes, and push.

On github.com in the repository - no changes.

When cloning again - the repository cloned with the changes.

Can someone fix this mess?

Thx

**Comment by technoweenie** [comment]
GitHub has had some minor service issues today: https://status.github.com/messages

It _should_ be clearing up now. Closing this, since it has nothing to do with the LFS client AFAIK.
