### ISSUE TITLE
LFS and TeamCity agent check out

### ISSUE THREAD

**Issue by mjwitte32** [github/git-lfs#1246]
I'm having a bear of a time trying to get my team's TeamCity agents to check out files tracked with LFS. We're using SSH for fetching from the remote. Just from reading other issues, I know SSH isn't the best supported by LFS, but we don't have any other option. Our repo is so damn large that the checkout times out when using HTTPS, so we're stuck with SSH. We use SSH keys to authenticate with the remote, which is hosted on Bitbucket Server.

Every build I've run fails when trying to download the first LFS-tracked file with exit status 255. I'm fairly certain this is an authentication issue. I've run the `ssh git@remote.com git-lfs-authenticate org/repo.git download` command (with my own remote, org, and repo, of course), but instead of getting JSON like everyone else, I'm met with a password prompt for git@remote.com. We didn't use a password when setting up the SSH key, but an empty password isn't accepted. Using the build user's domain password isn't accepted either. I tried adding the build user's credentials into `git credentials`, but that didn't help at all.

I've been wrestling with this now for two days, so if there's any help you can offer, I would be very appreciative. I don't know if it's something I'm doing wrong or if LFS isn't going to support this configuration. I'm sure it's the former, but I don't want to continue banging my head against a wall if it really is impossible.

**Comment by mjwitte32** [comment]
(Sort of) Obvious update: manually adjusting remote.url in .git/config in the local repo on the build agent to be the HTTPS path to the remote works without any issues.

**Comment by technoweenie** [comment]
Can you show the output from `GIT_TRACE=1 git whatever-command`? It sounds like your host doesn't support the `git-lfs-authenticate` ssh command.  You can try that too with `ssh`:

```
$ ssh git@github.com git-lfs-authenticate github/git-lfs-test download
{
  "href": "https://api.github.com/lfs/github/git-lfs-test",
  "header": {
    "Authorization": "RemoteAuth ...",
    "Github-Deploy-Key": "17045588"
  },
  "expires_at": "2016-05-24T22:48:46Z"
}
```

I don't know the status of Bitbucket's LFS server or anything, but the above command, when run against your Bitbucket repository, should return some form of JSON. 

I can only help if this is a client problem. @sinbad should be able to point you in a better direction if it's server related.

**Comment by sinbad** [comment]
Just to confirm that Bitbucket Server definitely supports SSH when using LFS, it's what I use most of the time. Here's what I get for example (Authorization token is way longer than this in practice of course):
```
ssh git@blah.com git-lfs-authenticate project/repo.git download
{"header": {"Authorization": "JWT XXXXXX.xxxxxxxx"}, "href": "http://blah.com/bitbucket/scm/project/repo.git/info/lfs"}
```
If you're getting a password prompt on `ssh git@remote.com git-lfs-authenticate org/repo.git download` then this rules out any issue with the git-lfs client itself as @technoweenie says, so my first thought would be that your TeamCity agent doesn't have a valid SSH key in its env which maps on to a real user - however your comment implies that it works when cloning just git?

If that's the case it's likely something more specific with the config on either end, and I'm not sure exactly what without more detail. It's probably best to take this to Bitbucket support - it's definitely intended to work fine and does here so they can go through your config in more detail & get this sorted out for you. Please can you create a ticket at https://support.atlassian.com?

**Comment by mjwitte32** [comment]
Thanks for the replies, y'all. Definitely an SSH authentication issue then. I'll create a ticket with Atlassian. Thanks for the help.

**Comment by mjwitte32** [comment]
For posterity (in case anyone ever has a similar issue), here was the problem. TeamCity has a master private key that it keeps on the server and copies over to the agents before starting the build. That private key is removed directly after the clone/fetch. By the time the agent got to the checkout (downloading LFS files) the private key was long gone. The solution I went with was just to keep that private key in the ~/.ssh/ folder of the build agents permanently. Everything seems to be hunky dory now.

**Comment by prashanthbollam** [comment]
I too was facing this issue and this thread helped me understand the problem.  How do I find the master private key on the agent machine ?
