### ISSUE TITLE
Add files to git-media by attribute such as size?

### ISSUE THREAD

**Issue by Haacked** [github/git-lfs#125]
I just watched @technoweenie's great demo on The Show and a thought occurred to me. You have to know in advance the file extensions of the files you want to use.

But what if I only want to use git-media for files that are larger than 100MB. Could I set it up for every file of that size?

**Comment by andrew-aladev** [comment]
You've sluck like leeches to this `.gitattributes`. What's going on?

This system is designed to create one to many relation between path and attribute. Users don't want to create attributes, they want absolutely custom filters. @Haacked wants to filter big files, I want to filter elf binaries. This question has nothing to do with `.gitattributes`. `.gitattributes` is a custom filter, but any custom filter can't be implemented using `.gitattributes`.

Why you can't patch git and add simple user-defined callback (path) -> [true, false] using bash, python, lua ,etc?

**Comment by technoweenie** [comment]
Still a neat idea, just haven't had time to experiment with it.

**Comment by ArianRudd** [comment]
Any updates on this?
