### ISSUE TITLE
pull -I: / at end of path changes behavior

### ISSUE THREAD

**Issue by dipnlik** [github/git-lfs#1251]
`git lfs pull -I dir/` is different from `git lfs pull -I dir`: the first "doesn't work" (meaning it does not download any files in `dir`), while the second works as expected and downloads the requested files.

This is bad because other command line tools usually don't care about the final `/`, and because tab-completion usually includes the final `/`.

**Comment by ttaylorr** [comment]
Hi @dipnlik! 👋  I applied a small refactoring to this part of the LFS code, and took note to fix your issue. It should be resolved once we merge #1257 😄
