### ISSUE TITLE
Too many dropped connections using Git-LFS

### ISSUE THREAD

**Issue by jhuynh-safe** [github/git-lfs#1263]
Here's our situation...

We have a repository with just under 3000 Large files that we want to manage with Git-LFS. We're also in the process of moving our GitHub Enterprise server to Amazon AWS (off-site). The connection between our on-site machines (Git clients) to the GHE server goes through our Cisco firewall.

The Problem:
When I try to download all the large files from the GHE server in the cloud, our firewall detects a malicious amount of dropped connections and decides to block my connection to the outside world. Our suspicion is that Git-LFS is vigorously trying to make connections to GHE so it can download all the files as quick as possible but it fails due to some unknown reason.

The Questions:
How many connections does Git-LFS try to establish with GHE? What could cause it to have so many dropped connections? Could it be something on the GHE side? Is there a way for us to control how many connections Git-LFS tries to make?

Any help would be much appreciated. Thanks!

**Comment by sinbad** [comment]
I can't comment on GHE but on the client with 1.2 there could be 4 connections at once by default assuming you're using the default batch route - 1 API connection and 3 download connections. You can control the download concurrency via the gitconfig option `lfs.lfs.concurrenttransfers` (default 3). I can't think of a reason why any of the connections would be dropped from the client end; we use a 30s keepalive by default, you can change this too in gitconfig with `lfs.keepalive`.

**Comment by jhuynh-safe** [comment]
Thanks for the reply @sinbad - Yes, I am using the default batch settings.

I'll try tinkering with the `lfs.keepalive` setting and hopefully it improves the situation. 

You can resolve/close this issue. Next time, if I have questions w.r.t. Git-LFS.. should I file an issue again? Or is there a better place to ask questions like the above?

**Comment by sinbad** [comment]
You might find the chat room useful: https://gitter.im/github/git-lfs - which is better depends on the complexity, how much detail you need to add and whether it's something that will likely be useful to have archived in the issues longer term; if you're not sure then try chat first and escalate back here if necessary.

**Comment by PascalRean** [comment]
@jhuynh-safe
I have a similar issue.
Do lfs.keepalive or  lfs.concurrenttransfers settings improves the situation ?

**Comment by jhuynh-safe** [comment]
@PascalRean -- Yes, it helped a little bit. However, this particular issue disappeared even after changing the settings back to default. 

Having said that, we starting encountering other network related issues instead, so we decided to keep our GHE server on premise and not put it on AWS.
