### ISSUE TITLE
Git LFS Implementation Questions

### ISSUE THREAD

**Issue by MikeNwin** [github/git-lfs#1264]
Hi @github/lfs,

I would like to ask for your help with the following questions from a customer:

> **a.** Are the files stored once per repository? I.e. if the same file with the same checksum is committed to another repository is it stored there again?

> **b.** To the same end, if a developer stores a file, changes it and then reverts to the original copy of the file, is it stored 3 times or just once?

> **c.** Can old copies of the files be purged?  I am thinking about runtime / buildtime libraries that tend to get checked in and are simply out of date.  I can see there is a console page for me to look at the files in LFS, but I don’t see any way to examine them or do a bulk purge.

I believe [the BFG](https://rtyley.github.io/bfg-repo-cleaner/), as per [Removing files from a repository's history](https://help.github.com/articles/removing-files-from-a-repository-s-history/), speaks to **c**.

Thanks❗

**Comment by technoweenie** [comment]
Hi @MikeNwin:

> a. Are the files stored once per repository? I.e. if the same file with the same checksum is committed to another repository is it stored there again?

It depends on the server side implementation. I can only speak for GitHub. On GitHub.com, objects are stored once per repository network, just like git objects. GitHub Enterprise stores one unique object per instance (or multiple, depending on your HA or Cluster setup).

> b. To the same end, if a developer stores a file, changes it and then reverts to the original copy of the file, is it stored 3 times or just once?

Multiple times.

> c. Can old copies of the files be purged? I am thinking about runtime / buildtime libraries that tend to get checked in and are simply out of date. I can see there is a console page for me to look at the files in LFS, but I don’t see any way to examine them or do a bulk purge.

Not currently. It's something we're discussing. Keep in mind, it will make any commits with deleted runtime libs unbuildable.  I wouldn't recommend using BFG multiple times in the lifetime of a repository, unless it's fixing some very recent commits. When BFG (or any Git history-rewriting tool) rewrites an old commit, every commit after it changes.

**Comment by sinbad** [comment]
a. Locally, files with the same SHA are stored once per repository. The same content added twice to the same repo will only be stored in the LFS store once, but if both are current in HEAD then they will be in your working copy twice. If the same content is added to a different local repository then it is stored separately; unless you use the `--reference` option when cloning, which can re-use objects in another repo.
b. Just once.
c. Locally yes, if the files are no longer referenced by a checkout; see the `git lfs prune` command. See `git lfs help prune` for more info.

**Comment by MikeNwin** [comment]
Thanks for the very information answers, @technoweenie and @sinbad ❕ 

:bow:

**Comment by technoweenie** [comment]
No problem, feel free to stop by the gitter chat room at https://gitter.im/github/git-lfs if you have more questions.
