### ISSUE TITLE
Git clone error 503

### ISSUE THREAD

**Issue by zayednetad** [github/git-lfs#1268]
Hi,

I have installed github-enterprise on a Openstack VM, i can use it, access it, but when i try to clone it from a client, it gives below:

git clone http://devour-github.vcp.vzwops.com/org-devour/openresty.git
Cloning into 'openresty'...
fatal: unable to access 'http://devour-github.vcp.vzwops.com/org-devour/openresty.git/': The requested URL returned error: 503

I run above command while in tcpdump and i got below:

<p><strong>No server is currently available to service your request.</strong></p>
      <p>Sorry about that. Please try refreshing and contact us if the problem persists.</p>

//Regards
Nuruddin Ahmed

**Comment by technoweenie** [comment]
Hi, this doesn't look related to the Git LFS client, and should be filed through GitHub Enterprise support. [These instructions](https://help.github.com/enterprise/2.6/admin/guides/installation/troubleshooting/) show you how to send our support team a support bundle so they can troubleshoot your VM.
