### ISSUE TITLE
'git lfs pull' downloads all files

### ISSUE THREAD

**Issue by Danand** [github/git-lfs#1284]
Hi there! The problem is downloading all files (not just new or modified) when calling `git lfs pull`.
But I'm using that hack:
```
git lfs init --skip-smudge # Avoiding failures with large content commits.
git pull
git lfs install --force
git lfs pull
```
May it causes the problem?

**Comment by javabrett** [comment]
Are you saying that a second and subsequent `git lfs pull` is re-downloading large-files that you already have in `.git/lfs/objects` from a previous/initial `git lfs pull`?  Or is it the first `git lfs pull` you are referring to - if your repository already has large-file pointers, then this is going to download/resolve them.

**Comment by Danand** [comment]
> Are you saying that a second and subsequent git lfs pull is re-downloading large-files that you already have in .git/lfs/objects from a previous/initial git lfs pull?

This.

**Comment by technoweenie** [comment]
Hi @Danand, I'm unable to replicate this. Can we see `git lfs env` from inside that repository? Also, can we see the output of `GIT_TRACE=1 git lfs pull`, with `tree .git/lfs/objects` before each call? 

```bash
$ tree .git/lfs/objects
.git/lfs/objects
├── 02
│   └── 63
│       └── 0263829989b6fd954f72baaf2fc64bc2e2f01d692d4de72986ea808f6e99813f
├── 55
│   └── d5
│       └── 55d51edb307ed7bf4a1bbca3867d132a07f76828d57f37e0f31f712c02ceafe0
├── 98
│   └── ea
│       └── 98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4
├── b9
│   └── f8
│       └── b9f86fab477109565871ced361ba69f2425a91fbe6057fa7a9629a8d536d7c71
├── d1
│   └── c8
│       └── d1c8fab51418ef587fcf5dd8e73c60b9700704e2f8f5292ea12ec27c285b23a3
├── e1
│   └── 73
│       └── e1732d149d262963996ca77a47a5d3c51c85c6e97187afad370a8bef2828b6b7

$ git lfs pull
Git LFS: (0 of 6 files) 0 B / 818.95 KB
```

Also, you don't need to run `git lfs install --skip-smudge` if you just want the behavior for a single `git` command. You could change your example in the original post to just:

```bash
$ GIT_LFS_SKIP_SMUDGE=1 git pull
$ git lfs pull
```

**Comment by Danand** [comment]
@technoweenie so I can't replicate this now.
I've solved my problem with `git reset --hard origin/my_branch` and it's gone.

**Comment by technoweenie** [comment]
Ok, please re-open with details if you run across this again.
