### ISSUE TITLE
PackageCloud issues with other distros

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#1288]
We used to happily upload the same centos packages to the fedora repo, and the debian packages to the ubuntu and linuxmint repos, but now PackageCloud is rejecting those:

```
pushing repos/debian/8/pool/main/g/git-lfs/git-lfs_1.2.1_amd64.deb to "linuxmint/rebecca"
script/packagecloud.rb:80:in `block (2 levels) in <main>': packagecloud put_package failed, error: {"repository"=>["The specified distro does not support the package you've tried to upload"]} (RuntimeError)
	from script/packagecloud.rb:71:in `map'
	from script/packagecloud.rb:71:in `block in <main>'
	from script/packagecloud.rb:67:in `each'
	from script/packagecloud.rb:67:in `<main>'
```

@andyneff, @ssgelm: Before I file a support issue, I want to know if this should be considered a bug on their end, or if we should be building individual packages for those other repos. Thoughts?

**Comment by ssgelm** [comment]
As far as I am able to determine this is a bug on their end.

**Comment by andyneff** [comment]
I would tend to agree, looks like a bug

**Comment by javabrett** [comment]
Try upgrading your [packagecloud ruby gem to 1.0.4](https://rubygems.org/gems/packagecloud-ruby/versions/1.0.4) (or at least 1.0.3).  I had similar problems and raised https://github.com/computology/packagecloud-ruby/issues/14 which was fixed in 1.0.3.

**Comment by technoweenie** [comment]
Gah, I remember that issue. I just didn't remember the exact error message. Thanks, I'll try that when I get to the office.

**Comment by technoweenie** [comment]
Thanks @javabrett, you were absolutely right :)
