### ISSUE TITLE
master needs a version-bump from 1.2.0

### ISSUE THREAD

**Issue by javabrett** [github/git-lfs#1293]
Since 1.2.1 is released.

Note that recent package refactoring moves the Version string from `lfs/lfs.go` to `config/version.go`.

This might occur at the same time as a later merge-up from the release-branch; there are a couple of other release things that will need merging such as `CHANGELOG.md`.

**Comment by ttaylorr** [comment]
The merge from `release-1.2` -> `master` maybe a little tricky, since we split those two branches before merging #1226 into `master`.

**Comment by ttaylorr** [comment]
This will be closed as soon as https://github.com/github/git-lfs/pull/1331 is merged 👍
