### ISSUE TITLE
Remove centos_5 from docker build

### ISSUE THREAD

**Issue by javabrett** [github/git-lfs#1295]
It doesn't work:

```
# github.com/github/git-lfs/tools
/usr/bin/ld: unrecognized option '--build-id=none'
/usr/bin/ld: use the --help option for usage information
collect2: ld returned 1 exit status
```

Seems this is expected on account of go not supporting Centos 5: https://github.com/golang/go/issues/9520 .

Looks like Centos 5 packages are not built anymore, or at least they aren't pushed to packagecloud, so this option could be removed from the default list for `run_dockers.bsh` and `test_dockers.bsh`.

/cc @andyneff

**Comment by andyneff** [comment]
The build is failing because the **unsupported** go fails in CentOS 5 whenever cgo is involved. We've tried to make sure the c parts don't try to compile in CentOS 5.

You can not use the CentOS 6 rpm in CentOS 5 (It may be possible for 6 to make a 5 compatible rpm, but is it worth it?)

So I kind of agree, drop the centos 5 docker, and maybe add something to generate a more universal  installer like http://stephanepeter.com/makeself/ to cover all the the other *nixes (Including CentOS 5)

**Comment by javabrett** [comment]
Right.  Go has stated as far back as 1.1 that RHEL/Centos 5 is unsupported - I'm not clear on whether that's toolchain only or runtime, but given that distro doesn't meet minimum kernel and glibc support, and Go statically-links everything, it looks like asking for trouble, eventually if not now.  The Go issue linked above and others from it are pretty down on Centos 5 support.

I did wonder why I wasn't seeing the benefit of https://github.com/andyneff/git-lfs_dockers/pull/1 - with `CGO_ENABLED=0` - looks like it was pushed to Hub and everything, but it still didn't build for me obviously.

Per comments on #952 :

> I'm in favor of disabling CGO on centos 5. If it's worth just dropping all support, that works too :) Once that happens, we can merge this PR.

Given the clear direction on non-support from Go, this might be the time to clarify Git LFS no-longer supports that distro either.  LFS probably needs a page/ghpage/wiki with clear minimum platform support.

/cc @technoweenie

**Comment by andyneff** [comment]
Well, we've been TRYING to say that RHEL 5 is (more or less) supported in that it works, until it's EOL finally in 2020 ;) But I feel like makeself is MORE than enough to check that box and make me and that ONE RHEL 5 user happy :) Plus I know that will be useful on all the other OSes that packagecloud doesn't have specific repos for.

**Comment by javabrett** [comment]
OK, I had a diff for this so I'll save it as a PR - feel free not to merge that depending on what is decided.

At the risk of stating obvious :) - people should not be developing code on RHEL5.  The LTS for that product is designed for server-systems, not developer or build environments.  So while it might work now, I suspect that trying to maintain that support whilst taking advantage of Go 1.6 upgrade etc. could lead to problems, especially given their support stance.  I accept that generic, non-packageable distros support is helpful.
