### ISSUE TITLE
LFS - not sure why publish is failing.

### ISSUE THREAD

**Issue by robhafey** [github/git-lfs#1300]
Having trouble doing a publish of a folder structure containing large files.  I am certainly not a git expert so bear with me.

I first used GitHub Desktop to try the publish.  My steps were create the repo, clone in desktop, drag my folders into the repo root, do an initial commit, and then publish.  After the first publish I realized that I had to track the large files so I went to the folder (on Mac) and did a "git lfs track" for all the known file types (after installing the lfs extensions).  Then i tried publishing multiple times without success (see errors below).  I also tried from the command line.  I used "git push origin master" and received similar errors as below.  

> File UnityEFM (U4)/DailyBuilds/3.3.11/3.3.11_Data/sharedassets2.assets is 57.40 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
> 
> File UnityEFM (U4)/EFM_Amazon/WebPlayer.unity3d is 86.36 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
> 
> File UnityEFM (U4)/Latest Build/version1.zip is 77.69 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
> 
> File UnityEFM (U5)/Build/HealthStream-EFM/HealthStream-EFM.unity3d is 79.15 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
> 
> File UnityEFM (U5)/UnityEFM-WEBPLAYER/UnityEFM-WEBPLAYER.unity3d is 74.72 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
> 
> File UnityEFM (U4)/DailyBuilds/3.3.11/3.3.11.app/Contents/Data/sharedassets2.assets is 57.40 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
> 
> GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.        
> 
> Trace: d2e85733a75c893ddbcdbd2d5404dddf        
> 
> See http://git.io/iEPt8g for more information.   

What is interesting about the error msg above is the line "You may want to try Git Large File Storage - https://git-lfs.github.com."  As far as I know I should already be using the LFS so I am very confused.  Is there a way to tell in the github.com whether a repo has large files enabled?  My track results are listed below.

git lfs track
Listing tracked paths
    *.unity3d (.gitattributes)
    *.zip (.gitattributes)
    *.exe (.gitattributes)
    *.*gz (.gitattributes)
    *.assets (.gitattributes)

After a few failed attempts I then created a paired down folder and successfully published to new test repo without errors.  It had just a few of the large files listed above.  I did first "track" the large files (*.unity3d and *.ogg).  After the first publish I threw in some more >50mb files (.assets) and they synced file even though I hadn't tracked them in LFS which seems inconsistent to me.  

I am really looking for a proper workflow to successfully move over a bunch of our larger SVN directories over to GITHUB.  Any help is appreciated.

...

**Comment by AppAdvisory** [comment]
Same error here .. :'(

**Comment by technoweenie** [comment]
You're getting that error message because there are files in your repository that aren't using LFS. The `git lfs track` command only affects new file changes. Files in older commits are not updated to use LFS. The [bozaro/git-lfs-migrate](https://github.com/bozaro/git-lfs-migrate) tool can be used to convert files in old commits to use LFS.

**Comment by robhafey** [comment]
This doesn't make sense to me.  The commit was failing on the initial
import.

On Fri, Jul 1, 2016 at 11:25 AM, risk danger olson <notifications@github.com
> wrote:

> You're getting that error message because there are files in your
> repository that aren't using LFS. The git lfs track command only affects
> new file changes. Files in older commits are not updated to use LFS. The
> bozaro/git-lfs-migrate <https://github.com/bozaro/git-lfs-migrate> tool
> can be used to convert files in old commits to use LFS.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/github/git-lfs/issues/1300#issuecomment-229975787>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA3wxWg2Xx0pDHKt3-BQDDGrghxanWBrks5qRTF-gaJpZM4IzPBl>
> .
>



-- 
Rob Hafey
Senior Software Developer
Simulation Training & Education Lab (SiTEL) of MedStar Health
robert.j.hafey@medstar.net
202.364.5180 x1219 (office)
301.503.6922 (cell)

www.sitel.org


CONFIDENTIAL: The information contained in this communication, including
its attachments may contain confidential information and is intended only
for the individual (s) or entity (ies) to whom it is addressed . The
information contained in this communication may also be protected by legal
privilege , federal law or other applicable law. If you are not the
intended recipient of this communication , you are hereby notified that any
distribution, dissemination or duplication of this communication is
strictly prohibited. If you have received this communication in error
please immediately delete and destroy all copies of this message and please
immediately notify us of the error by separate communication.

**Comment by technoweenie** [comment]
How did you import the repo from SVN to Git? It's very possible that you used a tool that doesn't support Git LFS. In that case, you'd want to do an additional conversion from your plain git repo, to a git lfs repo with the [bozaro/git-lfs-migrate](https://github.com/bozaro/git-lfs-migrate) tool.

If you're using GitHub, the [import tool](https://github.com/new/import) should support converting SVN repos to Git LFS.

**Comment by robhafey** [comment]
I created a new repo and checked it out in GitHub Desktop.  I then dumped
all my files into the checked out folder.  GitHub desktop saw all the files
but the import would fail.

My preferred method would be to use a SVN to GitHub tool which would
support the LFS.



On Fri, Jul 1, 2016 at 1:07 PM, risk danger olson <notifications@github.com>
wrote:

> How did you import the repo from SVN to Git? It's very possible that you
> used a tool that doesn't support Git LFS. In that case, you'd want to do an
> additional conversion from your plain git repo, to a git lfs repo with the
> bozaro/git-lfs-migrate <https://github.com/bozaro/git-lfs-migrate> tool.
>
> If you're using GitHub, the import tool <https://github.com/new/import>
> should support converting SVN repos to Git LFS.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/github/git-lfs/issues/1300#issuecomment-229999067>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA3wxZunkuYPKzKaocgG-wdlEeeXOWGRks5qRUlYgaJpZM4IzPBl>
> .
>



-- 
Rob Hafey
Senior Software Developer
Simulation Training & Education Lab (SiTEL) of MedStar Health
robert.j.hafey@medstar.net
202.364.5180 x1219 (office)
301.503.6922 (cell)

www.sitel.org


CONFIDENTIAL: The information contained in this communication, including
its attachments may contain confidential information and is intended only
for the individual (s) or entity (ies) to whom it is addressed . The
information contained in this communication may also be protected by legal
privilege , federal law or other applicable law. If you are not the
intended recipient of this communication , you are hereby notified that any
distribution, dissemination or duplication of this communication is
strictly prohibited. If you have received this communication in error
please immediately delete and destroy all copies of this message and please
immediately notify us of the error by separate communication.

**Comment by technoweenie** [comment]
Hmm, that should work if you set up the tracked files before dropping all the files in there.

**Comment by robhafey** [comment]
That is what I thought :)  If I keep trying the files will eventually
import, but the process is not very comforting as I don't want to have to
check to make sure which of the 1000s of files didn't import correctly.

If I recall (I haven't reread my post) when I use the command line an error
is thrown that I am not using LFS.  Very frustrating.




On Fri, Jul 1, 2016 at 1:15 PM, risk danger olson <notifications@github.com>
wrote:

> Hmm, that should work if you set up the tracked files before dropping all
> the files in there.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/github/git-lfs/issues/1300#issuecomment-230000770>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA3wxX3q5YkcrQNYgBq2SBA1AXPA9Qbjks5qRUsngaJpZM4IzPBl>
> .
>



-- 
Rob Hafey
Senior Software Developer
Simulation Training & Education Lab (SiTEL) of MedStar Health
robert.j.hafey@medstar.net
202.364.5180 x1219 (office)
301.503.6922 (cell)

www.sitel.org


CONFIDENTIAL: The information contained in this communication, including
its attachments may contain confidential information and is intended only
for the individual (s) or entity (ies) to whom it is addressed . The
information contained in this communication may also be protected by legal
privilege , federal law or other applicable law. If you are not the
intended recipient of this communication , you are hereby notified that any
distribution, dissemination or duplication of this communication is
strictly prohibited. If you have received this communication in error
please immediately delete and destroy all copies of this message and please
immediately notify us of the error by separate communication.

**Comment by technoweenie** [comment]
Can you send more details to https://github.com/contact? Our GitHub Desktop team should be able to help you out here, as I don't work on that tool.

**Comment by robhafey** [comment]
I think I had the same error when I tried to push from the command line as
well.  I need to go back and look at my post.

On Fri, Jul 1, 2016 at 1:21 PM, risk danger olson <notifications@github.com>
wrote:

> Can you send more details to https://github.com/contact? Our GitHub
> Desktop team should be able to help you out here, as I don't work on that
> tool.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/github/git-lfs/issues/1300#issuecomment-230002065>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA3wxUKvoyamVHdjymRItDBaDiZPNbckks5qRUyAgaJpZM4IzPBl>
> .
>



-- 
Rob Hafey
Senior Software Developer
Simulation Training & Education Lab (SiTEL) of MedStar Health
robert.j.hafey@medstar.net
202.364.5180 x1219 (office)
301.503.6922 (cell)

www.sitel.org


CONFIDENTIAL: The information contained in this communication, including
its attachments may contain confidential information and is intended only
for the individual (s) or entity (ies) to whom it is addressed . The
information contained in this communication may also be protected by legal
privilege , federal law or other applicable law. If you are not the
intended recipient of this communication , you are hereby notified that any
distribution, dissemination or duplication of this communication is
strictly prohibited. If you have received this communication in error
please immediately delete and destroy all copies of this message and please
immediately notify us of the error by separate communication.
