### ISSUE TITLE
git lfs fetch --all fails in bare git repo

### ISSUE THREAD

**Issue by xen2** [github/git-lfs#1307]
From my understanding, it should work. However, it fails with:
> Git can't resolve ref: "HEAD"

Problem is probably https://github.com/github/git-lfs/blob/master/commands/command_fetch.go#L54
git.CurrentRef() should be skipped when --all is specified

**Comment by ttaylorr** [comment]
👋  Thanks for this! I just pushed a branch which should resolve this issue.

**Comment by xen2** [comment]
Thanks for the quick fix!
