### ISSUE TITLE
Issue having Git LFS work with Teamcity

### ISSUE THREAD

**Issue by lcsthom** [github/git-lfs#1308]
I'm trying to get LFS automatically checkout files on my agent but I get a "Bad credential" when it tries to connect to our github enterprise url.

Is there a procedure to make it work over https? I already fixed the issue I had with the certificate by not precising the url in the config :
[http]
    sslcainfo = path to ca

As well I added the lfs config and it works if I try to fetch a repo directly from the agent but not with teamcity.

I'm using the last version of Teamcity and the 1.2.0 of git-lfs.

Can you advise me on where I should look?

**Comment by technoweenie** [comment]
Is your enterprise instance using an HTTPS cert that's not trusted by the server? Git LFS v1.2 should respect git's `http.sslcainfo` option though. Can you give some more details on the error?

**Comment by lcsthom** [comment]
Well we use a certificate which should be trusted. Anyway, it must be otherwise we couldn't even push or pull from the repository.
And I didn't use the noverify option so the certificate is probably used to secure the transaction. I do really think this is the url : [https http://githubenterprise/orga/repo] that is wrongly parsed.

**Comment by technoweenie** [comment]
You can check Git LFS's parsing by running `git lfs env`:

```bash
$ git lfs env
git-lfs/1.3.1 (GitHub; darwin amd64; go 1.6.3; git 4fa440f)
git version 2.9.2

Endpoint=https://github.com/github/git-lfs.git/info/lfs (auth=none)
Endpoint (epriestley)=https://github.com/epriestley/git-lfs.git/info/lfs (auth=none)
```

If you still see issues, can you post the following:

* Your git config: `git config --list`
* The output of `git lfs env`
* The output of `GIT_TRACE=1 git lfs ...` (I'm not sure what command you're running to get the bad credential error message).

Thanks!
