### ISSUE TITLE
LFS parallel transfers for git read-tree

### ISSUE THREAD

**Issue by woopla** [github/git-lfs#1314]
I'm using the sparse-checkout trick to selectively download files from an LFS-enabled repo. It boils down to:
```
# No files for you
git clone --no-checkout

# Prep list of files
git config --local core.sparsecheckout true
echo '*!' > .git/info/sparse-checkout
echo '.gitattributes' >> .git/info/sparse-checkout
echo 'file1' >> .git/info/sparse-checkout
...
echo 'fileX' >> .git/info/sparse-checkout

# Go go go!
git read-tree -mu HEAD
```

This causes all files to be downloaded sequentially by LFS. No amount of `-c lfs.concurrenttransfers=10` added to `git read-tree` helps.

Is this somewhere on the roadmap?

Thanks,

Clément

**Comment by larsxschneider** [comment]
Untested, but this could work:
```
git -c filter.lfs.smudge=cat read-tree -mu HEAD
git-lfs pull
```

Alternatively try:
```
git lfs clone
```

**Comment by woopla** [comment]
`git lfs clone` won't work since it will download the whole repository.

I also tried your first suggestion @larsxschneider, but LFS will download all the files in the archive (same things that `git lfs clone` does).

I'm open to suggestions.

Thanks,

Clément

**Comment by technoweenie** [comment]
@woopla look at [the include/exclude options](https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-pull.1.ronn) for the `git lfs pull` command. Building off of @larsxschneider's suggestion:

```
git -c filter.lfs.smudge=cat read-tree -mu HEAD
git-lfs pull -I file1
```
