### ISSUE TITLE
Pre-push failure with git-lfs 1.2

### ISSUE THREAD

**Issue by alex-davidson** [github/git-lfs#1318]
When attempting to push to an LFS-enabled GitHub repo using git-lfs 1.2, we get an error about filename or extension being too long.

(Repo and organisation names have been replaced with names of the same length)

* The repository is private.
* The repository is ~200MB in size with ~4.23GB of LFS objects.
* The LFS storage is nowhere near our quota limit.
* The machine attempting the push is running Windows 10 64-bit and Git for Windows 2.8.1.
* The same operation works fine with git-lfs 1.1.2.
* The error occurs even if the ref being pushed points to a commit which already exists on the remote.
* The longest path in the working copy of the branch being pushed is 159 characters, *including* the E:\dev\repo\ prefix.
* The longest path in the repository history is 224 characters, *excluding* the E:\dev\repo\ repository location.
* Unfortunately I am unable to provide access to the repository for testing.

The checkout and push commands:
```
$ git checkout -b spike/push-test origin/master
Branch spike/push-test set up to track remote branch master from origin by rebasing.
Switched to a new branch 'spike/push-test'

$ git push -u origin HEAD
Error scanning for Git LFS files

Errors logged to E:\dev\repo\.git\lfs\objects\logs\20160622T094314.4887767.log
Use `git lfs logs last` to view the log.
error: failed to push some refs to 'git@github.com:MyGitHubOrganisation/repo.git'
```

The contents of the log:
```
git-lfs/1.2.0 (GitHub; windows amd64; go 1.6.1; git 386c5d8)
git version 2.8.1.windows.1

$ git-lfs pre-push origin git@github.com:MyGitHubOrganisation/repo.git
Error scanning for Git LFS files

fork/exec C:\Program Files\Git\mingw64/libexec/git-core\git.exe: The filename or extension is too long.
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/lfs/errors.go:566 +0x87
github.com/github/git-lfs/commands.logPanicToWriter(0x11c42c0, 0xc08215c008, 0x11c45c8, 0xc0821f42d0)
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:195 +0xf87
github.com/github/git-lfs/commands.logPanic(0x11c45c8, 0xc0821f42d0, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:159 +0x419
github.com/github/git-lfs/commands.handlePanic(0x11c45c8, 0xc0821f42d0, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:134 +0x55
github.com/github/git-lfs/commands.LoggedError(0x11c45c8, 0xc0821f42d0, 0xa25b40, 0x20, 0x0, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:84 +0x89
github.com/github/git-lfs/commands.Panic(0x11c45c8, 0xc0821f42d0, 0xa25b40, 0x20, 0x0, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:94 +0x64
github.com/github/git-lfs/commands.prePushCommand(0xc52000, 0xc0821163a0, 0x2, 0x2)
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/command_pre_push.go:78 +0x618
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xc52000, 0xc0821161e0, 0x2, 0x2, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x3fb
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xc536c0, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x593
github.com/github/git-lfs/commands.Run()
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:99 +0x2a
main.main()
        C:/Users/techn/go/src/github.com/github/git-lfs/git-lfs.go:34 +0x135

ENV:
LocalWorkingDir=E:\dev\repo
LocalGitDir=E:\dev\repo\.git
LocalGitStorageDir=E:\dev\repo\.git
LocalMediaDir=E:\dev\repo\.git\lfs\objects
LocalReferenceDir=
TempDir=E:\dev\repo\.git\lfs\tmp
ConcurrentTransfers=3
BatchTransfer=true
GIT_PREFIX=
```

**Comment by javabrett** [comment]
Can you try with:

`git config --system core.longpaths true`

**Comment by alex-davidson** [comment]
Sorry, I should've mentioned we'd tried that too. It had no effect: same error, everything.

**Comment by ttaylorr** [comment]
@alex-davidson sorry to hear you're having troubles! Do you know what OS (and version) the other machine was running, by chance?

**Comment by alex-davidson** [comment]
The other machine (my home one) is set up pretty much identically in terms of OS, etc. 
{{
git-lfs/1.2.0 (GitHub; windows amd64; go 1.6.1; git 386c5d8)
git version 2.8.3.windows.1
}}
So it has a slightly newer version of Git installed. I'm pretty sure one of those at work suffering from this issue has 2.8.3 as well, though.

We've worked around the immediate problem by rolling back to LFS 1.1.2, which is adequate for our purposes. If I have the time I'll set up a Go environment and try debugging this directly.

**Comment by alex-davidson** [comment]
The machine which is not working returns the following from ```git config --global -l```:
```
filter.lfs.clean=git-lfs clean %f
filter.lfs.smudge=git-lfs smudge %f
filter.lfs.required=true
```

The machine which is working does not have these entries, and its output from ```git lfs env``` includes:
```
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""
```

Apart from that, they're configured identically. Git-lfs appears to be running on both, ie. I find the large binaries in the working copy rather than the pointer files.

**Comment by alex-davidson** [comment]
OK, so this machine finally seemed to 'notice' that filter.lfs.* setting and stopped checking out blobs automatically. I've run ```git lfs install``` and it is now configured the same as the failing one.

It's still happy to push, though...

**Comment by technoweenie** [comment]
That error is something weird with your setup:

> fork/exec C:\Program Files\Git\mingw64/libexec/git-core\git.exe: The filename or extension is too long.

Coming from `lfs.ScanRefs()`](https://github.com/github/git-lfs/blob/v1.2.0/commands/command_pre_push.go#L76-L79). Unfortunately, some context is lost, so we can't tell [which specific command is blowing up](https://github.com/github/git-lfs/blob/v1.2.0/lfs/scanner.go#L138-L151).

Can you try pushing with `GIT_TRACE=1 git push -u origin HEAD`? That'll give us some more detail.

**Comment by MaciejKucia** [comment]
I had similar issue. The temporary solution was to run
`git remote prune origin`
but this seems to be not enough anymore. I have quite a lot of refs as well:
`git for-each-ref | wc -l `
results in number 1982

The log:
```
$ git lfs logs last
git-lfs/1.2.1 (GitHub; windows amd64; go 1.6.2; git 79bedeb)
git version 2.9.0.windows.1

$ git-lfs pre-push origin ssh://[repo].git
Error scanning for Git LFS files

fork/exec C:\Program Files\Git\mingw64/libexec/git-core\git.exe: The filename or extension is too long.
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
/Users/rick/go/src/github.com/github/git-lfs/lfs/errors.go:566 +0x87
github.com/github/git-lfs/commands.logPanicToWriter(0x3a42c0, 0xc082192008, 0x3a45c8, 0xc082337e60)
/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:197 +0xf87
github.com/github/git-lfs/commands.logPanic(0x3a45c8, 0xc082337e60, 0x0, 0x0)
/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:161 +0x419
github.com/github/git-lfs/commands.handlePanic(0x3a45c8, 0xc082337e60, 0x0, 0x0)
/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:136 +0x55
github.com/github/git-lfs/commands.LoggedError(0x3a45c8, 0xc082337e60, 0xa2a720, 0x20, 0x0, 0x0, 0x0)
/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:86 +0x89
github.com/github/git-lfs/commands.Panic(0x3a45c8, 0xc082337e60, 0xa2a720, 0x20, 0x0, 0x0, 0x0)
/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:96 +0x64
github.com/github/git-lfs/commands.prePushCommand(0xc5a000, 0xc08210e6e0, 0x2, 0x2)
/Users/rick/go/src/github.com/github/git-lfs/commands/command_pre_push.go:78 +0x618
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xc5a000, 0xc08210e520, 0x2, 0x2, 0x0, 0x0)
/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x3fb
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xc5b6c0, 0x0, 0x0)
/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x593
github.com/github/git-lfs/commands.Run()
/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:101 +0x2a
main.main()
/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:34 +0x135

ENV:
LocalWorkingDir=C:\[repo]
LocalGitDir=C:\[repo].git
LocalGitStorageDir=C:\[repo].git
LocalMediaDir=C:[repo]\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\[repo]\.git\lfs\tmp
ConcurrentTransfers=5
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
GIT_PREFIX=
```
push with trace:
```
$ GIT_TRACE=1 git push
21:50:16.490034 git.c:350               trace: built-in: git 'push'
21:50:16.568034 run-command.c:336       trace: run_command: 'ssh' '-p' '7999' 'git@[repo]' 'git-receive-pack '\''/repo/repo.git'\'''
21:50:20.580034 run-command.c:336       trace: run_command: '.git/hooks/pre-push' 'origin' 'ssh://git@[repo].git'
21:50:21.675034 git.c:563               trace: exec: 'git-lfs' 'pre-push' 'origin' 'ssh://git@[repo].git'
21:50:21.675034 run-command.c:336       trace: run_command: 'git-lfs' 'pre-push' 'origin' 'ssh://git@[repo].git'
trace git-lfs: run_command: git rev-list --objects f4a15651d50333d843b88906fd46787f03c4fcbd --not refs/remotes/origin/ …. [long long list of refs]
```

**Comment by MaciejKucia** [comment]
Is it possible to revert into `git rev-list --objects <sha1> --not --remotes=origin` version?

**Comment by alex-davidson** [comment]
I think this was introduced by bb1239855a12f29cd9129ba3f7a6811ef42968b7, 'Check actual remote refs when scanning excluding remote refs', which seems like an entirely reasonable change. If the local repo contains any 'remote' refs which don't actually exist on the remote, git-lfs needs to be explicit about which refs to include.

Pruning the local repo does appear to be the correct fix, barring a more heavyweight solution to the same problem.

I wonder under what sort of circumstances ```git prune remote <name>``` would fail to resolve this?

**Comment by MaciejKucia** [comment]
What I am observing is: When I try to `git push` the command fails with (command is too long):
`trace git-lfs: run_command: git rev-list --objects dd9342056b2a0133a5a5543387a2b309cafe930b --not refs/remotes/origin/...[long long list]`
but succeeds with:
`trace git-lfs: run_command: git rev-list --objects dd9342056b2a0133a5a5543387a2b309cafe930b --not --remotes=origin --`

`git remote prune` does not help anymore because of large number of 'healthy' branches. It probably does help when executed every time before `git push` as the `--remotes=origin` option is executed when `missingRefs` inside `revListArgsRefVsRemote` is 0.

On **Windows** there is a limitation to `revListArgsRefVsRemote` where `missingRefs` can store a limited numer of references. To be honest I have no idea how this can be fixed.

PS. It would be nice to have this thread labelled as 'bug'.

**Comment by alex-davidson** [comment]
I don't suppose the meaning of ```--stdin``` depends on its position in the argument string? Something like ```git rev-list --objects A --not --stdin --``` might be an elegant solution if so.

Otherwise, am I correct in thinking that ```git rev-list --objects A --not B C``` is semantically equivalent to the intersection of ```git rev-list --objects A --not B``` and ```git rev-list --objects A --not C``` ? Could then do it with multiple length-limited invocations and a merge join.

**Comment by alex-davidson** [comment]
I'm not fluent in Go and it looks like making this change would be quite involved. The ```func revListArgsRefVsRemote``` is only generating a command line and doesn't get to play with STDIN, so a refactoring would be required. My employer's unlikely to let me spend time learning how to fix this, but I might have a shot at it while I'm on holiday next week. Can anyone see any problems with refactoring revListShas to permit revListArgsRefVsRemote to somehow submit content for STDIN?

**Comment by technoweenie** [comment]
The [`rev-list`](https://git-scm.com/docs/git-rev-list) `--stdin` flag doesn't accept flags like `--not`. Maybe they can be added with a `^` prefix though.

@MaciejKucia Marked as a bug now :)

**Comment by shtse8** [comment]
```
/var/www/site/www/static# GIT_TRACE=1 git push
14:42:23.838521 git.c:344               trace: built-in: git 'push'
14:42:23.838687 run-command.c:334       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/shtse8/NovelFeed-Web.git'
14:42:24.621427 run-command.c:334       trace: run_command: 'git credential-cache get'
14:42:24.622758 run-command.c:193       trace: exec: '/bin/sh' '-c' 'git credential-cache get' 'git credential-cache get'
14:42:24.626568 git.c:561               trace: exec: 'git-credential-cache' 'get'
14:42:24.626631 run-command.c:334       trace: run_command: 'git-credential-cache' 'get'
14:42:25.446179 run-command.c:334       trace: run_command: 'git credential-cache store'
14:42:25.448065 run-command.c:193       trace: exec: '/bin/sh' '-c' 'git credential-cache store' 'git credential-cache store'
14:42:25.451646 git.c:561               trace: exec: 'git-credential-cache' 'store'
14:42:25.451708 run-command.c:334       trace: run_command: 'git-credential-cache' 'store'
14:42:25.454408 run-command.c:334       trace: run_command: '.git/hooks/pre-push' 'origin' 'https://github.com/shtse8/NovelFeed-Web.git'
14:42:25.457100 git.c:561               trace: exec: 'git-lfs' 'pre-push' 'origin' 'https://github.com/shtse8/NovelFeed-Web.git'
14:42:25.457172 run-command.c:334       trace: run_command: 'git-lfs' 'pre-push' 'origin' 'https://github.com/shtse8/NovelFeed-Web.git'
trace git-lfs: run_command: 'git' version
trace git-lfs: pre-push: refs/heads/master 8cdb506694bbdf319f37da3988583c1e4c5c1aaa refs/heads/master 3dff10a95bcfc3f332b716e906526f205d53a750
trace git-lfs: run_command: git rev-list --objects 8cdb506694bbdf319f37da3988583c1e4c5c1aaa --not --remotes=origin --
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
```

I have the same issue when i push and it hangs

**Comment by ttaylorr** [comment]
Hi @shtse8; could you please make sure that you are running the latest version of Git LFS, and then open a new issue if the problem persists?
