### ISSUE TITLE
Write permission to main repo required to push Git LFS file 

### ISSUE THREAD

**Issue by mahammedasif** [github/git-lfs#1319]
We are using github enterprise 2.5 and we are using Git LFS to manage the large files used in our project.

Pulling Git LFS file from repositories currently works very well. However, when pushing Git LFS files to a repository or a forked repository, write permission to the main repository is required and this conflicts with our repositories' ownership philosophy as the main repo is owned by someone else. When a user tries to write Git LFS files to a repo, errors like "No ID found" will spawn. 

Please check whether there is any solution available for this or propose what can be done in these situations.

**Comment by technoweenie** [comment]
Did you send in a github enterprise support request? That's the recommended channel for server issues like this. I'm actually working on a patch for this today, that should get backported for the next 2.5.x and 2.6.x releases.
