### ISSUE TITLE
git lfs clone does not use repository config settings

### ISSUE THREAD

**Issue by gogodave** [github/git-lfs#1320]
If you use "git lfs clone" to clone a repository that has repository level lfs config (e.g., a .lfsconfig file that contains a fetchexclude setting), the clone ignores the repository config.

**Comment by ttaylorr** [comment]
Hi @gogodave! Thanks for opening this issue.

I added support for both the `-I` and `-X` flags in `git lfs clone` (like `git lfs fetch -{I,X}`), as well as support for reading the include/exclude paths in `.lfsconfig` (or `.gitconfig`, for older versions of LFS) if that file is checked into your remote repository.

The pull-request in question is https://github.com/github/git-lfs/pull/1321. Let me know if that works for you! Thanks again.

**Comment by technoweenie** [comment]
Closing this, since #1321 is merged, and will be in Git LFS v1.3.
