### ISSUE TITLE
Why Git-lfs can't be integrated with Git-base? My system is Windows 7.

### ISSUE THREAD

**Issue by heicks** [github/git-lfs#1325]
Why Git-lfs can't be integrated with Git-base? My system is Windows 7.how do use?
I enter the command prompt for git-lfs in Git-base
```
Administrator@username MINGW64 /d/Program Files/Github/Clone/-SS (Master)
$LFS Git
'lfs'is not a git: git command. See'git --help'.
You mean this Did?
Flow

//my Git version 
$Git --version 
Version 2.8.3.windows.1 Git

```
But I installed the git-lfs application on this web site at https://git-lfs.github.com/.

**Comment by technoweenie** [comment]
Did you install with the windows installer? The `git-lfs.exe` file needs to live in your system path so that git can find it when you run `git lfs ...`.  Also, the next Git For Windows release should include Git LFS: https://github.com/git-for-windows/build-extra/pull/110

**Comment by heicks** [comment]
Yes, I installed, but the git-lfs Why do not you git-base integrated together? 50M maximum limit or cancel, I do not understand.

**Comment by technoweenie** [comment]
Git LFS isn't integrated with Git because we're not part of the core team, and I don't think it's a feature that makes sense for the majority of Git users.
