### ISSUE TITLE
Git LFS uses the wrong paths when used with cygwin Git

### ISSUE THREAD

**Issue by TomyLobo** [github/git-lfs#1326]
https://gist.github.com/TomyLobo/cf8c7cc7cf9f98800f3182368a1cc718
It also ignores LANG=C, so sorry about the germanese :)

As you can see near the bottom of the shell session and all over the log file, Git LFS stores its objects in ``C:\home\...`` instead of ``/home/...`` (which would correspond to ``C:\cygwin64\home\...``)

**Comment by technoweenie** [comment]
Thanks for the report. I don't think any of the LFS developers use Cygwin, so we would need a submitted patch to fix this.

**Comment by TomyLobo** [comment]
It's free, easy to install and you can just delete C:\cygwin64 when you're done :)

**Comment by technoweenie** [comment]
Closing this issue. Still interested in a cygwin patch though.

**Comment by TomyLobo** [comment]
@technoweenie This issue is not fixed. Why did you close it?

**Comment by technoweenie** [comment]
Cygwin support is not a priority at all right now due to very low interest from users, and no Windows developers on the LFS team. If you're interested in maintaining Cygwin support for LFS, you're welcome to submit a patch. Otherwise, we're only supporting the Git shell that's installed with Git for Windows.

**Comment by deweysasser** [comment]
@technoweenie I also need cygwin support.  I suspect cygwin people find that things don't work and just go somewhere else (e.g. gitolite works just fine).  In short, if you supported cygwin, github.com would now be collecting storage money from me.

**Comment by technoweenie** [comment]
This seems like an issue with cygwin and the git-lfs client, so I'm not sure how it'd work with gitolite and not github. Can you elaborate?

**Comment by ardneran** [comment]
@technoweenie I also need cygwin support. I primarily develop in a windows 7 environment for a linux target platform. Is there another open issue I can track? This forces me to switch over to linux development environment which I would really prefer not pursuing. I'm happy to be a guinea pig if you need one.

**Comment by cclu** [comment]
I also need cygwin support. +1

**Comment by ttaylorr** [comment]
Cygwin support is still not on our list of priorities. The LFS team is currently focused elsewhere, on improving the resiliency and efficiency of transfers with large numbers of objects.

I don't think anyone else on @git-lfs/core uses Cygwin, but we'd be happy to help in terms of reviewing a PR.

**Comment by sschuberth** [comment]
> Cygwin support is not a priority at all right now due to very low interest from users, and no Windows developers on the LFS team.

That's not quite true anymore, as I (and I believe also @larsxschneider) primarily use Windows. In any case, I wonder what the reason for Windows users is to use Cygwin when Git for Windows comes with MSYS?

**Comment by ardneran** [comment]
The reason at least for us is dependency enforced by repo script which was written to support linux platforms.

**Comment by sschuberth** [comment]
> [..] repo script which was written to support linux platforms.

True. It's a shame that Google decided to use Python as a cross-platform scripting language, but still implement repo in a platform-specific way. Anyway, you might be interested in [this fork](https://github.com/esrlabs/git-repo) by E.S.R. Labs which supports Windows quite well.

As a side note, Google is going to [deprecate repo in favor of submodules](https://storage.googleapis.com/gerrit-talks/summit/2016/bye-bye-repo.pdf).

**Comment by cpages** [comment]
I understand this issue was the same as https://github.com/git-lfs/git-lfs/issues/865 and  thus is fixed by https://github.com/git-lfs/git-lfs/pull/1820? Can anyone confirm?
