### ISSUE TITLE
Add HTTP error 507 to the git-lfs protocol

### ISSUE THREAD

**Issue by green-coder** [github/git-lfs#1327]
I think it makes sense to have the HTTP error 507 (Insufficient Storage) in a Large File Server. The LFS protocol currently doesn't list this error in the optional codes to be returned by the server in case of problem.

I request to add it.

**Comment by technoweenie** [comment]
Thanks for the suggestion. Sounds good to me :)

**Comment by technoweenie** [comment]
Added this to the roadmap in #1438
