### ISSUE TITLE
How to add large file after commited.[question]

### ISSUE THREAD

**Issue by aaBaO** [github/git-lfs#1328]
Here is my problem.
One month ago,i had commited my changes without track my large files.
And now i want to track my large files,but i failed.
Here is the log:
`remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lE
fs.github.com.`
I track `*.psd` files in my repo.There is nothing when i input `git lfs ls-files`.

**Comment by aaBaO** [comment]
I found the solution of my question.
1. remove the tracked large files
`$ git rm --cached giant_file`
2. commit the change
3.retrack the large files

But i still want to know is there other way to do this?

**Comment by aaBaO** [comment]
Now i can get file list when i use `git lfs ls-files`
But when i use `git push`, it still failed!
here is the logs:
Git LFS: (0 of 7 files, 7 skipped) 0 B / 494.03 MB, 494.03 MB skipped
Counting objects: 1718, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (1716/1716), done.
Writing objects: 100% (1718/1718), 173.31 MiB | 425.00 KiB/s, done.
Total 1718 (delta 873), reused 0 (delta 0)
remote: warning: File Assets/Tugeleba/UI/background_grass_right/gressright_sheet.psd is 77.17 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File Assets/Tugeleba/UI/background_grass_left/gressleftSheet.psd is 70.21 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File Assets/Tugeleba/UI/fengche/fengcheSheet.psd is 52.32 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 17bdd887a0f825873a384b1b807a3fa9
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Assets/Tugeleba/UI/fish/fishSheet.psd is 123.04 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File Assets/Tugeleba/UI/logo/logoSheet.psd is 143.36 MB; this exceeds GitHub's file size limit of 100.00 MB
To git@github.com:NexTrigger/AR_tugeleba.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@github.com:NexTrigger/AR_tugeleba.git'

**Comment by jspillers** [comment]
➕1 👍 to handling this case more gracefully. Tracking a large file after it has already been added to a repo is the situation most people are going to run into when first using git-lfs. Maybe at least update the site homepage and repo README files to make everyone aware of this gotcha? Figuring out that I had to first remove a large file before tracking it definitely cost me some time and frustration.

**Comment by technoweenie** [comment]
@aaBaO That just means you have to go back further in history to fix files that were added but not pushed. Amending commits older than the latest can be tricky. Usually I reset to the latest commit that the server has, fix the bad files, and then make a single new commit to push.

1. `git branch foo` (create a new branch at the current commit as a backup)
2. `git reset {sha}`
3. Fix the files that should be using lfs
4. `git commit -m ...`
5. `git push`

@jspillers I definitely would love to have better git-lfs tools to detect and guide you in fixing these issues, and user docs beyond the man pages.

**Comment by aaBaO** [comment]
@jspillers @technoweenie Thanks for reply.
I solve my problem.It failed because i don't amend the commit which i had commit my large file, it has the old file history, so i always failed when i push.
Reset to the parent commit of this commit can solve this.
And it's really better to update README and tell everyone the right worlflow with git-lfs~

**Comment by whoaitsaimz** [comment]
This command was a lifesaver for me. Somehow I ended up with a non-lfs tracked version of a file in my local working copy (even though it said it was being tracked), so all my pushes were failing.  The way I fixed it was:
"git lfs fetch --all github"

https://www.atlassian.com/git/tutorials/git-lfs#moving-between-hosts

**Comment by adumont** [comment]
I found there's a git lfs migrate that does the trick:

git lfs migrate import --include="*.bin"

credits: https://github.com/git-lfs/git-lfs/issues/1933#issuecomment-351275765

**Comment by PhilipeFernandino** [comment]
> I found there's a git lfs migrate that does the trick:
> 
> git lfs migrate import --include="*.bin"
> 
> credits: [#1933 (comment)](https://github.com/git-lfs/git-lfs/issues/1933#issuecomment-351275765)

To anyone reading this in the future: be cautious. Not only did this corrupt all of my PSDs, but it also rewrote the entire history. I don't know if I'll be able to recover, but this is not a safe solution—perhaps not a solution at all.
