### ISSUE TITLE
"Object not found on the server" When Merging between remote repositories.

### ISSUE THREAD

**Issue by DavidGunderman-WGCells** [github/git-lfs#1333]
I'm encountering errors whenever I try to merge git-lfs stored assets between remote repositories. Is this a supported feature?

The second repository was "forked" from the first by copying the contents, adding them to git, committing them, and finally merging with the upstream remote. Everything is happy when merging non-lfs stored assets between the two repositories. However, if I were to push lfs-stored assets to the main repository and then try to merge that to the forked repository, I get an error. It seems like no matter what I do with the git config file or in lfsconfig config file to set lfs urls, it cannot find the asset. 

Here are the links to my repositories:
* https://github.com/DavidGunderman-WGCells/lfsMergeTest
* https://github.com/DavidGunderman-WGCells/lfsMergeTestForked

To reproduce the issue:
1. checkout the lfsMergeTestForked/master branch
2. create the upstream remote to https://github.com/DavidGunderman-WGCells/lfsMergeTest.git
3. fetch upstream/master branch
4. merge upstream/master

This will result in an error stating that it was unable to download the object. Using the _git lfs logs last_ command to view the log shows the "Object not found on the server" error.

**Comment by DavidGunderman-WGCells** [comment]
Can anyone at least speak to whether or not merging git-lfs assets between separate remote repositories is supported?

**Comment by technoweenie** [comment]
Blah, sorry for missing this. Busy week :)

It sounds like you'll have to push the data to the fork's lfs server before merging and checking it out locally:

```bash
# from the working dir of the original repo
$ git lfs push origin master
$ git lfs push fork master
```

You can also run `git lfs push --all {remote-name}`, which will scan every branch and tag for objects to upload.

**Comment by DavidGunderman-WGCells** [comment]
Thank you for the help. I'm new to git and am still wrapping my head around things.

Your solution worked after jumping through a few hoops. I scrapped my forked repo and ran the test in a new one since it was easy and allowed me to quickly test it.

If I look at the merged file on GitHub, instead of seeing the image itself and a message saying it's stored in git lfs, I see something that looks like this:
`version https://git-lfs.github.com/spec/v1
oid sha256:01692d5166ba46d4c5ae0ed4e417016869afa3da1fb950f86c92708fb3a11eba
size 132414`

Is that expected? Everything locally appears fine so I'm inclined to think it's working as intended.

**Comment by DavidGunderman-WGCells** [comment]
Closing the issue. Everything appears to be working after pushing the git-lfs assets to the separate remote repository. The only thing that appears out of the normal is how GitHub displays these assets (as mentioned above). If this is found to be an issue, I will re-open this ticket.

**Comment by technoweenie** [comment]
@DavidGunderman-WGCells That's what GitHub shows currently if the object (`01692d5166ba46d4c5ae0ed4e417016869afa3da1fb950f86c92708fb3a11eba` in your example) is not stored on GitHub, or you don't have LFS enabled. If you're using another LFS server outside of GitHub, then it doesn't know how to access the file. We can look into it if you send some details to https://github.com/contact.

**Comment by DavidGunderman-WGCells** [comment]
In this case, everything is stored in GitHub and using git-lfs. I only started seeing it after pushing git-lfs assets to the fork before merging. I'll type something up now and send it to you using the link provided.

**Comment by DavidGunderman-WGCells** [comment]
I've been trying to reproduce the issue to figure out what I did to get those results but haven't succeeded yet. If I create a new repository and populate it using the source assets, everything works fine. I just need to remember to push the lfs assets to the forked repository before merging new/modified assets or it'll complain about not finding them.

If I do manage to break it again, I will writeup the repo steps and send them to the link you provided.

For those curious, here's what I did when it worked:
I had a repository A that I wanted to fork from so I created an empty repository B and pushed the content from A to B using the following commands in A's working directory:

`git remote add fork repositoryBsUrlGoesHere
git push -u fork master`

This created a new remote in A called fork and pushed everything to the fork's repository. If I look at the files in B on GitHub I see that they're being "Stored with Git LFS" as expected.

Later, if I add content to A that I want to merge and push into B, I need to push A's lfs content to B and then pull A into B before pushing those changes. For example:
In A's working directory:
`git lfs push fork master`
In B's working directory (assuming you've configured an upstream remote that target's A's repository):
`git pull upstream master
git push master origin`

This flow appears to work. I'm guessing I can specify specific files to push/pull if I don't want to merge the entire repo but I haven't tried that yet.

**Comment by dammittom** [comment]
I came in just to tell you this saved my life! I had a bunch of issues with trying to sync a fork with LFS stuff - and going the route of pushing the LFS content from the original repo over to the fork looks like it's working. Thank you!

**Comment by dammittom** [comment]
Nm I was wrong - I'm still getting "Object does not exist on the server" errors
