### ISSUE TITLE
git lfs prune server command

### ISSUE THREAD

**Issue by blasto333** [github/git-lfs#1336]
Not sure if this is even possible; but it would be nice to prune the server that holds the files. I used bfg to remove a bunch of lfs file references in my repo but they had to be manually deleted on the lfs server. I don't know much about how the server part of lfs is setup; but it would be nice if this cleanup was automatic or accessible via a command.

**Comment by technoweenie** [comment]
While a really good point, this isn't something applicable to the `git lfs` client tool right now. Each server potentially implements things very differently, so there's no common solution that we can provide here.
