### ISSUE TITLE
config setting for progress reporting in bytes.

### ISSUE THREAD

**Issue by hbons** [github/git-lfs#1337]
This would make it a lot easier for apps using git-lfs to parse, calculate, and format the reported sizes when transferring files.

**Comment by ttaylorr** [comment]
Do you mean you always want the progress meter to show `downloaded / total` in bytes, regardless of how large the number is (see: [meter.go](https://github.com/github/git-lfs/blob/7ee533f646ea7d76afcd073556c445bab420aa2b/progress/meter.go#L158-L171))?

**Comment by hbons** [comment]
Yes. Of course you'd never want to present it to users in this way. It would make automation a lot easier if git-lfs could skip the formatting step by way of a setting or passed flag.

**Comment by technoweenie** [comment]
@hbons Can you describe specifically what you're trying to do? We do integrate with GitHub Desktop, so it's possible that Git LFS can already do what you need. If not, we'll at least have a better idea what you want :)

**Comment by hbons** [comment]
Let me try to explain a bit better. :) I'm integrating git-lfs into [SparkleShare](https://www.github.com/hbons/SparkleShare/), a dropbox like experience for Git. I use the OS's status item to report progress of the download/upload progress. I just parse the command line output to get the progress, however, I'd like to use slightly different formatting when displaying the sizes and possibly make a sum or average of the progress when multiple repos are syncing at the same time. So having this progress output available in just a number of bytes makes this much easier to do, and prevents breakage in the future. A bit like a porcelain.

**Comment by technoweenie** [comment]
Ah, try setting `GIT_LFS_PROGRESS=/abs/path/to/file`. GH Desktop shows upload/download progress by processing the updates to the file.  I'm not sure how it got left out of documentation :(

This just writes out a [simple string](https://github.com/github/git-lfs/blob/74a228f7ecb62186bad0820f73c3e35624f21bfc/lfs/util.go#L53) like:

    # downloaded 235 bytes, on the first of 2 files
    download 1/2 235/236672 foo.bar

**Comment by ttaylorr** [comment]
I added documentation in https://github.com/github/git-lfs/pull/1469, which should clarify how to use this option. Let me know if you have any further questions! 😄
