### ISSUE TITLE
How to properly mirror remote with LFS

### ISSUE THREAD

**Issue by Danand** [github/git-lfs#1338]
Hi there!
Our team consists of two subteams located in different offices.
There is slow connection and I'd like to `git clone --mirror` _far remote_ to make _near remote_ in local network for second subteam.
I've found similar [issue](https://github.com/github/git-lfs/issues/515) here, but I'd prefer just to manually `git fetch` and `git lfs pull` in _near remote_ when I want second team up to date (so as `git push` from _near remote_). Including LFS content of course.
So the question is how to set up LFS server for second team.

![lfs-remote-mirror](https://cloud.githubusercontent.com/assets/2430493/16487365/da09b39a-3ee3-11e6-9dcb-8308b3b7d33f.png)

**Comment by shane-kearns** [comment]
`git lfs fetch --all` will mirror the LFS objects into your repo created with `git clone --mirror`.
That's only a small piece of the puzzle though.

**Comment by technoweenie** [comment]
I think you'd want some kind of lfs server hosted in your LAN that can serve as a cache. This is out of scope for the Git LFS client, but would be a really cool project.

**Comment by yhl3692319** [comment]
@shane-kearns Hi, `git lfs fetch --all` can mirror the LFS objects into the repo-A created with `git clone --mirror`. But when I clone the repo-A from `near`, I can't download LFS objects in my local repo.

**Comment by technoweenie** [comment]
> But when I clone the repo-A from near, I can't download LFS objects in my local repo.

That's because LFS requires a running HTTP server for downloads. There are some ideas around supporting a local-only workflow like you describe, but it's not on our roadmap now. If someone wants to take that on, we'd be more than happy to provide coaching and code review.

**Comment by momcilo78** [comment]
I have possibly a similar use case.
Lets assume the following scenarion:
- far remote is non-lfs enabled, and contains lots of binaries
- near remote is lfs enabled and we wish to mirror with LFS

This means we we would need to specify .gitattributes file, which in turn will modify local repository. (if I got it right this will disrupt the mirroring from far).

What is the correct way to handle this?

**Comment by technoweenie** [comment]
> This means we we would need to specify .gitattributes file, which in turn will modify local repository. (if I got it right this will disrupt the mirroring from far).

That is correct. The two remotes are storing essentially two completely different repositories, from Git's point of view. LFS can't function as a pass through proxy to a plain repository like that.

**Comment by rotanov** [comment]
I've stumbled upon similar problem. Let's say I have a sync script operating on far server.
Performing `git lfs fetch --all` will fetch lfs objects into `./<repo>/lfs/objects` is there any way to fetch them directly into local lfs storage on server omitting existing files? 
i.e. basically I want to perform this on far server:
```
for each remote in repo:
  for each lfs-object in remote:
    if not lfs-server.exist(lfs-object):
      lfs-server.fetch(lfs-object, remote-url)
```

**Comment by doodoori2** [comment]
This issue was closed. and this is out of scope for the Git LFS client. 
Is there any thread for this discussion?

**Comment by rotanov** [comment]
> I'm also want to run miror/proxy/cache for local network.
> and I lfs-objects have to sync near/far each other.
> 
> This issue closed, and this is out of scope for the Git LFS client.
> Is there any thread for this discussion?

Yep I also think it's LFS server dependent in my case it's gitlab. They already have this https://gitlab.com/gitlab-org/gitlab-ce/issues/41843 issue, I think it's related.

Also I gave up on the idea to replicate via pull model directly on server. Instead I switched to separate clone and push model where on service syncs from multiple remotes and pushes to everyone. There's also some issues with this, but I came with a workaround here https://github.com/git-lfs/git-lfs/issues/3503

**Comment by rotanov** [comment]
You may also try to manually copy fetched lfs objects to local lfs storage on the server if not present yet and use something for deduplication.

**Comment by andyneff** [comment]
This can now be done with @sinbad 's https://github.com/sinbad/lfs-folderstore

When you are setting up _near_
```
git clone --mirror far .
git lfs fetch --all
```

---

To use it, you would
```
GIT_LFS_SKIP_SMUDGE=1 git clone near ....
cd {repo dir}
git config lfs.standalonetransferagent lfs-folder
git config lfs.customtransfer.lfs-folder.args "/some/network/or/local/dir/lfs/objects"
git config lfs.customtransfer.lfs-folder.path "/path/to/lfs-folderstore-linux-amd64/lfs-folderstore"
```

---

Push from _near_ back to _far_? Well, _far_ and _near_ are now "forks" really, so it'll depend on your workflow strategy what works best, but as for lfs is concerned, I think `git lfs push --all` does the trick.

Of course, if it was a submodule using lfs, you could `config` for that submodule too.

**Comment by xloem** [comment]
Hey, I found this thread from Google, and if it's okay seems helpful to mention that git-annex[git annex](https://git-annex.branchable.com/)  has supported this since its inception.  The smallest solution for this use-case might be to make a git-lfs external special remote for git-annex if one doesn't already exist.  External special remotes speak a simple line-based protocol.

**Comment by mhoffrog** [comment]
Refer to https://github.com/git-lfs/git-lfs/issues/2342#issuecomment-3538818344
