### ISSUE TITLE
PackageCloud repo missing redhat/centos 5 packages for 1.2.x

### ISSUE THREAD

**Issue by shane-kearns** [github/git-lfs#1343]
The most recent el5 rpm on https://packagecloud.io/github/git-lfs is for the 1.1.1 release.
Is there an incompatibility with the 1.2.x releases, or are the packages missing because of low interest?

I have observed a problem with lfs checkout of a file with a utf8 filename under centos 5/git-lfs 1.1.1, which does not occur with ubuntu 14.04 / git lfs 1.2.1.

**Comment by technoweenie** [comment]
Packages are missing because of low interest and issues with the docker scripts that build the packages. You could install it from one of the [linux downloads](https://github.com/github/git-lfs/releases), but I realize this isn't a desirable way to install software.

**Comment by shane-kearns** [comment]
Thanks - the 1.2.1 Linux AMD64 package seems to solve the checkout problems.

**Comment by ttaylorr** [comment]
Sounds good!
