### ISSUE TITLE
Support the `expires_at` property

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#1345]
The git lfs client currently [supports the `expires_at` property on objects](https://github.com/github/git-lfs/blob/master/docs/api/v1.3/http-v1.3-batch-response-schema.json#L17-L19), but doesn't actually do anything with it. I'd like the client to actually look at it to potentially retry batch transfers on expired objects.

If a user is uploading 100 objects, they get back 100 URLs that may include one time use, expiring tokens (such as through S3 authentication). Right now, the client will blindly try to make the request any way, and then report a 403 error. If it noticed the `expires_at` has passed, it should resend that object to the batch API to get a fresh token.

**Comment by ttaylorr** [comment]
I can take this on Tuesday 🇺🇸

**Comment by ttaylorr** [comment]
Did some digging before the week gets started, and I think I implemented the check we're looking for here, but I want to check on Tuesday to make sure it's correct before I go in and write the test.

Tracking my progress branch: #1350.

**Comment by ttaylorr** [comment]
#1350 is merged, and this issue is no longer. Hooray!
