### ISSUE TITLE
git lfs push stalls

### ISSUE THREAD

**Issue by sivakhno** [github/git-lfs#1348]
git lfs push origin master stalls after transferring around 20 files  (i.e. the upload progress line stops updating). I have tried different “concurrent transfers” settings (3, 10 and 20) to no avail. There are 415 files taking in total 13.71 GB. Any suggestions as there is no warning / error generated?
Thanks
**Environment:** 
git-lfs/1.1.0 (GitHub; linux 386; go 1.5.1; git 258acf1)
git version 2.6.3
ConcurrentTransfers=3
BatchTransfer=true
git config filter.lfs.smudge = "git-lfs smudge %f"
git config filter.lfs.clean = "git-lfs clean %f"

**Comment by MaciejKucia** [comment]
Your LFS and Git are very old. I would start with upgrade.

 Component | Version | Current Version 
---------------- |---------------- | ---------------- 
 LFS | 1.1.0 | 1.2.1 
 Git | 2.6.3 | 2.9.0

**Comment by technoweenie** [comment]
@sivakhno If you continue to have problems on the latest, can you run with `GIT_TRACE=1`? That should give more info about what it's doing.

**Comment by ZDL-zyndo** [comment]
@sivakhno Did you figure this out? Seeing similar stalls -- my git and git lfs are up to date, I'm getting stalls at ~1gb every time (out of a pretty big 45gb repo). Any ideas?
