### ISSUE TITLE
[NOTE] use Jenkins to work with git-lfs

### ISSUE THREAD

**Issue by panpan0000** [github/git-lfs#1353]
if you are running git-lfs with Jenkins automation
it may be mess up with Jenkins Git-plugin.
especially, you will see **git-reset** failed ,make big-files become **small** pointer files 
the problem can be recreated like this:

(1) Jenkins with Git plugin
(2) write SH scripts 

- git lfs clone https://user:pwd@github.com/your-repo/Big-Files.git            (note  if you wan to use ‘git clone’ directly, instead of "git lfs clone", I believe it willl download only pointer..  )
- cd Big-Files
- git status
- du * -sh
- git reset --hard HEAD^
- du * -sh
 

==========
the **solution** is to add '** git lfs install**' at the beginning of jenkins script(before git clone)

**Comment by ttaylorr** [comment]
Hi, @panpan0000 -- thanks for opening this issue! Our website and documentation both recommend running `git lfs install` (see: https://git-lfs.github.com/), so I'm going to close this issue out for now.

If you have any other problems with Git LFS please don't hesitate to open another issue here!

**Comment by MarkEWaite** [comment]
The Jenkins [git plugin 3.1.0 release](https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin#GitPlugin-ChangeLog) 4 Mar 2017 includes large file support.
