### ISSUE TITLE
Support direct download from github.com

### ISSUE THREAD

**Issue by fedorov** [github/git-lfs#1357]
In my view, it would be nice if git-lsf-managed files could be downloaded using "Clone or download" button in the repository view on github.com. As of now, only the pointers to the files managed by git-lfs are downloaded.

**Comment by technoweenie** [comment]
Thanks for the request, but this has nothing to do with the open source git-lfs project :) Feel free to add reactions if you want to show your support to our product team for this feature.

**Comment by fedorov** [comment]
I was wondering where this feature request fits. I guess I should submit to github support (a.k.a. "black hole").

**Comment by fedorov** [comment]
I am also confused by your response (as indicated by my reaction). When you say "our product team" are you talking about github product team? What is the relationship of that team to "the open source git-lfs project" team?

**Comment by fedorov** [comment]
Finally, reading over the front-page instructions of https://github.com/github/git-lfs, it is not clear at all how it can be used separately from github.com. You are only describing the client side, and there is no word on alternative server sides, or server-side setup instructions.

Sorry, I do realize this goes well beyond this one issue, but this is because I am confused!

**Comment by technoweenie** [comment]
Yes, the GitHub product team. You can reach our support at https://github.com/contact

Git LFS requires a Git host that supports the LFS API, or a separate LFS API server.  Implementations: https://github.com/github/git-lfs/wiki/Implementations

**Comment by fedorov** [comment]
Thanks!

Support reached, and the request duly noted here: https://github.com/isaacs/github/issues/712
