### ISSUE TITLE
GitLFS 1.2.0 not pushing files

### ISSUE THREAD

**Issue by panjandrum** [github/git-lfs#1364]
Hi,

When I modify binary content and try to push, gitlfs is skipping that file
Git LFS: (0 of 1 files, 1 skipped) 0 B / 275.87 KB
Counting objects: 13, done.
Delta compression using up to 16 threads.
Compressing objects: 100% (13/13), done.
Writing objects: 100% (13/13), 1.89 KiB | 0 bytes/s, done.
Total 13 (delta 8), reused 0 (delta 0) 

Thanks in advance!
BR/ M

**Comment by technoweenie** [comment]
That means the server has it already. Are you having any problems?

**Comment by panjandrum** [comment]
Hi

Server doesn't have it.
I'm using Artifactory Enterprise 4.7.7 rev 40199 as a server.

BR/ Maciej Lech

**Comment by technoweenie** [comment]
Can you re-run with `GIT_CURL_VERBOSE=1 git push ...`?  That will show the http requests and responses that cause the client to think it can skip the object.

**Comment by panjandrum** [comment]
```
> POST /artifactory/api/lfs/proj-test-lfs-local/objects/b...
> POST /artifactory/api/lfs/proj-test-lfs-local/objects/batch HTTP/1.1
> Host: XXXXXXXXXXXXXXXXXXXXX
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/1.2.0 (GitHub; linux amd64; go 1.6.1; git 9bd3b8e)
>
{"objects":[{"oid":"5fe0fde28af791b86bd5e9969fe9a09b295b44cb1336fab04aaef18677750343","size":282493}],"operation":"upload"}

< HTTP/1.1 200 OK
< Connection: close
< Transfer-Encoding: chunked
< Content-Type: application/vnd.git-lfs+json
< Date: Wed, 13 Jul 2016 08:45:45 GMT
< Server: Artifactory/4.7.7
< Set-Cookie: ROUTEID=.art2; path=/artifactory/
< X-Artifactory-Id: 462bb25b0f6b35edfe8f4917d5aecd5656bd9de1
< X-Artifactory-Node-Id: XXXXXX
<
{
  "objects" : [ {
    "oid" : "5fe0fde28af791b86bd5e9969fe9a09b295b44cb1336fab04aaef18677750343",
    "size" : -1
  } ]
Git LFS: (0 of 1 files, 1 skipped) 0 B / 275.87 KB
Counting objects: 13, done.
Delta compression using up to 16 threads.
Compressing objects: 100% (13/13), done.
Writing objects: 100% (13/13), 1.89 KiB | 0 bytes/s, done.
Total 13 (delta 8), reused 0 (delta 0)
remote: Resolving deltas: 100% (8/8)
remote: Processing changes: updated: 1, refs: 1, done
remote: (W) 2691f22: no files changed, message updated
remote:
remote: Updated Changes:
remote:   https://xxxxxxxxxxxxxxxxx XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
remote:
To ssh://xxx@gerrit.xxxxxxxxxxxxxxxxxx
 * [new branch]      HEAD -> refs/for/develop 

```

**Comment by technoweenie** [comment]
This looks like a bad response from Artifactory:

```json
{
  "objects" : [ {
    "oid" : "5fe0fde28af791b86bd5e9969fe9a09b295b44cb1336fab04aaef18677750343",
    "size" : -1
  } ]
}
```

If there's a problem with the object, Artifactory should be sending an `error` property according to the [api spec](https://github.com/github/git-lfs/blob/2900456efe5e5ac3a6387dbbb73796d1fee50c5b/docs/api/v1/http-v1-batch.md#successful-responses):

```json
{
  "objects" : [ {
    "oid" : "5fe0fde28af791b86bd5e9969fe9a09b295b44cb1336fab04aaef18677750343",
    "size" : -1,
    "error": {
      "code": 404,
      "message": "Object does not exist on the server"
    }
  } ]
}
```

**Comment by technoweenie** [comment]
I filed #1368 to further clarify the spec, and add client reporting of the bad response.

**Comment by nadav-y** [comment]
Hi,

This issue is now fixed, and Artifactory is now returning the error property in the batch response.
You can see Artifactory 5.0.0 [(release notes)](https://www.jfrog.com/confluence/display/RTF/Release+Notes#ReleaseNotes-Artifactory5.0), Along with it we've fixed some other minor Git LFS issues.

Jiras - [RTFACT-12947](https://www.jfrog.com/jira/browse/RTFACT-12947), [12951](https://www.jfrog.com/jira/browse/RTFACT-12951)

**Comment by ttaylorr** [comment]
> This issue is now fixed, and Artifactory is now returning the error property in the batch response.

@nadav-y -- thank you so much!

As an aside, I noticed that in [RTFACT-12947](https://www.jfrog.com/jira/browse/RTFACT-12947), Artifactory still responds with the deprecated `_links` property (which is now called `actions`, as per [this spec](https://github.com/git-lfs/git-lfs/blob/v2.0.1/docs/api/batch.md)).

We have code (via #2004) that will deal with this in a backwards compatible way, so this doesn't require any immediate changes.

**Comment by nadav-y** [comment]
Hi @ttaylorr,
Thanks for letting me know!
I've opened a Jira ticket [RTFACT-13920](https://www.jfrog.com/jira/browse/RTFACT-13920), you can follow it if you like. (btw our Jira is public so everyone could opened a ticket for us)
I'll go over the API again to see what else is needed

Thanks again,
Nadav

**Comment by ttaylorr** [comment]
@nadav-y thanks. I'm not sure how to create an account in order to comment on that ticket, but the property is named "actions" (plural), not "action".

**Comment by nadav-y** [comment]
typo :) fixed
