### ISSUE TITLE
GitLFS retry possibility

### ISSUE THREAD

**Issue by panjandrum** [github/git-lfs#1365]
Hi,

Is there possibility to automatically retry downloading objects after fail?

Thanks in advance!
P

**Comment by technoweenie** [comment]
Git LFS v1.3 will include a resumable download transfer adapter. The retry system could be tweaked to do more retries too. It already retries downloading once per object. Thanks for the feedback.

**Comment by panjandrum** [comment]
Hi,

I'm using 1.2.0. Can I set auto retransmission somehow?

P

**Comment by sinbad** [comment]
Not right now, unless you grab the source version from master right now and build it yourself.
