### ISSUE TITLE
Clarify API spec around responses

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#1368]
I want to clarify in the spec that the object size property is in bytes, and should be positive. Also, the client should point this out to the end user, instead of assuming that the object is ok. Here's a sample batch api response from #1364:

```json
{
  "objects" : [ {
    "oid" : "5fe0fde28af791b86bd5e9969fe9a09b295b44cb1336fab04aaef18677750343",
    "size" : -1
  } ]
}
```

**Comment by ttaylorr** [comment]
Closed in #1371 😄
