### ISSUE TITLE
GetAuth method does not handle multiple Www-Authenticate headers

### ISSUE THREAD

**Issue by VladimirKhvostov** [github/git-lfs#1377]
GetAuthType method in https://github.com/github/git-lfs/blob/master/httputil/request.go#L174 only takes into first WWW-Authenticate header into account. If server sends the following headers:
```
WWW-Authenticate: Bearer
WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM
```
the code returns "basic", which is definitely not correct in this case.
```GO
func GetAuthType(res *http.Response) string {
	auth := res.Header.Get("Www-Authenticate")
	if len(auth) < 1 {
		auth = res.Header.Get("Lfs-Authenticate")
	}
	if strings.HasPrefix(strings.ToLower(auth), "ntlm") {
		return "ntlm"
	}
	return "basic"
}
```
This code will fix the issue:
```GO
func GetAuthType(res *http.Response) string {

       authHeaders := res.Header["Www-Authenticate"]

       for i := range authHeaders {
              auth := authHeaders[i]
              if strings.HasPrefix(strings.ToLower(auth), "ntlm") {
                     return "ntlm"
              }
       }

       auth := res.Header.Get("Lfs-Authenticate")

       if strings.HasPrefix(strings.ToLower(auth), "ntlm") {
              return "ntlm"
       }
       return "basic"
}
```

**Comment by technoweenie** [comment]
That's a good idea. I would just extract out a small helper function like:

```go
// getAuthTypeFromHeader("Www-Authenticate")
// getAuthTypeFromHeader("Lfs-Authenticate")
func getAuthTypeFromHeader(key string) {
       authHeaders := res.Header[key]

       for i := range authHeaders {
              auth := authHeaders[i]
              if strings.HasPrefix(strings.ToLower(auth), "ntlm") {
                     return "ntlm"
              }
       }
       return ""
}
```

**Comment by VladimirKhvostov** [comment]
Sounds good. I submitted the following PR: https://github.com/github/git-lfs/pull/1378

**Comment by derrickstolee** [comment]
An aside: Why does LFS prioritize the Www-Authenticate header over an Lfs-Authenticate header? Shouldn't the more specific header be used?

**Comment by ttaylorr** [comment]
@derrickstolee Good point. I'm wondering if the `Lfs-Authenticate` header be the more specific one in this case.

**Comment by VladimirKhvostov** [comment]
It really does not matter in which order we process headers, because we will keep looking until we find a header that supports NTLM.

**Comment by derrickstolee** [comment]
I was thinking that hard-coding NTLM may not be the right solution if the server can specify the authentication method for LFS separate from the other WWW headers. Perhaps the server is using HTTPS and prefers using basic authentication for LFS.

While there are only two authentication options, it is probably fine to leave it as-is.
