### ISSUE TITLE
BatchAPI:Want information that can identify the file.

### ISSUE THREAD

**Issue by HimaJyun** [github/git-lfs#1380]
In the current specification has sent the following such Json.
```
{
	"objects": [
		{
			"oid": "e5b844cc57f57094ea4585e235f36c78c1cd222262bb89d53c94dcb4d6b3e55d",
			"size": 10485760
		}
	],
	"operation": "upload"
}
```

It seems that it is preferable to send the information that can identify the file (for example, a file path, etc.).
```
{
	"objects": [
		{
			"path": "/path/on/the/client/src/foo/bar.png",
			"oid": "e5b844cc57f57094ea4585e235f36c78c1cd222262bb89d53c94dcb4d6b3e55d",
			"size": 10485760
		}
	],
	"operation": "upload"
}
```
By this way, the server can provide a variety of functions using the difference between the past version. (For example, such as the reduction of repository size by binary patch)

**Comment by ttaylorr** [comment]
I'm not sure that this is something that should be supported right now. LFS objects are [content-addressable](https://en.wikipedia.org/wiki/Content-addressable_storage) on the server, not path-addressable as is likely the case with files on your computer.

I would definitely be interested to hear more about the benefits of having files be path-addressable on the server, so I'll leave this issue open for discussion. 😄

**Comment by HimaJyun** [comment]
oid is always a unique value.
In the current json, the server will not be able to know changed file.
Therefore, we propose a function of notifying the files that have been modified to lfs server.

For example, I have thought of such a method.
File is assumed to be located in the following manner.
```
/
|-.git/
|-.gitattributes
|-images/
||-foo.png
```
Here it sends a foo.png to lfs server.
lfs has sent such a json to server.
```
{
	"objects": [
		{
			"oid": "f627ca4c2c322f15db26152df306bd4f983f0146409b81a4341b9b340c365a16",
			"size": 102400
		}
	],
	"operation": "upload"
}
```
foo.png has been changed.
lfs has sent such a json to server.
```
{
	"objects": [
		{
			"oid": "0f6d7219c5295725e733b9910ae259ef98106a4bc7b388b513e707440f4da5cf",
			"size": 102401
		}
	],
	"operation": "upload"
}
```
The server, there is no way to associate the two files that are sent.
lfs will propose to include the file path.
```
{
	"objects": [
		{
			"path": "images/foo.png",
			"oid": "0f6d7219c5295725e733b9910ae259ef98106a4bc7b388b513e707440f4da5cf",
			"size": 102401
		}
	],
	"operation": "upload"
}
```
Or, it may be old oid.
```
{
	"objects": [
		{
			"old_oid": "f627ca4c2c322f15db26152df306bd4f983f0146409b81a4341b9b340c365a16",
			"oid": "0f6d7219c5295725e733b9910ae259ef98106a4bc7b388b513e707440f4da5cf",
			"size": 102401
		}
	],
	"operation": "upload"
}
```
By doing so, lfs server is able to associate the two files.
This , for example, lfs server can offer the following features.
- Saving disk space by binary patch.
- View the change point of the file in a Web browser. (image, etc.)
- Download the old version from the web browser.
- , etc....The possibilities are endless.

Thanks for reading.
lfs is a very good way.

**Comment by technoweenie** [comment]
I wouldn't mind adding it, but it's really easy to send spoofed information to the server. A git server can already build up those relationships based on the git data.

**Comment by HimaJyun** [comment]
OK, Thanks!!
My program will try to improve to refer to the git repository.
