### ISSUE TITLE
Some LFS files have gone sideways: always showing as modified

### ISSUE THREAD

**Issue by karlmdavis** [github/git-lfs#1383]
## Background
I honestly have no clue what happened here. I haven't touched any of the LFS content in my repository in weeks, but it's still somehow gone sideways on me. Today, I was working on a merge (that didn't involve these files!), went to push my changes, and got an error saying that my push to GitHub was rejected because I was trying to push files that were too large. Which is odd, since I wasn't.

Lo and behold, though, I went to look at the merge commit history and all of my LFS files had slipped into it somehow. Don't know why or how. Anyways...

## The Sitch
So, I need to drop that merge commit, figure out how it ended up including the LFS noise, and then recreate it without. Easy enough! Just whip out my trusty old `git rebase -i` and...

```
$ git rebase -i
Cannot rebase: You have unstaged changes.
Please commit or stash them.
```

Huh, that's odd. Wonder what's there.

```
$ git status
On branch rif-load-to-fhir-initial
Your branch is ahead of 'origin/rif-load-to-fhir-initial' by 23 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   bluebutton-data-pipeline-sampledata/src/main/resources/pharmacy-names.csv
        modified:   bluebutton-data-pipeline-sampledata/src/main/resources/prescriber-names.csv

no changes added to commit (use "git add" and/or "git commit -a")
```

That's weird. Those two files are in LFS, and I definitely haven't modified them. Looking at `git diff`, it seems that the LFS-pulled content has been replaced by just the LFS pointer file. Oh well, let's blow them away and re-checkout.

```
$ rm bluebutton-data-pipeline-sampledata/src/main/resources/prescriber-names.csv
$ GIT_TRACE=1 git checkout -- bluebutton-data-pipeline-sampledata/src/main/resources/prescriber-names.csv                                                   
trace: built-in: git 'checkout' '--' 'bluebutton-data-pipeline-sampledata/src/main/resources/prescriber-names.csv'
trace: run_command: 'git-lfs smudge '\''bluebutton-data-pipeline-sampledata/src/main/resources/prescriber-names.csv'\'''
trace: exec: '/bin/sh' '-c' 'git-lfs smudge '\''bluebutton-data-pipeline-sampledata/src/main/resources/prescriber-names.csv'\''' 'git-lfs smudge '\''bluebut
ton-data-pipeline-sampledata/src/main/resources/prescriber-names.csv'\'''
$ git status
On branch rif-load-to-fhir-initial
Your branch is ahead of 'origin/rif-load-to-fhir-initial' by 23 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   bluebutton-data-pipeline-sampledata/src/main/resources/pharmacy-names.csv
        modified:   bluebutton-data-pipeline-sampledata/src/main/resources/prescriber-names.csv

no changes added to commit (use "git add" and/or "git commit -a")
```

And that's where I'm at: I can't figure out how to un-sidewaysify this repo. Any ideas on what went wrong and how I might correct it?

**Comment by karlmdavis** [comment]
Just for background detail:

```
$ git lfs env
git-lfs/1.2.1 (GitHub; linux amd64; go 1.5.3)
git version 1.9.1

Endpoint=https://github.com/HHSIDEAlab/bluebutton-data-pipeline.git/info/lfs (auth=none)
  SSH=git@github.com:HHSIDEAlab/bluebutton-data-pipeline.git
LocalWorkingDir=/home/karl/workspaces/cms/bluebutton-data-pipeline.git
LocalGitDir=/home/karl/workspaces/cms/bluebutton-data-pipeline.git/.git
LocalGitStorageDir=/home/karl/workspaces/cms/bluebutton-data-pipeline.git/.git
LocalMediaDir=/home/karl/workspaces/cms/bluebutton-data-pipeline.git/.git/lfs/objects
LocalReferenceDir=
TempDir=/home/karl/workspaces/cms/bluebutton-data-pipeline.git/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
git config filter.lfs.smudge = "git-lfs smudge %f"
git config filter.lfs.clean = "git-lfs clean %f"
```

**Comment by ttaylorr** [comment]
Can you paste the contents of your `.gitattributes` file?

**Comment by karlmdavis** [comment]
Oh, of course. Sorry for forgetting that. Here it is:

```
$ cat .gitattributes 
bluebutton-data-pipeline-desynpuf/src/main/resources/de-synpuf/sample-1.tar.bz2 filter=lfs diff=lfs merge=lfs -text
bluebutton-data-pipeline-desynpuf/src/main/resources/de-synpuf/sample-test-a.tar.bz2 filter=lfs diff=lfs merge=lfs -text
bluebutton-data-pipeline-desynpuf/src/main/resources/de-synpuf/sample-test-b.tar.bz2 filter=lfs diff=lfs merge=lfs -text
bluebutton-data-pipeline-sampledata/src/main/resources/pharmacy-names.csv filter=lfs diff=lfs merge=lfs -text
bluebutton-data-pipeline-sampledata/src/main/resources/prescriber-names.csv filter=lfs diff=lfs merge=lfs -text
bluebutton-data-pipeline-desynpuf/src/main/resources/de-synpuf/sample-test-c.tar.bz2 filter=lfs diff=lfs merge=lfs -text
bluebutton-data-pipeline-desynpuf/src/main/resources/de-synpuf/sample-test-d.tar.bz2 filter=lfs diff=lfs merge=lfs -text
```

**Comment by ttaylorr** [comment]
Thanks for sending that along. Try removing these two lines from your `.gitattributes`:

```
bluebutton-data-pipeline-sampledata/src/main/resources/pharmacy-names.csv filter=lfs diff=lfs merge=lfs -text
bluebutton-data-pipeline-sampledata/src/main/resources/prescriber-names.csv filter=lfs diff=lfs merge=lfs -text
```

and then running `git checkout --` on both of those files. After that, run `git lfs track` on the two files again, and try again 😄

**Comment by ikriz** [comment]
Having the same issue, directly after a clone there are various modified files (all LFS files) without even touching the directory. after git attribute removal and checkout git lfs track it sets the files as modified again.

**Comment by technoweenie** [comment]
@ikriz Can you file a new issue with your `.gitattributes` and the `git status` output? That way we can look at your issue without disturbing other people in this thread unnecessarily. Thanks.

Also, to clarify: Having a file in `.gitattributes` doesn't really mean the file is currently stored on an LFS server. It just means that the next time a file is passed to `git add`, or a file is checked out, the LFS filter will run. If your repository is changed after a clone or pull, it usually means that Git blob for the file contains the actual contents, and not the LFS pointer.  You can confirm this with `git ls-tree`:

```bash
$ cat .gitattributes
git-lfs/**/*.* filter=lfs -crlf

$ git ls-tree master -rl | grep psd
100644 blob 4e72f9c1ccea2c80d1db2223f39f138e735f5162     131	git-lfs/psds/100.psd
100644 blob 6803d7016916e4ec7c099f0db29ac842d7122cdd     131	git-lfs/psds/1000-2.psd
100644 blob fe42e5c42823b8a4765b798f03a05bed358705c3     130	git-lfs/psds/1000.psd
100644 blob fe42e5c42823b8a4765b798f03a05bed358705c3     130	git-lfs/psds/300.psd
100644 blob 23007b9da3225933fa431106895b1086e8542992     132	git-lfs/psds/jurrasic_github.psd
100644 blob 68e4bf6655c0b9e6414f8a5e75f6848f63558469     131	git-lfs/psds/octicons-bg.psd
100644 blob 6da4de13e24b9c831339bb32a4a778ea581f7460     132	git-lfs/psds/v3-Screens.psd
100644 blob 75dbb4d2201fc1df113ef8a608c5472eceea3188  174884	psds/100.psd
100644 blob fc6afc783039aec392bb6e69b86f2cdda906ed40  160632	psds/1000-2.psd
100644 blob faa5424573d1d4e3289cc27d334c6665b6eedb49   50780	psds/1000.psd
100644 blob faa5424573d1d4e3289cc27d334c6665b6eedb49   50780	psds/300.psd
100644 blob 512c451fd5e807a82d3fe6726eea3a1ca1b30b1e  105082	psds/a-file.psd
100644 blob a4c0922219589574dfc0b914a078cd73b7b21dea 6308114	psds/jurrasic_github.psd
100644 blob d01a90e5122c9fcc16aa8a085996c135f15d0972  194561	psds/octicons-bg.psd
100644 blob 8d47cd4879ed653b9a77ff50988ae23423625f11 2751195	psds/v3-Screens.psd
```

If Git LFS notices a file matching a `filter=lfs` pattern in `.gitattributes`, it will convert the file to LFS Pointer, causing it to appear changed to Git.

How can your Git repository get into this state? 

1. Someone ran `git lfs track ...` on Git LFS _before_ v1.2.0 (see #1104)
2. Someone updated `.gitattributes` manually, without updating the matching files to use LFS.

Let us know if you're seeing something completely different. I just ask that we keep the issue threads separate to each reporter of the issue.

**Comment by cosmoc** [comment]
So - if this happens, what is the remedy?     We have a large number of LFS files and would not want to touch each one individually.    So, from the earlier post, is the remedy to delete all LFS file pattern lines from the .gitattributes, run git checkout  on all of those file, which maybe can be done using a file pattern, and then re-stating the git lfs track for each pattern?       I also do not want to risk re-introducing large files in the the git repo history.

**Comment by ferrouswheel** [comment]
So to clarify this behaviour, which I'm also experiencing:

- When someone does a checkout, and there are git blobs for files that match what git-lfs wants to track, git-lfs will automatically change these to pointers?
- One way this could happen is if someone adds a git-lfs tracked file without having git-lfs installed (using plain old git).
- This means those with git-lfs, when they do a checkout, will immediately see the files as modified.

It would be good to confirm how this works, because at one point when doing a merge I saw this behaviour only for some git-lfs files, but not for all. Then when I did a fresh checkout it detected all the git-lfs files as modified.

**Comment by technoweenie** [comment]
@ferrouswheel that is indeed how it works. Note that this isn't necessarily something LFS is doing on purpose. Git is running the files through the `clean` filter (which is configured for LFS) to see if it has changed. I wish there was a way to know if the `clean` filter is being invoked from `git add`, or something else.

If you are tracking file types, and there are matches that aren't using LFS, my suggestion would be to confirm that the file contents have not changed, and make the commit. Running `git lfs status` should tell you if the change is _only_ a Git -> LFS conversion.

**Comment by ferrouswheel** [comment]
Cool - thank you for the clarification @technoweenie :-)
