### ISSUE TITLE
Provide Ubuntu 12.04 packages

### ISSUE THREAD

**Issue by dankegel** [github/git-lfs#1387]
Turns out it's not too hard to coax the package to build on Ubuntu 12.04;
see http://kegel.com/linux/build-git-lfs-on-ubuntu-12.04.sh.txt

Users have to install a newer git from a PPA, but that's ok.

Yes, I know, Ubuntu 12.04 is ancient, but some of us poor sods have to support apps on it for a while yet.

**Comment by technoweenie** [comment]
Hi @dankegel, my understanding is that our packages are pretty simple. We currently build for debian 7 and 8, and then upload them to our package repo at packagecloud for various linux flavors according to [this distro map](https://github.com/github/git-lfs/blob/7baff5624d2a76ce9c7a5d64bd53a96cfeb6d544/script/packagecloud.rb#L39-L53). It looks like packagecloud already supports Ubuntu 12.04 as "ubuntu/precise". The latest Git LFS has an Ubuntu package here: https://packagecloud.io/github/git-lfs/packages/ubuntu/precise/git-lfs_1.2.1_amd64.deb

Does that work for you?

**Comment by dankegel** [comment]
Yes, they seem fine.  Thanks for pointing that out.  For some reason I couldn't see that -- I think the fact that https://packagecloud.io/github/git-lfs/ is unsorted threw me.

(It would be Really Useful to have a ppa with those packages, though.  It would reduce the friction for ubuntu users significantly.  For one, they wouldn't have to get used to the unsorted packagecloud thing...)
