### ISSUE TITLE
Git LFS exe files are getting line ending issues

### ISSUE THREAD

**Issue by glennawatson** [github/git-lfs#1402]
The LFS files that are being generated are causing me line ending issues.

It seems that the line endings don't match the settings in my .gitattributes file 

It will automatically check the file out for.

```
# Set the default behavior, in case people don't have core.autocrlf set.
* text=auto

# Basic .gitattributes for a MATLAB repo.
# This template includes Simulink and MuPAD extensions, in addition
# to the MATLAB extensions.

# Source files
# ============
*.m             text
*.mu            text

# Caution: *.m also matches Mathematica packages.

# Binary files
# ============
*.p             binary
*.mex*          binary
*.fig           binary
*.mat           binary
*.mdl           binary
*.slx           binary
*.mdlp          binary
*.slxp          binary
*.sldd          binary
*.mltbx         binary
*.mlappinstall  binary
*.mlpkginstall  binary
*.mn            binary

# Documents
*.doc	 diff=astextplain
*.DOC	 diff=astextplain
*.docx diff=astextplain
*.DOCX diff=astextplain
*.dot  diff=astextplain
*.DOT  diff=astextplain
*.pdf  diff=astextplain
*.PDF	 diff=astextplain
*.rtf	 diff=astextplain
*.RTF	 diff=astextplain
*.md text
*.adoc text
*.textile text
*.mustache text
*.csv text
*.tab text
*.tsv text
*.sql text

# Graphics
*.png binary
*.jpg binary
*.jpeg binary
*.gif binary
*.tif binary
*.tiff binary
*.ico binary
*.svg binary
*.eps binary

# Custom for Visual Studio
*.sln text eol=crlf
*.csproj text eol=crlf
*.vbproj text eol=crlf
*.fsproj text eol=crlf
*.dbproj text eol=crlf

*.vcxproj text eol=crlf
*.vcxitems text eol=crlf
*.props text eol=crlf
*.filters text eol=crlf

#sources
*.c text
*.cc text
*.cxx text
*.cpp text
*.c++ text
*.hpp text
*.h text
*.h++ text
*.hh text

# Compiled Object files
*.slo binary
*.lo binary
*.o binary
*.obj binary

# Pre-compiled Headers
*.gch binary
*.pch binary

# Compiled Dynamic libraries
*.so binary
*.dylib binary
*.dll binary

# Compiled Static libraries
*.lai binary
*.la binary
*.a binary
*.lib binary

# Database files
*.ldf binary
*.mdf binary

# Executable
*.exe binary
*.out binary
*.app binary

# C-Sharp
*.cs     diff=csharp

# LFS
*.bin filter=lfs diff=lfs merge=lfs -text
*.gz filter=lfs diff=lfs merge=lfs -text
*.jffs2 filter=lfs diff=lfs merge=lfs -text
*.zip filter=lfs diff=lfs merge=lfs -text
*.a filter=lfs diff=lfs merge=lfs -text
*.pdf filter=lfs diff=lfs merge=lfs -text
*.exe filter=lfs diff=lfs merge=lfs -text
*.apk filter=lfs diff=lfs merge=lfs -text
*.avi filter=lfs diff=lfs merge=lfs -text
*.chm filter=lfs diff=lfs merge=lfs -text
*.mp4 filter=lfs diff=lfs merge=lfs -text
*.wma filter=lfs diff=lfs merge=lfs -text
*.ldf filter=lfs diff=lfs merge=lfs -text
*.mdf filter=lfs diff=lfs merge=lfs -text
*.mp4 filter=lfs diff=lfs merge=lfs -text
*.myo filter=lfs diff=lfs merge=lfs -text
*.vsmdi filter=lfs diff=lfs merge=lfs -text
```

**Comment by ttaylorr** [comment]
Hi, @glennawatson, thanks for opening this issue, and attaching your `.gitattributes`. Can you provide me with a little more info about what specifically is wrong with the line endings?

**Comment by glennawatson** [comment]
Hi @ttaylorr

This issue happens on windows with git 2.9.2 and lfs 1.2. 1

Essentially it seems they are written on windows with just cr. Every time we change branches we have git marking the file as modified due to it converting the text in the staging area to cr lf. This causes issues changing branches since you can't undo the change since git will modify again.

**Comment by technoweenie** [comment]
Can you replicate this issue on a sample repository with that same `.gitattributes` file? What about a smaller one with only the LFS section? 

Git LFS doesn't do anything with line endings. It reads and writes the data as bytes. My hunch is that something else in that `.gitattributes` is triggering that crlf behavior.

How do you see the issues with different file types? Some in that list, like `.exe`, `.mdf`, `.ldf`, have multiple entries in .gitattributes. I wonder if Git is just doing something unexpected there?

I also noticed that `*.pdf` is in there twice:

```
*.pdf  diff=astextplain
*.pdf filter=lfs diff=lfs merge=lfs -text
```

I wonder if you'd be better off condensing the file to ensure every file pattern is in there once. For instance:

```
*.pdf filter=lfs diff=lfs merge=lfs diff=astextplain -text
```

**Comment by glennawatson** [comment]
Hi @techboweenie. Will try and reproduce today. 

Just so you know this isn't the binary downloaded that is the issue. That comes down correctly. It's the pointer file with the Sha in the staging area that is getting marked as modified.

**Comment by glennawatson** [comment]
I believe this issue is being caused by Visual Studio 2015 Update 3. 

Since they use LibGit2Sharp, they are going through and running any filters directly via a process. I suspect it's just the way they are storing the filter. 

I will lodge a bug with the Visual Studio team, since this doesn't seem to be a direct issue with git-lfs.
