### ISSUE TITLE
Respect core.hooksPath

### ISSUE THREAD

**Issue by danielbayley** [github/git-lfs#1407]
`git lfs install` currently puts `pre-push` into `.git/hooks` no matter the value of `core.hooksPath`.

https://github.com/github/git-lfs/blob/c21de411141a7536689a63e1f82bcc02f46fdf83/lfs/hook.go

**Comment by technoweenie** [comment]
Thanks for the report. Should be relatively easy to fix in v1.3.1.

**Comment by ttaylorr** [comment]
@danielbayley Thanks again for opening this. If you install Git LFS v1.3.1, this behavior is now supported. Enjoy! 😄

**Comment by danielbayley** [comment]
@ttaylorr @technoweenie That was fast… nice one 👍 I think the Homebrew formula will need a bump first though…

**Comment by ttaylorr** [comment]
@danielbayley it should be in Homebrew-core as soon as https://github.com/Homebrew/homebrew-core/pull/3551 is merged 😄
