### ISSUE TITLE
Review request - python lfs server

### ISSUE THREAD

**Issue by mgax** [github/git-lfs#1410]
Hey, I whipped together an LFS blob server for my local usage, but maybe other people find it useful. Would you care to take a look, maybe list it on the [Implementations](https://github.com/github/git-lfs/wiki/Implementations) wikipage?

https://github.com/mgax/lfs

Thanks!

**Comment by technoweenie** [comment]
Oh neat, I like how it wraps `git-http-backend` so it can function as a full git server.  Seems useful for local testing. I'd highly recommend supporting the latest LFS Batch API, however. The Legacy API has been deprecated, and support in the client will likely be removed this year.

**Comment by mgax** [comment]
> The Legacy API has been deprecated, and support in the client will likely be removed this year.

Ah, good to know. Thanks!

**Comment by ttaylorr** [comment]
Looks neat! Glad to see this is on the Wiki 😄
