### ISSUE TITLE
error: failed to push some refs

### ISSUE THREAD

**Issue by sandyleo26** [github/git-lfs#1414]
Hi,
**(Quesitons highlighted)**

I'm trying LFS with many large files (pdf, dll, exe etc) to see how far I can push the limit. I'm using github enterprise version. However, I met this error below. Tried a few times but no luck. However, I did successfully push a 100M+ file to server in another repo using LFS. **I suspect it's a quota related?**

As a new user of git lfs, **I wonder is it a good idea to put many large files like this? Is there a recommended limit in terms of size or numbers of large files tracked using LFS?** Having read #1230 I feel a bit worried about using it for production as we have lots of large files.  

Our concerns are stability and easier to use. Working offline is not an issue. Performance is not either since we update them infrequently although I don't mind some good practice to optimize it. Thanks in advance.

```
$ time git push origin master
git: 'credential-cache' is not a git command. See 'git --help'.
Git LFS: (41 of 1895 files, 1874 skipped) 184.51 MB / 3.09 GB, 2.99 GB skipped
Put http://wcmgithub.pgo.local/storage/lfs/18/objects/9edf39f1b1cfbb39100f08e46a879d882f9515f4765c1b3e95a00efc0cbdcb1d: EOF
Put http://wcmgithub.pgo.local/storage/lfs/18/objects/9edf39f1b1cfbb39100f08e46a879d882f9515f4765c1b3e95a00efc0cbdcb1d: EOF
...
Put http://wcmgithub.pgo.local/storage/lfs/18/objects/43bb4b50f920fec279f1743e92d882386708504b88eae7f1803e64171f0002b7: write tcp 192.168.20.98:56649->10.10.1.8:80: wsasend: An existing connection was forcibly closed by the remote host.
Put http://wcmgithub.pgo.local/storage/lfs/18/objects/43bb4b50f920fec279f1743e92d882386708504b88eae7f1803e64171f0002b7: write tcp 192.168.20.98:56649->10.10.1.8:80: wsasend: An existing connection was forcibly closed by the remote host.
Put http://wcmgithub.pgo.local/storage/lfs/18/objects/749cc009f1cae5c633083897e906b381aa685829fee2d7cd5e07bae543848ff7: EOF
...
error: failed to push some refs to 'http://wcmgithub.pgo.local/sleo/sheenroot.git'
```
Here's the output before error if I turn on GIT_CURL_VERBOSE
```
Git LFS: (36 of 1895 files, 1875 skipped) 182.39 MB / 3.09 GB, 2.99 GB skipped > PUT /storage/lfs/18/objects/3c5b9c4cf904365cd2bc804016424bcc21280b4cda045f834de825d3e22d81eb HTTP/1.1
> Host: wcmgithub.pgo.local
> Accept: application/vnd.github.smasher+json
> Authorization: RemoteAuth AAAAB9vEQkAfsX1ckHdy3HdW1MUgIpjwks5XoU97wA==
> Content-Type: application/octet-stream
> User-Agent: git-lfs/1.2.1 (GitHub; windows amd64; go 1.6.2; git 79bedeb)
>
Git LFS: (40 of 1895 files, 1875 skipped) 183.09 MB / 3.09 GB, 2.99 GB skipped Put http://wcmgithub.pgo.local/storage/lfs/18/objects/9edf39f1b1cfbb39100f08e46a879d882f9515f4765c1b3e95a00efc0cbdcb1d: EOF
...
```

And Here's the env
```
$ git lfs env
git-lfs/1.2.1 (GitHub; windows amd64; go 1.6.2; git 79bedeb)
git version 2.8.1.windows.1

Endpoint=http://wcmgithub.pgo.local/sleo/BronteTest.git/info/lfs (auth=basic)
LocalWorkingDir=C:\WorkSSD\sleo_Bronte_readonly
LocalGitDir=C:\WorkSSD\sleo_Bronte_readonly\.git
LocalGitStorageDir=C:\WorkSSD\sleo_Bronte_readonly\.git
LocalMediaDir=C:\WorkSSD\sleo_Bronte_readonly\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\WorkSSD\sleo_Bronte_readonly\.git\lfs\tmp
ConcurrentTransfers=3
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by ttaylorr** [comment]
Hey, @sandyleo26 -- thanks for opening this issue. Could you run the push again with `GIT_TRACE=1` in front and post the output?

```
$ GIT_TRACE=1 git push origin master
```

**Comment by sandyleo26** [comment]
Here is the output.
[push.txt](https://github.com/github/git-lfs/files/398684/push.txt)

**Comment by ttaylorr** [comment]
Looks like this is GHE. Can you have your system administrator send a Enterprise support ticket and we can take a look at those requests?

**Comment by technoweenie** [comment]
@sandyleo26 A few more clarifications:

> I suspect it's a quota related?

We're just assuming you're using GitHub Enterprise based on the url format. If you're not, ignore everything @ttaylorr and I said :)  If so, GHE has no LFS quotas. 

By sending us an Enterprise Support Bundle through a support issue, we can look for things to fix on the server side.

It is interesting that out of all the objects, pushing `9edf39f1b1cfbb39100f08e46a879d882f9515f4765c1b3e95a00efc0cbdcb1d` raised an EOF error both times. Is the push erroring on the same objects each time? Is `.git/lfs/objects/9e/df/9edf39f1b1cfbb39100f08e46a879d882f9515f4765c1b3e95a00efc0cbdcb1d` a valid file locally? 

There is definitely work to be done on the client to make these transfers more reliable. Git LFS v1.3.0 added resumable uploads and downloads (which aren't supported on LFS servers AFAIK, yet), for instance.

**Comment by jskmark** [comment]
I am getting **failed to push some refs to 'https://github.com/jskmark/name.git'**. Can someone help me getting rid of the issue.

**Comment by technoweenie** [comment]
@jskmark Sure, post a [new issue](https://github.com/git-lfs/git-lfs/issues/new) with details of your problem.
