### ISSUE TITLE
Git LFS not work at Cygwin ??

### ISSUE THREAD

**Issue by HiRepo** [github/git-lfs#1417]
Are there any plans to support the cygwin?
I'm waiting for one year. but, it didn't works.....

$git lfs pull 
-----------------------  error Code --------------------------------
Git LFS: (0 of 0 files, 2 skipped) 0 B / 0 B, 8.97 KB skipped                  Error updating the git index:
error: ..\..\..\Project\Start_T.png: cannot add to the index - missing --add option?
fatal: Unable to process path ..\..\..\home\khi\Project\HiSTD\Start_T.png

Errors logged to D:\Project\.git\lfs\objects\logs\20160804T175036.5732622.log
Use `git lfs logs last` to view the log.

**Comment by ttaylorr** [comment]
Hi, @HiRepo -- thanks for opening this issue. There is already another issue about LFS comparability with Cygwin, so I'm going to defer discussion to that instead. Thanks! 

See: https://github.com/github/git-lfs/issues/1326
