### ISSUE TITLE
Download Git LFS files using Octokit.NET

### ISSUE THREAD

**Issue by bmd-benita** [github/git-lfs#1418]
Is there any way to download Git LFS files using Octokit.NET?
Or is there any API to download (fetch) Git LFS files to our local computer?

Thanks.

**Comment by ttaylorr** [comment]
I don't believe that Octokit currently has support for the LFS API. The API, however, is documented in the [`docs/`](https://github.com/github/git-lfs/tree/master/docs) directory, if you're looking to add support, or make the HTTP calls yourself 😄
