### ISSUE TITLE
LFS cannot clone into current (empty) directory

### ISSUE THREAD

**Issue by tarka** [github/git-lfs#1431]
In LFS 1.2 this worked:

    mkdir MYPROJECT
    cd MYPROJECT
    git lfs clone git@bitbucket.org:ssmith/MYPROJECT.git .

With 1.3.1 it fails:

    $ git lfs clone git@bitbucket.org:ssmith/MYPROJECT.git .
    fatal: destination path '.' already exists and is not an empty directory.
    Error(s) during clone:
    git clone failed: exit status 128

This appears to be related to the premature initialisation of the LFS storage at the top level (see also #1231):

    $ find
    .
    ./lfs
    ./lfs/objects
    ./lfs/objects/logs
    ./lfs/tmp
    ./lfs/tmp/objects

Note that this top-level `lfs` dir is created even when the repo is cloned into it's default directory:

    $ git lfs clone git@bitbucket.org:ssmith/MYPROJECT.git
    Cloning into 'dacng'...
    remote: Counting objects: 2363, done.
    remote: Compressing objects: 100% (1724/1724), done.
    remote: Total 2363 (delta 779), reused 1846 (delta 440)
    Receiving objects: 100% (2363/2363), 34.38 MiB | 2.71 MiB/s, done.
    Resolving deltas: 100% (779/779), done.
    Checking connectivity... done.
    Git LFS: (498 of 498 files) 129.13 MB / 130.33 MB
    [] $ ll
    total 0
    drwxr-xr-x  4 ssmith wheel 136 Aug 10 10:54 .
    drwxrwxrwt 11 root   wheel 374 Aug 10 10:37 ..
    drwxr-xr-x 15 ssmith wheel 510 Aug 10 10:54 MYPROJECT
    drwxr-xr-x  4 ssmith wheel 136 Aug 10 10:54 lfs

(A workaround for this is to do a `git clone` with GIT_LFS_SKIP_SMUDGE and then `git lfs pull`.)

**Comment by tarka** [comment]
Still present in LFS 1.4.

**Comment by ttaylorr** [comment]
Hey @tarka, sorry I missed this when triaging. I knocked this one out in #1478 with a little write-up, and it should no longer be an issue. I'm planning to ship this in v1.4.1, but you're welcome to build and install LFS yourself if you need it sooner 😄

**Comment by ttaylorr** [comment]
Merged!
