### ISSUE TITLE
Are large objects downloaded for all branches?

### ISSUE THREAD

**Issue by waqas-syed** [github/git-lfs#1432]
Hi,

Sorry if the post is naive, but I will like to make a confirmation before we move to migrating our project to GIT LFS.

I understand that there are pointer files to point to large objects. But if a repo has multiple branches, and every branch contains e.g., one same pointer file(that points to a large object), then upon repo cloning with the default branch checked out, will that large file be downloaded for all the branches? Or the default branch only?

This confirmation will make my migration much confident. 

Thanks.

**Comment by technoweenie** [comment]
Objects are downloaded to `.git/lfs/objects`, and are accessible by any ref of that git repository. A `git checkout` or `git lfs pull` won't download any object that already exists locally.

Keep in mind, the only thing in LFS that deletes objects in `.git/lfs/objects` is the [`git lfs prune` command](https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-prune.1.ronn).

**Comment by waqas-syed** [comment]
Thanks for the clarification bro!
