### ISSUE TITLE
discrepency between custom transfer docs and implementation

### ISSUE THREAD

**Issue by ericfrederich** [github/git-lfs#1439]
Not sure where it should be fixed.

I'm seeing my client send a message like the following with an `"Event"` key instead of an `"event"` key like the docs suggest [here](https://github.com/github/git-lfs/blob/master/docs/custom-transfers.md#stage-1-intiation)

```json
{"Event":"init","operation":"upload","concurrent":false,"concurrenttransfers":3}
```

If I had my choice I'd probably want the code fixed to send a lower case key rather than fixing the docs.

**Comment by ttaylorr** [comment]
Hi @ericfrederich -- thanks for opening this.

I definitely agree that the code should send a lowercase `"event"` for consistency with other keys in the custom transfer API.

I'll go ahead and make that change now 😄

**Comment by technoweenie** [comment]
Thanks for the report @ericfrederich! We just shipped a small tweak to the code.
