### ISSUE TITLE
Repository or object not found / HTTP 404 error

### ISSUE THREAD

**Issue by Ceylo** [github/git-lfs#1444]
Hello,

I'm trying to setup a git server and use LFS with it. So far the Git server seems to be up and running good (I could commit and push to it).

Now if I try to push a commit that includes LFS managed files, it fails.

On server side:
```
git lfs env
git-lfs/1.3.1 (GitHub; linux amd64; go 1.6.3)
git version 2.8.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDir=
TempDir=lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

On client side
```
git lfs env
git-lfs/1.3.1 (GitHub; darwin amd64; go 1.6.3)
git version 2.7.4 (Apple Git-66)

Endpoint=https://lsoltic@yalir.org/git/Luciden.git/info/lfs (auth=basic)
LocalWorkingDir=/Users/ceylo/Luciden-bare
LocalGitDir=/Users/ceylo/Luciden-bare/.git
LocalGitStorageDir=/Users/ceylo/Luciden-bare/.git
LocalMediaDir=/Users/ceylo/Luciden-bare/.git/lfs/objects
LocalReferenceDir=
TempDir=/Users/ceylo/Luciden-bare/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

```
GIT_SSL_NO_VERIFY=true GIT_TRACE=1 git lfs push origin --all
01:20:57.092764 git.c:561               trace: exec: 'git-lfs' 'push' 'origin' '--all'
01:20:57.093141 run-command.c:334       trace: run_command: 'git-lfs' 'push' 'origin' '--all'
trace git-lfs: Upload refs [] to remote origin
trace git-lfs: run_command: git rev-list --objects --do-walk master --
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: run_command: 'git' config -l
trace git-lfs: tq: running as individual queue
trace git-lfs: api: uploading (0252e5ccd66f6e44bfcd8f7c982fc421ca9e4cf1bedfee11f1bcdb14b6397788)
trace git-lfs: Filled credentials for https://lsoltic@yalir.org/git/Luciden.git
trace git-lfs: HTTP: POST https://lsoltic@yalir.org/git/Luciden.git/info/lfs/objects
trace git-lfs: HTTP: 404
trace git-lfs: api: uploading (3ed28748e7a2eacb64f4ff59fe6cc90504a75ff995849051f4df1bd63a6996bd)
trace git-lfs: Filled credentials for https://lsoltic@yalir.org/git/Luciden.git
trace git-lfs: HTTP: POST https://lsoltic@yalir.org/git/Luciden.git/info/lfs/objects
trace git-lfs: HTTP: 404
trace git-lfs: tq: retrying 2 failed transfers
trace git-lfs: api: uploading (0252e5ccd66f6e44bfcd8f7c982fc421ca9e4cf1bedfee11f1bcdb14b6397788)
trace git-lfs: Filled credentials for https://lsoltic@yalir.org/git/Luciden.git
trace git-lfs: HTTP: POST https://lsoltic@yalir.org/git/Luciden.git/info/lfs/objects
trace git-lfs: HTTP: 404
trace git-lfs: api: uploading (3ed28748e7a2eacb64f4ff59fe6cc90504a75ff995849051f4df1bd63a6996bd)
trace git-lfs: Filled credentials for https://lsoltic@yalir.org/git/Luciden.git
trace git-lfs: HTTP: POST https://lsoltic@yalir.org/git/Luciden.git/info/lfs/objects
trace git-lfs: HTTP: 404
Git LFS: (0 of 2 files) 0 B / 1.07 GB                                                                                                                                    
Repository or object not found: https://lsoltic@yalir.org/git/Luciden.git/info/lfs/objects
Check that it exists and that you have proper access to it
Repository or object not found: https://lsoltic@yalir.org/git/Luciden.git/info/lfs/objects
Check that it exists and that you have proper access to it
Repository or object not found: https://lsoltic@yalir.org/git/Luciden.git/info/lfs/objects
Check that it exists and that you have proper access to it
Repository or object not found: https://lsoltic@yalir.org/git/Luciden.git/info/lfs/objects
Check that it exists and that you have proper access to it
```

And in the Apache server logs I can see
```
[Sat Aug 13 01:20:40.925405 2016] [cgi:error] [pid 27052] [client 80.12.43.28:34896] AH01215: Request not supported: '/home/git/Luciden.git/info/lfs/objects'
[Sat Aug 13 01:20:41.015777 2016] [cgi:error] [pid 27052] [client 80.12.43.28:34896] AH01215: Request not supported: '/home/git/Luciden.git/info/lfs/objects'
[Sat Aug 13 01:20:41.094590 2016] [cgi:error] [pid 27052] [client 80.12.43.28:34896] AH01215: Request not supported: '/home/git/Luciden.git/info/lfs/objects'
[Sat Aug 13 01:20:41.175263 2016] [cgi:error] [pid 27052] [client 80.12.43.28:34896] AH01215: Request not supported: '/home/git/Luciden.git/info/lfs/objects'
```

I'm a bit lost about which step I missed. I can indeed see on the server that there is nothing at "/home/git/Luciden.git/info/lfs/objects" but I don't know how it is supposed to be created.

I have found http://docs.gitlab.com/ce/workflow/lfs/manage_large_binaries_with_git_lfs.html#error-repository-or-object-not-found but none of the given explanations seem to fit my case (I tried giving all permissions, and I'm able to push normal commits so…).

I'd be very grateful if anyone had ideas to get this sorted :) In the beginning I did this in my own server because Bitbucket has a too low storage limit for Git LFS.

**Comment by technoweenie** [comment]
This seems to be a configuration issue with GitLab, and not related to the Git LFS client.

**Comment by Ceylo** [comment]
I'm not using GitLab. I posted the link to it only because it looked to be the closest to my issue.

**Comment by technoweenie** [comment]
What is your host then? I can only help if it's GitHub, but it looks like you're using some custom LFS server.

**Comment by Ceylo** [comment]
This is my own server, which my own Apache. I followed the instructions there : https://git-scm.com/book/be/v2/Git-on-the-Server-Smart-HTTP

However I realize I was wrong when I said that I could push a normal commit to it. So the issue does not seem to be related to git-lfs.

**Comment by technoweenie** [comment]
The LFS server api is described here: https://github.com/github/git-lfs/tree/master/docs/api. Don't bother implementing the "legacy" API stuff.

There are some server implementations on the wiki: https://github.com/github/git-lfs/wiki/Implementations. Of those, only the major Git hosts and Artifactory are what I would call supported/production ready LFS services. In addition, we wrote a [reference server implementation](https://github.com/git-lfs/lfs-test-server), but it's not under active development and not recommended for production use.

**Comment by Ceylo** [comment]
Oh I thought having a Git through HTTP server + git package + git-lfs package installed enough. I did not implement any LFS server.
So from what I understand, either I use Git LFS from a website that already provides it or I use the reference implementation (although not really safe for production) ?

**Comment by technoweenie** [comment]
The wiki has some other implementations. Some use S3 as a backend, others write to local disk. We haven't evaluated them. Git LFS is still a pretty young project, so there aren't a lot of well supported tools around it.

**Comment by Ceylo** [comment]
Ok thank you for your support! :) I'll probably stick with websites that already provide Git LFS

**Comment by csestudent** [comment]
Hello,

We have our own git server where lfs is installed. I'm trying to push war file to lfs directory but I'm getting below error:

Client error: http://git/plugins/lfs/content/bigfiles/objects from HTTP 405
Client error: http://git/plugins/lfs/content/bigfiles/objects from HTTP 405
error: failed to push some refs to 'http://git/git-lfs-test'

Can you please help me with your expert advice

Thanks in advance,
Pranav

**Comment by 3rdfoundation** [comment]
I setup my own linux git server for storing Unreal development content. works like a champ for non-binary stuff. public/private key ssh auth works perfectly.

Then I went to add binary support (LFS). I innocently thought I could install LFS in 5 minutes and be on my way. No can do on that. LFS does not support SSH authentication. This is the fun error:
batch request: bash: git-lfs-authenticate: command not found: exit status 127

So I tried to install http authentication for apache. Why should I need a webserver to use git? Because reasons... and that eventually failed. (see Ceylo's comments above). Here is that fun error:
AH01215: Request not supported: '/stuff/git/lfs_test.git/info/lfs/objects/batch'

Nobody said LFS on a custom git server was difficult. I have been fighting with this over a day. 

It appears that everyone who tries this gives up and uses an existing service such as github or gitlab. I refuse to give in. 

I am now looking at an Apache Server LFS Module. Will it work? Who knows, but if you want to use LFS on your own private git server ... be warned ... there be dragons.

Now bear in mind, beggars can't be choosers and github has been gracious enough to provide LFS via open source ... but I wish they provided public/private key SSH authentication. SSH authentication is the preferred server install per the instructions: https://git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server

**Comment by bk2204** [comment]
Git LFS does indeed support SSH authentication.  However, because the main body of the protocol is done over HTTPS even though SSH is used for authentication, the HTTPS server and SSH server must coordinate, which is why we don't ship an open source binary for `git-lfs-authenticate` (because it wouldn't work in most cases).

We do plan to ship a pure SSH-based protocol in the future.  In the mean time, you can use the git-lfs/lfs-test-server implementation and set `lfs.url` to point to that server and everything should work just fine.  Alternatively, you can mount the remote system's file system using SSHFS and push to a local remote (as long as it's a Git repository), and that will also work.

**Comment by 3rdfoundation** [comment]
@bk2204: Thanks for you quick reply. That pointed me in the right direction.

lfs test sever can be found here:
https://github.com/git-lfs/lfs-test-server

I finally got it working. I learned a lot about LFS in the process.

I think my initial confusion was that this really did very little for me on the server:
sudo apt-get install -y git-lfs

That is not installing an LFS server. You need to do that separately.

For anyone who finds these comment, there are a few things you should know about LFS:
1. LFS is storing files separate from your git repo in its own directory (LFS_CONTENTPATH)
2. Make sure you have correct permissions on the LFS directory (LFS_CONTENTPATH) that holds files. It took me several hours to sort out I just needed to chmod it.
3. Once you have the lfs-test-server up, you can add a user via the mgmt page. I am working locally so I don't care a ton about the security on this for now so I just hardwired the user/password in the URL on the client side like this: url = "http://USER:PASSWORD@{URL}:9999/" (substitute {URL} with your URL / IP address of course...)
4. You can download any file from the mgmt objects page to verify it is working. When I saw an object there and it wouldn't download I figured out I had a directory permission issue.

I think the README.md is slightly out of date on the lft-test-server. When you issue "go get github.com/github/lfs-test-server" it is going to put it in your home directory under "go/bin/"

I still need to turn the bash script into a service so LFS always comes up when the machine boots, but that is separate from getting it up and running.

Good luck to anyone setting up LFS on a private git server. It can be done.
