### ISSUE TITLE
Clarification of how to make git-lfs use the version that was built locally

### ISSUE THREAD

**Issue by dpursehouse** [github/git-lfs#1446]
Sorry if this is a stupid question.

I've installed go and set the workspace to `~/go`:

```
~ $ echo $GOPATH
/Users/dpursehouse/go
```

I had previously installed git-lfs with homebrew, so removed that and installed again using `go get github.com/github/git-lfs` per the documentation. Now the default `git-lfs` is the one from the workspace:

```
~ $ which git-lfs
/Users/dpursehouse/go/bin/git-lfs
```

So far so good.  But my usual place to do development work is in `~/git/`, so I've made a symlink from there to the one in the go workspace:

```
~ $ ls -la ~/git/git-lfs
lrwxr-xr-x  1 dpursehouse  790772617  51 Aug 13 13:17 /Users/dpursehouse/git/git-lfs -> /Users/dpursehouse/go/src/github.com/github/git-lfs
```

Building with `script/bootstrap` works, and generates `git-lfs` in `./bin`, but to make it actually be used I had to symlink to it:

```
~ $ ls -la /Users/dpursehouse/go/bin/git-lfs
lrwxr-xr-x  1 dpursehouse  790772617  42 Aug 13 13:37 /Users/dpursehouse/go/bin/git-lfs -> /Users/dpursehouse/git/git-lfs/bin/git-lfs
```

This isn't described in the documentation, so I'm wondering if it's the expected way to do it, or I'm missing something?

**Comment by technoweenie** [comment]
The various packages and installers that we release should put the Git LFS binary in the appropriate path. Using `go get` to download Git LFS is mainly for LFS developers, and not end users. Using the symlink is a valid workaround, though.

Keep in mind that for Go development, Git LFS should live in `$GOPATH/src/github.com/github/git-lfs` (this is where `go get` puts it). I'm surprised `script/bootstrap` worked from your `~/git` directory :)

**Comment by dpursehouse** [comment]
> Git LFS should live in `$GOPATH/src/github.com/github/git-lfs` (this is where `go get` puts it). I'm surprised script/bootstrap worked from your `~/git` directory :)

That's where it is.  It's symlinked into `~/git`.

I was doing some hacking on the git-lfs client (issue 1356) which is why I installed it with `go get`.

It all seems to be working with the symlink, so I guess this one can be closed.
