### ISSUE TITLE
git not uploading files recursively in a folder

### ISSUE THREAD

**Issue by alishah151** [github/git-lfs#1457]
I am trying to move uploads folder of wordpress to Git LFS....
i have added followings to .gitattribute 

`wp-content/uploads/**/ filter=lfs diff=lfs merge=lfs -text

wp-content/uploads/** /* filter=lfs diff=lfs merge=lfs -text` (space added so it wont change otherwise i do not have space in path)

but still it is not uploading images to LFS of Git.
directory structure is
uploads/soemFolder-1/(year)/(image files)
uploads/soemFolder-2/(year)/(image files)
.
.
.

uploads/soemFolder-n/(year)/(image files)

regards

**Comment by technoweenie** [comment]
The second filter you used works for me. Make sure you've run `git lfs install` so that the filters are set up in your global git config. Also, it only works with files added _after_ you've run `git lfs track`.  Here's a transcript of me adding a file in the same directory structure:

```bash
$ git init
Initialized empty Git repository in /Users/rick/p/wptest/.git/
$ git lfs track "wp-content/uploads/**/*"
Tracking wp-content/uploads/**/*

$ mkdir -p wp-content/uploads/somefolder/2016
$ echo "hi" > wp-content/uploads/somefolder/2016/hi
$ git add wp-content .gitattributes

$ git commit -m "commit"
[master (root-commit) b6da033] commit
 2 files changed, 5 insertions(+)
 create mode 100644 .gitattributes
 create mode 100644 wp-content/uploads/somefolder/2016/hi

$ git show
commit b6da03330e03493e8780e4e8182cd7ec940406a2
Author: risk danger olson <technoweenie@gmail.com>
Date:   Tue Aug 16 16:35:28 2016 -0600

    commit

diff --git a/.gitattributes b/.gitattributes
new file mode 100644
index 0000000..6cf55ac
--- /dev/null
+++ b/.gitattributes
@@ -0,0 +1,2 @@
+wp-content/uploads/**/* filter=lfs diff=lfs merge=lfs -text
diff --git a/wp-content/uploads/somefolder/2016/hi b/wp-content/uploads/somefolder/2016/hi
new file mode 100644
index 0000000..90353d7
--- /dev/null
+++ b/wp-content/uploads/somefolder/2016/hi
@@ -0,0 +1,3 @@
+version https://git-lfs.github.com/spec/v1
+oid sha256:98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4
+size 3
```

**Comment by alishah151** [comment]
thankyou @technoweenie 
so the issue was that the files were already in the repo thats why they were nto going to LFS i think...i removed files and then pushed it...then readded files and re-pushed to repo and  now its working.
