### ISSUE TITLE
LFS Files show up as changed when there is no difference between them

### ISSUE THREAD

**Issue by mlohstroh** [github/git-lfs#1465]
Hello,

My team is using Git LFS for a [Unity](https://unity3d.com/) game project because the light maps files that the engine generates are massive textures.

We have recently run into an issue with these `.exr` files where they are showing up as changed, but there is no file differences between them. The file length is the same and the lightmaps are the same and the hash for the file is exactly the same. 

As a team, we are wary on committing them because lighting is very delicate. And it doesn't make sense that they would have changed because we never told the engine to generate them (it's a very explicit action). However, the huge problem comes in whenever we try to just discard the changes. The `git reset --hard` command seems to just do nothing to these files, mainly because there just aren't any changes and git starts giving us trouble when switching branches because it says that the files are different in the other branch (they aren't) and so it stops the checkout. It pretty much halts our workflow. 

A temporary fix has been to checkout an older branch and then delete the branch we were just on that was marking those files as dirty, then checking out the branch again from the origin seems to make the problem go away for a time. 

This doesn't happen all of the time though. It mainly happens whenever we are switching branches that someone else has committed on. The reason I have a suspicion of Git LFS instead of just plain old git, is because we have another team also working on our same git version, but an older version of git LFS. 

## Environment
```
Windows 10 Pro
Git Version 2.8.2.windows.1

$ git lfs env
git-lfs/1.3.1 (GitHub; windows amd64; go 1.6.3; git 9c9dffb)
git version 2.8.2.windows.1

LocalWorkingDir=C:\playful\project
LocalGitDir=C:\playful\project\.git
LocalGitStorageDir=C:\playful\project\.git
LocalMediaDir=C:\playful\project\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\playful\project\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

## Git Attributes
```
# Auto detect text files and perform LF normalization
* text=auto

#Text Files
*.prefab text eol=lf
*.mat text eol=lf
*.shader text
*.cginc text
*.meta text eol=lf
*.unity text eol=lf
*.asset text eol=lf
*.json text

# Custom for Visual Studio
*.cs     diff=csharp
*.sln    merge=union
*.csproj merge=union
*.vbproj merge=union
*.fsproj merge=union
*.dbproj merge=union

# Standard to msysgit
*.doc	 diff=astextplain
*.DOC	 diff=astextplain
*.docx diff=astextplain
*.DOCX diff=astextplain
*.dot  diff=astextplain
*.DOT  diff=astextplain
*.pdf  diff=astextplain
*.PDF	 diff=astextplain
*.rtf	 diff=astextplain
*.RTF	 diff=astextplain

# Denote all files that are truly binary and should not be modified.
*.png binary
*.jpg binary
*.tga binary
*.psd binary
*.fbx binary
*.mp4 binary
*.exr filter=lfs diff=lfs merge=lfs -text
*LightingData.asset filter=lfs diff=lfs merge=lfs -text
*.mp4 filter=lfs diff=lfs merge=lfs -text
*.bnk filter=lfs diff=lfs merge=lfs -text
*.cache filter=lfs diff=lfs merge=lfs -text
*.wav filter=lfs diff=lfs merge=lfs -text
*.mp3 filter=lfs diff=lfs merge=lfs -text
*.ogg filter=lfs diff=lfs merge=lfs -text

```

**Comment by technoweenie** [comment]
When this happens, are all the "changed" files different in the old and new branches? Are they LFS pointers in both branches? For example:

```bash
# the git blob oid and size of the file on "master" branch
$ git ls-tree -rl master gif/dupe.gif
100644 blob 50eb175bbfde63504add621427a6a98910e89697     130   	gif/dupe.gif

# the git blob oid and size after changing to "update-gif" branch
$ git ls-tree -rl update-gif gif/dupe.gif
100644 blob 18ccf724df0de9f6451d7e4172610333269e0991     130   	gif/dupe.gif
```

If the file in the 2nd branch has a much larger blob size, then it's not using LFS on that branch. That will definitely cause the file to appear changed to Git, because the Git LFS has replaced it with an LFS pointer. This would only happen if you've made a partial conversion to LFS, or if someone accidentally added a file without LFS.

**Comment by mlohstroh** [comment]
The .exr files have always been marked as LFS files so that doesn't seem to be an issue. 

```
$ git ls-tree -rl project/development Assets/project/Scenes/Prototype\ Levels/PrototypeEnd/Lightmap-2_comp_light.exr
100644 blob 538d09aec5540cae65a4ebdb46fc1831aca4b682 6614737    Assets/project/Scenes/Prototype Levels/PrototypeEnd/Lightmap-2_comp_light.exr

$ git ls-tree -rl project/feature/dither Assets/project/Scenes/Prototype\ Levels/PrototypeEnd/Lightmap-2_comp_light.exr
100644 blob 538d09aec5540cae65a4ebdb46fc1831aca4b682 6614737    Assets/project/Scenes/Prototype Levels/PrototypeEnd/Lightmap-2_comp_light.exr
```

Also, for what it's worth, here is the git diff and MD5's.

```
$ git diff
diff --git a/Assets/project/Scenes/Prototype Levels/PrototypeEnd/Lightmap-2_comp_light.exr b/Assets/project/Scenes/Prototype Levels/PrototypeEnd/Lightmap-2_comp_light.exr
index 538d09a..d104dbd 100644
Binary files a/Assets/project/Scenes/Prototype Levels/PrototypeEnd/Lightmap-2_comp_light.exr and b/Assets/project/Scenes/Prototype Levels/PrototypeEnd/Lightmap-2_comp_light.exr differ
```


This is when git says the files differ
```
$ md5sum Assets/project/Scenes/Prototype\ Levels/PrototypeEnd/Lightmap-2_comp_light.exr
2a68b13c10ae976625329e16cc2fc671 *Assets/project/Scenes/Prototype Levels/PrototypeEnd/Lightmap-2_comp_light.exr
```

This is after finally get the file to a good state.
```
# After getting to a good state with these files
$ md5sum Assets/project/Scenes/Prototype\ Levels/PrototypeEnd/Lightmap-2_comp_light.exr
2a68b13c10ae976625329e16cc2fc671 *Assets/project/Scenes/Prototype Levels/PrototypeEnd/Lightmap-2_comp_light.exr
```

**Comment by technoweenie** [comment]
Those files are not using LFS. You can tell by the file size `6614737`, and the diff output mentioning "Binary files". 

Is it possible you're not running `git lfs install` after installation?

**Comment by mlohstroh** [comment]
That is a potential issue by one of our team members. I ran it on their computer and it says that it was just now initialized. Is there a way to tell if someone else hasn't not run that? Or is it just a command that I can just run for everyone?

**Comment by technoweenie** [comment]
You can look for `filter.lfs.*` keys in their git config: `git config --global --list | grep filter\.lfs`. It's safe to run `git lfs install` on anyone's computer.

**Comment by mlohstroh** [comment]
Oh my goodness. I'm just not entirely sure how I would have found that without asking for help. Removing the offending files and adding them back into LFS seemed to do the trick. This stuff becomes a lot to juggle when we are made up of programmers, artists, and designers who use a variety of tools. 

Thank you very much for helping. :smile:

**Comment by technoweenie** [comment]
@mlohstroh just curious, are you all on windows? I just double checked, and our installer does prompt to run it. I don't recall if there's a reason it can't just run for you...

**Comment by mlohstroh** [comment]
Yes we all have to run on Windows. And I'm not fully versed on LFS, but if
there is nothing repo dependent, it seems like the installer should just
run it.

It does seem weird that you run the installer and then "install" LFS again.
Just thoughts that I'm sure you've has. :)

**Comment by kkamata2** [comment]
git checkout HEAD~1
git checkout master
で取り直したらとりあえず出なくなった
