### ISSUE TITLE
Installing on debian stretch

### ISSUE THREAD

**Issue by nikolai-b** [github/git-lfs#1468]
When I followed packagecloud.io script: https://packagecloud.io/github/git-lfs/install
it set the deb source to be:

https://packagecloud.io/github/git-lfs/debian stretch InRelease

but you don't have a stretch version in to repo.  Are you planning on adding one?  If not then the jessie version installed and worked fine.

Thanks

**Comment by technoweenie** [comment]
Last I knew, Stretch wasn't released yet (but I admit I don't follow Debian releases that closely). However, all it takes to add support is an appropriate docker image (here's our [jessie image](https://github.com/git-lfs/build-dockers/tree/master/debian/8), and adding an entry to [this map](https://github.com/github/git-lfs/blob/74a228f7ecb62186bad0820f73c3e35624f21bfc/script/packagecloud.rb#L27-L53).

I have a hunch that we can essentially copy that and change the docker `FROM` property and be good to go.

**Comment by technoweenie** [comment]
Closing this, our [debian 9 image built successfully](https://hub.docker.com/r/gitlfs/build-dockers/tags/). My hunch was correct :)  We're working on a release today.

**Comment by nikolai-b** [comment]
Thanks, stretch hasn't been released (it is still in testing) so its fine if it isn't supported,.
