### ISSUE TITLE
Ubuntu 14.04 Install Broken

### ISSUE THREAD

**Issue by davetcoleman** [github/git-lfs#1476]
I'm attempting https://packagecloud.io/github/git-lfs/install

I'm on Ubuntu 16.04

I run the curl script:
```
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
```

It says:
```
Detected operating system as Ubuntu/xenial.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/github_git-lfs.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.
The repository is setup! You can now install packages.
```

Inside a git repo I attempt:
```
git lfs
git: 'lfs' is not a git command. See 'git --help'.
Did you mean this?
	last
```

I also try
```
git lfs install
And it also says its not a command.
```

What am I doing wrong?

**Comment by ttaylorr** [comment]
Hi, @davetcoleman -- thanks for opening this. I noticed you didn't mention running an `apt-get install git-lfs` anywhere. All that script does is set up the packagecloud repo within your apt repositories list. You will still have to run an `apt-get` install to get LFS installed on your system.

Could you give that a shot and let me know if that does the trick? Thanks!

**Comment by davetcoleman** [comment]
No where on https://git-lfs.github.com/ does it mention running ``apt-get``

I already got it to work by downloading the tar.gz and running the install script, but I'm still confused what the big blue ``Install via PackageCloud`` button does

**Comment by technoweenie** [comment]
We may just want to replace that page with a page that explains what PackageCloud is. Closing this in favor of https://github.com/git-lfs/git-lfs.github.com/issues/3. Thanks for the feedback!
