### ISSUE TITLE
`git lfs clone` for LFS v1.3+ creates `lfs` dir in pwd (outside of checkout area)

### ISSUE THREAD

**Issue by woopla** [github/git-lfs#1483]
Hello,

There are some extra files that should belong to `<checkout dir>/.git/lfs` that are left over in the dir where `git lfs clone` was called from. For example:
```shell
> git lfs clone http://hostname/repo.git
...
> ls -l
drwxr-sr-x 4 cmoyroud prdg2g 2048 Aug 23 15:59 lfs
drwxr-sr-x 6 cmoyroud prdg2g  2048 Aug 23 15:59 repo
> ls -l repo/.git
total 52
drwxr-sr-x 2 cmoyroud prdg2g 2048 Aug 23 15:59 branches
-rw-r--r-- 1 cmoyroud prdg2g  377 Aug 23 15:59 config
-rw-r--r-- 1 cmoyroud prdg2g   73 Aug 23 15:59 description
-rw-r--r-- 1 cmoyroud prdg2g   23 Aug 23 15:59 HEAD
drwxr-sr-x 2 cmoyroud prdg2g 2048 Aug 23 15:59 hooks
-rw-r--r-- 1 cmoyroud prdg2g 5325 Aug 23 16:00 index
drwxr-sr-x 2 cmoyroud prdg2g 2048 Aug 23 15:59 info
drwxr-sr-x 4 cmoyroud prdg2g 2048 Aug 23 15:59 lfs
drwxr-sr-x 3 cmoyroud prdg2g 2048 Aug 23 15:59 logs
drwxr-sr-x 4 cmoyroud prdg2g 2048 Aug 23 15:59 objects
-rw-r--r-- 1 cmoyroud prdg2g  202 Aug 23 15:59 packed-refs
drwxr-sr-x 5 cmoyroud prdg2g 2048 Aug 23 15:59 refs
> ls -l lfs
total 8
drwxr-sr-x 3 cmoyroud prdg2g 2048 Aug 23 15:59 objects
drwxr-sr-x 3 cmoyroud prdg2g 2048 Aug 23 15:59 tmp
```

And here's the [git-lfs-log.txt](https://github.com/github/git-lfs/files/435537/git-lfs-log.txt) with GIT_TRACE=1

I haven't actually tried with earlier versions, but it might happen there too.

Let me know if you need more info, or if there are more experiments to run.

Thanks,

Clément

**Comment by ttaylorr** [comment]
Hey @woopla, thanks for opening this. Can you try this with 4d516f0e2d127ac4c84a2e3fb83b1c37c7225fab and let me know if the problem persists?

**Comment by woopla** [comment]
All clean @ttaylorr :+1:  Now to wait for 1.4.1 release :)
