### ISSUE TITLE
lfs timeout

### ISSUE THREAD

**Issue by victorv** [github/git-lfs#1490]
Frequently get the following error while cloning or pulling a github repo with LFS files -

**Error downloading object: tools/00.50.77.4/win32/sparc-myriad-elf-4.8.2/bin/sparc-myriad-elf-gcc-ar.exe (662d7ecc20ece4b1a687331b9411d2e7a2a48019661ff98062e3e71f1afa7e76)

Errors logged to /home/ten/10imaging/mdk/.git/lfs/objects/logs/20160828T195036.555835484.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: tools/00.50.77.4/win32/sparc-myriad-elf-4.8.2/bin/sparc-myriad-elf-gcc-ar.exe: smudge filter lfs failed**

I can resume the operation with `git checkout -f HEAD`

A dump of the log file -

git-lfs/1.4.1 (GitHub; linux amd64; go 1.7; git 2070e4c)
git version 1.9.1

$ git-lfs smudge -- tools/00.50.77.4/win32/models/i2cDll.dll
Error downloading object: tools/00.50.77.4/win32/models/i2cDll.dll (9bfb11a4377ae4dca12b0d104914f9d9c0fa7483c5c04da0a1380eccd4051ab9)

Smudge error: Error downloading 9bfb11a4377ae4dca12b0d104914f9d9c0fa7483c5c04da0a1380eccd4051ab9: http: Post https://github.com/10imaging/mdk.git/info/lfs/objects/batch: dial tcp: lookup github.com on 127.0.1.1:53: dial udp 127.0.1.1:53: i/o timeout: http: Post https://github.com/10imaging/mdk.git/info/lfs/objects/batch: dial tcp: lookup github.com on 127.0.1.1:53: dial udp 127.0.1.1:53: i/o timeout
github.com/github/git-lfs/errors.newWrappedError
	/Users/rick/go/src/github.com/github/git-lfs/errors/types.go:166
github.com/github/git-lfs/errors.NewSmudgeError
	/Users/rick/go/src/github.com/github/git-lfs/errors/types.go:252
github.com/github/git-lfs/lfs.PointerSmudge
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer_smudge.go:69
github.com/github/git-lfs/lfs.(*Pointer).Smudge
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer.go:64
github.com/github/git-lfs/commands.smudgeCommand
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_smudge.go:66
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
	/Users/rick/go/src/github.com/github/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
	/Users/rick/go/src/github.com/github/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/github/git-lfs/commands.Run
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:70
main.main
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:33
runtime.main
	/usr/local/Cellar/go/1.7/libexec/src/runtime/proc.go:183
runtime.goexit
	/usr/local/Cellar/go/1.7/libexec/src/runtime/asm_amd64.s:2086

ENV:
LocalWorkingDir=/home/ten/10imaging/mdk
LocalGitDir=/home/ten/10imaging/mdk/.git
LocalGitStorageDir=/home/ten/10imaging/mdk/.git
LocalMediaDir=/home/ten/10imaging/mdk/.git/lfs/objects
LocalReferenceDir=
TempDir=/home/ten/10imaging/mdk/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.git
GIT_PREFIX=

**Comment by technoweenie** [comment]
Hi @victorv, that looks like a DNS issue. You can increase the timeout by configuring `lfs.dialtimeout` as described on the [config man page](https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-config.5.ronn).

    $ git config lfs.dialtimeout 60

**Comment by ttaylorr** [comment]
Hi @victorv. I'm going to close this out for now, but if the issue persists please don't hesitate to re-open this!
