### ISSUE TITLE
Git clone fails when downloading lfs files

### ISSUE THREAD

**Issue by grkkarthick90** [github/git-lfs#1491]
We are using git lfs to store the large file system. When we download our github repository which has git lfs fails very often with the error message in console.
> Error downloading object: thirdparty/boost/1.60.0/lib/mac/libboost_regex.a (876c                                                                                                                017c66f74baa4e86743960ac99a64a44721c661b859d3e660aeda201849b)
> 
> Errors logged to C:\GRK\GIT\temp\kslocker\.git\lfs\objects\logs\20160829T153659.                                                                                                                9984081.log
> Use `git lfs logs last` to view the log.
> error: external filter git-lfs smudge -- %f failed 2
> error: external filter git-lfs smudge -- %f failed
> fatal: thirdparty/boost/1.60.0/lib/mac/libboost_regex.a: smudge filter lfs faile                                                                                                                d
> warning: Clone succeeded, but checkout failed.

Attached the log file for your reference [20160829T153659.9984081.txt](https://github.com/github/git-lfs/files/442399/20160829T153659.9984081.txt)

This error happens at some random place when downloading the lfs files.
This error is happening when I'm try from my office network. When I try with other network providers I don't get any error. So from network team I was asked to get them the ports to be open. Or what else has the network engineer to do to get rid of this error.

**Comment by technoweenie** [comment]
Hi @grkkarthick90:

> Post https://api.github.com/lfs/RealImage/kslocker/objects/batch: dial tcp: lookup api.github.com: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server.

That looks like a DNS issue. You can increase the timeout by configuring `lfs.dialtimeout` as described on the [config man page](https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-config.5.ronn).

    $ git config lfs.dialtimeout 60

**Comment by grkkarthick90** [comment]
Hi @technoweenie Before it was failing with the error message `An existing connection was forcibly closed by the remote host.` And this is the first time I'm seeing the above error message in the log file. I missed to read it before upload. Attached the log file which has the error message which I get quite frequently. 
[20160812T155807.9907819.txt](https://github.com/github/git-lfs/files/442706/20160812T155807.9907819.txt)

**Comment by technoweenie** [comment]
Yeah, looks like general network instability with S3. That `52.216` address is from amazon.

**Comment by grkkarthick90** [comment]
@technoweenie Yes it always fails from aws S3 I have confirmed that with tracet also. What should I do to get rid of this error?

**Comment by technoweenie** [comment]
My only suggestion for the Git LFS client is tweaking the `lfs.dialtimeout` setting as I mentioned above. Our [GitHub support team](https://github.com/contact) may be able to help you out with troubleshooting your connection to GitHub.

**Comment by ttaylorr** [comment]
Hi @grkkarthick90, I'm going to close this issue out since it seems like the issue may be resolved. If the issue re-appears, or you have any further questions, don't hesitate to re-open this issue!
