### ISSUE TITLE
Size Limitations in LFS?

### ISSUE THREAD

**Issue by bfdonny** [github/git-lfs#1493]
It's my understanding that GitHub imposes a 2GB file size limit for git-lfs on Github. Are there any file size or repository size restrictions on self-hosted git-lfs? 

Thanks!

**Comment by technoweenie** [comment]
The Git LFS client doesn't really impose any limits. However, if your server doesn't implement resumable uploads (through the _experimental_ tus.io adapter) and resumable downloads, dealing with multi-GB files will be a pain.
