### ISSUE TITLE
Is it possible to be used in the redmine?

### ISSUE THREAD

**Issue by novaoki** [github/git-lfs#1502]
Is it possible to use the gitlfs in redmine?
If available, how do I set the redmine?
I use this version.

Redmine version 2.5.2.stable
Ruby version 2.1.2-p95 (2014-05-08) [x86_64-linux]
Git 1.7.1

I'm sorry. I'm not good at English.
Thank you.

**Comment by ttaylorr** [comment]
👋  @novaoki -- thanks for opening this.

Redmine does not have support for working with Git LFS. I am not a regular user of Redmine, so I went ahead and set up a demo instance of a Redmine project, and did not see any options for configuring Redmine to work with Git LFS.

Redmine should, however, display the LFS pointer files tracked with Git, which contain OIDs that can be used to resolve a link to download that file by using the v1.3 Batch API. Some more information on how to preform that sort of resolution can be found [here](https://github.com/github/git-lfs/blob/master/docs/api/v1/http-v1-batch.md#post-objectsbatch).

Your Git version, unfortunately, is unsupported by Git LFS. We require a Git version that is at least v1.8.2. You can download newer Git versions from [here](https://www.kernel.org/pub/software/scm/git/).

**Comment by novaoki** [comment]
@ttaylorr 
Thank you for answer.
I think let's questions in the Redmine community.
Thanks.

**Comment by ttaylorr** [comment]
@novaoki, it's my pleasure 😄 . Please let me know what they say!
