### ISSUE TITLE
Add an AppVeyor build badge to the README

### ISSUE THREAD

**Issue by sschuberth** [github/git-lfs#1510]
We have a badge for Travis CI, so we should now have one for AppVeyor, too. I'd happily do this myself in a PR, but I do not have access to https://ci.appveyor.com/project/git-lfs/git-lfs/settings/badges to get the correct URL for the badge.

**Comment by ttaylorr** [comment]
I think this is a good idea once we get AppVeyor running tests on Windows (instead of just building artifacts). 😄

**Comment by sschuberth** [comment]
Don't you think it makes sense to have the badge already now, so that interested people can easily get the latest master build artifacts for Windows to try out?

**Comment by ttaylorr** [comment]
I think I'd like to hold off until real tests are running and passing on AppVeyor.

**Comment by sschuberth** [comment]
Can we have the build badge now, please? :-) And also, while you're at it, probably make the AppVeyor check for PRs a required one?
