### ISSUE TITLE
`git lfs clone --depth=1` fails

### ISSUE THREAD

**Issue by drussel** [github/git-lfs#1514]
Complaining about "--depth" although the error message says it supports all arguments supported by git clone.

This comes up in trying to do expedited copies of the code base for running continuous integration.

Same thing for `-q`.

**Comment by technoweenie** [comment]
Can you show the output of `git lfs env`, and your exact `git lfs clone` command? This works fine for me:

```
$ git lfs env | head -n 2
git-lfs/1.4.1 (GitHub; darwin amd64; go 1.7; git 228c177)
git version 2.9.2

$ git lfs clone https://github.com/github/git-lfs-test --depth=1
Cloning into 'git-lfs-test'...
remote: Counting objects: 14, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 14 (delta 0), reused 12 (delta 0), pack-reused 0
Unpacking objects: 100% (14/14), done.
Checking connectivity... done.
Git LFS: (6 of 6 files) 781.12 KB / 818.95 KB

$ git lfs clone https://github.com/github/git-lfs-test --depth=1 -q
Git LFS: (6 of 6 files) 780.54 KB / 818.95 KB
```

**Comment by drussel** [comment]
git-lfs/1.2.0 (GitHub; windows amd64; go 1.6.1; git 9bd3b8e)
git version 2.9.0.windows.1

Hmmm, I'll have to look in to why I'm on such an old version. Thanks.
