### ISSUE TITLE
Pushing LFS does not work on Mac

### ISSUE THREAD

**Issue by SommerEngineering** [github/git-lfs#1515]
Dear LFS team,

I got an issue with LFS. I added two new files, make the commit followed by push origin master to Github.com (private repo).

`git lfs ls-files` shows, that the two new files are tracked by LFS. While pushing, the pre-hook was not triggered. Visiting Github, I see only some meta data:

```
version https://git-lfs.github.com/spec/v1
oid sha256:a6d7a92ef2fd27e6f315407a222a415a371f85d62df0ca2664e3642ed78c1273
size 172831414
```

Finally, I tried to force the LFS by using `echo “refs/heads/master <HASH> refs/heads/master 0000000000000000000000000000000000000000” | GIT_TRACE=1 git lfs pre-push origin`.

The output was:
```
13:48:01.241128 git.c:563               trace: exec: 'git-lfs' 'pre-push' 'origin'
13:48:01.241617 run-command.c:336       trace: run_command: 'git-lfs' 'pre-push' 'origin'
trace git-lfs: run_command: 'git' version
trace git-lfs: run_command: git rev-list --objects f85c4aef069f518e6877f8023a3d445a850a78ba --not --remotes=origin --
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: run_command: 'git' config -l
trace git-lfs: tq: running as batched queue, batch size of 100
```

But nothing happens. At Github, there are just the meta data.

My Git version: 1.10.0
My LFS version: 1.4.1
My system: Mac OS X, installed Git and LFS by `brew`.

Background information: I moved the entire data of this repo on the file system-level from a Windows 10 machine to my new Mac. Afterwards, I re-activated LFS by `git lfs install`.

Question: Why does LFS not uploading the binary data or ... why does the hook is not working?

**Comment by technoweenie** [comment]
Git didn't add pre-push hooks until git v1.8.2. Until you upgrade git, run `git lfs push` manually before `git push` to upload your LFS objects. You can run `git lfs push --all` to upload everything locally to the server.

**Comment by 4fthawaiian** [comment]
but, but but...

`git --version
git version 2.7.4 (Apple Git-66)`

**Comment by SommerEngineering** [comment]
Thanks @technoweenie for your response. I had used v1.8.2 or newer on Windows and Mac since I used LFS. Thus, I should not have this issue. Anyway, `git lfs push origin master --all` works fine. Is there a way to fix my hooks in order to force Git to push LFS while `git push`?

**Comment by ttaylorr** [comment]
@SommerEngineering running `git lfs install --force` should fix up any broken hooks 😄

**Comment by CuriousVini** [comment]
@ttaylorr  @technoweenie Is this a bug in git version 2.8.1? I see the same issue with this version too
