### ISSUE TITLE
Missing documentation for LFS server configuration

### ISSUE THREAD

**Issue by radarsat1** [github/git-lfs#1524]
I am trying out git LFS and I've got to say, I find it surprisingly hard to figure out how to actually use it.

I started a docker container running Ubuntu 16.04 and installed git and curl in order to follow the instructions on https://git-lfs.github.com/

(I use a container because I don't like installing things from 3rd-party repositories on my system, but especially not if it recommends running a script as root from curl! But I understand this just sets up a PPA, no worries.. still... containerized for testing.)

Now, I thought I would make a local LFS repository, in order to follow the instructions on the site:

~~~
cd ~/
root@ee04efbff5e9:~# mkdir testlfs 
root@ee04efbff5e9:~# cd testlfs/
root@ee04efbff5e9:~/testlfs# git init
Initialized empty Git repository in /root/testlfs/.git/
root@ee04efbff5e9:~/testlfs# echo "Test for git LFS" >README
root@ee04efbff5e9:~/testlfs# git add README 
root@ee04efbff5e9:~/testlfs# git commit -m 'initial'
[master (root-commit) 63c2b4d] initial
 1 file changed, 1 insertion(+)
 create mode 100644 README
~~~

So far so good, just regular git.  Now I follow the instructions to add an LFS file:

~~~
root@ee04efbff5e9:~/clonelfs# git lfs version
git-lfs/1.4.1 (GitHub; linux amd64; go 1.7)
root@ee04efbff5e9:~/testlfs# git lfs track "*.csv"
Tracking *.csv
root@ee04efbff5e9:~/testlfs# echo "this,is,a,large,csv,file" >large.csv
root@ee04efbff5e9:~/testlfs# git add large.csv 
root@ee04efbff5e9:~/testlfs# git commit -m 'first large file'
[master 8edffda] first large file
 1 file changed, 3 insertions(+)
 create mode 100644 large.csv
~~~

Now I set it up so I can push to it and make a clone:

~~~
root@ee04efbff5e9:~/testlfs# git config receive.denyCurrentBranch ignore
root@ee04efbff5e9:~/testlfs# cd ../
root@ee04efbff5e9:~# git clone testlfs clonelfs 
Cloning into 'clonelfs'...
done.
root@ee04efbff5e9:~# cd clonelfs/
root@ee04efbff5e9:~/clonelfs# ls
README  large.csv
~~~

Decide to add a "large" file here too, and push it, and here is where I run into trouble:

~~~
root@ee04efbff5e9:~/clonelfs# git lfs track "*.csv"
Tracking *.csv
root@ee04efbff5e9:~/clonelfs# echo "this,is,another,large,csv,file" >another.csv
root@ee04efbff5e9:~/clonelfs# git add another.csv 
root@ee04efbff5e9:~/clonelfs# git commit -m 'another large file'
[master 3d943eb] another large file
 1 file changed, 3 insertions(+)
 create mode 100644 another.csv
root@ee04efbff5e9:~/clonelfs# git push origin master
Git LFS: (0 of 1 files) 0 B / 31 B                                                      
http: Post /root/testlfs.git/info/lfs/objects/batch: unsupported protocol scheme ""
error: failed to push some refs to '/root/testlfs'
~~~

Now I realize of course that git LFS expects to put the large files in some alternative location, which is perfect for my project, but where? Searching tells me that git LFS works using an http server..  How? Where do I tell it to use a server, and how do I configure that server?

Ideally I'd like to put the large files in a dropbox or google drive folder, to be honest, or on our local NFS drive, I don't even know if that's possible because I can't see anything about how file storage actually works on git-lfs.github.com.

I watched the video https://www.youtube.com/watch?v=uLR1RNqJ1Mw, but it again only repeats the same information about how to clone an LFS repository and track files, but nothing about how to actually set up an LFS repository.  I'm sure with more googling I can figure this out, but from my point of view this is a real documentation issue so I post it here.  I really recommend adding some info to the main "getting started" page on how to configure the file storage.

**Comment by technoweenie** [comment]
Hey @radarsat1, thanks for the feedback. You're correct, our user docs are severely lacking. The docs in the repo describe the [server API](https://github.com/github/git-lfs/tree/master/docs/api) that Git LFS talks to, and [how to configure the server endpoint](https://github.com/github/git-lfs/blob/master/docs/spec.md#the-server).

In theory, Git LFS could talk to a local cloud storage folder or shared drive through a local server, or something built into the client. While it's not a priority of mine right now, it's something I'd support if another contributor wanted to add it.

**Comment by radarsat1** [comment]
Oh, that second link is exactly what I was looking for.  Why not stick that at the bottom of Getting Started?

Anyways, just thought my "confused first user" experience might be helpful for you.. thanks for answering.

**Comment by ttaylorr** [comment]
@radarsat1, thanks for opening this. I agree with @technoweenie that our documentation is certain lacking in some areas.

I'd love to figure out why you got that unknown protocol scheme error. I have a hunch it has a similar cause as to https://github.com/github/git-lfs/pull/1507#issuecomment-244975660. Leaving a note for myself to look into this further.

**Comment by radarsat1** [comment]
Oh sorry, I closed this because I assumed it was explained.  The protocol error is because it requires being told where to store files, which requires a URL to be specified, it's just that I didn't see this in the documentation under Getting Started.  I assumed (huge assumption I guess) that by default it would keep the files in some place under the original project's `.git` folder and that I could move them somewhere else later and update the clone to point to the new location, like an NFS drive for example.  I wasn't really thinking of setting up any kind of server when taking a look at git LFS, and therefore wasn't thinking about http, I assumed it had a kind of local-by-default approach like git itself.

**Comment by ttaylorr** [comment]
Ah, thanks for clarifying. 😄
