### ISSUE TITLE
Static URL to allow easy download of latest release.

### ISSUE THREAD

**Issue by jeffreydwalter** [github/git-lfs#1526]
Would it be possible to setup a "static" url where the latest version of git-lfs can be downloaded from?
Something like:
https://github.com/github/git-lfs/releases/download/latest/git-lfs-freebsd-amd64.tar.gz

I'd like to be able to programmatically pull down the latest version when setting up our development environments, and it's a little tricky as-is.

**Comment by technoweenie** [comment]
The Release API has an endpoint for grabbing the [latest Release](https://developer.github.com/v3/repos/releases/#get-the-latest-release). It will return the URLs for each os/architecture. You can download the `asset` you want by matching its `label`, and then hitting the `browser_download_url` (be sure to follow http redirects).

Let me know if you need more help!

**Comment by jeffreydwalter** [comment]
Awesome! I guess I need to RTFM one of these days. :) Thanks!!!
