### ISSUE TITLE
git-lfs locks. Does anyone support it?

### ISSUE THREAD

**Issue by skondratov** [github/git-lfs#1533]
1.3.0 version release notes contain very desirable for me feature:
> Experimental file locking commands 

Do you know server which supports this feature at the moment? I checked GitBlit and BitBucket. And it does not work for them. May be you are aware about upcoming releases.. I know that @sinbad belongs to Atlassian group. 

How i can test these experimental commands right now?

**Comment by technoweenie** [comment]
You can test them by setting `GITLFSLOCKSENABLED=1` in your environment. I hope no one supports them yet, since they're experimental and subject to change.

@sinbad is working on some stuff in https://github.com/github/git-lfs/tree/locking-workflow, but I don't know the status of it yet.

**Comment by skondratov** [comment]
Thank you for response. Yes, i saw this variable. I just thought about some extension for https://github.com/git-lfs/lfs-test-server to make experiments with. But ok, i understood, it is in prototyping stage.

Will wait for your updates guys.

**Comment by sinbad** [comment]
> @sinbad is working on some stuff in https://github.com/github/git-lfs/tree/locking-workflow, but I don't know the status of it yet.

So far I've concentrated on local workflow aspects, marking files as needing locking, making files read-only while unlocked. Eventually I'll probably have to modify the API a little to satisfy some other workflow constraints. Very WIP.
