### ISSUE TITLE
Object skipped when upload link missing

### ISSUE THREAD

**Issue by rjbell4** [github/git-lfs#1534]
Due to a permissions issue for Artifactory, push a new LFS object resulted in the following exchange:
```
> POST /artifactory/api/lfs/automatos_git_lfs/objects/batch HTTP/1.1
> Host: host.domain.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: Basic * * * * *
> Content-Length: 124
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/1.4.0 (GitHub; linux amd64; go 1.7; git 9f1f93f)
>
{"operation":"upload","objects":[{"oid":"8ef0d1dc5eb9a56ff62f5d62caf7807803ab6c9edf413e989d84271b4db6dfb6","size":2097152}]}

< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Connection: keep-alive
< Content-Type: application/vnd.git-lfs+json
< Date: Wed, 21 Sep 2016 13:54:45 GMT
< Server: Artifactory/4.11.0
< X-Artifactory-Id: c591e197ecfaabfd:612f7dbb:15748c7dba3:-8000
<
{
  "objects" : [ {
    "oid" : "8ef0d1dc5eb9a56ff62f5d62caf7807803ab6c9edf413e989d84271b4db6dfb6",
    "size" : -1
  } ]
Git LFS: (0 of 0 files, 1 skipped) 0 B / 2.00 MB
Git LFS: (0 of 0 files, 1 skipped) 0 B / 2.00 MB
```

The base issue here is (I believe) that the Artifactory LFS server did not return an upload link.  That was fixed with a change to Artifactory.

However, I don't like the way that Git LFS responded.  Git LFS skipped the upload.  As a result, I had a repository for which I couldn't fetch all LFS objects.  This basically is like a "hole" in my repository.

Shouldn't Git LFS say, in effect, "hey, I really need to upload this, and there's no upload link!", and exit with an error?

**Comment by technoweenie** [comment]
I don't think so. The correct response from Artifactory would be returning a `403 Forbidden` response to a request if a batch request with `"operation": "upload"` can't complete due to a permissions issue.

The API docs don't really have a concept of per-object permissions, but a server could also implement this with a `200 OK` response, with an error for the bad object like this:

```json
{
  "objects" : [ {
    "oid" : "8ef0d1dc5eb9a56ff62f5d62caf7807803ab6c9edf413e989d84271b4db6dfb6",
    "size" : -1,
    "error": {
      "code": 403,
      "message": "permissions error"
    }
  } ]
}
```

**Comment by ttaylorr** [comment]
I agree with @technoweenie in that LFS's current behavior is correct. Going to close this one out for now.
