### ISSUE TITLE
`git lfs status` crashes on new repos

### ISSUE THREAD

**Issue by larsxschneider** [github/git-lfs#1536]
### Steps to reproduce

```bash
$ git init .
$ git lfs status
Could not get the current ref

Errors logged to /path/to/repo/.git/lfs/objects/logs/20160926T120454.38945701.log
Use `git lfs logs last` to view the log.
```

### Error log
```
git-lfs/1.4.1 (GitHub; darwin amd64; go 1.7)
git version 2.10.0

$ git-lfs status
Could not get the current ref

Git can't resolve ref: "HEAD"
```

**Comment by sinbad** [comment]
There are actually 2 issues here, one is the panic when `HEAD` fails to resolve, the other issue I spotted after fixing that - it looks like `git lfs status` never reports added files correctly even after the first commit. I've fixed the former and made a start on the latter but it's a but more complicated than I thought. I thought I just had to resolve the fact that the `diff-index` commands weren't working with `HEAD` either, but actually no added files show up.

**Comment by sinbad** [comment]
Actually it's only non-added files that are never displayed; however added files were not displayed either before the initial commit, so I've fixed that as well. My push permissions seem to have been revoked atm - assuming that's a mistake I'll push this to a PR when I get those back.
