### ISSUE TITLE
Git-lfs uploads way beyond actual flie size and then aborts due to 413

### ISSUE THREAD

**Issue by JonasT** [github/git-lfs#1539]
For some reason, I am failing to get one recent repository (freshly created) properly pushed:

Git-lfs uploads with a proper estimated file size of 700MB.... and then uploads and uploads way beyond it, until it aborts with 413 error server-side due to exceeding the maximum file size. If you don't understand what I mean with uploading beyond the maximum, see the attached screenshot. 

here is definitely no file larger than 300MB in the repo and in overall 700MB is pretty much the expected size, so I have absolutely no idea what is going or what it is uploading so much 
![brokenupload](https://cloud.githubusercontent.com/assets/1573352/18837614/ab7c4c66-8404-11e6-99f7-cdee50eed764.png)
:confused: any help appreciated

**Comment by JonasT** [comment]
The folder actually seems to be 1.4GB, but there is no file which alone is beyond the max entity limit of the webserver (not even close, more around 300MB for the largest one).

Does the webserver limit actually need to be larger than ALL the files combined in the commit? That would be pretty silly... is there any way to work around that?

**Comment by technoweenie** [comment]
I think that output tracks sent bytes twice if an object is retried. So, a 500 MB file that failed 300MB into the transfer could add 800MB to the output.

The 413 issue is a server related issue. What are you using as your Git LFS server?

**Comment by technoweenie** [comment]
> Does the webserver limit actually need to be larger than ALL the files combined in the commit?

Nope, it should be for a single request.

**Comment by JonasT** [comment]
Ok, I just realized my pipeline goes like this me -> nginx proxy in front -> gitlab's nginx proxy -> gitlab LFS, and I forgot to raise the limit of the gitlab nginx proxy.

However, it would be super helpful if the sent data wouldn't go above the maximum in case of an error, since that made me think it had actually tried to sent 1.4GB in total as a commit and that has lead me on a completely incorrect track of an actually quite simple configuration error.

(also with the correct config, it didn't go above the maximum anymore, so that very confusing behavior was caused by the error)

Summed up: the actual error was my own mistake, but can this display anomaly with failed upload parts be changed? It is very confusing and misleading.

**Comment by technoweenie** [comment]
Cool, thanks for the feedback. A 413 response should always tip you off that it's a server side issue, but I agree the progress meter should be fixed.

**Comment by ttaylorr** [comment]
Thanks (again) for the report! Tracking the progress meter fixes in: https://github.com/github/git-lfs/issues/1542.

**Comment by aparico** [comment]
I am experiencing something similar. The actual file size is 1.36GB. But after reaching 1.36GB, the file size just keeps increasing.

And then it fails to push.
![image](https://user-images.githubusercontent.com/47623790/195261824-b15d727c-1e2b-4337-9d2b-9edf269c5ace.png)
