### ISSUE TITLE
Support git file:/// remotes

### ISSUE THREAD

**Issue by rothgar** [github/git-lfs#1547]
I'm trying to find a way to use git-lfs to make multiple copies of large files on disk. The files are all on the same disk (external mounted storage) but take 100+ GB of data. I'm trying to see if this is possible with lfs.
I am able to track files in the first directory and then `git clone file:///foo/bar` all of the files clone properly and I can ls the directory but accessing the files obviously doesn't work.
Maybe someone has an idea on how this could work or if it isn't the right tool to try and do this.

Any feedback would be appreciated. Thanks

**Comment by technoweenie** [comment]
Unfortunately, you're out of luck with the current Git LFS. It talks to an HTTP API (see [documentation](https://github.com/github/git-lfs/tree/master/docs/api)) to transfer objects. 

However, Go lets you [register functions to different uri schemes](https://golang.org/pkg/net/http/#Transport.RegisterProtocol), like `file://`. It may be possible to mimic the Git LFS API with this, but I haven't tried. This is something I'd be interested in supporting, but is not a priority of mine right now.

**Comment by ttaylorr** [comment]
Thanks for opening this, but I don't think we'll be adding this in the near future.

**Comment by rothgar** [comment]
Thank you for the consideration. I actually discovered that for repos on the same computer git can do this by default.

The thing I was doing wrong was I shouldn't specify file:/// as the URL because that sets up a non-shared repo
If I `git clone /foo/bar` it will automatically clone the repo with .git/objects/info/alternatives pointed to the source repo and sharing object data for less usage on disk.
