### ISSUE TITLE
Git lfs denying to work macOS Sierra on Unity3D project.

### ISSUE THREAD

**Issue by equidevium** [github/git-lfs#1555]
I have a problem with the git lfs. I followed the instructions of the http://en.joysword.com/posts/2016/03/setting_up_github_for_unity_projects/

article. I encountered an error when i try to commit after the first two plugins that i use for unity were added. 

I use UI-Builder and GamestrapUI which are mostly graphic asset libraries and have multiple .psd files. 

I was reading issue #1516 but somehow i cannot find a proper solution. 

I am using SourceTree and a bitbucket account. I did the steps 5 times in case something was missing from my side. No result. 

Sidenote: I am not some kind of pro with git commands on this level. 

Here is the error that i get when i try to stage the files.

fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x10da9122a28a pc=0x1039b]

runtime stack:
runtime.throw(0x62e660, 0x2a)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x836680)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x836680, 0x80, 0x100000000, 0x839630)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x70000cd44dc8)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x836680, 0x80, 0x10100000000, 0x15d4c)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:503 +0x63
runtime.largeAlloc(0x100000, 0x1, 0x42)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:766 +0xb3
runtime.mallocgc.func3()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:664 +0x33
runtime.systemstack(0xc82001e000)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:245 fp=0xc82005af68 sp=0xc82005af60
runtime.mallocgc(0x100000, 0x418c00, 0xc800000001, 0x10)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:665 +0x9eb fp=0xc82005b040 sp=0xc82005af68
runtime.newarray(0x418c00, 0x100000, 0xc820032298)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:798 +0xc9 fp=0xc82005b080 sp=0xc82005b040
runtime.makeslice(0x4073c0, 0x100000, 0x100000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/slice.go:32 +0x165 fp=0xc82005b0d0 sp=0xc82005b080
github.com/github/git-lfs/errutil.Stack(0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/errutil/errors.go:578 +0x4a fp=0xc82005b120 sp=0xc82005b0d0
github.com/github/git-lfs/errutil.newWrappedError(0x970028, 0xc820130490, 0x601ce0, 0x21, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/errutil/errors.go:326 +0x1a3 fp=0xc82005b210 sp=0xc82005b120
github.com/github/git-lfs/errutil.NewNotAPointerError(0x0, 0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/errutil/errors.go:518 +0x50 fp=0xc82005b270 sp=0xc82005b210
github.com/github/git-lfs/lfs.decodeKVData(0xc820035400, 0x3fc, 0x400, 0xc8200fd080, 0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer.go:236 +0xd9 fp=0xc82005b4c8 sp=0xc82005b270
github.com/github/git-lfs/lfs.decodeKV(0xc820035400, 0x3fc, 0x400, 0xc820035400, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer.go:139 +0x5f fp=0xc82005b6f8 sp=0xc82005b4c8
github.com/github/git-lfs/lfs.DecodeFrom(0x9b0000, 0xc820032008, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer.go:120 +0x17b fp=0xc82005b790 sp=0xc82005b6f8
github.com/github/git-lfs/lfs.copyToTemp(0x9b0000, 0xc820032008, 0x1473, 0x0, 0x0, 0x0, 0x0, 0xc820032290, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer_clean.go:79 +0x2b6 fp=0xc82005b910 sp=0xc82005b790
github.com/github/git-lfs/lfs.PointerClean(0x9b0000, 0xc820032008, 0x7fff5fbff9c1, 0x2d, 0x1473, 0x0, 0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer_clean.go:54 +0x979 fp=0xc82005baf8 sp=0xc82005b910
github.com/github/git-lfs/commands.cleanCommand(0x82aa00, 0xc8200c3140, 0x1, 0x2)
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_clean.go:44 +0x264 fp=0xc82005bcf0 sp=0xc82005baf8
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute(0x82aa00, 0xc8200c2fc0, 0x2, 0x2, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/github.com/spf13/cobra/command.go:477 +0x3f4 fp=0xc82005bdb8 sp=0xc82005bcf0
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute(0x82e2e0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/github.com/spf13/cobra/command.go:551 +0x46a fp=0xc82005bec0 sp=0xc82005bdb8
github.com/github/git-lfs/commands.Run()
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:112 +0x23 fp=0xc82005bee0 sp=0xc82005bec0
main.main()
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:33 +0x12e fp=0xc82005bf50 sp=0xc82005bee0
runtime.main()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc82005bfa0 sp=0xc82005bf50
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82005bfa8 sp=0xc82005bfa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/Cellar/go/1.6.3/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.6.3/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [select, locked to thread]:
runtime.gopark(0x674f58, 0xc820031728, 0x58bad0, 0x6, 0x18, 0x2)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820031728, 0x0, 0x18)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820031728)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/signal1_unix.go:279 +0x32c
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 9 [chan receive]:
main.main.func1(0xc820011800, 0xc82000fb40)
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:21 +0x66
created by main.main
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:31 +0x129
error: external filter git-lfs clean -- %f failed 2
error: external filter git-lfs clean -- %f failed
fatal: Assets/Gamestrap UI/Prefabs/ButtonIcon.prefab: clean filter 'lfs' failed

Please some help would be really appreciated.

**Comment by equidevium** [comment]
Some more things that i tried after some posts that were referring to the same behaviour was to uninstall go and reinstall it. I went to my usr/local and deleted the go folder. Made a cleanup with CleanMyMac 3 application and then restarted the computer. 

Reinstalled via the go package installer provided by their website. 

Still no result.

**Comment by equidevium** [comment]
git-lfs/1.3.1 (GitHub; darwin amd64; go 1.6.3; git 9c9dffb)  from the git lfs version

**Comment by equidevium** [comment]
<img width="422" alt="screen shot 2016-10-03 at 22 33 27" src="https://cloud.githubusercontent.com/assets/11783663/19050962/8f504b4a-89b9-11e6-9de8-4426f9f41188.png">

This is been spammed every time that i try to stage the files to make a commit. 

And this time out of random this came as an error.

error: git-lfs clean -- 'Assets/UI - BUILDER/Prefabs/1. Fundamental UI Elements/ColorSchemes/ColorPalette_17.prefab' died of signal 11
error: external filter git-lfs clean -- %f failed 139
error: external filter git-lfs clean -- %f failed
fatal: Assets/UI - BUILDER/Prefabs/1. Fundamental UI Elements/ColorSchemes/ColorPalette_17.prefab: clean filter 'lfs' failed

**Comment by ttaylorr** [comment]
Hi @equidevium, thanks for opening this.

The error that sticks out to me is:

> /Users/rick/go/src/github.com/github/git-lfs/lfs/pointer.go:236 +0xd9 fp=0xc82005b4c8 sp=0xc82005b270

which points [here](https://github.com/github/git-lfs/blob/9c9dffb1b5baddfa06f280ef1b5fbf68ecbc90b1/lfs/pointer.go#L236). It looks like your pointer file is either corrupt, or wasn't generated.

Can you run `git lfs env` (and paste a copy of your .gitattributes file) so we can verify that your LFS filters are set up correctly?

**Comment by equidevium** [comment]
Endpoint (equideviumui)=https://douoht@bitbucket.org/douoht/equideviumui.git/info/lfs (auth=none)
LocalWorkingDir=/Users/RANDOMUSERNAME/Desktop/MyUnity/Projects/EquideviumUI
LocalGitDir=/Users/RANDOMUSERNAME/Desktop/MyUnity/Projects/EquideviumUI/.git
LocalGitStorageDir=/Users/RANDOMUSERNAME/Desktop/MyUnity/Projects/EquideviumUI/.git
LocalMediaDir=/Users/RANDOMUSERNAME/Desktop/MyUnity/Projects/EquideviumUI/.git/lfs/objects
LocalReferenceDir=
TempDir=/Users/RANDOMUSERNAME/Desktop/MyUnity/Projects/EquideviumUI/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
Theodoross-MacBook-Pro:Assets RANDOMUSERNAME $

**Comment by equidevium** [comment]
*.wav filter=lfs diff=lfs merge=lfs -text
*.fbx filter=lfs diff=lfs merge=lfs -text
*.png filter=lfs diff=lfs merge=lfs -text
*.mp3 filter=lfs diff=lfs merge=lfs -text
*.hdr filter=lfs diff=lfs merge=lfs -text
*.tga filter=lfs diff=lfs merge=lfs -text
*.ogg filter=lfs diff=lfs merge=lfs -text
*.sip filter=lfs diff=lfs merge=lfs -text
*.jpg filter=lfs diff=lfs merge=lfs -text
*.mp4 filter=lfs diff=lfs merge=lfs -text
*.exr filter=lfs diff=lfs merge=lfs -text
*.prefab filter=lfs diff=lfs merge=lfs -text


and this is the .gitattributes

**Comment by ttaylorr** [comment]
Thanks. Looks like your Go version is slightly out-of-date. Since there were a few issues with the Go v1.6.x series on macOS Sierra, could you try and upgrade to Go v1.7.1?

**Comment by equidevium** [comment]
go version go1.7.1 darwin/amd64  but this is what i am using. I have uninstalled and reinstalled the go lang two times now.

**Comment by ttaylorr** [comment]
Sorry, I misspoke, the version of Git LFS is out of date, and was compiled against the v1.6.x series. Could you upgrade git-lfs to `v1.4.1`?

**Comment by equidevium** [comment]
Theodoross-MacBook-Pro:Assets RANDOMUSERNAME $ git-lfs update --force
Updated pre-push hook.
Theodoross-MacBook-Pro:Assets RANDOMUSERNAME $ git-lfs version
git-lfs/1.3.1 (GitHub; darwin amd64; go 1.6.3; git 9c9dffb)
Theodoross-MacBook-Pro:Assets RANDOMUSERNAME $ 

this is strange for me.

**Comment by ttaylorr** [comment]
The `update` command only updates hooks and filters, not Git LFS itself. You can use `brew update && brew upgrade git-lfs` (if you used Homebrew to install), or any of the other installation guides in [our README](https://github.com/github/git-lfs#getting-started).

**Comment by equidevium** [comment]
Oh i did that some hours ago and i thought something had to do with brew installation or update.

Theodoross-MacBook-Pro:Assets RANDOMUSERNAME $ brew upgrade git-lfs
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, homebrew/x11).
==> New Formulae
sonar-scanner                                      sqldiff                                          
==> Updated Formulae
homebrew/x11/xastir      hub                      jboss-forge              mogenerator            

Error: git-lfs 1.4.1 already installed
Theodoross-MacBook-Pro:Assets RANDOMUSERNAME $ git-lfs version
git-lfs/1.3.1 (GitHub; darwin amd64; go 1.6.3; git 9c9dffb)
Theodoross-MacBook-Pro:Assets RANDOMUSERNAME $

**Comment by ttaylorr** [comment]
There are multiple versions of `git-lfs` installed on your computer. Try:

```
$ rm "$(which git-lfs)"
$ brew link git-lfs --overwrite
```

**Comment by equidevium** [comment]
Thanks for that quite a lot. Did not notice to be honest. 

error: git-lfs clean -- 'Assets/Gamestrap UI/Graphics/gamestrap-h.png' died of signal 11
error: external filter git-lfs clean -- %f failed 139
error: external filter git-lfs clean -- %f failed
fatal: Assets/Gamestrap UI/Graphics/gamestrap-h.png: clean filter 'lfs' failed

These are the new errors on the stage files window though. Any ideas?!

**Comment by ttaylorr** [comment]
Does SourceTree provide you any more information? Signal 11 is usually a segfault, but without more info, I'm not sure what is causing it.

**Comment by equidevium** [comment]
git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree add -f -- 
.......  then a very big list of "asset name here" then the error message i posted

**Comment by equidevium** [comment]
ok i found out that the gitattributes file has been deleted now that we fixed the git lfs version.

The following arrises again though. 

fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x14eddb6d1884 pc=0x1039b]

runtime stack:
runtime.throw(0x62e660, 0x2a)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x836680)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x836680, 0x80, 0x100000000, 0x839630)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x70000d09fdc8)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x836680, 0x80, 0x10100000000, 0x15d4c)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:503 +0x63
runtime.largeAlloc(0x100000, 0x1, 0x42)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:766 +0xb3
runtime.mallocgc.func3()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:664 +0x33
runtime.systemstack(0xc82001e000)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:245 fp=0xc82005af68 sp=0xc82005af60
runtime.mallocgc(0x100000, 0x418c00, 0xc800000001, 0x10)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:665 +0x9eb fp=0xc82005b040 sp=0xc82005af68
runtime.newarray(0x418c00, 0x100000, 0xc820032298)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:798 +0xc9 fp=0xc82005b080 sp=0xc82005b040
runtime.makeslice(0x4073c0, 0x100000, 0x100000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/slice.go:32 +0x165 fp=0xc82005b0d0 sp=0xc82005b080
github.com/github/git-lfs/errutil.Stack(0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/errutil/errors.go:578 +0x4a fp=0xc82005b120 sp=0xc82005b0d0
github.com/github/git-lfs/errutil.newWrappedError(0x970028, 0xc820132490, 0x601ce0, 0x21, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/errutil/errors.go:326 +0x1a3 fp=0xc82005b210 sp=0xc82005b120
github.com/github/git-lfs/errutil.NewNotAPointerError(0x0, 0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/errutil/errors.go:518 +0x50 fp=0xc82005b270 sp=0xc82005b210
github.com/github/git-lfs/lfs.decodeKVData(0xc820035400, 0x400, 0x400, 0xc8200fd080, 0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer.go:236 +0xd9 fp=0xc82005b4c8 sp=0xc82005b270
github.com/github/git-lfs/lfs.decodeKV(0xc820035400, 0x400, 0x400, 0xc820035400, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer.go:139 +0x5f fp=0xc82005b6f8 sp=0xc82005b4c8
github.com/github/git-lfs/lfs.DecodeFrom(0x9b0000, 0xc820032008, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer.go:120 +0x17b fp=0xc82005b790 sp=0xc82005b6f8
github.com/github/git-lfs/lfs.copyToTemp(0x9b0000, 0xc820032008, 0xc7ca, 0x0, 0x0, 0x0, 0x0, 0xc820032290, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer_clean.go:79 +0x2b6 fp=0xc82005b910 sp=0xc82005b790
github.com/github/git-lfs/lfs.PointerClean(0x9b0000, 0xc820032008, 0x7fff5fbff9c1, 0x2f, 0xc7ca, 0x0, 0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer_clean.go:54 +0x979 fp=0xc82005baf8 sp=0xc82005b910
github.com/github/git-lfs/commands.cleanCommand(0x82aa00, 0xc8200cf140, 0x1, 0x2)
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_clean.go:44 +0x264 fp=0xc82005bcf0 sp=0xc82005baf8
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute(0x82aa00, 0xc8200cefc0, 0x2, 0x2, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/github.com/spf13/cobra/command.go:477 +0x3f4 fp=0xc82005bdb8 sp=0xc82005bcf0
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute(0x82e2e0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/github.com/spf13/cobra/command.go:551 +0x46a fp=0xc82005bec0 sp=0xc82005bdb8
github.com/github/git-lfs/commands.Run()
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:112 +0x23 fp=0xc82005bee0 sp=0xc82005bec0
main.main()
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:33 +0x12e fp=0xc82005bf50 sp=0xc82005bee0
runtime.main()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc82005bfa0 sp=0xc82005bf50
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82005bfa8 sp=0xc82005bfa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/Cellar/go/1.6.3/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.6.3/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [select, locked to thread]:
runtime.gopark(0x674f58, 0xc820031728, 0x58bad0, 0x6, 0x18, 0x2)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820031728, 0x0, 0x18)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820031728)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/signal1_unix.go:279 +0x32c
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 9 [chan receive]:
main.main.func1(0xc820011800, 0xc82000fb40)
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:21 +0x66
created by main.main
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:31 +0x129
error: external filter git-lfs clean -- %f failed 2
error: external filter git-lfs clean -- %f failed
fatal: Assets/Gamestrap UI/Editor/UI/Button Normal.psd: clean filter 'lfs' failed

**Comment by ttaylorr** [comment]
Did some more digging, and it turns out that my previous suggestion is incorrect. It turns out the reason that there are two versions of LFS on your computer is that SourceTree bundles its own version of Git LFS in its release. Since LFS v1.3.1 (the latest version I assume is bundled with the latest version of SourceTree) is compiled under a version of Go that is incompatible with macOS Sierra, there's nothing we can do to make SourceTree + Git LFS work under macOS Sierra.

In the meantime, I recommend you use the version of LFS that you installed over the command line until SourceTree releases a new version with the latest Git LFS.

cc @sinbad

**Comment by equidevium** [comment]
Thanks for your time @ttaylorr. At least this solves a lot of confusion for me. I will try to check any other solution that anyone had to introduce and bang on Unity forums for your answer so that more people know about this issue. Be good.

**Comment by ttaylorr** [comment]
Thanks for your quick responses. Please re-open this issue if you find anything out. 😄

**Comment by sinbad** [comment]
This has been resolved for a while in SourceTree 2.4, but I checked with the SourceTree team and it's been held up in beta because of other issues. If you don't want to [switch to the beta](https://blog.sourcetreeapp.com/2016/03/25/sourcetree-beta-program-is-here-become-a-trusted-tester/) you can use your own version of git-lfs instead:

1. In SourceTree, go to Preferences > Git
1. At the bottom in the Git LFS section, click  "Use System git-lfs" and browse to your version

**Comment by equidevium** [comment]
This indeed fixed the problem for now. Thanks for the tip.
