### ISSUE TITLE
fetchinclude and fetchexclude under Windows

### ISSUE THREAD

**Issue by smorin-primero** [github/git-lfs#1556]
Under Windows, the lfs.fetchinclude,lfs.fetchexclude configurations and --include= and --exclude= options requires Windows style path (using backslashes instead of slashes).

Since most of the configuration for git uses the Unix style path, these configurations and options should also support the Unix style path.

**Comment by ttaylorr** [comment]
Those paths are cleaned according to Go's [`path.Clean`](https://golang.org/src/path/path.go?s=1806:1836#L59), which uses `/`s. Are you using `git-bash.exe`, or `cmd.exe`? Those two have different behavior,.

**Comment by smorin-primero** [comment]
This is using git-bash

**Comment by ttaylorr** [comment]
Fixed in https://github.com/github/git-lfs/pull/1565.
