### ISSUE TITLE
Cannot do a multiple commands due to "clean filter 'lfs' failed"

### ISSUE THREAD

**Issue by Toldy** [github/git-lfs#1559]
Hi,

I recently renamed a directory. This directory is a git repository in which I use git-lfs.
The problem is that most of the git commands fails now when I launch them in this repo.

By example:
```
➜  iOS git:(proto) git status
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x625469325e8 pc=0x1039b]

runtime stack:
runtime.throw(0x62e660, 0x2a)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x836680)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x836680, 0x1, 0x9, 0x926670)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7fff5fbff778)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x836680, 0x1, 0x10000000009, 0x1003f)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x837d40, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x837d40, 0xc82000a1b0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x920000, 0x9, 0xc82000a180)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0x831700)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:1051

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:245 fp=0xc82004fcc0 sp=0xc82004fcb8
runtime.mallocgc(0x80, 0x5471e0, 0x0, 0x1)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:643 +0x869 fp=0xc82004fd98 sp=0xc82004fcc0
runtime.newobject(0x5471e0, 0xc820011bd0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:781 +0x42 fp=0xc82004fdc0 sp=0xc82004fd98
github.com/github/git-lfs/vendor/github.com/spf13/pflag.(*FlagSet).VarPF(0xc8200f9e00, 0x974758, 0x84d75b, 0x58abf8, 0x6, 0x58aba8, 0x1, 0x601da0, 0x26, 0xc8200f9f80)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/github.com/spf13/pflag/flag.go:473 +0x4f fp=0xc82004fe00 sp=0xc82004fdc0
github.com/github/git-lfs/vendor/github.com/spf13/pflag.(*FlagSet).BoolVarP(0xc8200f9e00, 0x84d75b, 0x58abf8, 0x6, 0x58aba8, 0x1, 0xc82004fe00, 0x601da0, 0x26)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/github.com/spf13/pflag/bool.go:58 +0xb2 fp=0xc82004fe70 sp=0xc82004fe00
github.com/github/git-lfs/commands.init.26()
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_update.go:63 +0xf3 fp=0xc82004fee0 sp=0xc82004fe70
github.com/github/git-lfs/commands.init()
	/Users/rick/go/src/github.com/github/git-lfs/commands/uploader.go:159 +0x4c6 fp=0xc82004ff48 sp=0xc82004fee0
main.init()
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:35 +0x54 fp=0xc82004ff50 sp=0xc82004ff48
runtime.main()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:177 +0x27f fp=0xc82004ffa0 sp=0xc82004ff50
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82004ffa8 sp=0xc82004ffa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/Cellar/go/1.6.3/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.6.3/libexec/src/os/signal/signal_unix.go:28 +0x37
error: external filter git-lfs clean -- %f failed 2
error: external filter git-lfs clean -- %f failed
fatal: Frameworks/Debug/Softphone.framework/Headers/RingerSetting.h: clean filter 'lfs' failed
```

I have other repositories in which I am using git lfs and I have no problems with them.
I don't know if it's linked but, I installed the macOS Sierra just before having this bug 🤔

Do you have any idea of what the problem could be ?
Thanks for the help !

**Comment by ttaylorr** [comment]
Hi @Toldy, thanks for opening this. The macOS Sierra release had a number of issues with Go v1.6.2 and under, which is what some versions of Git LFS are built on.

Could you try upgrading to the latest version of Git LFS (v1.4.1) and try again?

**Comment by Toldy** [comment]
I am already to the latest version (v1.4.1)

**Comment by ttaylorr** [comment]
Strange. Could you try and updating the reference to that directory in your `.gitattributes`?

**Comment by Toldy** [comment]
Hmm, sorry what do you mean by updating the reference to this directory ?

This is the content of my `.gitattributes`

```
Frameworks/** filter=lfs diff=lfs merge=lfs -text
```

**Comment by ttaylorr** [comment]
If your directory was renamed from `Frameworks` to something else, replace the old references in `.gitattributes` to whatever it is called now.

**Comment by Toldy** [comment]
Oh sorry, perhaps I expressed myself poorly...
This is my structure:
```
./ An iOS project  -> Git repository (host on github)
├── some files
└── Frameworks/    -> repository managed with git-lfs
```
The directory which have been renamed is the root directory, namely "An iOS project".
I didn't change anything about the Frameworks directory :/

So the reference in `.gitattributes` should not be changed, right ?

**Comment by ttaylorr** [comment]
Ah, thanks for explaining. I'm not immediately sure what's going on here. @technoweenie: any thoughts?

**Comment by technoweenie** [comment]
This issue looks like it has to do with Go 1.6.3 and Sierra. Can you install Git LFS with Go 1.7? How did you install Git LFS? Did you use homebrew, or did you download it from [the github release page](https://github.com/github/git-lfs/releases/tag/v1.4.1)?

Renaming the directory containing your repository should have no effect on Git LFS.

**Comment by Toldy** [comment]
I installed git LFS with homebrew.

I understand that it should have no impact. The strange thing is that I still have an old copy of my  "An iOS project" in an other directory and there is no git problem with this one.

What should I do then ? Uninstall git LFS with brew, install Go 1.7 and then install git LFS from the release page ?

**Comment by technoweenie** [comment]
If you're comfortable with homebrew, try `brew update` to update the formulas, and then upgrade go and git-lfs. It should use your current version of Go to compile LFS.

The Mac binary on the release page is pre-compiled, so you could just download it and replace the file at `which git-lfs` without recompiling anything.

**Comment by Toldy** [comment]
Time to go bed in France, I will try that tomorrow :)

**Comment by Toldy** [comment]
Wow many thanks, it works now!

I replaced my binary located at `which git-lfs` with the one from [the github release page](https://github.com/github/git-lfs/releases/tag/v1.4.1).

No git-lfs error anymore 👍

**Comment by technoweenie** [comment]
Great! In the future, make sure homebrew has Go 1.7.1+ installed before upgrading Git LFS, and you should be fine (until the _next_ macOS release :trollface:)
