### ISSUE TITLE
can not check out repo: "read: connection reset by peer"

### ISSUE THREAD

**Issue by nrser** [github/git-lfs#1578]
i'm getting consistent failures trying to check out a repo with lfs content using

```
git-lfs/1.4.2 (GitHub; darwin amd64; go 1.7.1)
git version 2.8.2
OSX 10.10.5
```

each failure results in the same log / stack trace like:

```
$ git-lfs smudge -- art/big-logo.psd
Error downloading object: art/big-logo.psd (344456fe780b8ad91e1c2255d8c9d29c8bb14458322e46356723bba76d305f76)

Smudge error: Error buffering media file: cannot write data to tempfile "/Users/nrser/dev/gh/beiarea/web/.git/lfs/objects/incomplete/344456fe780b8ad91e1c2255d8c9d29c8bb14458322e46356723bba76d305f76.tmp": LFS: read tcp 10.0.1.8:61741->54.231.82.106:443: read: connection reset by peer: 
github.com/github/git-lfs/errors.newWrappedError
	/private/tmp/git-lfs-20161012-16180-10xir79/git-lfs-1.4.2/src/github.com/github/git-lfs/errors/types.go:166
```

full log (they're all identical except for different file names):

https://gist.github.com/nrser/76be1f49f825ce8a6adedd958d408b09

i seem to be able to re-start the process with `git checkout -f HEAD`, and it seems to start again at the file it previously erred at, and doing this enough times will sometimes eventually succeed, but other times it just keeps failing at the same spot, leaving the repo in a weird state and preventing me from doing any work.

i'm in Beijing, so my connection to the US isn't super fast or stable, but i have no problem checking out non-lfs repos. i've tried over secure tunnels and it actually seems to work better without.

any help would be greatly appreciated, this has put us in difficult spot having repo content in lfs and not being able to check the repos out.

**Comment by technoweenie** [comment]
Hi @nrser, sorry you're having a rough time here. The transfer code is getting a major overhaul focusing on better retries and resumable downloads for v1.5.0.

You could try bumping the timeout settings a bit, as [described here](https://github.com/github/git-lfs/blob/76ad7e8343cae72866aa36581e329f34f5614243/docs/man/git-lfs-config.5.ronn#L31-L40), but I'm not sure that will help too much.

You could also try skipping the smudge command, and running `git lfs pull` directly. This lets us workaround git's filters, and handle the download completely in Git LFS:

```bash
# run once to set globally for ~/.gitconfig
$ git lfs install --skip-smudge

$ git checkout -f HEAD
$ git lfs pull # this actually downloads the objects and updates your local files
```

You can tweak a few more variables to control this too:

* [`lfs.concurrenttransfers`](https://github.com/github/git-lfs/blob/76ad7e8343cae72866aa36581e329f34f5614243/docs/man/git-lfs-config.5.ronn#L51-L53)
* [`lfs.transfer.maxretries`](https://github.com/github/git-lfs/blob/76ad7e8343cae72866aa36581e329f34f5614243/docs/man/git-lfs-config.5.ronn#L104-L109) (only available in v1.4.2+)

**Comment by nrser** [comment]
thank, i haven't had occasion to do a pull but just running `git lfs push origin master` instead of through `git push` seems to have helped quite a bit. i'll check out twiddling the settings as well, and am looking forward to the update.

i'll close this for now and open another issue if i hit something more specific.

**Comment by nrser** [comment]
@technoweenie this has helped considerably. `--skip-smudge` lets me get shit done while i try to `git lfs pull` in another tab (lfs files are all art that isn't needed to run the app).

specific question about config settings - it seems like connections intermittently stall and won't get any more data through them until they're retried. i set `lfs.transfer.maxretries` up to 10, but my guess is that it's taking quite some time to figure out that the connection is dead... is there any way to lower that timeout? basically, i'd like to tell it if it doesn't see data for 1s or something to close and retry the connection.

**Comment by technoweenie** [comment]
Git LFS doesn't set any idle timeouts on connections, so it's just going by the default that Go uses (which may be no timeout). We should investigate incorporating a custom dialer that sets read/write deadlines on the underlying connection. I have a [sample custom dialer](https://github.com/technoweenie/httpretry/blob/8b5e81f44aedb09f45acce2a60b367f1ac5a27cb/http_client.go#L27-L76) that should work. We'll investigate for v1.5.0.

**Comment by nrser** [comment]
sounds good, look forward to it

**Comment by ttaylorr** [comment]
Hi! We unfortunately didn't get to this in time for v1.5.0 (which was released last week), so I've gone ahead and moved it to the `v2.0.0-maybe` milestone. 👍
