### ISSUE TITLE
Versio 1.4.2 introduces "invalid memory address or nil pointer dereference" on fetch

### ISSUE THREAD

**Issue by sschuberth** [github/git-lfs#1580]
When doing `git lfs fetch` with version 1.4.2 on Windows x64 I get:

    Fetching master
    &{0xc042044120} WARNING: Git LFS is using a deprecated API, which will be removed in v1.5.0.
    &{0xc042044120}          Consider enabling the latest API by running: `git config lfs.batch true`.
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xc0000005 code=0x0 addr=0x0 pc=0x525a18]

    goroutine 41 [running]:
    panic(0x79e920, 0xc04200c0a0)
            c:/go/src/runtime/panic.go:500 +0x1af
    github.com/github/git-lfs/lfs.(*TransferQueue).individualApiRoutine(0xc042200000, 0xc0423738c0)
            c:/go/src/github.com/github/git-lfs/lfs/transfer_queue.go:341 +0xe8
    created by github.com/github/git-lfs/lfs.(*TransferQueue).launchIndividualApiRoutines.func1
            c:/go/src/github.com/github/git-lfs/lfs/transfer_queue.go:515 +0x72

with version 1.4.1 everything is fine. So my guess one of these introduced this:

    $ git log v1.4.2 --not v1.4.1  -- lfs/transfer_queue.go
    commit 6c0b9373ee7490ab0453e7f1fb65ea1743ec0a90
    Author: Taylor Blau <me@ttaylorr.com>
    Date:   Mon Oct 10 15:57:12 2016 -0600

        lfs/tq: send error before terminating object

        Previously, decrementing the surrounding `sync.WaitGroup` allowed the
        `q.errorc` channel to be closed before this send could occur. This racy
        behavior introduced a send-on-closed-channel panic, which is fixed in this
        commit.

    commit b5cba63f36656a75624b1cee4d1fdaf7525f4060
    Author: Taylor Blau <me@ttaylorr.com>
    Date:   Wed Sep 28 12:25:37 2016 -0600

        lfs/tq: extract `RetryCounter`

    commit 4b194496c15d584820ceaf40524f2492b53782da
    Author: Taylor Blau <me@ttaylorr.com>
    Date:   Wed Sep 21 17:38:32 2016 -0600

        lfs/transfer_queue: remove debug stmt

    commit 9b1bd0471c061c306c07f18ed48dd80e895f8d32
    Author: Taylor Blau <me@ttaylorr.com>
    Date:   Wed Sep 21 13:46:34 2016 -0600

        lfs/transfer_queue: support multiple retries per object

@ttaylorr Mind having a look?

**Comment by sschuberth** [comment]
Maybe we need to check `obj` for nil [here](https://github.com/github/git-lfs/blob/master/lfs/transfer_queue.go#L341), too?

**Comment by ttaylorr** [comment]
You're absolutely correct. I'll patch this today.

**Comment by sschuberth** [comment]
Any idea why none of the tests catched this, and/or mind adding a tests accordingly?
