### ISSUE TITLE
Clarify why git-lfs-migrate is preferred over bfg-repo-cleaner

### ISSUE THREAD

**Issue by sschuberth** [github/git-lfs#1589]
In the [Tutorial](https://github.com/github/git-lfs/wiki/Tutorial) there are still several references to [BFG](https://github.com/rtyley/bfg-repo-cleaner), but the actual migration instruction have been stroked out and replaced by a link to [git-lfs-migrate](https://github.com/bozaro/git-lfs-migrate) by @andyneff . I believe this is confusing. What makes git-lfs-migrate preferable over BFG? If there is some valid reason to only use git-lfs-migrate all references to BFG should go completely (and not just be stroked out). If both do the job equally well, both should be mentioned equally.

**Comment by technoweenie** [comment]
BFG writes gitattributes files incorrectly if you're updating multiple file types: https://github.com/rtyley/bfg-repo-cleaner/issues/116

**Comment by sschuberth** [comment]
I've [edited the wiki](https://github.com/github/git-lfs/wiki/Tutorial#migrating-existing-repository-data-to-lfs) to make this more clear.
