### ISSUE TITLE
Credentials not found when `git pull` is run via subprocess

### ISSUE THREAD

**Issue by theNewFlesh** [github/git-lfs#1598]
`git pull` works fine in the command line

However, 

When I run this:
```
command = 'git push origin alex'
output = Popen(command, shell=True, stdout=PIPE, stderr=PIPE, cwd='/tmp/test-repo/')
stderr = output.stderr.read().decode('utf-8')
stdout = output.stdout.read().decode('utf-8')

print(stdout)
print(stderr)
```

I get this:
```
Git LFS: (0 of 1 files) 0 B / 8 B                                              

LFS: Git credentials for http://localhost:8080 not found.
error: failed to push some refs to 'git@github.com:nerve-test-organization/nerve-test-repo-3.git'
```

python=3.4
os=macOS 10.11.3
lfs-server=meltingice/git-lfs-s3

**Comment by ttaylorr** [comment]
Hi @theNewFlesh, thanks for opening this. I don't have a whole lot of Python experience, but my hunch is that your normal command prompt's environment isn't making its way into the command you spawned from `Popopen`.

Do you have a `credential.helper` key set in your git config in the subprocess?

**Comment by theNewFlesh** [comment]
As is customary for me, figured it out about an hour after creating this issue.  I just have to pass in the environment vars when I call Popen.  

I do, however, have another issue:
I cannot run `git push origin master` from subprocess, even with the environment.  I think it has to do with a race condition created by the lfs pre-push hook.  Subprocess calls `git push`, `git push` calls `git lfs`, `git push` ends before lfs or lfs kills the stdout/return code.  Git push works normally in the command line, so one would think that invoking it through suprocess would work the same, since the module literally sends the same commands to a shell environment.

**Comment by ttaylorr** [comment]
Glad you got it! 👍 

I'd be curious to hear more about a potential race in the pre-push hook. Can you confirm this by running the same command with `GIT_TRACE=1` in your environment?

**Comment by theNewFlesh** [comment]
My stdout gets clobbered.  However, I ran the same python code with and without LFS enabled.  Everything works fine without LFS (no pre-push hook), with LFS, I have an error when I try to run `git push`.  I am running `git push` with GitPython and subprocess (trying to avoid subprocess).  
Git and Git lfs work normally via commandline.  So I am pretty sure it is the pre-push hook, as that is the only lfs that is called when git push is called.

How do I manually use `git lfs pre-push`? I see the hook grabs $@.  I'de imagine I'de have to format some  params to hand off to it.

**Comment by theNewFlesh** [comment]
Yup, deleting the pre-push file and calling `git lfs push` manually before `git push` did the trick.

**Comment by technoweenie** [comment]
> How do I manually use git lfs pre-push?

The docs are [here](https://github.com/github/git-lfs/blob/97306ee58215a3c7730e8588d57d1db133b5df75/commands/command_pre_push.go#L18-L39). If you're pushing a single branch to github, you could simulate it like this:

```bash
$ echo "master {latest-local-commit-sha} master {latest-github-commit-sha}" | git lfs pre-push origin https://github.com/foo/bar.git
```

My hunch is that the env in your python script is different that the env that `git` runs `git lfs pre-push`. You could try dumping the env in your python script AND at the top of the pre-push hook.

```bash
#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
env > pre-push-env.txt
git lfs pre-push "$@"
```

See how that compares to the env in your python script. This doesn't seem like an LFS bug (we have no control over how git calls the pre-push hook), but there's probably something we can add to make debugging these issues easier if we can nail down what the problem is.

**Comment by theNewFlesh** [comment]
Yeah, I already did that.  The environment variables are a part of the problem, the other is some sort of race condition between `git push` and `git lfs prepush` when called from non-standard contexts.  Somewhere in your docs (unless I missed it), maybe mention that you should call all git lfs operations manually, rather than relying on git to orchestrate the behavior correctly.

**Comment by Hemanth211** [comment]
Hi, I'm doing the pre-receive hook, when I create new branch the old rev is 0. When I try to read all the latest commit hashes using this line in python.

new_branch_revs = 'git rev-list origin' + ".." + newrev
all_revs = subprocess.Popen(new_branch_revs, shell=True, stdout=subprocess.PIPE)
new_rev = all_revs.stdout.read().rstrip('\n')

I'm getting the following exception:

remote: fatal: ambiguous argument 'origin': unknown revision or path not in the working tree.

Please help me where I'm doing wrong.

**Comment by Hemanth211** [comment]
> Yeah, I already did that. The environment variables are a part of the problem, the other is some sort of race condition between `git push` and `git lfs prepush` when called from non-standard contexts. Somewhere in your docs (unless I missed it), maybe mention that you should call all git lfs operations manually, rather than relying on git to orchestrate the behavior correctly.

**Comment by Hemanth211** [comment]
> As is customary for me, figured it out about an hour after creating this issue. I just have to pass in the environment vars when I call Popen.
> 
> I do, however, have another issue:

Could you please suggest how you resolved this issue?

**Comment by theNewFlesh** [comment]
I honestly don't remember the details of this three year old issue.

You can look at my git-lfs repo [nerve](https://github.com/theNewFlesh/nerve) for answers.

I'de look here:
https://github.com/theNewFlesh/nerve/blob/master/python/nerve/core/git.py
