### ISSUE TITLE
Can't push: transfer/object has expired

### ISSUE THREAD

**Issue by ArianRudd** [github/git-lfs#1601]
We can't push a commit with new LFS objects from diffrent locations. The message is that the object has "expired", any suggestions?

$ git push
Git LFS: (0 of 8 files) 0 B / 40.34 MB
LFS: lfs/transfer: object "xxxxxxx" has expired
LFS: lfs/transfer: object "xxxxxxxxxxxxx" has expired
error: failed to push some refs to 'xxxxxxxxxxxxxxx'

**Comment by ttaylorr** [comment]
Hi @ArianRudd, sorry to hear that you're having trouble. This error is normal, and means that the object that you are trying to push no longer has an active URL that you can push it to.

There are a couple of reasons that this can happen, and I'm adding a patch to 1.4.4 that will make this error clearer and easier to debug. My plan is to release that on Monday.

Can we follow up after you've tried again with the new release?

**Comment by ArianRudd** [comment]
Thanks for your answer. 
It is so critical for us as it is blocking all our github related activities on in hand projects. now we miserably had to switch to Google drive which is a total disaster but the only solution.
we hope the new patch works or we have to rethink having git in our development main stream.

**Comment by ttaylorr** [comment]
Git LFS v1.4.4 was just released, could you try again after upgrading your installed version of LFS:

If you installed this using Homebrew, the process looks like:

```bash
$ brew update
$ brew upgrade git-lfs
```

**Comment by ArianRudd** [comment]
Thanks.
The problem has been solved but not by the new patch. some how it had something to do with the local computers daylight saving time settings.

**Comment by ttaylorr** [comment]
Glad to hear that it was resolved. 👍

**Comment by Grislymanor** [comment]
I still have to manually turn back my computer's time...  This started after early March (assuming my timezones "Spring Forward" 3.12.17).

**Comment by ttaylorr** [comment]
@Grislymanor #2125 was just opened which should fix your problem in the next release of LFS so long as your server supports it.
