### ISSUE TITLE
git-lfs scripts/bootstrap fails on RHEL 6/7

### ISSUE THREAD

**Issue by joericks** [github/git-lfs#1606]
I need to build a git-lfs binary for internal use for security reasons.  I have attempted to build using the contributor documentation and using a clone and the bootstrap script with the same results.  go is reporting missing files when the files appear to be present and accounted for: 

```
rtp-apl-gitadm:160> script/bootstrap
go build github.com/github/git-lfs/vendor/github.com/ThomsonReutersEikon/go-ntlm/ntlm/md4: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/bgentry/go-netrc/netrc: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/kr/pty: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/rubyist/tracerx: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/pkg/errors: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/olekukonko/ts: : fork/exec : no such file or directory
rtp-apl-gitadm:161> ls github.com/github/git-lfs/vendor/github.com/ThomsonReutersEikon/go-ntlm/ntlm/md4/
LICENSE  md4.go  md4_test.go  md4block.go
rtp-apl-gitadm:162> git status
# HEAD detached at v1.4.3
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#   github.com
nothing added to commit but untracked files present (use "git add" to track)
rtp-apl-gitadm:163> git checkout master
Previous HEAD position was 57234cb... Merge pull request #1591 from github/release-next
Switched to branch 'master'
rtp-apl-gitadm:164> script/bootstrap
go build github.com/github/git-lfs/vendor/github.com/ThomsonReutersEikon/go-ntlm/ntlm/md4: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/bgentry/go-netrc/netrc: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/kr/pty: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/rubyist/tracerx: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/pkg/errors: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/olekukonko/ts: : fork/exec : no such file or directory
rtp-apl-gitadm:165> ls
CHANGELOG.md        INSTALLING.md  README.md   appveyor.yml  config  docs    git-lfs.go  glide.yaml  localstorage  script      tools
CODE-OF-CONDUCT.md  LICENSE.md     ROADMAP.md  auth          debian  errors  github.com  httputil    progress      subprocess  transfer
CONTRIBUTING.md     Makefile       api         commands      docker  git     glide.lock  lfs         rpm           test        vendor
rtp-apl-gitadm:166> echo $GOPATH
/ws/joericks-rtp/git-lfs-build
rtp-apl-gitadm:167> pwd
/ws/joericks-rtp/git-lfs-build/src/github.com/github/git-lfs
```

This build is currently being run against RHEL6 U6 64 bit.

**Comment by ttaylorr** [comment]
Hi @joericks, thanks for opening this. It looks like this error is because you don't have any vendored dependencies installed. You can fix this by first running `script/vendor`, but we should probably run that in `script/bootstrap` anyway.

**Comment by technoweenie** [comment]
Did you clone this to `$GOPATH/src/github.com/github/git-lfs`? You can do this with `go get github.com/github/git-lfs`. I usually symlink that into my normal projects dir too.

**Comment by technoweenie** [comment]
I'm certainly not a bash expert, but I wonder if the error is coming from [this line in `script/bootstrap`](https://github.com/github/git-lfs/blob/798998b129ec2a40751fcfb4bb25a35193f370c3/script/bootstrap#L19):

    GO15VENDOREXPERIMENT=1 go run script/*.go -cmd build "$@"

It looks like it's running `go build` on each dependency, which definitely will not work:

```
go build github.com/github/git-lfs/vendor/github.com/ThomsonReutersEikon/go-ntlm/ntlm/md4: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/bgentry/go-netrc/netrc: : fork/exec : no such file or directory
...
```

Does `$@` mean something different in your environment? The script uses that to pass any `script/bootstrap` args to the [`script` package](https://github.com/github/git-lfs/blob/798998b129ec2a40751fcfb4bb25a35193f370c3/script/script.go#L18-L19).

```bash
$ script/bootstrap -all
$ GO15VENDOREXPERIMENT=1 go run script/*.go -cmd build "-all"

**Comment by joericks** [comment]
I'll apologize in advance if my ramblings seem ignorant.  This is new territory for me (using go and glide).  I installed the latest version of glide (v0.12.3)  to $GOPATH/bin and added it to my path.  When I ran $GOPATH/src/github.com/github/git-lfs/script/vendor I saw a large number of errors and of course, post errors bootstrap failed as I thought it would.  The errors are attached below:

[error.txt](https://github.com/github/git-lfs/files/549313/error.txt)

What version of glide are you currently using in your successful builds?  

I researched the VCS errors and some folks suggested adding .git to the repository path in the glide.yaml file but this change yielded an error complaining about the alteration so I reset the file to its original format.   At this point I stopped and opted to post an update in place of continuing my blind ramblings.  Any clues would be greatly appreciated.

**Comment by technoweenie** [comment]
You shouldn't need to run `script/vendor` unless you're changing the dependencies. We cache them in `./vendor` so that people can clone and build git-lfs with just go. 

Those "cannot detect vcs" errors are against standard lib packages like `fmt`, `os`, `sync`, etc. Glide should not be trying to do anything to those.

**Comment by joericks** [comment]
I ran your tests TW and returned the same error whether I ran bootstrap or called the go scripts individually.  I do not believe that $@ has any special meaning within my environment.  

rtp-apl-gitadm:135> ./script/bootstrap -all
go build github.com/github/git-lfs/vendor/github.com/ThomsonReutersEikon/go-ntlm/ntlm/md4: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/bgentry/go-netrc/netrc: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/kr/pty: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/rubyist/tracerx: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/pkg/errors: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/olekukonko/ts: : fork/exec : no such file or directory

rtp-apl-gitadm:138> setenv GO15VENDOREXPERIMENT 1
rtp-apl-gitadm:139> go run script/*.go -cmd build "-all"
go build github.com/github/git-lfs/vendor/github.com/ThomsonReutersEikon/go-ntlm/ntlm/md4: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/bgentry/go-netrc/netrc: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/kr/pty: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/rubyist/tracerx: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/pkg/errors: : fork/exec : no such file or directory
go build github.com/github/git-lfs/vendor/github.com/olekukonko/ts: : fork/exec : no such file or directory

I'm looking for a debugger of sorts currently to see if I can get any additional info such as which file, where is the stop occurring etc to see if I can provide a more complete picture.

**Comment by technoweenie** [comment]
I'm not sure the problem is go. It should not be running `go build` on each package like that. It should be running the `./script` package, which has some basic things for building stuff. 

* `go run script/*.go -cmd build` runs the script package
* `main()` in the script package [calls `mainBuild()` based on the `-cmd` flag](https://github.com/github/git-lfs/blob/97306ee58215a3c7730e8588d57d1db133b5df75/script/script.go#L18-L19)
* `mainBuild()` runs [`go generate`](https://github.com/github/git-lfs/blob/master/script/build.go#L42), [`git rev-parse`](https://github.com/github/git-lfs/blob/master/script/build.go#L47) to get the HEAD commit sha, and then [`build()`](https://github.com/github/git-lfs/blob/master/script/build.go#L65)
* `build()` just runs [`go build -o bin/git-lfs .`](https://github.com/github/git-lfs/blob/master/script/build.go#L137-L144), which is what seems to be failing in your case. It should definitely not be running `go build` on every package in `./vendor`. I don't know what would be causing that.

This is getting beyond my knowledge of how go internals work. It may just be easier to get the linux amd64 package from [our releases page](https://github.com/github/git-lfs/releases).

**Comment by technoweenie** [comment]
What version of Go do you have? Git LFS supports 1.5+, but ideally you are using 1.7.3.

`go build` can dump out the commands it expects to run with the `-n` flag.

```bash
$ go build -n -o bin/git-lfs

#
# github.com/github/git-lfs/auth
#

mkdir -p $WORK/github.com/github/git-lfs/auth/_obj/
mkdir -p $WORK/github.com/github/git-lfs/
cd /Users/rick/go/src/github.com/github/git-lfs/auth
/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64/compile -o $WORK/github.com/github/git-lfs/auth.a -trimpath $WORK -p github.com/github/git-lfs/auth -complete -buildid fca0142d0aace4eeed34c91fe9f800a032254d97 -importmap github.com/rubyist/tracerx=github.com/github/git-lfs/vendor/github.com/rubyist/tracerx -D _/Users/rick/go/src/github.com/github/git-lfs/auth -I $WORK -I /Users/rick/go/pkg/darwin_amd64 -pack ./auth.go ./credentials.go ./ssh.go

... snip ....

#
# github.com/github/git-lfs
#

mkdir -p $WORK/github.com/github/git-lfs/_obj/
mkdir -p $WORK/github.com/github/git-lfs/_obj/exe/
cd /Users/rick/go/src/github.com/github/git-lfs
/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64/compile -o $WORK/github.com/github/git-lfs.a -trimpath $WORK -p main -complete -buildid eeb2d8f2e0c072501a39be898ab6880c398984f3 -D _/Users/rick/go/src/github.com/github/git-lfs -I $WORK -I /Users/rick/go/pkg/darwin_amd64 -pack ./git-lfs.go
cd .
/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64/link -o $WORK/github.com/github/git-lfs/_obj/exe/a.out -L $WORK -L /Users/rick/go/pkg/darwin_amd64 -extld=clang -buildmode=exe -buildid=eeb2d8f2e0c072501a39be898ab6880c398984f3 $WORK/github.com/github/git-lfs.a
mkdir -p bin/
mv $WORK/github.com/github/git-lfs/_obj/exe/a.out bin/git-lfs
```

It runs the go compile tool on every package, and then the link tool on the main one. As you can see from my output, they are located at `/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64/compile` and `/usr/local/Cellar/go/1.7.1/libexec/pkg/tool/darwin_amd64/link` (obviously very different paths on rhel). Do both of those commands exist for you at the paths in your output?

**Comment by joericks** [comment]
I was using a pull off of gccgos master branch which is probably part of my problem.  I retried an install off of the releases page and it worked without a blip.
