### ISSUE TITLE
How To Free More Space On git-lfs

### ISSUE THREAD

**Issue by GMCadiom** [github/git-lfs#1614]
Hello All
i want to upload one of my projects but i got this
`Git LFS: (0 of 1 files) 0 B / 345.13 MB
batch response: http: This repository is over its data quota. Purchase more data packs to restore access.
Docs: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-an-organization/
error: failed to push some refs to 'https://github.com/MTK-ROMS-TEST/cm13-mt6580.git'
`
and there was large zip files there so i deleted the full repo and create a new one thinking with that way i will free  up more space to i can upload the last version of my project but i got the same error !!

what i do to free up more space on my account ??

**Comment by technoweenie** [comment]
You've used up all your download bandwidth for the month. There's no way to undo that. You'll have to buy more data packs or wait until your next billing period. Hit up https://github.com/contact  if you have more questions.
