### ISSUE TITLE
Fatal error: Server error on "git push"

### ISSUE THREAD

**Issue by Infotaku** [github/git-lfs#1637]
Hi, 

I've successfully installed **and used** git, git-lfs and git flow on my windows 10 computer to be able to version my Unity projects over gitlab.com. 
I've committed and pushed several files handled by git-lfs without any issue until today.
Now I get this : 
```
Fatal error: Server error: https://gitlab.com/OtherworldDungeons/OtherworldDungeons.git/gitlab-lfs/objects/3cc17dc6a5a1b07a42795cfcf84c54022c01c085c79f02430edb1c1b7943ea0e/22471
Fatal error: Server error: https://gitlab.com/OtherworldDungeons/OtherworldDungeons.git/gitlab-lfs/objects/a920e3eae7e7dddf139d691f26362420d60bf46c25e70e1000e3098c647451bb/2474
Fatal error: Server error: https://gitlab.com/OtherworldDungeons/OtherworldDungeons.git/gitlab-lfs/objects/8f0b8da0d9bb3c5924a4aadde2ce742df81d6f6b257cb6b61c5ea28680ce0e4c/2731
Fatal error: Server error: https://gitlab.com/OtherworldDungeons/OtherworldDungeons.git/gitlab-lfs/objects/dfe0b2be69f3cd28dce367c34dbf4a821b707f1a928779e55a9ae31a71128e2a/847
error: failed to push some refs to 'git@gitlab.com:OtherworldDungeons/OtherworldDungeons.git'
```

I tried updating git and git-lfs to their latest version but no luck there. 
Using GIT_CURL_VERBOSE=1 I get : [git_curl_verbose.txt](https://github.com/github/git-lfs/files/583586/git_curl_verbose.txt)

The most odd thing I can find from this (excepte all the "Internal Server Error"s) is the way the upload seems to go over its target : `Git LFS: (0 of 4 files, 1 skipped) 55.71 KB / 27.85 KB, 78 B skipped` but I don't know if this is the root of the issue.

Here is my git-lfs env result if you need it : 
```
git-lfs/1.4.4 (GitHub; windows amd64; go 1.7.3; git cbf91a9)
git version 2.10.2.windows.1

Endpoint=https://gitlab.com/OtherworldDungeons/OtherworldDungeons.git/info/lfs (auth=basic)
LocalWorkingDir=C:\Users\yreki\Documents\Projects\OtherworldDungeons
LocalGitDir=C:\Users\yreki\Documents\Projects\OtherworldDungeons\.git
LocalGitStorageDir=C:\Users\yreki\Documents\Projects\OtherworldDungeons\.git
LocalMediaDir=C:\Users\yreki\Documents\Projects\OtherworldDungeons\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Users\yreki\Documents\Projects\OtherworldDungeons\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

Thank you for your time.

**Comment by technoweenie** [comment]
You'll need to check with your server to see what the issue is. There's nothing that can be done on the client.

> The most odd thing I can find from this (excepte all the "Internal Server Error"s) is the way the upload seems to go over its target

The progress meter doesn't take retries into account. It's a totally separate issue: https://github.com/github/git-lfs/issues/1542

**Comment by Infotaku** [comment]
Ok so I need to take this to gitlab I guess. Thank you !

**Comment by friuns2** [comment]
did you found what the reason? i have same issue

**Comment by sanja7s** [comment]
Me, too
