### ISSUE TITLE
Same issue as https://github.com/github/git-lfs/issues/833

### ISSUE THREAD

**Issue by 4fthawaiian** [github/git-lfs#1645]
Hi there,

It appears that our organization is having the same issue as the one seen in https://github.com/github/git-lfs/issues/833.

Please let me know what needs to be done to correct the issue.

`
 ~/Desktop/BloxelsSandbox   v1.4.3 ✚  git lfs fetch
Fetching v1.4.3
Git LFS: (0 of 2 files) 0 B / 247.01 MB
batch response: http: Git LFS is disabled for this repository.
Docs: https://github.com/contact
Warning: errors occurred
 ✘  ~/Desktop/BloxelsSandbox   v1.4.3 ✚ 
`

**Comment by 4fthawaiian** [comment]
I resolved this by moving to the $5/monthly plan for LFS. Will reopen if I find another issue.

**Comment by david-soyez** [comment]
weird, when I upgraded the plan, it fails uploading because of quota. Maybe it needs time to update with the plan.
