### ISSUE TITLE
How to download large files properly?

### ISSUE THREAD

**Issue by mandosrex** [github/git-lfs#1648]
Ok so, I am a complete noob when it comes to Github but I needed it for my mod. A while ago one of my mod's files got too big (150mb) for a normal upload on Github so I had to install Git Large File Storage.

I understand that it breaks the file down for storage, all good and dandy, I uploaded my file and all went good.
But if I go and download the mod as a zip, the file is still broken down... Having 100kb and being completely empty.

So I have to ask, how the heck do you properly download a large file now?
I searched everywhere for a straight answer but none was found.

Please help.

**Comment by ttaylorr** [comment]
Hi @mandosrex, thanks for opening this. Git LFS uses Git's `clean` and `smudge` filters to convert files from small "pointers" to the large objects that they represent. The symptoms you're describing usually indicate that LFS isn't installed on your system.

Can you run:

```
$ git lfs install
```

and try again?

**Comment by mandosrex** [comment]
Wait what? No no, it is installed and I uploaded the file.

But if I go to the link (https://github.com/mandosrex/AoE3ImpMod_Base) and use the option on the right to download as ZI, all files are good except the large file, which is broken.

Is there no way to download the proper file without Github anymore?

**Comment by ttaylorr** [comment]
Ah, sorry, I didn't realize you wanted to download the repository from the website. To answer your question, no, downloading as a ZIP does _not_ include the full LFS files, and you'll need to use Git over the command line to get the full objects.

**Comment by mandosrex** [comment]
Oh... Well that defeats the whole purpose in using it, sadly.
Thank you for your help. They should really mention this somewhere you know.

**Comment by TroutZhang** [comment]
@mandosrex @daggerok  totally agree.

Why would I click the download button in the first place, if it doesn's support LFS content?

**Comment by VR-Architect** [comment]
Totally agree

**Comment by AhmadxAli** [comment]
agree github is useless

**Comment by francocar** [comment]
Il Mar 26 Gen 2021, 18:09 AhmadxAli <notifications@github.com> ha scritto:

**Comment by bk2204** [comment]
Hey,

This repository is not for GitHub, but only for the open source Git LFS project.  If you have comments or questions about GitHub's implementation of Git LFS on the server side, please direct those to GitHub Support.

However, having said that, I will point out that a project may choose to enable LFS objects in archives in the settings panel for the repository.  It's opt-in per repository, but projects may (or may not) choose to turn it on.
