### ISSUE TITLE
.gitattributes needs to be in the  repository root folder?

### ISSUE THREAD

**Issue by livia-b** [github/git-lfs#1654]
I added some files in a subfolder of my repository:
```
cd subfolder 
git lfs track  Data/*
git add .gitattributes
```
Note that .gitattributes was created in subfolder

I could push without errrors, but the lfs files were created in Data instead of subfolder/Data

In short, the original repo structure  is:
```
repo
|__subfolder
      |__.gitattributes 
      |__Data
           |__ bigfile...
```

The cloned repo structure is:
```
repo
|__subfolder
|     |__.gitattributes 
|
|__Data
      |__ bigfile...
```

Subfolder/.gitattributes has relative paths:
`Data/bigfile.txt filter=lfs diff=lfs merge=lfs -text
`

**Comment by livia-b** [comment]
Sorry for the noise, it seems that it was me making an error in creating the Data folder

**Comment by C-Kenny** [comment]
Thanks @livia-b , I also made the mistake of tracking of a sub folder. Helpful comment!

**Comment by ttaylorr** [comment]
Git LFS will work properly even if your `.gitattributes` is in a directory other than the root, it will simply cascade downwards. That is to say, if I have the following in `a/.gitattributes`

```
b filter=lfs ...
```

then `a/b` will be tracked using LFS, while `/b` (`b` in the root) will not.
