### ISSUE TITLE
Chunking

### ISSUE THREAD

**Issue by jezell** [github/git-lfs#190]
Awesome idea. Glad someone is finally doing this. 

From the spec it appears that the SHA hash must point to a specific gigantic blob. This may result in a lot of wasted space if only portions of a large file are changing. If spec allowed for chunked hashes so you can split files into something like 4 MB chunks like DropBox does, then you would not have to store duplicate chunks across large files / versions, things like resume operations become much more straightforward for very large files, and in many cases total upload / download time will be significantly reduced.

**Comment by technoweenie** [comment]
That is a great idea.  This is something I'm really interested in, but haven't thought too much about how it'd work yet.  The hypermedia API in the spec was designed that way to make room for future things like this, though.  No promises about when or if we'll do it though.

**Comment by jezell** [comment]
I'll see if I can get together a pull request to throw some ideas down.

**Comment by technoweenie** [comment]
Chunking isn't in the immediate future. However, it is something worth experimenting on with the custom transfer adapter in v1.3: https://github.com/github/git-lfs/blob/master/docs/custom-transfers.md
