### ISSUE TITLE
[Bug]Asking username and password for many times

### ISSUE THREAD

**Issue by PeterDaveHello** [github/git-lfs#203]
Seems to be a bug, 
```
$ git push
Username for 'http://localhost:8080': temp
Password for 'http://temp@localhost:8080':
Username for 'http://localhost:8080': temp
Password for 'http://temp@localhost:8080':
0 B / 9.32 KB  0.00 % Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 379 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
To test@test:test/test.git
   01f8787..410ae56  master -> master
```

It'll ask me twice for each files, which means I need to enter it for 20 times if I add 10 files to git-lfs ...

Thanks a lot.

**Comment by tclem** [comment]
Heh, that is very annoying. We're currently recommending that people use [credential caching](https://help.github.com/articles/caching-your-github-password-in-git/) as the best way to get around this for now.

**Comment by PeterDaveHello** [comment]
Oh, I don't know that it also works on git-lfs, but I think the whole process should be the same session, just like you won't need to enter your id and password for many times when pushing a commit(or even 100 commits).

**Comment by tclem** [comment]
Makes sense. We choose not to re-implement credential caching, but instead rely on the stuff built into Git now so that there aren't multiple places where your password is being saved.

**Comment by PeterDaveHello** [comment]
Ha, I think it didn't work on my machine.

Ubuntu 14.04.2 LTS with kernel 3.13.0-44-generic
git version 1.9.1 (1:1.9.1-1ubuntu0.1)

**Comment by tclem** [comment]
Are you saying credential caching isn't working for you? What does `git config -l | grep credential` return? I think it is off by default.

You can turn it on (on Linux) like so:
``` sh
git config --global credential.helper cache
```

**Comment by PeterDaveHello** [comment]
My fault on this point, typo ... haha.

**Comment by tclem** [comment]
Ah, :cool: and no worries at all. I'm going to close this out if that's ok then.

**Comment by PeterDaveHello** [comment]
Hmmmm ... so we are not going to let it remember that in the same session as native git does?

**Comment by tclem** [comment]
It should work exactly as native git does by using Git's credential helper. If that's not working for you it's a bug, but I'll need some help with addition repro steps and we should verify what your global git config is for `credential.*`

**Comment by PeterDaveHello** [comment]
It works for me, I meant the problem is entering the username and password multiple times in the same push, it makes no sense, native git won't do that even without credential help, right?

**Comment by rubyist** [comment]
One thing to note is that when running against the lfs test server, that is a different set of credentials than your git credentials. The credential helper should cache them, though, so you should be asked for your git credentials once (max) and your lfs test server credentials once (max).

**Comment by tomspilman** [comment]
I'm running into this same issue even with credential caching enabled.

I'm on Windows.  I've tried both from the dos command line and git bash.  

![capture](https://cloud.githubusercontent.com/assets/103522/8599391/c4a3f1e6-2625-11e5-958e-2b6ff665c2e7.JPG)

Notice the weird wrapping with the `E` on the right side of the command window.  That does not happen normally when i'm using git to commit changes.

Also I tried the same sequence entering wrong information...  wrong password, wrong user name... and it looks almost identical in output.  Doubting myself I fetched from a different git repo and everything worked correctly.

**Comment by technoweenie** [comment]
@tomspilman Interesting. That passphrase message is likely coming from Git LFS running `ssh`, and not from `git-credential`. Could you open a brand new issue for this? Otherwise, I'll just copy your comment and create one myself.

**Comment by tomspilman** [comment]
@technoweenie - Done https://github.com/github/git-lfs/issues/474.

**Comment by technoweenie** [comment]
Thanks!

**Comment by ppKrauss** [comment]
I have the same problem, there are a summary with the solution?

**Comment by tomspilman** [comment]
> I have the same problem, there are a summary with the solution?

@ppKrauss - Don't use SSH when you clone you're repo.  Use HTTPS.

**Comment by cgibsonmm** [comment]
Seems like I just started having the same problem too, every time I push I have to control c to break the loop.

**Comment by ppKrauss** [comment]
Hi, thanks @tomspilman and @cgibsonmm , I solved!!  Recipe from https://stackoverflow.com/a/49244743/287948


1. check `git --version`, if less tham *2.16*, install better as [instructions here using PPA](https://stackoverflow.com/a/41357503/287948)

2. check your `git config credential.helper` output, if it is empty,<br/> execute this line: `git config --global credential.helper /usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret`<br/>... Them check again your `git config credential.helper` output: need to be this `/usr/...`  path.

3. Do your usual `git clone` (with care remove the broken old with `sudo rm -r oldBrokenBadClone`)... Giving usernae and password twice is ok, will be only it.

**Comment by zackperdue** [comment]
Add this to your `~/.ssh/config` file.
```
Host *
  AddKeysToAgent yes
  UseKeychain yes
```

Start your ssh agent:
```
eval "$(ssh-agent -s)"
```

Then add your key:
```
ssh-add ~/.ssh/id_rsa
```
*note* your key could be named differently.
