### ISSUE TITLE
Support track with multi-level directory scheme

### ISSUE THREAD

**Issue by PeterDaveHello** [github/git-lfs#204]
I am not sure what is the best title for it, origin may be too bad, sorry.

Let's use [cdnjs/cdnjs](https://github.com/cdnjs/cdnjs) as an example here,
I want to put the js files under `ajax/libs` to git-lfs, but not under other dir like `build`,
currently, I should do `$ git lfs track "*.js"` under `ajax/libs`, so there will be a `.gitattributes` under `ajax/libs`,
it'll be easier to manage and trace if we could set it in the root directory,
but in this case, the levels of directories are not static and also not predictable, so I can't set it with:
`$ git lfs track "ajax/libs/*.js"`
which means the js files directly under `ajax/libs`,
there is a syntax in [node/glob](https://github.com/isaacs/node-glob) - `**` can match all the js files under `ajax/libs` recursively, that's what I hope git-lfs can support,
with this support, I don't need to have multiple `.gitattributes`, easier to manage this repo now!

Just a personal feature request, what do you think?

I'm not a native speaker and my English is not so good, so there may  be some strange grammars or something else, hope you can get my point here, thanks a lot.

**Comment by rubyist** [comment]
The pattern matching is handled by git itself  and should support such a glob, e.g. `git lfs track "ajax/libs/**/*.js"` ought to pick up all js files under `ajax/libs/`. Is that not working for you?

**Comment by PeterDaveHello** [comment]
Wow, really? 
Sorry for my ignorance, I don't even know that git supports that syntax, I'll try it, thanks again @rubyist!

**Comment by rubyist** [comment]
Cool, I think we can do a better job of pointing to git's documentation on the pattern format, and maybe include some more examples in our own documentation. I'll leave this issue open for now as a reference to that. Thanks for the feedback!

**Comment by PeterDaveHello** [comment]
Okay, it's really clear that you told me it's handle by git itself, so I'll check git's document first :smile:
