### ISSUE TITLE
Various auth issues, depending on remote protocol URL

### ISSUE THREAD

**Issue by kevinSuttle** [github/git-lfs#209]
Installed git-lfs. Added .png to a repo via this command: `git lfs track "*.png"`. My repo's .gitattributes file only contains this:  `*.png filter=lfs -crlf`

Now, when I try to push, I get the following error on https remotes:
`fatal: could not read Username for 'https://github.com': terminal prompts disabled`

Tried switching to ssh, but get a different error.
```
'git credential fill' error: exit status 128


Errors logged to /Users/kevinsuttle/Code/REDACTED/.git/lfs/objects/logs/20150410T011656.046035274.log.
Use `git lfs logs last` to view the log.
error: failed to push some refs to 'git@github.com:REDACTED.git'
```

The log says:
```
> git-lfs push --stdin origin git@github.com:REDACTED.git
LocalWorkingDir=/Users/kevinsuttle/Code/REDACTED
LocalGitDir=/Users/kevinsuttle/Code/REDACTED/.git
LocalMediaDir=/Users/kevinsuttle/Code/REDACTED/.git/lfs/objects
TempDir=/Users/kevinsuttle/Code/REDACTED/.git/lfs/tmp
GIT_TERMINAL_PROMPT=0
GIT_PREFIX=

'git credential fill' error: exit status 128


'git credential fill' error: exit status 128

goroutine 16 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/errors.go:85 +0x89
github.com/github/git-lfs/commands.logPanic(0x64f1b0, 0xc208001160, 0x694a00, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:148 +0xf17
github.com/github/git-lfs/commands.handlePanic(0x64f1b0, 0xc208001160, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:100 +0x6c
github.com/github/git-lfs/commands.LoggedError(0x64f1b0, 0xc208001160, 0xc208023f20, 0x2d, 0x0, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:65 +0x89
github.com/github/git-lfs/commands.Panic(0x64f1b0, 0xc208001160, 0xc208023f20, 0x2d, 0x0, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:75 +0x68
github.com/github/git-lfs/commands.pushCommand(0x58bf00, 0xc208023140, 0x2, 0x3)
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/command_push.go:120 +0x572
github.com/spf13/cobra.(*Command).execute(0x58bf00, 0xc20804eb00, 0x3, 0x4, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:355 +0x17c
github.com/spf13/cobra.(*Command).findAndExecute(0x58c600, 0xc20800e010, 0x4, 0x4, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:334 +0xd3
github.com/spf13/cobra.(*Command).Execute(0x58c600, 0x0, 0x0)
	/Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:408 +0x7b0
github.com/github/git-lfs/commands.Run()
	/Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:80 +0x2a
main.main()
	/Users/rick/github/git-lfs/cmd/git-lfs.go:8 +0x1a
```

[My gitconfig](https://github.com/kevinSuttle/dotfiles/blob/master/gitconfig)

SSH is fine.
```
❯ eval "$(ssh-agent -s)"
Agent pid -----
❯ echo $?
0
❯ ssh -T git@github.com
Hi kevinSuttle! You've successfully authenticated, but GitHub does not provide shell access.
```

**Comment by kevinSuttle** [comment]
Should note: I couldn't push via the `git` CLI, or via the Tower UI client, but using GitHub for Mac allowed me to "Sync" and push.

**Comment by technoweenie** [comment]
TIL about [GIT_TERMINAL_PROMPT](http://www.spinics.net/lists/git/msg242892.html).  It has to do with that "terminal prompts disabled" error messsage. You do have `GIT_TERMINAL_PROMPT=0` set in your environment.  Is that on purpose?  If you remove that, it should work.

Thanks for reporting this.  Git LFS should skip any `git credential` commands if that environment is set.  We'll have to do a bit of research on how we should handle it, but I imagine it's something we can fix fairly easily.

**Comment by kevinSuttle** [comment]
Thanks @technoweenie. I'm just learning about that setting as well, so I definitely didn't intentionally turn it off. Actually, now that I'm reading that link, I remember futzing with PGP signing my commits not long ago. Wonder if that has anything to do with it. 

Would I just check for its value by `echo $GIT_TERMINAL_PROMPT`, and set it to 1 if it's 0?

**Comment by kevinSuttle** [comment]
Also, stumbled upon the following, showing that this was a recent update shipped with Git 2.3.
"**The credential subsystem is now friendlier to scripting**"
https://github.com/blog/1957-git-2-3-has-been-released

**Comment by technoweenie** [comment]
@kevinSuttle What do you get when you run git credential manually?

```
$ echo "host=github.com" | git credential fill
host=github.com
username=YEAHNICETRYLOL
password=x-oauth-basic
```

**Comment by kevinSuttle** [comment]
```
❯  echo "host=github.com" | git credential fill
host=github.com
username=kevin@suttle.io
password=[REDACTED]
````

**Comment by technoweenie** [comment]
What's your remote?  Can you show me the output of `git lfs env` too?  If this is a private project, feel free to [take this to private GitHub support](https://github.com/c).  Just mention "Git LFS" and it'll get routed to us.

**Comment by kevinSuttle** [comment]
@technoweenie Sent!

**Comment by technoweenie** [comment]
@kevinSuttle You should be able to clear that env var with:

    $ export GIT_TERMINAL_PROMPT=

We'll have to do some code spelunking to see why `git credential` is returning a 128 exit code.  We've never seen that before.  But, we're also not familiar with the Git source code either :)

What does `git lfs version` return?

**Comment by kevinSuttle** [comment]
```
❯ git lfs version
git-lfs/0.5.0 (GitHub; darwin amd64; git 2.3.3; go 1.3)
❯ export GIT_TERMINAL_PROMPT=

❯ echo $GIT_TERMINAL_PROMPT
0
```
:worried:

**Comment by kevinSuttle** [comment]
I tried:
```
env GIT_TERMINAL_PROMPT=1
export GIT_TERMINAL_PROMPT
GIT_TERMINAL_PROMPT=1
GIT_TERMINAL_PROMPT='1'
export GIT_TERMINAL_PROMPT="1"
❯ echo $GIT_TERMINAL_PROMPT
0
```

**Comment by tclem** [comment]
Maybe try `unset GIT_TERMINAL_PROMPT`?

**Comment by kevinSuttle** [comment]
```
❯ unset GIT_TERMINAL_PROMPT

❯ echo $GIT_TERMINAL_PROMPT
0
```
:hurtrealbad:

**Comment by tclem** [comment]
Hmmm. Maybe something else is running in your shell environment and setting it back? Prompt generation code? dotenv? Try a different shell that you don't have customized? SHH into your own machine to get a fresh env? `ssh -t username@hostname /bin/sh`

**Comment by kevinSuttle** [comment]
After SSH-ing into my machine, I was able to see that it works there.

```
sh-3.2$  export GIT_TERMINAL_PROMPT=1
sh-3.2$ echo $GIT_TERMINAL_PROMPT
1
```

I'm also using Pure ZSH for prompt, which I installed via NPM. I uninstalled it, reloaded my shell, and setting `GIT_TERMINAL_PROMPT` worked. 

```
$ MacBook-Pro%  export GIT_TERMINAL_PROMPT=1
$ MacBook-Pro% echo $GIT_TERMINAL_PROMPT
1
```
Opening an issue there.

**Comment by tclem** [comment]
Perfect. OK to close this issue out for now and track over in https://github.com/sindresorhus/pure/issues/111?

**Comment by kevinSuttle** [comment]
I think so @tclem. Thanks for your help, also @technoweenie.

**Comment by kevinSuttle** [comment]
BTW, got this resolved. https://github.com/sindresorhus/pure/issues/111
