### ISSUE TITLE
Project probably in violation of gpm's license

### ISSUE THREAD

**Issue by skade** [github/git-lfs#211]
This is probably a minor oversight. The project vendors [gpm](http://github.com/pote/gpm) without the appropriate copyright notice.

https://github.com/github/git-lfs/blob/master/script/gpm

GPMs license is MIT:

https://github.com/pote/gpm/blob/master/LICENSE

Which says:

```
The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
```

While the projects MIT license file can be considered the permission notice, the copyright notice is definitely missing.

This can turn out to be a problem for anyone who wants to use git-lfs and is faced with a license audit.

This can easily be fixed by either having an additional file for third-party licenses or putting the notice in the gpm script itself.

**Comment by technoweenie** [comment]
Definitely an oversight.  Thanks for letting us know.  We'll merge #213 once we've confirmed with our legal team that everything's correct.

**Comment by technoweenie** [comment]
Just merged the license to the vendored script/gpm.  Thanks for bringing this up!

**Comment by skade** [comment]
No biggie, thanks :+1:.
