### ISSUE TITLE
Possible to stream the files to git-lfs?

### ISSUE THREAD

**Issue by PeterDaveHello** [github/git-lfs#214]
Hi there,
I'm trying to move [cdnjs/cdnjs](https://github.com/cdnjs/cdnjs) on using git-lfs, though there are not very huge files, but too many small static files, which will make the repo very huge, so I think the feature of git-lfs can help us solve the problem of making the repo too heavy(hope I'm not wrong at this point), I think git-lfs is designed for large files like psd, multimedia files, so the overhead of directly post them to server is not so high, in cdnjs, we have 727777 files, and I think all of them are very small here(compare to the git-lfs's target), so the overhead of  post them individually became relatively high, I wonder if git-lfs can treat them as a stream to decrease the overhead and speed up the upload/download process? This request may be complex and not very appropriate to the use case, just want to know you guys' thoughts, thanks!

**Comment by technoweenie** [comment]
Are you talking about uploading multiple files as part of one single request (such as a multipart request)?  That's an interesting idea, but it's not supported right now.  It's an interesting idea though.

Also it looks like this is hosting css/js files.  Git is already amazing at it.  Using Git LFS would add overhead that you don't need.

**Comment by PeterDaveHello** [comment]
Yeah, I wonder if git-lfs can support that in future.
Because git-lfs uses pointers to replace the files, I think they may be obviously lighter than the real files, even they are js and css(in fact, also font, image, flash files), the overhead will worth it. Maybe the first commit will be painful, but I guess it can sure make our repo smaller and make the git progress faster, that's why I'm trying to use git-lfs, hope I'm not wrong, ha.

**Comment by technoweenie** [comment]
Are you hosting the cdnjs file directly from the Git repository?  Git and Git LFS are not designed for web cdn traffic.

**Comment by PeterDaveHello** [comment]
No, we'll put the files on the sponsors' cdn server, just use git to manage the project and let people join and contribute.

**Comment by technoweenie** [comment]
Ah, whew :)  

We can't parallelize downloads because of how the git smudge filter works.  Fixing that would require moving off smudge filters altogether.  I'm not opposed to it if we can find a new solution that doesn't compromise the Git LFS UI.  Not sure Git LFS is going to be a good fit for this cdnjs dproject right now.

**Comment by PeterDaveHello** [comment]
The problem I get now is that uploading 727777 files to git-lfs server is so slow :sob:

**Comment by PeterDaveHello** [comment]
I have another thought, if git-lfs can reuse the connections, the overhead to send many small files will be lower.

**Comment by technoweenie** [comment]
Go's HTTP client uses keep alive by default.

I appreciate the bug report, but I really don't think this is a good fit for cdnjs.  Storing small files is certainly not our intended use case, so it's not something we're going to prioritize right now.

**Comment by PeterDaveHello** [comment]
I think I should close this issue, with a 3 days testing with git-lfs, seems cdnjs's problem can not be so easily solved, the difference is to push to a git server or push to another git-lfs server, if the files are a lot and small, the overhead become super huge. Still thanks this awesome project!
