### ISSUE TITLE
The Windows install script still refers to git-media

### ISSUE THREAD

**Issue by sgraham** [github/git-lfs#216]
git-media.exe, etc.

**Comment by tclem** [comment]
Whoop! Yes, we should fix this. Marked as a bug.

**Comment by bumxnhoc** [comment]
may i know when you fix done ?
2015年4月11日 7:30 AM于 "Timothy Clem" <notifications@github.com>写道：

**Comment by rubyist** [comment]
Merged in, thanks for the report!
