### ISSUE TITLE
Lack of code documentation

### ISSUE THREAD

**Issue by thekafkaf** [github/git-lfs#217]
It's really missed :(, was it a deliberate decision?
Can I try my hand at adding some docs(for files and funcs at first)?

**Comment by technoweenie** [comment]
It wasn't a deliberate decision.  You are welcome to try writing docs, but don't feel like you have to or anything :)  If you're not a go programmer, be sure to follow the [Go commenting guidelines](https://code.google.com/p/go-wiki/wiki/CodeReviewComments).

**Comment by thekafkaf** [comment]
I'm on it, it'll be my pleasure.
