### ISSUE TITLE
Large File revisions causing issues

### ISSUE THREAD

**Issue by topherredden** [github/git-lfs#224]
If you get a previous version of the file and commit, you end up with a text file such as this:

 ```
version https://git-lfs.github.com/spec/v1
oid sha256:9aaa09d00c4f9fa80e3d3afb0e05e19423d8d43901fb905834ea9193e05754a4
size 233971
```

I'm curious, since I didn't see anything in the spec to delete past revisions, are revisions meant to be supported? If so, at what stage is the file downloaded/updated to the correct version from the server?

**Comment by technoweenie** [comment]
Nothing specifies when past revisions are deleted.  It's up to the server to implement cleanup routines.

**Comment by topherredden** [comment]
I'm not sure that really answers the whole issue. With git-lfs you can change to an old revision and end up with a broken file, and no ability to acquire the correct file. Is this a bug? Undefined behaviour? Something unfinished?

**Comment by technoweenie** [comment]
Did you get an error?  Checking out an old file should download it.

**Comment by topherredden** [comment]
I investigated further and discovered I was using an older version of TortoiseGit which was causing Smudge and Clean filters to be ignored. Seems to have been the problem :)

**Comment by technoweenie** [comment]
Ahh, good to know!  Thanks for updating :)
