### ISSUE TITLE
Support metalink format for file location

### ISSUE THREAD

**Issue by MarkusTeufelberger** [github/git-lfs#229]
http://en.wikipedia.org/wiki/Metalink seems to me to be a potentially great solution to create the kind of versionable file "proxies" that get verioned in git but point to the actual location. It supports more protocols than your proposal and also offers fields for various checksums and even signatures.

There is a lot of existing software out there that can use this format and git could also call this software (e.g. aria2 or curl) to get the actual content described in the metalink file.

While metalink files are probably larger than your "pointer" file format, they are more versatile and you don't have to supply/install an external server to deploy your files if you are offering them - making your content available via FTP/HTTP/BT via any existing means is enough.

**Comment by technoweenie** [comment]
Thanks for the suggestion. That's an interesting format.  However, the text pointers that we store need to be deterministic.  Given the same file, the _exact_ text pointer should be created, no matter how your client is configured.  Otherwise, you may run into the case where changing where your files are stored causes Git to update all of the git pointers.

Git LFS handles this by letting the server dictate how files are stored.  If you want your large objects stored in multiple places, you can push to multiple git remotes.

**Comment by dvdrtrgn** [comment]
Can "git notes" be leveraged to augment file metadata?

**Comment by MarkusTeufelberger** [comment]
The only thing that is deterministic about a file is its content hash and size. If you also require that the location of the file is ALWAYS the same (e.g. it is impossible to host a subset of files one Server1 and some other large files on Server2) this might limit the usefulness of your solution I guess.
The current solution requires a single server (or at least server frontend) to have access to _all_ large files, while with Metalink every single file could be stored at a different location, as long as this location is adressable.

I don't see how changing where one of your files is stored (which in metalink means adding/editing a single line in an XML file) would affect the location of other files?

Reading a bit more about your design it seems like you are already working in a different direction and paradigm, so incorporating metalinks instead of "pointer files" might cause some bigger changes in design too (not just one single all-knowing server possible, the repo owner is partly responsible to manage file location), but the current functionality would also be possible as a limited subset too. One could for example give a "default" location so new large files that fit your filters automatically are hashed and uploaded under a certain URL to a service that is specified in the lfs-endpoint config setting. It would however also be possible then to manually extend this file to also include alternative locations (and even prioritize them, so most traffic goes to e.g. AmazonS3 and BitTorrent, but if that fails, the download would failover to Github).

**Comment by technoweenie** [comment]
@MarkusTeufelberger: Thank you for opening this and showing me an interesting new spec.  However, I don't think this is the right solution for Git LFS.

> The current solution requires a single server (or at least server frontend) to have access to all large files, while with Metalink every single file could be stored at a different location, as long as this location is adressable.

This is one of the main ideas around Git LFS.  As you can push your repository to any Git remote, you should be able to push your large files to any Git LFS server (whether it's hosted by your Git remote, or separately).  If you want more control over where your large files are stored, I'd suggest you check out something like Git Media, Git Annex, or something inspired by those.

Thanks again for taking an interest in this project!

**Comment by MarkusTeufelberger** [comment]
Yes, I guess we just have different basic design goals with this (repo content controls file location vs. git server stores files) - all the best with your project and thanks for the consideration! :)
