### ISSUE TITLE
git lfs track doesn't make file paths relative to working dir

### ISSUE THREAD

**Issue by MSch** [github/git-lfs#230]
Given a git repo in `/Users/msch/work/foo`:

```
git lfs track /Users/msch/work/foo/testcases/bigfile.pdf
```

leads to this `.gitattributes` file:

```
/Users/msch/work/foo/testcases/bigfile.pdf filter=lfs -crlf
```

when it should lead to this `.gitattributes` file:

```
testcases/bigfile.pdf filter=lfs -crlf
```

**Comment by technoweenie** [comment]
Thanks, that's legit.  I wonder if we should block any paths that start with `/`, unless they happen to match the current working directory?

**Comment by MSch** [comment]
IMO paths outside the working dir are invalid, so yeah. But so would be `../../*.pdf`.

The way I managed to find this was by dragging the bigger files from Finder.app to Terminal.app, expecting the paths to be resolved. If I had dragged files from e.g. the wrong working dir I'd have ended up with e.g. `../../*.pdf`.

**Comment by michael-k** [comment]
PR #356 takes care of absolute paths and paths outside the repository
