### ISSUE TITLE
Be explicit about how OIDs are used in sharded filepath

### ISSUE THREAD

**Issue by borromeotlhs** [github/git-lfs#236]
In your documentation, you state:
>These filters ensure that large files aren't written into the repository proper, instead being stored locally at .git/lfs/objects/{OID-PATH} (where {OID-PATH} is a sharded filepath of the form OID[0:2]/OID[2:4]/OID), synchronized with the Git LFS server as necessary.

So with the example OID of:
>oid sha256:4d7a214614ab2935c943f9e0ff69d22eadbb8f32b1258daaa5e2ca24d17e2393

would the sharded filepath become:
> .git/lfs/objects/4d7/7a2/4d7a214614ab2935c943f9e0ff69d22eadbb8f32b1258daaa5e2ca24d17e2393

or

> .git/lfs/objects/4d/7a/4d7a214614ab2935c943f9e0ff69d22eadbb8f32b1258daaa5e2ca24d17e2393

Your syntax is confusing, as I don't know if it is inclusive or exclusive range syntax, python indexing syntax, etc. that you are using.  I'm thinking it's the latter. . .

Please update docs with a sharded filepath example based on the example OID you already provide.  Alternatively, please answer the above, and I can submit a PR

**Comment by technoweenie** [comment]
The latter:

    .git/lfs/objects/4d/7a/4d7a214614ab2935c943f9e0ff69d22eadbb8f32b1258daaa5e2ca24d17e2393

I'll get a quick spec tweak out soon.  Thanks for pointing the ambiguity out.
