### ISSUE TITLE
docs/spec.md sample out of date

### ISSUE THREAD

**Issue by jmarshall** [github/git-lfs#239]
The docs/spec.md **## The Server** section discusses `lfs.url` and `remote.{name}.lfsurl` config settings, but the adjacent sample Git config file has different names for the settings:

```
[core]
  repositoryformatversion = 0
[lfs]
  endpoint = "https://github.com/github/git-lfs.git/info/lfs"      # url
[remote "origin"]
  url = https://github.com/github/git-lfs
  fetch = +refs/heads/*:refs/remotes/origin/*
  lfs = "https://github.com/github/git-lfs.git/info/lfs"           # lfsurl
```

**Comment by rubyist** [comment]
I've merged these changes in, thanks for the report! :sparkles:
