### ISSUE TITLE
Atlassian Stash implementation

### ISSUE THREAD

**Issue by BLOODTIDE12** [github/git-lfs#249]
Hi there,
I am just writing to inform you all that I've created a ticket on Atlassian's JIRA for Stash & if you would also like to see an implementation of Git LFS than please vote for it here: https://jira.atlassian.com/browse/STASH-7300

Also see #250 for Atlassian BitBucket implementation.

**Comment by nuclearsandwich** [comment]
Thanks for the head's up on both of these!
