### ISSUE TITLE
Atlassian BitBucket implementation

### ISSUE THREAD

**Issue by BLOODTIDE12** [github/git-lfs#250]
Hi there,
I am just writing to inform you all that I've found a ticket on Atlassian's BitBucket issues for BitBucket & if you would also like to see an implementation of Git LFS than please vote for it here: https://bitbucket.org/site/master/issue/11204/support-git-lfs-extension

Also see #249 for Atlassian Stash implementation.

**Comment by jimthedev** [comment]
Thank you! Good idea.

**Comment by nuclearsandwich** [comment]
Thanks again.
