### ISSUE TITLE
git-lfs does not work well with git-svn 

### ISSUE THREAD

**Issue by tvandijck** [github/git-lfs#251]
git svn init http://somebigrepo/trunk
git svn fetch
git lfs track *.bundle
git push origin master

remote: error: File somefile-debug.bundle is 156.81 MB; this exceeds GitHub Enterprise's file size limit of 100 MB
remote: error: File somefile.bundle is 161.32 MB; this exceeds GitHub Enterprise's file size limit of 100 MB
To git@internal.domain:team1/project.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@internal.domain:team1/project.git'

Is there any way to import a repository from SVN and process "large files" throughout the import process?? or a way to process the repository afterwards?

**Comment by technoweenie** [comment]
@tvandijck: The first problem is that you're not actually adding any files.  The `track` command only adds the entry to your `.gitattributes` file.  You still need to add the files.

Also, unless you're rewriting your git history with `git filter-branch`, older commits will still have the large files so GitHub Enterprise will keep rejecting your pushes.

**Comment by tvandijck** [comment]
Indeed, and so using git-lfs on a pre-existing repository is currently not supported, and hence useless for project that want to transition from SVN to Git..

I need a command in git-lfs to do the git filter-branch, but preferably not by using filter-branch, because it would have to go through about 200.000 commits and over 20 million objects, so that would take about a year... (in my case)

git-lfs should provide some way to deal with this, either as a git-svn-import filter (if such a thing exists) so that it does it's work during the svn fetch... OR as a post import step, such as "git lfs rewrite"

**Comment by technoweenie** [comment]
I agree that Git LFS should help out.  But it won't be able to do this without going through all of your commits, unfortunately.

There's also a PR to support Git LFS rewrites in [BFG](https://github.com/rtyley/bfg-repo-cleaner/pull/87).

**Comment by tvandijck** [comment]
I took a stab at it and wrote a similar tool, which can be found here.
it's a little rough around the edges for sure, and does not currently support .pack files, so you have to unpack your repository into loose files..

https://github.com/tvandijck/git-lfs-rewrite

it's based on the work from this page:
https://www.primianotucci.com/blog/large-scale-git-history-rewrites

**Comment by technoweenie** [comment]
> Unfortunately right now Git-LFS is so unstable and broken that the "git lfs push" command doesn't work, so actually pushing something just borks.
> 
> Oh well... we'll keep investigating as it updates I guess...

The `git lfs push` command is designed as a plumbing command that users aren't meant to run themselves.  It's meant to be invoked through Git's `pre-push` hook.

```
$ cat .git/hooks/pre-push 
#!/bin/sh
git lfs push --stdin "$@"
```

You can run it yourself just fine, but it requires you to pass the arguments the hard way:

```
$ echo "refs/heads/master 7c9f1fd6f579612764b072117746cad65a6dfc29 refs/heads/master 00878278519ce1054e279c67cfd83ad469eeaadc" | git lfs push --stdin origin
```

Though based on your feedback, I want to rename the command to `pre-push`, hide any "plumbing" commands from the git lfs help, and eventually add a better `git lfs push` command designed for cli users.

**Comment by tvandijck** [comment]
I'm sorry, I think my comments in my readme.md at a little untactful... I think I wrote that in a moment of frustration... will update....

That said... we will obviously keep track of changes and see how things progress... I am still of the opinion that right now things are a little hard to use on a big giant pre-existing repository, but am slowly getting it to a point where it might be usable..

**Comment by technoweenie** [comment]
No worries, this whole project is born out of frustration :)  I also opened a PR to split out a separate pre-push command: https://github.com/github/git-lfs/pull/263.  

> I am still of the opinion that right now things are a little hard to use on a big giant pre-existing repository

I totally agree.  I really appreciate you taking the time to dive in anyway though.

**Comment by jroelofs** [comment]
> The first problem is that you're not actually adding any files. The track command only adds the entry to your .gitattributes file. You still need to add the files.

It'd be really helpful if LFS were able to hook into the `git svn fetch`, re-writing the git side of the history as it is being created. The fact that this has to be done in two steps (i.e. use git-svn to get all the commits into svn, install LFS, then rewrite all of the git history to LFS-add the relevant files) means that shuffling commits back from an LFS git repo into the svn repo isn't as easy as it is if LFS were not involved.  Because the history is rewritten after the fact, I have to cherry-pick commits back and forth between the two histories in order to use `git svn rebase` and `git svn dcommit`.

From a user's perspective, it'd be nice if OP's workflow "just worked".

> I agree that Git LFS should help out. But it won't be able to do this without going through all of your commits, unfortunately.

Does this mean that it would have to rewrite the history in the svn repository to do it, or are you only referring to the history in git? (I ask not knowing much about how git / git svn / git LFS work internally)

**Comment by technoweenie** [comment]
SVN support isn't high on my priorities now, but I'd be open to outside contributions.

**Comment by Mingun** [comment]
As for 2022, can anyone said, what is status of this? Does situation has improved, or `git svn` and `git lfs` still not working together?

**Comment by Mingun** [comment]
Where to start looking to fix that?

**Comment by Mingun** [comment]
I made some research. The script below creates a demo SVN repository, a git-svn mirror of it with Git LFS enabled:

```sh
#!/bin/sh

# Create repository `svn-repo``
svnadmin create svn-repo
# Allow anonimuous access to everyone
cat >./svn-repo/conf/svnserve.conf <<EOL
[general]
anon-access=write
auth-access=write
EOL
# make repository available over the web
svnserve -d -r svn-repo
# Check that everything is OK - expected empty output
svn ls svn://localhost

# Checkout svn working copy to `svn-wc`
svn co svn://localhost svn-wc
# Enter to that directory
cd svn-wc

# Create non-LFS file
echo "File 1" > ordinary-file.txt
svn add ordinary-file.txt
svn commit -m "Non-LFS file, version 1"
# Create LFS file
dd if=/dev/urandom of=lfs-file.img count=1 bs=10M
svn add lfs-file.img
svn commit -m "LFS file, version 1"

# Make changes in Non-LFS file
echo "File 2" > ordinary-file.txt
svn commit -m "Non-LFS file, version 2"
# Make changes in LFS file
dd if=/dev/urandom of=lfs-file.img count=1 bs=1M
svn commit -m "LFS file, version 2"

# Initialize git-svn working copy
cd ..
git svn init --trunk=. svn://localhost git-wc
cd git-wc
# Initialize Git LFS and track big files
git lfs track "*.img"
# Migrate SVN repo to Git
git svn fetch

# Make changes in the SVN repo again
cd ../svn-wc
echo "File 3" > ordinary-file.txt
svn commit -m "Non-LFS file, version 3"
dd if=/dev/urandom of=lfs-file.img count=1 bs=5M
svn commit -m "LFS file, version 3"

# Get new changes from the SVN to git working copy
cd ../git-wc/
git svn rebase
```

Result of the `git svn fetch` command:
```console
$ git svn fetch
	A	ordinary-file.txt
r1 = 38a3c7889681d030f8be8575bd557d53eb22c881 (refs/remotes/origin/trunk)
	A	lfs-file.img
r2 = dce21271cee171772e39be7ee2e078e67cdf6cb7 (refs/remotes/origin/trunk)
	M	ordinary-file.txt
r3 = 0503e34815222c91284e90a0daf122564bc73713 (refs/remotes/origin/trunk)
	M	lfs-file.img
r4 = a1966fec809a99a7794769a592768d41201bbcf6 (refs/remotes/origin/trunk)
Encountered 1 file(s) that should have been pointers, but weren't:
	lfs-file.img
Checked out HEAD:
  svn://localhost r4
$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   lfs-file.img

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.gitattributes

no changes added to commit (use "git add" and/or "git commit -a")
$ git diff
diff --git a/lfs-file.img b/lfs-file.img
index c1090ad..dde528b 100644
Binary files a/lfs-file.img and b/lfs-file.img differ
```

Any attempt to make git working copy clean failed, situation does not changed:
```console
$ git restore lfs-file.img
Encountered 1 file(s) that should have been pointers, but weren't:
	lfs-file.img
$ git reset --hard
HEAD is now at a1966fe LFS file, version 2
Encountered 1 file(s) that should have been pointers, but weren't:
	lfs-file.img
$ git stash
Saved working directory and index state WIP on master: a1966fe LFS file, version 2
Encountered 1 file(s) that should have been pointers, but weren't:
	lfs-file.img
```
It is not possible to get new revisions from SVN while git working copy is dirty, so the git-svn workflow does not work.

If you look at the imported history (I'd use GitKraken), you'll notice that git-svn is not aware of Git LFS -- all big files appeared as-is and only in working copy file replaced with a Git LFS handle:
Overall history
![History](https://user-images.githubusercontent.com/450131/165462333-339a02f4-d543-4855-ac86-d73ca77b093f.png)
First commit of big file:
![Without LFS](https://user-images.githubusercontent.com/450131/165462670-62f6930b-7142-4334-b0fb-5e3e1980bdcc.png)
Working dir changes:
![Big file changes](https://user-images.githubusercontent.com/450131/165462329-bc2b9f8d-e586-4c57-af26-e5c0eb6486bc.png)

**Comment by Mingun** [comment]
If this is the problem of a git-svn, could someone point to me their issue tracker because I can't find it

**Comment by bk2204** [comment]
git-svn is part of core Git, which uses a mailing list instead of an issue tracker: https://git-scm.com/community.  However, if you go to the Git list and say, “git-svn doesn't work with Git LFS,” you're not likely to get a warm welcome.  You'd want instead to propose a set of hooks or patches that could let a program in general hook in this way, and then allow Git LFS to hook into them using those interfaces.

**Comment by Mingun** [comment]
I've patch my git-svn installation and grab command-line arguments that git-svn uses when making git commits. It seems that it use the following commands to make a commit:
```sh
# <fetch data from SVN into working copy>
git update-index -z --index-info
# Log changes, like 
# A	ordinary-file.txt
git write-tree
git update-ref -m -r1 refs/remotes/origin/trunk 1f7a7456c2085092618f11d65a6159bd518cc5ac
# Log commit info, like
# r1 = 1f7a7456c2085092618f11d65a6159bd518cc5ac (refs/remotes/origin/trunk)
git write-tree
git cat-file commit 1f7a7456c2085092618f11d65a6159bd518cc5ac
```
See the full log in [create.sh.txt](https://github.com/git-lfs/git-lfs/files/8629471/create.sh.txt)

Сan the Git LFS team say which side is the problem? Is that Git LFS or git-svn problem?

**Comment by Mingun** [comment]
@bk2204, could you help with this?

**Comment by bk2204** [comment]
I think it depends on what you want to do.  If you want to store the full data of the object in the Subversion repository, then you'll need to modify the code that pushes the data to Subversion to replace the pointer file that Git has checked in with the actual large file.  If you're just looking to store the pointer, then you'll probably want to hook into the push code to also push the object to the LFS server at the same time you're pushing the LFS object.

In both cases, assuming you've set `lfs.url` in `.lfsconfig` appropriately, Git should check out the large object correctly in the repository.

**Comment by Mingun** [comment]
Ideally I want to have a Subversion repository played as a Git LFS storage for big files. All git and git-svn commands should work when using Git LFS.

First, I need to understand, it is a Git LFS fault that it does not correctly hooks git commands that git-svn uses, or it is a git-svn fault that uses unhookable commands to work with git?

**Comment by Mingun** [comment]
Problem in that that git working copy is damaged after `git svn fetch`, as shown [here](https://github.com/git-lfs/git-lfs/issues/251#issuecomment-1110633628). So something wrong happens already at this stage.

**Comment by bk2204** [comment]
Yeah, the likely situation is that Git is adding those files as non-LFS files.  You'd need to add some sort of hook to get git-svn to add them in a way that causes them to be run through the smudge and clean filters, such as `git add`, and not using whatever git-svn is using now.

**Comment by Mingun** [comment]
Thanks. So, it is likely a git-svn problem in the end
