### ISSUE TITLE
Was this that mysterious "git-media" command that was bundled with GitHub for Mac?

### ISSUE THREAD

**Issue by geoff-codes** [github/git-lfs#256]
And in the Github for Mac situation, what _was_ it for?
If you feel like divulging. 
:see_no_evil::hear_no_evil::speak_no_evil:

**Comment by technoweenie** [comment]
Yup.  It's replaced with Git LFS now.  It's there so GitHub Desktop can support repositories that use Git LFS, and to help distribute it to existing GitHub Desktop users.
