### ISSUE TITLE
Support for non-ASCII URLS in pointer files

### ISSUE THREAD

**Issue by dikonov** [github/git-lfs#259]
I have just learned about git-lfs and while reading https://github.com/github/git-lfs/blob/master/docs/spec.md it struck me that the pointer files contain URLs for files at remote servers _and_ must contain only ASCII characters. This excludes all URLs with non-ASCII characters in them (e.g. cyrillic domain zone .рф, Chinese domains) etc. This sounds like a design defect limiting the possibility to deploy own LFS servers in certain domains. Perhaps, it would be smarter to allow Unicode in pointer files.

**Comment by technoweenie** [comment]
There is a PR for [clarifying the spec](https://github.com/github/git-lfs/pull/246/files?short_path=6e196c9#diff-6e196c98aaadaa54d9ba9bbe92a13320), which includes stating that the pointer file contents need to be UTF-8, and not just ASCII.

Also, the URL in the pointer is not to the remote server.  It is a URL identifying the pointer file version that is in use.  It's not likely to change often.

**Comment by technoweenie** [comment]
Closing... Please re-open and clarify if this is still an issue for ou.
