### ISSUE TITLE
git-lfs fsck (bitrot detection)

### ISSUE THREAD

**Issue by zeroshirts** [github/git-lfs#262]
Would anyone else find it useful if git-lfs offered a fsck command that verified the integrity of tracked (large) files?  Re-calculating hashes for files under .git/lfs/objects and comparing against the object name (dir+filename) could serve as an integrity check.

My goal with this would be to detect bitrot in large files like photos and mp3s.

**Comment by technoweenie** [comment]
I think this would be cool :+1:  Seems like it could go hand in hand with #260.

**Comment by technoweenie** [comment]
FWIW this would've helped an issue like https://github.com/github/git-lfs/issues/266

**Comment by zeroshirts** [comment]
I have a rough implementation up at https://github.com/zeroshirts/git-lfs.  @technoweenie , could you take a quick look and comment on my approach?  I need to add unit tests, at the very least.

**Comment by technoweenie** [comment]
Cool, can you open a pull request?  You can create one [from the compare view](https://github.com/github/git-lfs/compare/master...zeroshirts:master).  It's also typically best to start off in your own branch.
