### ISSUE TITLE
install.bat in release for windows do not work

### ISSUE THREAD

**Issue by bssthu** [github/git-lfs#272]
Should replace it by git-lfs/script/install.bat.example

BTW, the script will fail and cause problems if length of %PATH% > 1024 byte.

**Comment by tclem** [comment]
[The fix](https://github.com/github/git-lfs/commit/c7b71c1ad17efa6fef70457857d0b91110db1356) should go out in [v0.5.1](https://github.com/github/git-lfs/issues/268), but the "%PATH% > 1024 byte" might still be an issue.
