### ISSUE TITLE
Need push rights?

### ISSUE THREAD

**Issue by raquel-ucl** [github/git-lfs#275]
Hi,

I was testing Git LFS in a new dummy repo with a 174.33 MB file. I committed this file to the local repo, but when I try to push it to GitHub, I get the following message:

```
(1 of 1 files) 0 B / 174.33 MB  0.00 % 0
You need Push access to upload Git LFS objects.
Docs: https://github.com/contact
error: failed to push some refs to 'https://github.com/EIT-team/template_project.git'
```

I have push access to the repository, since everything else there was pushed by me just before I installed Git LFS. I'm not sure why I'm getting that message, or if there is something left to configure. Any help would be greatly appreciated! :-)

**Comment by raquel-ucl** [comment]
I realise this is probably due to me not having an invitation yet. Sorry! It'd be nice that's clearer in the steps to follow to get Git LFS working.

**Comment by technoweenie** [comment]
Thanks for the feedback.  We're tweaking the messages right now to make them more clear.  Also, you're much better off contacting [GitHub support](https://github.com/contact) for issues related to our Early Access program, as it's not totally relevant to this open source repository.  There are also more people watching our support queue, so you should get an answer sooner :)
