### ISSUE TITLE
HTTP connections don't use correct IP

### ISSUE THREAD

**Issue by catphish** [github/git-lfs#284]
When making some HTTP connections, LFS appears to look up hostnames by DNS instead of gethostbyname. This results in failed connections when using a hosts file or other non-DNS lookup mechanism.

**Comment by catphish** [comment]
Upon further investigation, I suspect this uses Go's built in DNS resolver, which does honour hosts file entries, but not other lookup mechanisms. This is likely a Go bug rather than a LFS bug.

**Comment by catphish** [comment]
> <Aram> previously Go used internal resolver if build without cgo, or with netgo tag, more recently it does as previously, except it also uses the internal resolver (even with cgo) if nsswitch.conf permits.
> <catphish_> so modern versions will revert to getnameinfo() if nsswitch doesn't permit?
> <Aram> IFF they are build with cgo and without netgo.
> <Aram> and recent means like a week old
> <Aram> the way to address it is to recompile the program with a cgo-enabled go.

**Comment by technoweenie** [comment]
@catphish Which Git LFS build are you using?

**Comment by catphish** [comment]
git-lfs/0.5.1 (GitHub; linux amd64; git 1.9.1; go 1.3)

**Comment by bkeepers** [comment]
https://inconshreveable.com/04-30-2014/cross-compiling-golang-programs-with-native-libraries/ looks like it could be a solution to this. (Thanks @inconshreveable)

I'll also looking into getting CI and release assets running on native platforms.

**Comment by technoweenie** [comment]
No longer relevant, our releases are built on native platforms. Go also has much better cross compiling these days :)
