### ISSUE TITLE
Possible inconsistency in OID format

### ISSUE THREAD

**Issue by catphish** [github/git-lfs#286]
I notice that the OID is sometimes specified as a hash with a prefixed hash function:

> oid tracks the unique object id for the file, prefixed by its hashing method: {hash-method}:{hash}. Currently, only sha256 is supported.

But in other places, the hash function is not specified:

> .git/lfs/objects/4d/7a/4d7a214614ab2935c943f9e0ff69d22eadbb8f32b1258daaa5e2ca24d17e2393

> "oid": "the-sha-256-signature",
> "size": 123456,

This isn't a problem in any practical sense, but I wanted to check whether it's considered correct that:

1) Hashes from different hashing functions be merged together for filesystem and network operations into one large address space.
2) "OID" refers to 2 different formats, one with a function prefixed and one without

**Comment by technoweenie** [comment]
Good catch.  It doesn't matter right now, but I think solving this would be good.  My suggestions:

1. Add an `oid_type` property to the JSON objects.  The client can just assume "sha256" if it's not specified.
2. Change the object path.  A couple options:
  * `.git/lfs/objects/sha256/4d/7a/4d7a214614ab2935c943f9e0ff69d22eadbb8f32b1258daaa5e2ca24d17e2393`
  * `.git/lfs/objects/4d/7a/4d7a214614ab2935c943f9e0ff69d22eadbb8f32b1258daaa5e2ca24d17e2393-sha256`

Currently not a high priority though.

**Comment by catphish** [comment]
On point 1, this is an excellent solution for handling this in the future. For now, sha256 can be assumed.

On point 2, I would favour `.git/lfs/objects/sha256/4d/7a/4d7a214614ab2935c943f9e0ff69d22eadbb8f32b1258daaa5e2ca24d17e2393`. Since this isn't going to happen immediately, a backward compatible search of sha256 in the root could be added if this is implemented in the future.

**Comment by mathstuf** [comment]
Hmm. Is there a reason this was closed? Still looks valid to me.

**Comment by bk2204** [comment]
I don't think it would be valid to mix hash functions in the same repository, so I'm not sure that we need to reopen this.  The ongoing work to switch to SHA-256 in Git is making the same assumption.

**Comment by mathstuf** [comment]
Thanks, that makes sense. Was more curious since it was just closed without comment.
