### ISSUE TITLE
Build CI and release assets on native platforms

### ISSUE THREAD

**Issue by bkeepers** [github/git-lfs#288]
#284 is related to Go using it's own DNS resolver when its cross-compiled. Even if there is a workaround for this, it would be ideal to run CI and build release assets on the native platforms.

Travis supports [OS X](http://docs.travis-ci.com/user/osx-ci-environment/) and [uploading release assets](http://docs.travis-ci.com/user/deployment/releases/). I have never used either, but we can experiment with them.

Any recommendations for Windows build services? /cc @github/windows

**Comment by shiftkey** [comment]
[AppVeyor](http://www.appveyor.com/)

**Comment by ChaseFlorell** [comment]
I've used AppVeyor before and it's actually pretty great. I could be interested in contributing, but I'm a powershell guy, so I'm not entirely sure if it fits.

**Comment by bkeepers** [comment]
> I could be interested in contributing, but I'm a powershell guy, so I'm not entirely sure if it fits.

That would be great! None of us have windows experience, so any help would be appreciated!

**Comment by technoweenie** [comment]
We run CI on mac and linux. Tests pass on windows, but I haven't gotten AppVeyor to work though.
