### ISSUE TITLE
history; clarifications

### ISSUE THREAD

**Issue by underscorediscovery** [github/git-lfs#289]
I've been exploring git-lfs and like most others, am quite excited about the idea in practice.

One thing I just can't seem to find any information on is regarding history.

Things like: What happens when modifications are done to the files? What happens when cloning, and there is a history? Does checking out a previous revision require an internet connection to fetch it? 

These are things I can reason about via the code and structure and spec, but if there is any further information or documentation I'd appreciate a link!

Edit: found this in the readme actually, somehow missed this line:

>Large files are only synced from the server when they are checked out, so your local repository doesn't carry the weight of every version of every file when it is not needed.

**Comment by technoweenie** [comment]
Your git repository will have multiple Git LFS pointer objects in the history.  Each modification should create a new one that changes the OID and file size.  

Git LFS doesn't change how Git clones a repository.  When Git checks out a commit to the working directory, it passes any matching files from `.gitattributes` through the Git LFS filter.  Any pointer file is downloaded from your Git LFS server.

The [roadmap](https://github.com/github/git-lfs/blob/master/ROADMAP.md) has two items that could affect this:

* A "narrow clone" feature could let users choose which files to download.  Maybe you don't want to download _anything_.  Or maybe you only care about a few specific directories.
* A `git lfs get` command could let you download objects manually.  

> Does checking out a previous revision require an internet connection to fetch it?

Right now, it will error if it tries to download any Git LFS files from a previous revision.  If the file exists in your local `.git/lfs/objects`, Git LFS will use that instead.  This is where I hope `git lfs get` can help out.  If you anticipate going offline, then run `git lfs get` to grab the files you need ahead of time.  If you forget, then changing to a previous commit will print out some warnings.  You should be able to go back online and use `git lfs get` to download them.

This is all speculation, so I look forward to your input once we implement more of the roadmap.

**Comment by jeffhostetler** [comment]
Could we use this "git lfs get" as something like a "pre-checkout" hook (or inside of such a hook) ?

That is, to ensure that all of the LFS objects are present locally in the cache before we attempt the checkout?  So that the WD spends less time in a transitional state during the actual checkout.

**Comment by technoweenie** [comment]
@jeffhostetler That's a really great idea.  :+1:

**Comment by technoweenie** [comment]
@jeffhostetler Oh there isn't a pre-checkout hook.  I think what you're suggesting would have to be done either with a tool that uses libgit2.  Or you could disable the smudge filter and run it in post-checkout.

**Comment by strich** [comment]
@technoweenie I assume you keep all revisions of a large file you have made locally, even after pushing to remote? Eg does one need to do a git clean fairly often if they're making many changes to files several hundred MB in size?

**Comment by technoweenie** [comment]
Git LFS doesn't have any kind of automatic GC of objects in `.git/lfs/objects`.  It's something on the [roadmap](https://github.com/github/git-lfs/blob/master/ROADMAP.md) though.  There's a balance though.  If a gc command scrubs every object not in the current git commit, then you have to re-download files as you check out older commits or switch branches.  Of course, the downside to having no gc is that the `.git/lfs/objects` directory grows unbounded.

**Comment by lcsthom** [comment]
@technoweenie : can't see it in the roadmap, is there a way to at least create a command to run manually this gc?

**Comment by technoweenie** [comment]
@lcsthom Check out the prune command: https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-prune.1.ronn
