### ISSUE TITLE
Tests fail if global user.name and user.email are not set

### ISSUE THREAD

**Issue by ssgelm** [github/git-lfs#292]
When running tests a number of tests fail with the following error if a global user and email aren't set:
```
--- FAIL: TestPushToMaster (0.28 seconds)
        commands_test.go:210: Error running command:
                $ git commit -m a


                *** Please tell me who you are.

                Run

                  git config --global user.email "you@example.com"
                  git config --global user.name "Your Name"

                to set your account's default identity.
                Omit --global to set the identity only in this repository.
```
This probably should not be a requirement for tests to pass.

**Comment by technoweenie** [comment]
Thanks for the report!

**Comment by technoweenie** [comment]
Why are your global user and email values unset?  If this is a CI server for tests and builds, run `script/cibuild` to get default values set, instead of just `script/test`.

**Comment by ssgelm** [comment]
I was running this on my build box on which i do not use git to build a package for git-lfs.  Part of the debian standard is running tests on binaries it builds.  Should the debian build scripts use `script/cibuild` instead?

**Comment by technoweenie** [comment]
Yes, that's the convention we use for our CI servers.  It's basically [`script/test` + some default git user/email configs](https://github.com/github/git-lfs/blob/master/script/cibuild).

Thanks for explaining.  I'm going to close this out.

**Comment by ssgelm** [comment]
I'm not sure that's really a solution though.  That would set the global config on my box to "Git LFS Tests" <git-lfs@example.com> which is not optimal.  Can the git repos used in the tests not have a user set in them?

**Comment by technoweenie** [comment]
You can easily set them yourself if you don't want the script to set them.

I'm working on a new test suite that uses `git` and `bin/git-lfs` to test against temporary repos and git servers in #291.  I can add the user config there.

**Comment by ssgelm** [comment]
Sounds good.  Thanks!
