### ISSUE TITLE
git lfs not check git file system before start tracking files

### ISSUE THREAD

**Issue by Aorjoa** [github/git-lfs#293]
File tracking not check necessary items before (git lfs require git file system and into git influence directory) , to prevent error I will hack some code for support this issue and I will show reproduce issue as below. ( I think it's like #200 but duplicate line of tracking file in my case)

System environments
git-lfs/0.5.1 (GitHub; darwin amd64; git 2.0.1; go 1.4.1) on Mac OS X : Yosemity 10.10.4

I woking in directory contain a testfile.png and use git lfs without git file system
```bash
$ git lfs track "testfile.png"
Tracking testfile.png
```
.gitattributes was created and I looking into file
```bash
$ cat .gitattributes
testfile.png filter=lfs diff=lfs merge=lfs -crlf
```
then use git lfs track again
```bash
$ git lfs track "testfile.png"
Tracking testfile.png
```
and read it
```bash
$ cat .gitattributes
testfile.png filter=lfs diff=lfs merge=lfs -crlf
testfile.png filter=lfs diff=lfs merge=lfs -crlf
```
It seem like git lfs not check git file system before. but if git already in the directory it’s warnning user about file exits in git lfs system (.gitattributes).

create git file system
```bash
$ git init
Initialized empty Git repository in /Users/AorJoa/repository/test_check_git_exists/.git/
```
git check tracking file before add any line
```bash
$ git lfs track "testfile.png"
testfile.png already supported
```
and file contains two line of tracking file
```bash
$ cat .gitattributes 
testfile.png filter=lfs diff=lfs merge=lfs -crlf
testfile.png filter=lfs diff=lfs merge=lfs -crlf
```

**Comment by technoweenie** [comment]
Hey, I'm not able to replicate this:

```
$ git lfs track "testfile.png"
Tracking testfile.png

$ cat .gitattributes 
testfile.png filter=lfs diff=lfs merge=lfs -crlf

$ git lfs track "testfile.png"
testfile.png already supported

$ cat .gitattributes
testfile.png filter=lfs diff=lfs merge=lfs -crlf
```

I added a passing test for this in #323.  Are you still seeing this?  What version of Git LFS are you running?

**Comment by Aorjoa** [comment]
I use `$ go install cmd/git-lfs/git-lfs.go` from commit 38657a8. It's still problem but I think test pass in #323 because `$ git init` was created .git directory. (I guess this issue coming from I run `$ git lfs track <some file>` out of git directory.

**Comment by technoweenie** [comment]
Can you try it with 7bbd60ddc70973f01285d3bd0ae94f3b26fc01d9?

**Comment by Aorjoa** [comment]
I try to use git lfs with 7bbd60d it's look good. :+1:

**Comment by technoweenie** [comment]
Great!  I'll merge that PR.  Thanks again for the report and patch :)

**Comment by technoweenie** [comment]
This should be fixed in #323.  

    git lfs track "testfile.png"

By the way, it's probably better to track file types or directories instead of additional files. 

    # better
    git lfs track "*.png"

**Comment by Aorjoa** [comment]
:+1:

**Comment by rajatguptarg** [comment]
I am using Git LFS and initialized the git repo with LFS. I can add files and commit them in the git, but when I am doing this `git lfs ls-files`, it shows nothing, means LFS is not tracking(I think).
