### ISSUE TITLE
ssh:// style URLs not correctly handled

### ISSUE THREAD

**Issue by catphish** [github/git-lfs#295]
I'm trying to push a repository to an ssh remote, however the client never appears to make a `git-lfs-authenticate` request. When I run `git-lfs push origin master` the SSH server receives `git-upload-pack /test/lfs/lfs-test.git` but nothing else. The output on the client is as follows:

    charlie@charlie-pc ~/git-lfs-test $ git remote -v
    origin	ssh://charlie@127.0.0.1:2222/test/lfs/lfs-test.git (fetch)
    origin	ssh://charlie@127.0.0.1:2222/test/lfs/lfs-test.git (push)

    charlie@charlie-pc ~/git-lfs-test $ git-lfs push origin master
    (0 of 18 files) 0 B / 522 B  0.00 %
    Username for '://':

**Comment by catphish** [comment]
My suspicion is that this problem relates to the ssh:// URL format.

**Comment by technoweenie** [comment]
Thanks for the report!

**Comment by technoweenie** [comment]
Hey, just a heads up. We just completed a big rewrite of our test suite (#306), which unblocks us from implementing and properly testing little bugs like this.  We should be able to get to this next week, and definitely for the next release of Git LFS.

**Comment by technoweenie** [comment]
Added way back in v0.5.3 :)
