### ISSUE TITLE
install.bat not working in v0.5.1 on Windows 8.1

### ISSUE THREAD

**Issue by ediebold** [github/git-lfs#297]
When running the install.bat included in v0.5.1 on an up to date Windows 8.1 64-bit machine, the setx command does not seem to run. All of the other installation steps appear to work, but my path is not updated to include the GIT_LFS_BIN_PATH.

**Comment by niik** [comment]
@ediebold Could you tell us a little more about the environment you're in? Are you the only user of your machine or is it part of a corporate network?

Looking at the install.bat file it seems it's setting the [machine-level PATH](https://github.com/github/git-lfs/blob/master/script/install.bat.example#L38) environment variable. Could you open your environment variables dialog and see if it has successfully updated the machine-level PATH?

@joshvera @shiftkey @ammeep it seems odd to me that we'd install into the user directory yet update the machine level env var. Shouldn't we omit the /M flag to setx?

**Comment by ediebold** [comment]
It's a personal computer, and I have administrator privileges. I only have the one user account.

The machine-level path wasn't touched- I added the git-lfs entry in manually.

**Comment by niik** [comment]
@ediebold Was this the first time you ran the script on this machine? I ask because it seems we don't try to update the environment variable if the installation directory exists.

**Comment by ediebold** [comment]
I ran it a few times with no luck. Then I opened the batch file in a text editor and saw where it was placing the git-lfs executables. I confirmed they were there and added that directory to my machine-level path manually and it began working.

**Comment by technoweenie** [comment]
Closing this ancient issue. Git LFS has a windows installer now. Everything is awesome!
