### ISSUE TITLE
git lfs blows up when a space is present in filename

### ISSUE THREAD

**Issue by kernelsmith** [github/git-lfs#298]
if I

```
git lfs track "file/with/a space in it"
```
all goes well until I do a push or similar, then I get

```
file/with/a is not a valid attribute name: .gitattributes:1
```
and manually adding quotes around the file name in .gitattributes doesn't help.  This is pretty brutal.  Is there a config option or somesuch that enables this behavior.  I don't personally use spaces in file names, but some of my users do.

**Comment by technoweenie** [comment]
Try editing your `.gitattributes`, using `[[:space:]]` in place of actual spaces.

    file/with/a[[:space:]]space[[:space:]]in[[:space:]]it filter=lfs diff=lfs merge=lfs -crlf

This seems to be a limitation in the gitattributes file.  But if `[[:space:]]` works, we can have `git lfs track` insert it in place of spaces pretty easily.

**Comment by kernelsmith** [comment]
It's probably clear at this point that [[:space]] did fix the problem. Thanks for that as well as the PR to fix!
