### ISSUE TITLE
Unable to build git LFS client on Ubuntu 12.0

### ISSUE THREAD

**Issue by brabil** [github/git-lfs#301]
I have been trying to build git lfs from the source and I couldn't manage to build it. I installed the required packages and tried with master branch or tag 0.5.1 and still the same error. Here below the steps I performed:

```
~/repos$ sudo apt-get install golang-go git
~/repos$ git clone https://github.com/github/git-lfs.git; cd git-lfs

~/repos/git-lfs$ script/bootstrap 
# github.com/github/git-lfs/lfs
.vendor/src/github.com/github/git-lfs/lfs/setup.go:28: function ends without a return statement

~/repos/git-lfs$ go run script/build.go
# command-line-arguments
script/build.go:7: imported and not used: "github.com/github/git-lfs/lfs"
script/build.go:44: undefined: Release
script/build.go:89: undefined: Release
```

Am I doing something wrong ? Are there any steps that I should execute before script/bootstrap ?
I tried to follow the instructions documented at: https://github.com/github/git-lfs/blob/master/docs/linux-build.md. Is there another documentation for such procedure ?

**Comment by technoweenie** [comment]
What version of Go are you using?  Also, what commit are you on in the git-lfs repo?  [`lfs/setup.go:28`](https://github.com/github/git-lfs/blob/923be66fdd733be438a3fbdd1eb1201ec24bda0c/lfs/setup.go#L28) is not inside a function.

**Comment by brabil** [comment]
Here below the current git HEAD and go version:

~/repos/git-lfs$ go version
go version go1

~/repos/git-lfs$ git show HEAD
commit 923be66fdd733be438a3fbdd1eb1201ec24bda0c
Merge: 5e47f06 3e355b3
Author: risk danger olson <technoweenie@gmail.com>
Date:   Tue May 5 09:31:38 2015 -0600

    Merge pull request #283 from catphish/patch-1
    
    Remove trailing period when printing log file location

**Comment by technoweenie** [comment]
Can you dump `.vendor/src/github.com/github/git-lfs/lfs/setup.go` to a Gist?  It doesn't make any sense that 28 needs a return, since it's inside a struct declaration.   

Also, you can't run `script/build.go` manually.  `script/bootstrap` runs it.

**Comment by brabil** [comment]
$ cat .vendor/src/github.com/github/git-lfs/lfs/setup.go
package lfs

import (
	"errors"
	"fmt"
	"github.com/github/git-lfs/git"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var (
	valueRegexp           = regexp.MustCompile("\\Agit[\\-\\s]media")
	NotInARepositoryError = errors.New("Not in a repository")

	prePushHook     = "#!/bin/sh\ngit lfs pre-push \"$@\""
	prePushUpgrades = map[string]bool{
		"#!/bin/sh\ngit lfs push --stdin $*":     true,
		"#!/bin/sh\ngit lfs push --stdin \"$@\"": true,
	}
)

type HookExists struct {
	Name     string
	Path     string
	Contents string
}

func (e *HookExists) Error() string {
	return fmt.Sprintf("Hook already exists: %s\n\n%s\n", e.Name, e.Contents)
}

func InstallHooks(force bool) error {
	if !InRepo() {
		return NotInARepositoryError
	}

	if err := os.MkdirAll(filepath.Join(LocalGitDir, "hooks"), 0755); err != nil {
		return err
	}

	hookPath := filepath.Join(LocalGitDir, "hooks", "pre-push")
	if _, err := os.Stat(hookPath); err == nil && !force {
		return upgradeHookOrError(hookPath, "pre-push", prePushHook, prePushUpgrades)
	} else {
		return ioutil.WriteFile(hookPath, []byte(prePushHook+"\n"), 0755)
	}

	return nil
}

func upgradeHookOrError(hookPath, hookName, hook string, upgrades map[string]bool) error {
	file, err := os.Open(hookPath)
	if err != nil {
		return err
	}

	by, err := ioutil.ReadAll(io.LimitReader(file, 1024))
	file.Close()
	if err != nil {
		return err
	}

	contents := strings.TrimSpace(string(by))
	if contents == hook {
		return nil
	}

	if upgrades[contents] {
		return ioutil.WriteFile(hookPath, []byte(hook+"\n"), 0755)
	}

	return &HookExists{hookName, hookPath, contents}
}

func InstallFilters() error {
	var err error
	err = setFilter("clean")
	if err == nil {
		err = setFilter("smudge")
	}
	if err == nil {
		err = requireFilters()
	}
	return err
}

func setFilter(filterName string) error {
	key := fmt.Sprintf("filter.lfs.%s", filterName)
	value := fmt.Sprintf("git lfs %s %%f", filterName)

	existing := git.Config.Find(key)
	if shouldReset(existing) {
		git.Config.UnsetGlobal(key)
		git.Config.SetGlobal(key, value)
	} else if existing != value {
		return fmt.Errorf("The %s filter should be \"%s\" but is \"%s\"", filterName, value, existing)
	}

	return nil
}

func requireFilters() error {
	key := "filter.lfs.required"
	value := "true"

	existing := git.Config.Find(key)
	if shouldReset(existing) {
		git.Config.UnsetGlobal(key)
		git.Config.SetGlobal(key, value)
	} else if existing != value {
		return errors.New("Git LFS filters should be required but are not.")
	}

	return nil
}

func shouldReset(value string) bool {
	if len(value) == 0 {
		return true
	}
	return valueRegexp.MatchString(value)
}

**Comment by technoweenie** [comment]
That certainly looks like the same file.  I wonder if it's a Go version issue.  The current stable release is v1.4.  Though we currently ship releases on v1.3.  There are some small changes in Go 1.1 and 1.2, but the only thing that looks relevant is [return requirements in Go 1.1](https://golang.org/doc/go1.1).  

Go programs are forward compatible, but not necessarily backwards compatible.  Any apps written in Go 1.0 should run on every Go 1.x release.  But something written in Go 1.4, taking advantage of the changes to the language since 1.0 may not necessarily work in Go 1.0.

If you just want to use this on your system, you should be fine with the pre-compiled "Linux" release of Git LFS v0.5.1: https://github.com/github/git-lfs/releases/tag/v0.5.1.

**Comment by brabil** [comment]
It works for me now using Go 1.3. Thanks for your support and guidance.
