### ISSUE TITLE
Sanitize Authorization header when outputting traced http operations

### ISSUE THREAD

**Issue by rubyist** [github/git-lfs#314]
When using `GIT_CURL_VERBOSE` to output http tracing, we should sanitize the `Authorization` header. This output could end up in support emails or screenshots and is unnecessary for any debugging.

Code is [here](https://github.com/github/git-lfs/blob/c91bb6f3555f052f933165b484685d9039df0e63/lfs/http.go#L88)

**Comment by rubyist** [comment]
Turns out that git itself will also put those headers out in the clear when using `GIT_CURL_VERBOSE` making it much less useful to sanitize the client's output. :unamused:

**Comment by technoweenie** [comment]
We don't have to be as insecure as git.  What if we did something like this:

1. Introduce `GIT_LFS_HTTP_TRACE` that strips Authorization headers.  Maybe any *Key headers too?
2. Add `GIT_LFS_AUTH_TRACE` which keeps the auth headers.
3. Keep `GIT_CURL_VERBOSE` as an alias for `GIT_LFS_HTTP_TRACE` + `GIT_LFS_AUTH_TRACE`?

Might be too much effort...
