### ISSUE TITLE
Uninstall Git Lfs

### ISSUE THREAD

**Issue by ChristoCoder** [github/git-lfs#316]
how can i remove git-lfs

**Comment by technoweenie** [comment]
We haven't built an uninstaller into Git LFS yet.  Assuming you installed it by downloading a zip from the Releases section, you should be able to simply delete the `git-lfs` binary.  The linux installer either throws it in:

* `/usr/local/bin/git-lfs`
* `$PREFIX/bin/git-lfs`
* `$BOXEN_HOME/bin/git-lfs`
* `%LOCALAPPDATA%\GitLFS\bin` (Windows only)

You can run `which git-lfs` to see where the installer put it.  

Once that's done, you can also remove the global git configs that Git LFS sets up.  However, leaving them on the system won't affect anything, unless you happen to install another "git lfs" tool.

```
$ git config --global --unset filter.lfs.required
$ git config --global --unset filter.lfs.smudge  
$ git config --global --unset filter.lfs.clean 

# confirm all git lfs settings are gone
$ git config -l | grep lfs
```

**Comment by technoweenie** [comment]
Let me know if you need more help.

**Comment by shadowwalkersb** [comment]
In addition to the suggestion above, I have removed every folder named lfs under .git of a few other local repositories that I can find on my system. I still get the following message
```
git: 'lfs' is not a git command. See 'git --help'.

Did you mean this?
	log
error: failed to push some refs to 'git@github.com:.............'
```

**Comment by shadowwalkersb** [comment]
Is this related to #333 and #334 ?
I reinstalled git-lfs and I can push now.

**Comment by YannickNascimento** [comment]
i just put git-lfs the 777 permission, opensuse(usr/local/bin) and it work for me!

**Comment by hayesmaker** [comment]
please make an uninstaller.. there's no way currently to update (or at least make updates easier)

**Comment by nuest** [comment]
Just in case somebody is looking for help here to **remove git lfs from a repository**: After deleting git-lfs binary, the following error message told me to remove a hook. I assume I could have kept the binary and the global config if I just removed the hook from the repo in question:

```
This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.

error: failed to push some refs to 'https://github.com/...'
```

**Comment by kaspar-allenbach** [comment]
How about that uninstaller?

**Comment by bk2204** [comment]
Except on Windows, we don't provide an installer. If you want to uninstall Git LFS on a Linux or macOS system, you can either uninstall the package using the package manager or just delete the binary, depending on how you installed it.
