### ISSUE TITLE
Chocolatey Install

### ISSUE THREAD

**Issue by ChaseFlorell** [github/git-lfs#320]
Would love to see a chocolatey install for git-lfs. It'll make setting up our environment that much easier.

    > choco install poshgit
    > choco install git-lfs

> win.

**Comment by technoweenie** [comment]
That sounds great.  The Git LFS team has very little Windows experience, so help would be a huge help here.

**Comment by ChaseFlorell** [comment]
In other words, if I get time, I can start a branch and PR? Just want to
make sure I have the go-ahead before starting.

**Comment by technoweenie** [comment]
Absolutely. Anything you can do to help automate and document the process would be great. Check out the [debian install script](https://github.com/github/git-lfs/blob/master/script/debian-build) for one example.

Currently, our release process involves cross compiling for Mac, Linux, and Windows from my laptop.  We also only have automated CI builds for linux only through Travis CI. I'd love to have automated CI builds on each native platform (https://github.com/github/git-lfs/issues/288), and automated package building.

Obviously this all doesn't have to happen in one PR.  Baby steps :)

**Comment by ChaseFlorell** [comment]
separate topic, but can I do it via powershell instead of .bat files? I maintain [poshBAR](https://github.com/futurestatemobile/poshBAR), and could cherry pick some of my nuget stuff in there as well as automated builds and such.

**Comment by technoweenie** [comment]
Is powershell readily available in any flavors of Windows that would be worth supporting in Git LFS? I'm way out of touch since the Windows 98 days :)

**Comment by ChaseFlorell** [comment]
Absolutely, it comes baked into Windows 7 and later, and is redily
available for download in WinXP and server 2k3
https://en.wikipedia.org/wiki/Windows_PowerShell

**Comment by technoweenie** [comment]
Cool, powershell sounds fine to me.

**Comment by technoweenie** [comment]
@ChaseFlorell Hey, can you hold off on this for a little bit? We've been talking internally about changing the build scripts a bit.  We want this to work more like a standard Go project, and one side benefit is that it should build just fine on Windows without any of the symlink stuff in `script/bootstrap`.

**Comment by ChaseFlorell** [comment]
Yep, I totally can, just let me know your thoughts.. I was just typing out another message...

-----

So, I don't have any GO experience. I've installed GO via chocolatey `choco install golang`, but when I try to do a quick compile (bare minimum to get the ball rolling, I get errors.

Is there a document I can go over (no pun intended) to getting my environment setup for compilation? I figure once I can compile via `go.exe`, I can wrap it all up in a nice powershell wrapper to kick off the build, run tests, and package artifacts for chocolatey. I figure there'll be some script to do the same for apt-get or whatever package manager you guys want for the other platforms.

**Comment by technoweenie** [comment]
Yup, you probably ran into the issue I'm referring to :)  I'll reply when I think it's ready for you to try again.

**Comment by ChaseFlorell** [comment]
ah, wonderful.

On Thu, May 21, 2015 at 1:24 PM, risk danger olson <notifications@github.com

**Comment by technoweenie** [comment]
Hey @ChaseFlorell: things are ready for you to try again. You should be able to build Git LFS with standard go commands.  The `script/bootstrap` and `script/test` run the recommended go commands, and should work unmodified on Windows now. I hoooope :) 

I plan to dig out my windows vm credentials and try it myself tomorrow.
