### ISSUE TITLE
Asks for "Username for '://':"

### ISSUE THREAD

**Issue by HashBang173** [github/git-lfs#322]
When cloning over https, it asks for "Username for '://':" and "Password for '://':"

It asks this to download the large file(s)

**Comment by technoweenie** [comment]
What does `git lfs env` show?

What's the actual url for the remote?  `git remote show origin -n` (replace "origin" with your remote name).

**Comment by HashBang173** [comment]
git lfs env: https://gist.github.com/HashBang173/652c2fa4dbf94706c402

git remote show github -n: https://gist.github.com/HashBang173/628ca2627edc77c70606

**Comment by technoweenie** [comment]
What about just `git remote`?  It looks like the `git lfs env` output mentions a "githubs" remote too.

What are you typing to push?  Just `git push`?

**Comment by HashBang173** [comment]
I originally pushed the repository using ```git push``` after I tracked the large file with ```git lfs```.

Maybe I did this incorrectly? Cloning the repository with ssh also fails for me. It gives me [this error log] (https://gist.github.com/HashBang173/73753a6e08a1e8ee88b2).

**Comment by technoweenie** [comment]
What is the exact SSH url that you're using?  Also, you never answered my question about the mysterious "githubs" remote.

**Comment by HashBang173** [comment]
githubs is another remote I tried to see if it would work better with git://

The ssh URL I used to clone (to get that error log) was ```git@github.com:SMAICP/aarch64-5.1.git```

**Comment by technoweenie** [comment]
So does it still fail if you run `git push github master` (replace "master" with the current branch)?  My hunch is that Git LFS is confused about not having an "origin" remote.  Or just "git push" is picking the remote with the `git://` URL.

**Comment by HashBang173** [comment]
I did a git push via ssh. I pushed it with ```git push -u origin master```.
The origin remote was git@github.com:SMAICP/aarch64-5.1.git

**Comment by technoweenie** [comment]
So you do have an origin remote?  I wonder why it doesn't show up in your `git lfs env` output?  Here's an example from one of my repositories:

```
$ git remote
gh-enterprise
origin

$ git remote show origin -n
* remote origin
  Fetch URL: git@github.com:github/git-lfs-test.git
  Push  URL: git@github.com:github/git-lfs-test.git
...

$ git remote show gh-enterprise -n   
* remote gh-enterprise
  Fetch URL: https://some-enterprise-server/technoweenie/git-lfs-test
  Push  URL: https://some-enterprise-server/technoweenie/git-lfs-test

$ git lfs env           
Endpoint=https://github.com/github/git-lfs-test.git/info/lfs
  SSH=git@github.com:github/git-lfs-test.git
Endpoint (gh-enterprise)=https://some-enterprise-server/technoweenie/git-lfs-test.git/info/lfs
```

I'm not really sure why I'm not seeing an "Endpoint=" line in your git lfs output.  This is what it looks like if I try to use your SSH remote url:

```
$ git remote add origin git@github.com:SMAICP/aarch64-5.1.git
$ git remote rm origin                                       
$ git lfs env
Endpoint=https://github.com/SMAICP/aarch64-5.1.git/info/lfs
  SSH=git@github.com:SMAICP/aarch64-5.1.git
```

What does `git lfs version` say?

**Comment by HashBang173** [comment]
I have git lts 0.5.1

**Comment by technoweenie** [comment]
Can you post your `.git/config` file so I can try to reproduce this?  Feel free to send it to technoweenie@github.com if you don't want it public.

**Comment by HashBang173** [comment]
started the process over and now it seems to be working...

**Comment by HashBang173** [comment]
new error log for https: https://gist.github.com/HashBang173/c6c6259b34a839592ca5

**Comment by technoweenie** [comment]
* What command are you using to push to HTTPS?
* What does `git lfs env` show?
* Do you have any lfs config values set?  `git config -l | grep lfs`

**Comment by HashBang173** [comment]
I am not pushing via https. I am pushing over ssh, but when I __clone__ via https it failes to download the large file. 

This command doesn't seem work properly with lfs: ```git clone https://github.com/SMAICP/aarch64-5.1.git```

**Comment by technoweenie** [comment]
Worked fine for me on `git-lfs/0.5.1 (GitHub; darwin amd64; git 2.3.0; go 1.3)`:

https://gist.githubusercontent.com/technoweenie/95f1bc1b0d29a1685404/raw/f08b01608ea3662ef89cf91d7cd3392cf73e54fe/whatever.log

Your error suggests that it's not making the correct Git LFS endpoint from the remote.  Git LFS takes HTTPS remote urls and converts them to a Git LFS endpoint:

```
$ git remote
origin

$ git remote show origin -n
* remote origin
  Fetch URL: https://github.com/SMAICP/aarch64-5.1.git
  Push  URL: https://github.com/SMAICP/aarch64-5.1.git

$ git lfs env
Endpoint=https://github.com/SMAICP/aarch64-5.1.git/info/lfs
LocalWorkingDir=/Users/rick/p/aarch64-5.1
LocalGitDir=/Users/rick/p/aarch64-5.1/.git
LocalMediaDir=/Users/rick/p/aarch64-5.1/.git/lfs/objects
TempDir=/Users/rick/p/aarch64-5.1/.git/lfs/tmp
```

If you're not seeing that, then there's some other configuration setting in use that I don't know about.

**Comment by technoweenie** [comment]
Did you get this resolved?  I'm curious what the problem was.
