### ISSUE TITLE
RPM installs

### ISSUE THREAD

**Issue by andyneff** [github/git-lfs#328]
I'm working on some rpm install for git-lfs, (Currently under andyneff/git-lfs@91b185b435e382a69598f61e6df8193ad4c1faf7) I eventually want to get it to work for the supported CentOS's (5, 6, 7), Fedora Versions as of July 2015 ( 21, 22, since 20 will be EOL by July), and maybe if I can EVER get to it, OpenSUSE... although I've never tried that or SLES. Any comments on that?

When I am done with this, would you like me to PR? If so, do you want a PR as soon as I am done with CentOS (this weekend I hope?) or just wait until all the stretch goals are done and do one PR?

(A little background of rpms, they are built using the rpmbuild command, so as you update your own build scripts, etc... only the few lines in the "spec" file need be updated, and rpmbuild will always be called to build the actual rpms.)

Side-note: Given the static nature of go executables, I can probably even make a generic set that can be compiled on any OS (since rpm is actually available on most OSes including Debian, etc...) so that as long as you build on a 64 bit ELF OS. Advantage is you can build the rpms from whatever Linux OS you are using for the releases, and Redhat OSes can install them... I think it will work?

**Comment by technoweenie** [comment]
I'd love to see rpm builds for Git LFS.  Anything that makes Git LFS easier for people to install and use, AND can be eventually automated on our end through cloud build servers or something. Smaller PRs are nice. :metal:

**Comment by technoweenie** [comment]
Thanks so much for taking this on!
