### ISSUE TITLE
I couldn't push code into github with git-lfs hook on git push

### ISSUE THREAD

**Issue by Sobrr** [github/git-lfs#333]
git-lfs is currently not completely supported by github (only allow part of the users). Now I couldn't push any of my changes because of that.

"
You're signed up for early access and invitations will be going out soon. We're excited about Git LFS too!
Docs: https://github.com/contact
error: failed to push some refs to 'https://github.com/Sobrr/iOS.git'
"

After I tried to uninstall git-lfs so that I can push my files in, there is this error. 
"git: 'lfs' is not a git command. See 'git --help'."

Where do I change the push command to the old one and bypass the git lfs command?

**Comment by rubyist** [comment]
Sorry for the trouble, you should be able to fix your pushes by removing the `.git/hooks/pre-push` file from your repository. This is where git is trying to run `git lfs` when you push.

We'll add some more documentation around uninstalling Git LFS as this is not very clear. Feel free to close this issue if this solves your problem, or if you run into any other problems just let me know how I can help. Thanks!

**Comment by technoweenie** [comment]
Blah, this sucks. Git LFS will put that file back. @sobrr: If it keeps happening, you can probably get away with throwing a dummy pre-push hook in there.

However, why is Git LFS trying to push anything? It shouldn't even try to contact the Git LFS API unless you've committed some Git LFS pointers in that repo.

**Comment by rubyist** [comment]
The problem, as I understand it, is that the git-lfs binary is uninstalled. The pre-push hook will always run, and if the git-lfs binary isn't there it will error out.

**Comment by technoweenie** [comment]
Oh right right. I was thinking of the larger issue. You shouldn't have to uninstall Git LFS just because not all of your repo remotes have support for it.

**Comment by rubyist** [comment]
This problem is fixed as of #339, a new push hook is installed that will allow git to continue pushing when the git-lfs binary is missing. Thanks for the report!

**Comment by shadowwalkersb** [comment]
I was having problems pulling even after deleting ```.git/hooks/pre-push```. Then, I removed the global git configs that Git LFS sets up following instructions in #316 . I am posting this, in case it is not addressed with #339 .

**Comment by Sobrr** [comment]
Hi @technoweenie, can you enable LFS for this account?

**Comment by technoweenie** [comment]
@Sobrr Can you open a new issue with details on your problem? It looks like Git LFS is enabled, but you're hitting some error that I can't see in the screenshot. I'm locking this old thread issue from further updates though since it's a very different problem.

**Comment by technoweenie** [comment]
LOL, well I just realized you opened this issue. Everyone has LFS access on github since last October though.
