### ISSUE TITLE
STDERR and STDOUT merged when making SSH requests

### ISSUE THREAD

**Issue by catphish** [github/git-lfs#343]
When making SSH requests, the `STDOUT` and `STDERR` responses from the server seem to get merged together and processed as response data.

It would be desirable if `STDOUT` were processed as data, but `STDERR` was printed to the user's console for information and debugging purposes. This would match the behaviour of Git itself.

**Comment by technoweenie** [comment]
That's a great idea. :+1:

**Comment by technoweenie** [comment]
Fixed in https://github.com/github/git-lfs/pull/718
