### ISSUE TITLE
Interested in more community stuff?

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#344]
Any interest in building up the Git LFS community more?

A hosted forum like [Discourse](https://discourse.org) could be used to move general discussion, proposals, and support requests away from the issue tracker.

A [Slack](https://slack.com/) chat room would be cool too. Let me know here or at technoweenie@github.com if you want an email invite to it. If popular, we'd probably setup some way for users to generate their own invitations, [like the Atom team has done](https://discuss.atom.io/t/join-us-on-slack/16638/2).

/cc @andyneff @Aorjoa @ChaseFlorell @ddanier @meltingice @michael-k @ssgelm @zeroshirts

**Comment by catphish** [comment]
I've dropped you an email but in case it gets lost, please send me any relevant invitations: charlie@atechmedia.com

**Comment by larsxschneider** [comment]
:+1: for a chat room.

**Comment by meltingice** [comment]
I'd like an invite to the Slack room please! meltingice8917@gmail.com

**Comment by technoweenie** [comment]
Ok, sent you all invites.

**Comment by ssgelm** [comment]
I'd be down for a slack room!

**Comment by technoweenie** [comment]
@ssgelm: Sure, just send your email to technoweenie@github.com.

**Comment by michael-k** [comment]
@technoweenie I've sent you an email ~24h ago :)

**Comment by technoweenie** [comment]
Doh, it was in my spam box. Invited!

**Comment by ssgelm** [comment]
@technoweenie invite sent.  thanks!

**Comment by Aorjoa** [comment]
:+1:  me please,,

**Comment by technoweenie** [comment]
We've started experimenting with https://gitter.im/github/git-lfs. It should hit all the same features we use in the current slack room, and then some:

* _Anyone_ can join easily.
* There's an [irc gateway](https://irc.gitter.im/).
* Private messages and rooms are still supported.

I really don't want to invite every single community member to Slack, and don't want to worry about managing [a tiny app just to let people email themselves an invite](http://atom-slack.herokuapp.com/).
