### ISSUE TITLE
commands/repos; leftovers from old integration tests?

### ISSUE THREAD

**Issue by michael-k** [github/git-lfs#357]
I didn't find anything that uses the repositories in `commands/repos`.  There are the cleanup scripts `script/clean-git-text-fixture` and `script/clean-git-text-fixtures` which clean them up.  The cleanup scripts are invoked from `script/fmt`, so no hint there either.

**Can the repos and the cleanup scripts be removed?**

If so, just merge in/cherry pick the commit mentioned below.  (In branch [michael-k/git-lfs@cleanup](https://github.com/michael-k/git-lfs/tree/cleanup))

**Comment by technoweenie** [comment]
Yup, I made a mental note this weekend to clean them up. Thanks for the reminder.
