### ISSUE TITLE
Step 2 fails in the [guidelines for contributing](https://github.com/github/git-lfs/blob/master/CONTRIBUTING.md).

### ISSUE THREAD

**Issue by aln787** [github/git-lfs#359]
I attempted to follow the  [guidelines for contributing](https://github.com/github/git-lfs/blob/master/CONTRIBUTING.md). The second step: "2. Configure and install the dependencies: script/bootstrap" from the script directory in the cloned repo (pwd shows ~/Development/tmp/git-lfs/script) fails, details shown below.

I executed this command:
```
./bootstrap 
```

but received this response:
```
./bootstrap: line 3: script/fmt: No such file or directory
stat script/*.go: no such file or directory
```

I am at commit 87264d01411046716bdf178da516e77cb958ed06 on the default branch (master).

I successfully followed the first step: "1. Fork and clone the repository"

```
git clone https://github.com/aln787/git-lfs.git
```

**Comment by ssgelm** [comment]
@aln787 The wording on that is a little unclear, but the script is intended to be run from the root of the project.  E.g.:
```
cd ~/Development/tmp/git-lfs
script/bootstrap
```

**Comment by aln787** [comment]
@ssgelm thanks for the clarification, trying that now!

**Comment by aln787** [comment]
@ssgelm that worked thanks again!
