### ISSUE TITLE
"hello world" not working

### ISSUE THREAD

**Issue by aleaverfay** [github/git-lfs#368]
I got the green light to start using github's git-lfs service, so I created a dummy repo with a dummy file, pushed it, and then tried to clone it elsewhere (same machine), but the file didn't download and I can't figure out how to turn the pointer file into an actual file.  Here's what I did.

1) install git lfs v 0.5.1 for amd64 linux
2) github -> create new repo
3) git clone that repo from github
4) git lfs track "*.pdb"
5) put a .pdb file into the repo directory
6) git add my.pdb 
7) git commit
8) git push
9) cd ~/temp; git clone that repo from github

The 2nd clone has my.pdb, but as a pointer file and not an actual file.  Is there a command I have to issue here to get my 2nd clone to download that file?  "git lfs ls-file" from the first repo says that git lfs is tracking the my.pdb file.

**Comment by technoweenie** [comment]
You need the smudge filter setup. This can be done per repo, but should be global so it applies to new clones:

```
$ git config --list --global | grep lfs
filter.lfs.clean=git lfs clean %f
filter.lfs.smudge=git lfs smudge %f
filter.lfs.required=true
```

Running `git lfs init` should add those config values for you. You only need to run it once for every user account of every computer that you use with a git repo using git lfs. This should be part of the install process.

If you have the smudge filter configured, does cloning give you any error messages?

**Comment by aleaverfay** [comment]
Thanks for getting back to me so quickly.

When I run the command you gave, it produced your output, but maybe because between the time when I cloned my repo the 2nd time and when I ran your command, I had re-run "git lfs init" in the off chance that it would change something.

It looked like the instal.sh file concludes by running git init lfs (and I ran "sudo bash install.sh" to install -- perhaps that was my mistake?  It looked like it was going to write to /usr/local), so it seemed like I wouldn't have to run that command myself.  (If I am any indication, your user base is going to be full of idiots who are going to do the wrong thing, so more thorough documentation would be awesome -- even the advice that you need to run "git lfs init" in non-sudo mode and once per user so that it registers.)

I cloned again just now, and this time it downloaded the my.pdb file. FWIW, running "git pull" after the "git lfs init" command did not download the file -- it'd be nice if there were some mechanism for fetching files w/o having to reclone.

**Comment by technoweenie** [comment]
Thanks for the feedback regarding the install process.

> it'd be nice if there were some mechanism for fetching files w/o having to reclone.

You can actually run `git checkout .` to do that. But Git LFS v0.5.2 will have a `git lfs fetch` command for exactly that purpose.
