### ISSUE TITLE
confused: error when push to repo own by another?

### ISSUE THREAD

**Issue by rBatt** [github/git-lfs#369]
I decided to try LFS on a GitHub repo owned by a user (@mpinsky) who does not yet have access to the trial of LFS. I installed on my machine, did some work (adding some kinda big .csv's), and then tried to push.

I then get the message:

```
Git LFS support is coming! Sign up for early access: https://github.com/early_access/git-lfs
Docs: https://github.com/contact
```

a whole bunch of times. Is this because the owner of the GitHub repo doesn't have the LFS trial yet, or is it likely that I'm doing something else wrong?

Regardless, what's the best way to abandon my attempted trial of LFS so that I can push my work? I tried using `untrack`, and I tried deleting the .gitattributes file. Neither worked. I'm still a bit of a git novice, so it's possible I'm missing something obvious. Thanks.

**Comment by michael-k** [comment]
It might be enough to delete `.git/hooks/pre-push`.  But only if your commit weren't made with files tracked by git-lfs.  If so, you need to rewrite the regarding commits.

@technoweenie We need an uninit command.

**Comment by michael-k** [comment]
@technoweenie We need an uninit command.

**Comment by dotnetCarpenter** [comment]
+1 for an uninit command. This just bit me.

**Comment by rBatt** [comment]
@michael-k thanks for the detailed solution to try. How do I get git lfs to stop tracking a file?

**Comment by michael-k** [comment]
By deleting `.gitattributes` (one per directory) or by removing the respecting line from it.  There's also `.git/info/attributes`.

There's also the `untrack` command, but I wouldn't rely on that.

**Comment by rBatt** [comment]
I got everything to work here. Thank you so much.

I deviated slightly from your instructions. Basically I took all the large files I had, and .zip them up into something small enough for github. Then I used `rebase` to go back and move a .gitignore *.csv as one of the first commits, and deleted the history of ever commit involving the initialization of the lfs. Then I used `git rebase` (could have done it at the same time if this wasn't so exploratory for me) to go back and `edit` the commits involving the .csv's (many of these commits also made changes to code that I wanted to save), and each of those steps just did a `git rm` for the problematic file. I can now push. Thank you. @mpinsky

**Comment by michael-k** [comment]
Glad I could help.

csv files shouldn't be a problem for git. The delta compression is pretty good. When the csv files change over time, it's definitely a good idea to commit the raw files instead of zip files. With zip files, git must save every seperate file. (Consider reading `man git-gc`.)

Git's problem with large files has to do more with binary files than with file size.

**Comment by rBatt** [comment]
The .csv's were too big to upload to github. Otherwise I would be simply
tracking them with git :-/

Good points though, thanks for sharing the wisdom.
