### ISSUE TITLE
Unable to find the .exe application

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [github/git-lfs#371]
Hi guys, :smile: 

I tried to use the **Git extension for versioning large files [*v0.5.1*](https://github.com/github/git-lfs/releases/download/v0.5.1/git-lfs-windows-amd64-0.5.1.zip)** program.
I run `install.bat` but it reports permanently "*Unable to find git.exe, exiting...*". :unamused: 

The `git-lfs.exe` program is in the same folder. What's wrong :question:  :question:  :question: 

Can somebody help me, please?

Yours,
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by michael-k** [comment]
`git.exe` must be in your path.

Here is the relevant snippet from `install.bat`:
```
:: Check if git.exe is in the user's path before continuing
where /q git.exe
if %errorlevel% neq 0 (ECHO Unable to find git.exe, exiting... & EXIT /b %errorlevel%)
```

So, I guess you don't have git installed.  At least not in the way needed by `install.bat`.

**Comment by SuriyaaKudoIsc** [comment]
I have Git installed.

**Comment by michael-k** [comment]
What is the output of `where /q git.exe` when run in a shell?

**Comment by SuriyaaKudoIsc** [comment]
My answers:

* **What is the output of where `/q git.exe` when run in a shell?**
*Git:* `"C:\Program Files (x86)\Git\bin\sh.exe" --login -i`
*Git Shell:* `C:\Users\Suriyaa\AppData\Local\GitHub\GitHub.appref-ms --open-shell`

* **Which version do you have installed?**
*Git:* 1.9.5.msysgit.0
*Git Shell:* 1.9.5.github.0
*GitHub for Windows:* "I Wear Goggles When You Are Not Here" (2.14.5.1) cc018b2

* **Do you have the maintained build installed or any third party software (like Github for Windows)?**
*Maintained build version 1.9.5 of Git for the Windows platform* and *GitHub for Windows* (include also *Git Shell*)

* **Does it help if you adjust the path, i.e. add the directory where your git.exe is located?**
No. I tried to run it from Git folder but it doesn't work. Then I tried to run it under `Git\cmd` and `Git\lib`. But it still does not work.

**Comment by technoweenie** [comment]
Since you have GitHub for Windows, it should have an option to install command line tools, which includes Git LFS. Did you try that?

**Comment by SuriyaaKudoIsc** [comment]
No. How should I do it?

**Comment by SuriyaaKudoIsc** [comment]
Hi guys,

I found the problem!

I tired to run `install.bat` but it's still not ffunction.

Then I copied the `git-lfs.exe` file into **`Git/bin`** folder and see it works!

![screenshot 2015-07-05 13 31 24](https://cloud.githubusercontent.com/assets/5073946/8511500/4d7936de-231a-11e5-8287-c818f7b98591.png)

**Comment by technoweenie** [comment]
Ah, thanks for the update. The Git LFS windows installer could definitely use some work.
