### ISSUE TITLE
Use git-lfs with libgit2

### ISSUE THREAD

**Issue by ChristophM2000** [github/git-lfs#375]
Hi,

We are a software company with a customer that uses Microsoft TFS for version control. In the main time we work completely disconnected from the customer on our side on a part of the software and sync the code changes e.g. once in a week. So we decided to use git-tfs bridge to pull from TFS server into a git repository that is than cloned by our developers. This works very good.
But we have a performance problem. Our customer has put some very large (>1gb) binary files in TFS, which has no problem with that. E.g. the complete MS SQL Server Setup files or some binary dependencies. Some files, like the SQL Server setup, can be ignored by "git-tfs pull", but some binary dependencies are needed needed to run the project. So in the end the repository has a size of >20gb and git gets very very slow.

So the idea is to use git-lfs for that binaries. Which works if we manually create a git repos and "git add" the whole project. Every tracked binary goes in lfs.
But cause we use git-tfs to create the git repos from TFS this does not work, cause git-tfs uses libgit2 to work on the git repos and that does not support the smudge and clean filters of standard git. They support smudge and clean filters but they seam to be coded in a different way. See https://github.com/libgit2/libgit2/issues/1473.

Does git-lfs support working with libgit2 smudge and clean filters or maybe in foreseeable future?

Thanks and greetings,
 Christoph

**Comment by ryansimmen** [comment]
Our team at Microsoft is currently working to add the proper smudge and clean filter support to libgit2.  Once this work is complete libgit2 will be fully operational with GitHub's git lfs client.

**Comment by Jericho25** [comment]
You can also try what comes in july...       #jgaj

**Comment by ChristophM2000** [comment]
Hi

Thanks for your answer.
Is there a timeframe when your contribution to libgit2 is ready to use?

Thanks,
 Christoph

**Comment by whoisj** [comment]
@ChristophM2000 I'm one of the developers working on TFS and Visual Studio Git integration. We plan to include support for tools like Git-LFS with the first big update for VS2015. I don't have information like timing or dates, but I hope that helps.

**Comment by ChristophM2000** [comment]
Thank you very much, that gives us something to hope for.

**Comment by svermeulen** [comment]
Was this sucessful?  In other words, does libgit2 support smudge and clean filters for use with git lfs?
