### ISSUE TITLE
Synchronization with standard unix ssh-server (e.g. via rsync)

### ISSUE THREAD

**Issue by perrette** [github/git-lfs#379]
I really like the way git-lfs integrates with git with minimal changes to the standard git workflow, and requires basically only one setup by project, and not by clone (unlike git-annex: "git annex init; git annex initremote etc...; "). The one thing that deters me, though, is the difficulty of setting up the server (as other users already noted in previous issues).

The use-case is as follow:
- supercomputer (let us call it "cluster") with remote access via ssh, where files can be stored and shared among users (unix filesystem). Among other things, it allows file exchange via rsync and git. No way of setting up a specific git-lfs server on the "cluster" (it is not made for that, no authorization from the IT)
- a remote, central git repository (on the "cluster" or gitlab or github, it should work for any of these cases)
- several git clones (on various local machines, and/or directly on the "cluster"), with access to the central git repo, and to the cluster
- the cluster seems like the right place to store large binary files, regardless of where the central git repo is located 

In this case which is common is a research environment, the sad thing is that the ssh/git infrastructure is perfectly operational, but it seems impossible to push files with git-lfs on the "cluster". The only option seems to setup a brand new server somewhere else. Locally I found https://github.com/l3iggs/docker-lfs-test-server and https://github.com/artemkin/git-lfs-server work fine, but it feels overkill with normal git works transparently with "file:///....". But for the general case (multiple users from different machines => public server), the setup is not trivial for the lambda user (me).

I notice that git-annex offers the neat alternative solution of [synchronizing the files via rsync](http://git-annex.branchable.com/special_remotes/rsync/). I was wondering whether anything like that was possible or planned for git-lfs, or whether there are workaround for this use-case? Or have I simply missed something?

Thanks for the good work.

**Comment by perrette** [comment]
I just saw #378 PR, I suppose that is what I was asking for...

**Comment by technoweenie** [comment]
In your scenario, how do the git clones know where in the supercluster to get their files? Are you using some kind of central coordination, consistent hashes, something like NFS?

**Comment by perrette** [comment]
The root of the data repository is indicated in the .gitconfig, the files under it use consistent hashes. In the case of git-annex, if the data directory is located on cluster.domain.de under /path/to/gitrepos/mycode.git-annex-rsync, each file looks like that:

    1b8/29b/SHA256E-s655103--9f9fd17da2835b214d8517a2b1dc29d4b527d32bdc0873e2622931a0c4d387b8.nc/SHA256E-s655103--9f9fd17da2835b214d8517a2b1dc29d4b527d32bdc0873e2622931a0c4d387b8.nc

Where the file in the directory tree is the same as under the clone's .git/annex/objects (but the prefix varies, for some reason). In the clone's config, there is also an annex-uuid next to annex-rsyncurl, which seems to be used to determine the prefix (directory tree) of the file. I do not quite understand while the tree is not simply based on the first 2x2 characters of the hashcode (without the need for a uuid), but that is not fundamental.

The corresponding .git/config is:

    [remote "origin"]
            url = cluster.domain.de:/path/to/gitrepos/mycode.git
            fetch = +refs/heads/*:refs/remotes/origin/*

    [remote "data"]
            annex-rsyncurl = cluster.domain.de:/path/to/gitrepos/mycode.git-annex-rsync
            annex-uuid = 31999a27-3bb7-4688-94fe-24af056ee7bf

To be consistent with current lfs config, I guess the simplest option would be, for the second line:

    [lfs]
            rsyncurl = cluster.domain.de:/path/to/gitrepos/mycode.git-lfs-rsync

That's it. And determine a convenient way of building the tree (e.g. using the first letters of the hash code). So git-lfs would check if lfs.rsyncurl variable is defined and synchronize using rsync (via ssh) if it is the case, instead of sending a HTTP(S) server request.

I had not realized this needed these assumptions about how to store the data (which indeed a server does not need, beyond the requests' API), but it seems to me worthwhile having such a feature (since it is simpler to set a ssh server than an actual HTTP server, at least in the unix world).

**Comment by ttaylorr** [comment]
This is something that would definitely be neat. It should be possible to implement within the new [custom transfer API](https://github.com/github/git-lfs/blob/master/docs/custom-transfers.md).

**Comment by aleb** [comment]
What would be a good place in the git-lfs repository for a custom transfer agent supporting rsync?
Are there examples of custom transfer agents?

**Comment by ttaylorr** [comment]
@aleb I don't know offhand whether there are public implementations of custom transfer agents that support `rsync(1)`, but I can point you to an example that we use during integration tests in LFS: ([source][1]).

[1]: https://github.com/git-lfs/git-lfs/blob/master/test/cmd/lfstest-customadapter.go

**Comment by aleb** [comment]
@ttaylorr I implemented a custom transfer agent which rsyncs the files, but I can't figure out how to use it.

https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-config.5.ronn says that a custom transfer is invoked only if the server accepts the agent's name:

> * `lfs.customtransfer.<name>.path`
> 
>   `lfs.customtransfer.<name>` is a settings group which defines a custom
>   transfer hook which allows you to upload/download via an intermediate process,
>   using any mechanism you like (rather than just HTTP). `path` should point to
>   the process you wish to invoke. The protocol between the git-lfs client and
>   the custom transfer process is documented at
>   https://github.com/git-lfs/git-lfs/blob/master/docs/custom-transfers.md
> 
>   <name> must be a unique identifier that the LFS server understands. When
>   calling the LFS API the client will include a list of supported transfer
>   types. If the server also supports this named transfer type, it will select it
>   and actions returned from the API will be in relation to that transfer type
>   (may not be traditional URLs for example). Only if the server accepts <name>
>   as a transfer it supports will this custom transfer process be invoked.

It would be useful if there is a way to force a custom transfer agent such that it's used directly when a file needs to be uploaded or downloaded. Do you think it's possible, or will there always be a need for a git-lfs server?

**Comment by technoweenie** [comment]
> It would be useful if there is a way to force a custom transfer agent such that it's used directly when a file needs to be uploaded or downloaded. Do you think it's possible, or will there always be a need for a git-lfs server?

This isn't on our roadmap, but we're open to working with someone else that wants to contribute the change.

**Comment by aleb** [comment]
It is now possible to have a custom transfer agent used as standalone (without a git-lfs server). 

To fully take advantage of rsync's capabilities, the rsync process would be started at the same time as the agent, passed transfer requests, and the agent should wait until the rsync process is done.

I'm not sure what exactly the agent should do with the `{ "event": "terminate" }` step mentioned in the [spec](https://github.com/git-lfs/git-lfs/blob/master/docs/custom-transfers.md): 
- Does the adapter wait for each request to be complete/failed before giving the next one?
- Does the adapter continue to listen to progress and success/failure messages after it sends the "terminate" message?

I'll implement something and see how it works.

**Comment by ttaylorr** [comment]
> Does the adapter wait for each request to be complete/failed before giving the next one?

Yes. [[source](https://github.com/git-lfs/git-lfs/blob/v2.2.1/tq/custom.go#L284)]

> * Does the adapter continue to listen to progress and success/failure messages after it sends the "terminate" message?

It does not appear so. [[source](https://github.com/git-lfs/git-lfs/blob/v2.2.1/tq/custom.go#L247-L251)]

**Comment by aleb** [comment]
Indeed, I just noticed this in the [spec](https://github.com/git-lfs/git-lfs/blob/master/docs/custom-transfers.md#stage-2-0n-transfers):

> Once a transfer request is sent to the process, it awaits a completion response before sending the next request.

This would have to be changed to take full advantage of rsync's features (so it authenticates only once). Something like: adapter sends all the requests, then sends "terminate", then waits for progress/success/failure until all the requests are done. This would also allow a custom transfer agent to have some parallelism of its own (when using concurrent=false meaning a single custom transfer agent instance is started).

What do you think?

**Comment by ttaylorr** [comment]
> What do you think?

This seems like a great idea, and I think it is certainly something that is totally possible. I don't have anything like this on my roadmap at the moment, but I'd be more than happy to help provide some pointers for getting started.

**Comment by aleb** [comment]
Please do!

**Comment by ttaylorr** [comment]
@aleb thinking more about this, I think that instead of changing the request/reply nature of the custom transfer adapter protocol, we should instead change the `*tq.Adapter`'s API. Specifically, instead of `DoTransfer()` returning an `error` indicating a successful transfer or not, it should return a `<-chan error` which indicates a transfer's success _eventually_.

That being said, I think that this would have implications in how the `*tq.TransferQueue` itself works, which would require more discussion. For example, the way the `*tq.TransferQueue` works right now is:

1. Accept items until either `tq.Wait()` is called, or enough items have been read to fill one batch.
2. Run the batch, returning items that didn't transfer successfully.
3. Append those items into the next batch.
4. See step 1.

The above approach has the invariant that retried items from the last batch are prioritized before new items can be accepted into subsequent batches. I don't think we would be able to make that guarantee anymore if the `*tq.adapterBase` type returned a non-blocking response.

**Comment by aleb** [comment]
I don't understand why you propose to change `*tq.TransferQueue` so drastically. Even with the change you proposed, I think the protocol used by the custom transfer adapter to communicate with the agents would have to be changed anyway. We could start with that? The nice part with changing the request/reply nature of the custom transfer adapter protocol is that the old adapters are still supported. 

> The above approach has the invariant that retried items from the last batch are prioritized before new items can be accepted into subsequent batches. I don't think we would be able to make that guarantee anymore if the `*tq.adapterBase` type returned a non-blocking response.

Not sure why it matters. Anyway, I don't see why it would not be possible. If it needs to remember the order of the requests it sent, it can be done. Then before preparing the next batch it can block until all the previous requests are done.

I did not find in the documentation how it works now: If there are 3 agent processes running, and there are 201 requests, the first will get a batch of 100, another a batch of 100 and the third a batch of 1? Trying to make sense on why the order matters.

**Comment by ttaylorr** [comment]
> > The above approach has the invariant that retried items from the last batch are prioritized before new items can be accepted into subsequent batches. I don't think we would be able to make that guarantee anymore if the `*tq.adapterBase` type returned a non-blocking response.
> 
> Not sure why it matters. Anyway, I don't see why it would not be possible. If it needs to remember the order of the requests it sent, it can be done. Then before preparing the next batch it can block until all the previous requests are done.

Hm, I agree that this shouldn't matter as much now as it once did. The idea behind blocking `Add()` behind a complete execution of all transfers in a given batch was that it would apply backpressure to the repository scan and therefore consume less memory. We now consume a trivial amount of memory per object, so this should be OK.

> I did not find in the documentation how it works now: If there are 3 agent processes running, and there are 201 requests, the first will get a batch of 100, another a batch of 100 and the third a batch of 1? Trying to make sense on why the order matters.

Not quite -- the concept of "agent process" is a somewhat confusing here. Only one thread is ever sending a batch API request (i.e., you will never see >1 batch API requests occur at once). The "agent process" I believe that you are referring to are the adapters, and they eagerly consume work from the list of available work, i.e.:

1. A batch request is issued, and a response is given back
2. Until there are no items left in the response:
3. Each running transfer adapter (the amount of these is determined by `lfs.concurrenttransfers`) takes one item from the response, and uploads/downloads/etc it.
4. See step 2.

**Comment by aleb** [comment]
Ok, then I'll try to hack something?
