### ISSUE TITLE
Build scripts broken

### ISSUE THREAD

**Issue by joerg** [github/git-lfs#388]
I just tried compiling LFS in a clean Ubuntu 14.04 (trusty) Docker container and got an error. Something about package includes (sorry, I don't know much about GO). I got similar errors trying to build it on a Debian 8 machine. To reproduce use the following:

```
docker run -i -t --entrypoint /bin/bash ubuntu:trusty
apt-get install git
git clone https://github.com/github/git-lfs.git
cd git-lfs/
script/debian-build
```

which gives

```
<output omitted>
+ ./script/bootstrap
script/build.go:13:2: cannot find package "github.com/github/git-lfs/lfs" in any of:
	/root/.gvm/gos/go1.4.2/src/github.com/github/git-lfs/lfs (from $GOROOT)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/github/git-lfs/lfs (from $GOPATH)
++ echo FAIL
FAIL
```

On CentOS 7 following the same steps I get: 

```
script/build.go:13:2: cannot find package "github.com/github/git-lfs/lfs" in any of:
	/usr/lib/golang/src/github.com/github/git-lfs/lfs (from $GOROOT)
	($GOPATH not set)
FAIL
```

**Comment by michael-k** [comment]
Debian (and derivates): see #383
CentOS: see #313 an #332
Meta: see #281 and https://gitlfs.slack.com (via #344)

**Comment by michael-k** [comment]
```
apt-get install git
git clone https://github.com/github/git-lfs.git
```
Update the lines above as follows:
```
apt-get install git
export GOPATH=$PWD/go
mkdir -p go/src/github.com/github
cd go/src/github.com/github
git clone https://github.com/github/git-lfs.git
```

**Comment by joerg** [comment]
Thanks. I was able to build it, before I read your posts, by syminking a lot of the vendor stuff etc.

**Comment by mikemcquaid** [comment]
I've submitted a fix for this in #458.

**Comment by terion-name** [comment]
same error here

**Comment by terion-name** [comment]
Even like @michael-k wrote, the same:
```
can't load package: package github.com/github/git-lfs/commands: cannot find package "github.com/github/git-lfs/commands" in any of:
	/root/.gvm/gos/go1.4.2/src/github.com/github/git-lfs/commands (from $GOROOT)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/github/git-lfs/commands (from $GOPATH)
can't load package: package github.com/github/git-lfs/lfs: cannot find package "github.com/github/git-lfs/lfs" in any of:
	/root/.gvm/gos/go1.4.2/src/github.com/github/git-lfs/lfs (from $GOROOT)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/github/git-lfs/lfs (from $GOPATH)
script/build.go:15:2: cannot find package "github.com/github/git-lfs/lfs" in any of:
	/root/.gvm/gos/go1.4.2/src/github.com/github/git-lfs/lfs (from $GOROOT)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/github/git-lfs/lfs (from $GOPATH)
++ echo FAIL
FAIL
```

**Comment by unixnewbie** [comment]
Hello,

I am trying to rpm package git-lfs-1.1.0 using a custom SPEC file .  I get the following error during the build. I don’t know anything about go. Could you please help ?

Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.F57yah
+ umask 022
+ cd /home/rpmuser/rpmbuild/BUILD
+ cd git-lfs-1.1.0
+ GOARCH=amd64
++ pwd
+ GOPATH=/home/rpmuser/rpmbuild/BUILD/git-lfs-1.1.0
+ ./script/bootstrap
Using go1.4.2
# _/home/rpmuser/rpmbuild/BUILD/git-lfs-1.1.0
./git-lfs.go:23: cannot use lfs.ClearTempObjects (type func() error) as type func() in argument to once.Do
./git-lfs.go:36: cannot use lfs.ClearTempObjects (type func() error) as type func() in argument to once.Do

2016/02/24 09:10:31 exit status 2
exit status 1
error: Bad exit status from /var/tmp/rpm-tmp.F57yah (%build)


Thanks
