### ISSUE TITLE
[win8] fatal: failed to launch browser

### ISSUE THREAD

**Issue by dotnetCarpenter** [github/git-lfs#394]
`git lfs --help`
Launching default browser to display HTML ...
fatal: failed to launch browser for C:\Program Files (x86)\git/doc/git/html//git-lfs.html

Windows 7 Professional SP 1

**Comment by technoweenie** [comment]
So `--help` is not a Git LFS thing (though it should be):

```
# run git-lfs through git
$ git lfs --help
No manual entry for git-lfs

# run git-lfs directly
$ git-lfs --help


Usage: 
  git-lfs [flags]
  git-lfs [command]
....
```

We need to beef up the install process to include man pages. I have no clue how that even works on Windows though.

**Comment by danilaml** [comment]
It fails for me for every git command.
```
git mv --help
Launching default browser to display HTML ...
fatal: failed to launch browser for G:\Users\myusername\AppData\Local\GitHub\PortableGit_c7e0cbde92ba565cb218a521411d0e854079a28c\mingw32/share/doc/git-doc/git-mv.html
```
For some reason only on my Desktop, on my Laptop it works fine. Maybe newer installation?

**Comment by dotnetCarpenter** [comment]
npm uses man pages on posix systems and open a browser to display the same content in HTML format on Windows. I suspect git does the same. Perhaps this is only a path issue? `C:\Program Files (x86)\git/doc/git/html//git-lfs.html` has both forward slash and backward slash + double forward slash.

**Comment by danilaml** [comment]
@dotnetCarpenter in my case the problem was that there is no default app specified for opening .html files.

**Comment by technoweenie** [comment]
Added to the roadmap in #1438.
