### ISSUE TITLE
reliability in syncing assets

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#4]
What should we do in the event of failures?  There are bound to be issues when uploading a bunch of data over HTTPS.  

* Progress updates in the console for...
  * [x] Downloading
  * [x] Uploading
* Retries and resumes...
  * [ ] Downloading (Range header)
  * [ ] Uploading ([tus.io](http://tus.io/))

**Comment by andyneff** [comment]
In cases where we have a partial http/https download (for whatever reason) is

    git checkout .

The best way to resume/retry right now?

**Comment by technoweenie** [comment]
That is the best way currently.  We're looking into other options.  

When you say a partial http/https download, what do you mean exactly?  Is the Git data fully fetched and checked out to the working directory?  Do you just need to download specific files using Git LFS?  There is a clunky way to fix this with `git lfs smudge`, but we're looking into adding something like `git lfs get` that can download files outside of the git attributes smudge filter that runs on git checkouts.

**Comment by andyneff** [comment]
I had half my binaries as text pointers still (never downloaded from the lfs server locally) and half were proper binaries

    git status 
    git lfs status
    git diff

Did NOT tell me which ones were good or not. The only way I knew which ones were good was by the output on my screen/the lfs logs. 

How could I have used ```git lfs smudge```? Or would that have only helped if the files were already pulled locally?

**Comment by technoweenie** [comment]
If you pass a Git LFS pointer to the smudge filter as STDIN, it downloads the file if necessary, and dumps the actual contents to STDOUT.  

Let's say foo/bar.zip is a text pointer file.  Here's how you could write to it.

```
# verify that the file is a text pointer
$ cat foo/bar.zip
version https://git-lfs.github.com/spec/v1
oid sha256:ef9a6cea10508990aeb4bfabdf3ce9d7545e9d9c4f4a735682144fc60fd49e3a
size 123

$ cat foo/bar.zip | git lfs smudge > foo/bar.zip
```

**Comment by technoweenie** [comment]
Closing this. There are some retry capabilities now. You can also run "git lfs pull".
