### ISSUE TITLE
git lfs fetch requests more metadata than it needs from the batch endpoint

### ISSUE THREAD

**Issue by ryansimmen** [github/git-lfs#430]
When lfs.batch is turned on, git lfs fetch will send a request to the batch endpoint requesting metadata for every tracked file in the repository.  Instead, git lfs fetch should only request metadata for clean pointer files that need smudging.

**Comment by rubyist** [comment]
:+1: for fetch we can definitely filter out things we already  have.

**Comment by technoweenie** [comment]
I think this will be fixed in #527:

> `fetch` only adds missing or incorrect objects to the download queue, not all of them. This improves the progress reporting; previously fetch would appear to be trying to download all objects referenced at a ref then only have to download the missing ones as the download queue figured out they were already local. Also means fetch reports nothing at all if you're completely up to date already, instead of reporting "(0 of 1000 files)".
