### ISSUE TITLE
Question: LFS-ONLY REPO ??

### ISSUE THREAD

**Issue by boustanihani** [github/git-lfs#433]
Is there a way to declare a git-lfs-only repository?

I mean if the repository will only contain large (or maybe binary) files without any source-code... In that case there is no need to track specific files but all files added to the repo should be managed by git-lfs automatically. Is this currently possible?

**Comment by Aorjoa** [comment]
You mean a directories, when you edit your file in there the file auto commit and then push to your remote repository, right?

**Comment by boustanihani** [comment]
No mean without the need to do ```git lfs track ...``` and all files added to git will be automatically managed by git-lfs.

**Comment by technoweenie** [comment]
Try `git lfs track "*.*"`. I don't know if the git attributes file will support that, though.

**Comment by boustanihani** [comment]
@technoweenie should this always be called again when new files are added ?

**Comment by whoisj** [comment]
Would not adding * binary filter=lfs in the .gitattributes not achieve this?

**Comment by boustanihani** [comment]
I don't know I'm new to git-lfs... I would like to create a repo were all files are managed by git-lfs, I am not planning to include any source code in this repo :bowtie:

**Comment by technoweenie** [comment]
@boustanihani nope, the track command simply adds an entry to `.gitattributes`. That file decides what files to run through the Git LFS filter.

**Comment by epriestley** [comment]
`git lfs track '*'` appears to produce the desired behavior:

```
$ git lfs track '*'
Tracking *
```

After running this command, adding files with various names all triggered the filter and activated LFS locally.

This seems like an unusual use case, but I can shoot you a pull to mention it in the documentation if you think it's merited.

**Comment by epriestley** [comment]
Actually, this is somewhat more subtle/involved: I think doing this will make `git-lfs` track `.gitattributes` as an LFS file, smudge/clean it, and break itself.

**Comment by whoisj** [comment]
> Actually, this is somewhat more subtle/involved: I think doing this will make git-lfs track .gitattributes as an LFS file, smudge/clean it, and break itself.

Ha! Awesome - same should be true of ignore. `git-lfs track` should prudently refuse to track said files: ".gitattributes", ".gitignore", and ".gitmodules" as they are special case handled by Git itself.

**Comment by jreniel** [comment]
Old thread but what saved me was:
```bash
git lfs track '*'
echo ".gitattributes -filter=lfs -diff=lfs -merge=lfs -text" >> .gitattributes
```
