### ISSUE TITLE
Can't push to github (pre-receive hook declined)

### ISSUE THREAD

**Issue by rvi** [github/git-lfs#434]
Hi,

This bug may be related to #333 

I just tried `git lfs`, and it doesn't worked for me...
What I did : 
- Install lfs (0.5.2)
- git lfs track myFramework.framework
- git add 
- git commit
- git push 

Here is the error : 

```logs
Counting objects: 20, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (20/20), done.
Writing objects: 100% (20/20), 52.06 MiB | 7.52 MiB/s, done.
Total 20 (delta 5), reused 0 (delta 0)
remote: error: GH001: Large files detected.
remote: error: Trace: f22735321d76092fa67a1011835dfdcc
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File mySDK.framework/mySDK is 185.09 MB; this exceeds GitHub's file size limit of 100.00 MB
To git@github.com:company/repo.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@github.com:company/repo.git'
```

```
$ git lfs version
git-lfs/0.5.2 (GitHub; darwin amd64; go 1.3)
```

**Comment by technoweenie** [comment]
That's unrelated. Your file "mySDK.framework/mySDK" is stored in Git, not Git LFS, and exceeds GitHub's file size limit.

**Comment by rvi** [comment]
So how can I store it in Git LFS ?

**Comment by technoweenie** [comment]
`git lfs track "*.ext"` will add an entry to your `.gitattributes` to store "ext" files. From then on, any time an "*.exe" file is added to Git, it will be stored in Git LFS. Existing commits do not change though. If you have older commits trying to add the file to Git, you will have to squash those commits before pushing.

**Comment by rvi** [comment]
Ok thanks, I understood what went wrong. I did that : `git lfs track mySDK.framework`
It worked well (at least it shows `Tracking mySDK.framework`...)

But I just tried to do `git lfs track **/mySDK`

And now on the git push I've got this : 
```
(0 of 1 files) 0 B 2s
Git LFS support is coming! Sign up for early access: https://github.com/early_access/git-lfs
Docs: https://github.com/contact
error: failed to push some refs to 'git@github.com:company/repo.git' 
```

Is it possible for you to bypass the waiting queue for my account ? :D Would be awesome !! :)

__A nice feature would be to know that tracking is not working for a directory.__

Thanks for your help !!

**Comment by technoweenie** [comment]
> Is it possible for you to bypass the waiting queue for my account

Possibly. Let me know which account to look at via support@github.com.

> A nice feature would be to know that tracking is not working for a directory.

How do you see this working?

**Comment by rvi** [comment]
> How do you see this working?

 I did that : `git lfs track mySDK.framework`
it logs `Tracking mySDK.framework...``
But it fail on the git push.

**Comment by rubyist** [comment]
Is `mySDK.framework` really a directory? Some things on OSX masquerade as files but are really directories, I think `.framework` are often that. If that's the case, the `track` command won't handle that well because the way `.gitattributes` works doesn't handle that very well.

**Comment by rvi** [comment]
Yes `mySDK.framework` is a directory.

**Comment by kamoljan** [comment]
Hi @rubyist , so what to do then?
I also have huge `.framework` dirs.

**Comment by kamoljan** [comment]
@rubyist 

The problem was that `.framework` is a dir not a file.
I had to find a big file inside my framework dirs and add them to `git-lfs`.
Everything works ok!

**Comment by Chandraa-Mahadik-au8** [comment]
Hi.. getting the same error as @rvi But My large file is .mp4 n Files are getting added.. committed too.. But git push shows error.. remotes rejected.. .. n failed to push.. ..
