### ISSUE TITLE
Push and Pull with git-lfs personal server

### ISSUE THREAD

**Issue by danimasa** [github/git-lfs#435]
Hello folks

I pushed files in my own git repository created with [lfs-test-server](https://github.com/github/lfs-test-server) with "git lfs push" and it works perfectly. But, if I try to push with "git push" command I get the error:

"RCP failed: result = 52, HTTP code = 0"

How can I push files that isn't tracked by git lfs?

One more question: when I tried to clone the repository in other PC the repository arrived like an empty repository. If I try to fetch and pull I get the message:

"Your configuration specifies to merge with the ref 'master' from the remote, but no such ref was fetched."

How can I get the files in the lfs server?

Thank you

**Comment by technoweenie** [comment]
Those are both Git problems. The first looks like you're having issues talking to your git server:

http://stackoverflow.com/questions/18436812/why-do-i-get-error-rpc-failed-result-52-http-code-0-fatal-the-remote-end-h

The second implies something is wrong with your local repository config: 

http://stackoverflow.com/questions/4297795/configure-git-so-that-git-pull-instead-of-git-pull-origin-master

**Comment by danimasa** [comment]
Hello technoweenie

Really both problems are about git, I tried to correct it increasing the post buffer but it doesn't work for me, the error continues the same. Searching I don't found any other explanation about that, I'll try to change the protocol from http to ssh to correct it. Do you know another way to correct it?

Thanks
