### ISSUE TITLE
git cherry-pick results in conflicts between file contents and file references

### ISSUE THREAD

**Issue by eric-brechemier** [github/git-lfs#438]
I started using Git LFS in a repository in a new branch, which I rolled back from master before the introduction of a large file. After configuring Git LFS to track these large files, I started to replay the history commit by commit using git cherry-pick -n (to review changes before committing them).

The conflicts occur because on one hand the patch works with actual file contents while on the other hand Git LFS works with a pointer description which gets updated with each new version.

Could Git LFS detect the discrepancy and avoid the conflict somehow?

**Comment by technoweenie** [comment]
I don't think Git LFS has an opportunity to detect and avoid conflicts. I've added this to our list of bugs.

**Comment by technoweenie** [comment]
Added to the roadmap in #1438
