### ISSUE TITLE
Is it (or will it be) possible to execute `diff` on the backend?

### ISSUE THREAD

**Issue by ivotron** [github/git-lfs#439]
More generally, I'm interested in knowing if the goal is to have the backend be format-agnostic, i.e. only working with binary files. Or would it ever be possible for it to "understand" about multiple formats (e.g. a big CSV file or binary JSON)? The use case I have in mind is to execute a remote `diff` of two versions of an lfs-tracked file and get meaningful results instead of just a yes/no answer

**Comment by technoweenie** [comment]
You'll be able to view diffs of Git LFS objects on GitHub, provided it's a format we support (PSD, PDF, etc). CSV and JSON are interesting though. If the CSV is big enough to bother throwing into Git LFS, I'm not sure how we could display a diff (on the command line or on the site) in a way that would be readable.

This is something I'm interested in, but certainly not a [priority](https://github.com/github/git-lfs/blob/master/ROADMAP.md) at this point.

**Comment by ivotron** [comment]
I see. And is there a list of supported formats somewhere?

The main motivation for my question was to see how suitable is git-lfs for versioning data science projects, which usually involve tabular (CSV, JSON, dataframes) or n-dimensional (netcdf/hdf) formats. I encountered the following from the [dat](https://github.com/maxogden/dat/blob/master/docs/whitepaper.md) white paper:

>  ... Git takes upwards of 40 minutes to respond to a simple command [7]. To fix this performance problem with Git, there is an extension called the 'Git Large File Storage (LFS)' released in 2015 [8], and Git-Annex [9], written in Haskell. We believe these extensions are not designed well for data science use cases, which often require support for features such as versioning at the row-level, real-time data feeds, partial replication or parallel downloading. 

Seems to me (correct me if I'm wrong) that these issues could potentially be addressed in git-lfs?

For visualizing tabular diffs, [this](http://okfnlabs.org/blog/2013/08/08/diffing-and-patching-data.html) describes what people working in these areas would like to have.
