### ISSUE TITLE
404 link on git-lfs.github.com

### ISSUE THREAD

**Issue by rossfeller** [github/git-lfs#443]
Couldn't find the source for [git-lfs.github.com](https://git-lfs.github.com/) to submit a PR, but the link for the "API Specification" currently points to `https://github.com/github/git-lfs/blob/master/docs/api.md` which 404's. It probably should point to `https://github.com/github/git-lfs/tree/master/docs/api`.

**Comment by technoweenie** [comment]
Thanks for the report!  Fixed in #441 :)
