### ISSUE TITLE
LFS resyncing all my assets

### ISSUE THREAD

**Issue by Leviathan1753** [github/git-lfs#445]
The LFS system seems to be reuploading files it doesn't need to be uploading.

What I'm experiencing is this:
1)  I had master branch synced with origin with about 3gb of stuff in the LFS system
2)  I had worked on an alt branch some and pushed several commits (just code)
3)  I started pushing this alt branch
4)  It was taking a long time...
5)  I eventually realized it was resyncing the 3gb of stuff, despite it already being on the server
6)  I stopped the push
7)  Switched to master
8)  Merged it with the tip of my alt branch, so they were at the same spot
9)  Pushed master, that finished instantly
10)  Swapped back to my alt branch (same location as master, which was synced to origin again)
11)  Started pushing
12)  Got the same long push where it was wanting to sync all my assets again.

Here's a quick pic of the end situation.  (Pushing Justin or Justin2 branch causes the long asset upload, despite the commit already being on the server).  The pic is from SourceTree (as they have the fantastic tree view.  You guys need this), but i've attempted this from Github for Windows, as well as a shell.

![lfs-bug](https://cloud.githubusercontent.com/assets/4665186/8390688/eb3e0052-1c67-11e5-9efa-97c4874e5bca.png)

Update:
Looking at the current issues, I'm wondering if my bug is a result of https://github.com/github/git-lfs/issues/438 , as I do remember doing a cherry pick recently

**Comment by rubyist** [comment]
How many asset files are in your repository? Git LFS shouldn't be re-uploading the data, but if there are a lot of files it can take some time to push a new branch. When Git LFS sees that git is pushing up some commits, it scans those commits for LFS files. Git LFS then has to ask the server whether or not it has the file, which results in an HTTP request. Unfortunately, this is an HTTP request per file, so if there are a lot of files there ends up being a lot of HTTP requests, and those add up.

What I think happened in your scenario above (thank you for the very clear steps, it was very useful!) was that when you stopped the push in 6, Git first pushed the commit objects to the repo, but got interrupted so it was not able to push the branch object. Then in 9 those commits had been merged in so Git didn't have to send any commits up, meaning Git LFS didn't run and didn't need to verify any files. However, in 11 when trying to push the interrupted branch Git must have had to re-negotiate everything, causing those files to be re-scanned by Git LFS, making it verify that they were on the server.

If you're comfortable digging into this further, you can try pushing branch from the command line while setting a variable, like this: `GIT_CURL_VERBOSE=1 git push origin Justin2`. You _should_ see an HTTP `POST` per LFS file, but you _should not_ see an HTTP `PUT` (where the actual data transfer occurs) per file. If you _do_ still see a `PUT` per file, we can dig into this a little deeper with your repo.

That was a longwinded way of saying the Git LFS protocol is chatty, and a little inefficient in this scenario. There is work being done to greatly reduce the number of network calls when pushing to only one or two, depending on the number of files being checked, which should land in the [0.6.0 release](https://github.com/github/git-lfs/issues/426). Please let me know, though, if you are still seeing extra `PUT` calls when there shouldn't be.

**Comment by Leviathan1753** [comment]
We have a few thousand LFS items, I believe.  We're making a game, so binary assets are a large part of our project.  This is one of the reasons I'm so excited to see LFS taking off, as it was an extreme pain to do it previously (we had a simlinked pair of SVN + git repos before)

I don't think it's the HTTP request-per-file issue you're mentioning.  Reasons for this are:
1)  I let that long push execute.   During that long push, the cmd line was spitting out messages that looked very much like an upload (kb rate, etc).  It didn't look like it was just doing a comparison check
2)  Now that the long push is over, new commits push up really quick... so the existing LFS content doesn't seem to be causing a huge lag due to any HTTP request spam (or if that's happening for my files, it goes quick enough)

It definitely seemed like a reupload, but maybe that was due to something funky I did like stopping a midpush, triggering a bad state that required a reupload?

Anyway, if it happens again, I'll be sure to report back.

Also, I tried to run the GIT_CURL_VERBOSE = 1, but my GitHub for Windows started Powershell didn't like it.  term not recognized as the name of a cmdlet, function, or script file, etc etc.   I'm not too well versed in the art of cmdline, so if that's a simple issue, I'm unaware of how to address it.

**Comment by Leviathan1753** [comment]
So, I just preformed another cherry-pick and it functioned properly.

I can't seem to trigger this again.

I'm going to guess it had some interaction with the fact that origin/Justin was from before when the Assets were commited, so merging that old branch into the now-LFSed branch might have caused the need for some resyncing/merging shinnanigans?  Not sure.  
Now that all our branches are now post-LFS-init, I doubt I'll see it again.

Either way, seems to have gone away.  I'll report if I ever encounter it again, though.

**Comment by rubyist** [comment]
With thousands of files you will definitely see a large delay when pushing a new branch, and the counter just pretends like it's uploading the files it's really skipping. It's not a very optimal experience. The batch stuff in 0.6.0 should definitely improve things for repos with a lot of LFS files, even when there are cherry picking shenanigans going on.

**Comment by Leviathan1753** [comment]
Lovely!  Keep up the good work!
Can't tell you how much of a godsend LFS has been so far.
