### ISSUE TITLE
Git LFS Cloning a repository is always giving the pointer files 

### ISSUE THREAD

**Issue by peddinenis** [github/git-lfs#455]
I have configured Artifactory3.9.1 as LFS server and pushed couple of large binaries. I can see pointer files added to Git Repostory and actual binaries are pushed to Artifactory server. I tried to clone the Git Repo from a different place but I am always getting pointer files and the actual files is not downloading.

The below was my gitconfig
[lfs]
   url = "http://xyx:8081/artifactory/api/lfs/Git-LFS-Test" 

Can any one please tell me how to get the actual files during the cloning of Repo.

**Comment by rubyist** [comment]
When cloning from a different place, do you mean a different account or machine entirely? If so, have you run `git lfs init` on the place you're cloning from?

**Comment by peddinenis** [comment]
I tried from different machine and also from a different directory on the same machine. I have run 
git lfs init  command though I am getting the same issue.

![git lfs issue](https://cloud.githubusercontent.com/assets/2292235/8477445/42678efa-2098-11e5-96dc-a0b629a6315a.png)

If you see the above picture other than .txt files all are pointer files

**Comment by peddinenis** [comment]
Any resolutions or comments for this issue.

**Comment by technoweenie** [comment]
If you're able to clone without any error messages, then it's likely that Git LFS is not being triggered at all. This means either Git LFS isn't setup or your version of Git is too old.

Some commands to try:

* `git lfs env` - This should tell what version of Git and Git LFS you're using.
* `git config --global -l` - This spits out your global git config to ensure Git LFS is setup.

**Comment by peddinenis** [comment]
I got the below results when I run these commands


git lfs env

Endpoint=http://rtp-wasl-bldex:8081/artifactory/api/lfs/Git-LFS-Test
LocalWorkingDir=
LocalGitDir=
LocalMediaDir=
TempDir=C:\cygwin64\tmp\git-lfs

git lfs config

git-lfs/0.5.1 (GitHub; windows amd64; git 2.1.4; go 1.3)


git config --global -l

user.name=Srinivas Peddineni
user.email=speddine@cisco.com
core.editor=emacs
filter.lfs.clean=git lfs clean %f
filter.lfs.smudge=git lfs smudge %f
filter.lfs.required=true
lfs.url=http://rtp-wasl-bldex:8081/artifactory/api/lfs/Git-LFS-Test


Is there any thing incorrect in these config.

**Comment by technoweenie** [comment]
That looks fine.

What happens when you do `GIT_TRACE=1 git clone {repo-url}`?  That should dump out some extra debug info that you can throw in gist or any pastebin.

**Comment by peddinenis** [comment]
I got the below output 

$ GIT_TRACE=1 git clone ssh://git@stash-eng.cisco.com:7999/git/bms-lfs-test2.git
17:28:30.652465 git.c:349               trace: built-in: git 'clone' 'ssh://git@stash-eng.cisco.com:7999/git/bms-lfs-test2.git'
Cloning into 'bms-lfs-test2'...
17:28:30.813833 run-command.c:341       trace: run_command: 'ssh' '-p' '7999' 'git@stash-eng.cisco.com' 'git-upload-pack '\''/git/bms-lfs-test2.git'\'''
remote: Counting objects: 20, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 20 (delta 6), reused 0 (delta 0)
17:28:33.662866 run-command.c:341       trace: run_command: 'index-pack' '--stdin' '-v' '--fix-thin' '--keep=fetch-pack 10792 on SPEDDINE-WS' '--check-self-contained-and-connected'
17:28:33.677863 exec_cmd.c:134          trace: exec: 'git' 'index-pack' '--stdin' '-v' '--fix-thin' '--keep=fetch-pack 10792 on SPEDDINE-WS' '--check-self-contained-and-connected'
17:28:33.730652 git.c:349               trace: built-in: git 'index-pack' '--stdin' '-v' '--fix-thin' '--keep=fetch-pack 10792 on SPEDDINE-WS' '--check-self-contained-and-connected'
Receiving objects: 100% (20/20), done.
Resolving deltas: 100% (6/6), done.
Checking connectivity... 17:28:33.870624 run-command.c:341       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all'
17:28:33.886621 exec_cmd.c:134          trace: exec: 'git' 'rev-list' '--objects' '--stdin' '--not' '--all'
17:28:33.923614 git.c:349               trace: built-in: git 'rev-list' '--objects' '--stdin' '--not' '--all'
done.

**Comment by technoweenie** [comment]
What does `git lfs track` say then?

**Comment by peddinenis** [comment]
$ git lfs track
Listing tracked paths

I don't see any tracked paths the above command displaying.  Do we need
tracked paths while cloning a a repo,if so where to add them I tried by
tracking the paths from the place where I am cloning the repo but no use.

**Comment by technoweenie** [comment]
You should have been adding file extensions the first time you add that file to git:

```
$ git lfs track "*.zip"
$ git add foo.zip
$ git add bar.zip
```

There's no problem with tracking whatever file extensions you're storing now, however.

Once that's done, I think you can run `git checkout .` to replace the Git LFS pointers with the real object.

**Comment by peddinenis** [comment]
After I clone the Repo , I run the checkout command from inside the cloned
folder, but I got the below message.

$ git checkout
Your branch is up-to-date with 'origin/master'.


I really appreciate your time to help me.

**Comment by technoweenie** [comment]
FWIW I meant:

    $ git checkout .

But if it works without the `.`, that's cool too :)

> I really appreciate your time to help me.

No prob!

**Comment by peddinenis** [comment]
Looks like there is a communication gap with my previous post, sorry for
that,


The issue is not resolved, git checkout doesn't replaced the pointer files
with original files.

**Comment by technoweenie** [comment]
Did you try `git checkout .` with the period?

If that didn't work, grab Git LFS v0.5.2 and try `git lfs fetch master`.

**Comment by peddinenis** [comment]
After installing Git LFS v0.5.2 when I run git lfs init    It is
giving the below error message, Is this ok?

The clean filter should be "git-lfs clean %!f(MISSING)" but is "git
lfs clean %!f(MISSING)"
git lfs initialized

Looks like git lfs fetch master is giving some results for me, but I
see it is malfunctioning while asking the username and password for
LFS server.

I have 5 binaries but it downloaded only two files and asking for
username, password for so many times.

$ git lfs fetch master
(0 of 5 files) 0 B
sername for 'http://rtp-wasl-bldex:8081': admin
Password for 'http://admin@rtp-wasl-bldex:8081':
Username for 'http://rtp-wasl-bldex:8081': admin
Password for 'http://admin@rtp-wasl-bldex:8081':
Username for 'http://rtp-wasl-bldex:8081': admin
Password for 'http://admin@rtp-wasl-bldex:8081':
(0 of 5 files) 793.13 KB
(1 of 5 files) 837.42 KB
sername for 'http://rtp-wasl-bldex:8081': Username for
'http://rtp-wasl-bldex:8081': admin
Password for 'http://admin@rtp-wasl-bldex:8081': password
Password for 'http://password@rtp-wasl-bldex:8081': admin
Password for 'http://admin@rtp-wasl-bldex:8081':
Username for 'http://rtp-wasl-bldex:8081':
Username for 'http://rtp-wasl-bldex:8081':

Password for 'http://rtp-wasl-bldex:8081': Password for
'http://password@rtp-wasl-bldex:8081':

(2 of 5 files) 837.42 KB 3m42s

speddine@SPEDDINE-WS /C/work-space/New folder/bms-lfs-test2 (master)
$ git lfs fetch master
(0 of 5 files) 0 B
sername for 'http://rtp-wasl-bldex:8081': admin
Password for 'http://admin@rtp-wasl-bldex:8081':
Username for 'http://rtp-wasl-bldex:8081': admin
Password for 'http://admin@rtp-wasl-bldex:8081':
Username for 'http://rtp-wasl-bldex:8081': admin
Password for 'http://admin@rtp-wasl-bldex:8081':
(0 of 5 files) 505.20 KB
sername for 'http://rtp-wasl-bldex:8081': Username for
'http://rtp-wasl-bldex:8081': Username for
'http://rtp-wasl-bldex:8081': admin
Password for 'http://admin@rtp-wasl-bldex:8081': password
Password for 'http://password@rtp-wasl-bldex:8081': password
Password for 'http://password@rtp-wasl-bldex:8081':
Username for 'http://rtp-wasl-bldex:8081':
Username for 'http://rtp-wasl-bldex:8081':

Password for 'http://rtp-wasl-bldex:8081': Password for
'http://password@rtp-wasl-bldex:8081':

(2 of 5 files) 505.20 KB 1m34s

speddine@SPEDDINE-WS /C/work-space/New folder/bms-lfs-test2 (master)
$

**Comment by technoweenie** [comment]
> After installing Git LFS v0.5.2 when I run git lfs init    It is
giving the below error message, Is this ok?

```
The clean filter should be "git-lfs clean %!f(MISSING)" but is "git
lfs clean %!f(MISSING)"
git lfs initialized
```

Yes, that's fine. I'm actually working on improving that message now.

> Looks like git lfs fetch master is giving some results for me, but I
see it is malfunctioning while asking the username and password for
LFS server.

Git LFS should be saving the password on successful requests against your Git LFS server. It may be acting funny since you don't have a real host name though. Or, it may be an issue with artifactory.

How is `rtp-wasl-bldex` set? is that an `/etc/hosts` entry or custom dns?

**Comment by peddinenis** [comment]
yeah it is an    /etc/hosts entry

**Comment by technoweenie** [comment]
Do you have a git credential cacher setup? This is a common issue for users that push through SSH.

https://help.github.com/articles/caching-your-github-password-in-git/

**Comment by peddinenis** [comment]
I don't have a git credentials cacher setup, but the issue we are seeing is asking the same credentials again and again for LFS server(Artifactory).

**Comment by technoweenie** [comment]
Yes, that's because you don't have something caching it. Assuming you're using a set username/password (as opposed to some expiring token) with Artifactory, it should only ever ask you once. Would netrc support help? Git LFS doesn't include it, but there is an issue for it: #171.

With GitHub, you pass your HTTPS or SSH auth to our server, and don't have to worry about custom auth through another system. It doesn't look like you're using GitHub, but I say this to let you know that it IS built into the Git LFS specification. I'm hoping that if Git LFS gets more popular, other Git hosts start integrating built-in support too. 

I had never heard of Artifactory, but I'm really flattered that they added Git LFS support so quickly. So I am interested in making sure Git LFS works with them (and other 3rd party Git LFS servers).

**Comment by gouchangjiang** [comment]
Maybe you should delete the directory then clone it again. And then with the command "git lfs fetch", that works for me.

**Comment by jamesdalg** [comment]
I am having this issue and it is making git actions not correctly check my software package because git is only pulling pointers upon cloning, from what I can tell. It checks fine on a regular machine.

**Comment by bk2204** [comment]
GitHub Actions doesn't enable Git LFS by default.  You'd need to adjust your `actions/checkout` workflow item as described in [the documentation](https://github.com/actions/checkout).
