### ISSUE TITLE
git-lfs should make use of a previous repo when I use git clone --reference

### ISSUE THREAD

**Issue by tlbtlbtlb** [github/git-lfs#459]
Using --reference [previous-repo] makes many checkouts 10x faster. But with lfs files, it still downloads them from the server. I wish the --reference argument would also hint to the lfs system to look there for files it can reuse.

**Comment by technoweenie** [comment]
That's a great idea. While it's not currently on our immediate roadmap, this is definitely an interesting smaller feature that some can tackle.

**Comment by jwittner** [comment]
I'm all about this as well, :+1: It would help with CI - Jenkins Git Plugin, for example, allows using reference repos on clone operations.
