### ISSUE TITLE
Error accessing media when checkout files

### ISSUE THREAD

**Issue by demonyangyue** [github/git-lfs#470]
Hi there,

I use LFS 0.5.1 with Github Enterprise, when checkout binaries, always get the error `Error accessing media ...`, and here is the details about the error log:

```
git-lfs smudge jvms/SunOS/sunjre160_07-solaris64.bin
LocalWorkingDir=/test/official_build/3rdParty_UNIX
LocalGitDir=/test/official_build/3rdParty_UNIX/.git
LocalMediaDir=/test/official_build/3rdParty_UNIX/.git/lfs/objects
TempDir=/test/official_build/3rdParty_UNIX/.git/lfs/tmp
GIT_DIR=.git
GIT_PREFIX=

Error accessing media: jvms/SunOS/sunjre160_07-solaris64.bin (e337bf5319cb28171ad7d02addf10a12dd2bb98795948262662eb3a988a429de)

Error downloading /test/official_build/3rdParty_UNIX/.git/lfs/objects/e3/37/e337bf5319cb28171ad7d02addf10a12dd2bb98795948262662eb3a988a429de.
Server error: http://<github_enterprise_url>/Analytics/3rdParty_UNIX.git/info/lfs/objects/e337bf5319cb28171ad7d02addf10a12dd2bb98795948262662eb3a988a429de from HTTP 502
Request:Content-Length=54835
Request:Etag="5538b9e2-d633"
Endpoint=http://<github_enterprise_url>/Analytics/3rdParty_UNIX.git/info/lfs
URL=GET http:/<github_enterprise_url>/Analytics/3rdParty_UNIX.git/info/lfs/objects/e337bf5319cb28171ad7d02addf10a12dd2bb98795948262662eb3a988a429de
Request:Content-Type=text/html
Request:Server=GitHub.com
Request:Date=Wed, 08 Jul 2015 09:35:53 GMT
Response:User-Agent=git-lfs/0.5.1 (GitHub; linux amd64; git 2.2.2; go 1.3)
Response:Authorization=--
Response:Accept=application/vnd.git-lfs+json; charset-utf-8
Status=502 Bad Gateway
goroutine 16 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/errors.go:85 +0x89
github.com/github/git-lfs/lfs.Errorf(0x2b95185001b0, 0xc208001560, 0x79c160, 0x0, 0x0, 0x0, 0x0, 0xb3)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/errors.go:29 +0x62
github.com/github/git-lfs/lfs.Error(0x2b95185001b0, 0xc208001560, 0x2b95186a5538)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/errors.go:17 +0x52
github.com/github/git-lfs/lfs.defaultError(0xc20802e630, 0x71fbe0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:363 +0x151
github.com/github/git-lfs/lfs.handleResponse(0xc20802e630, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:325 +0x102
github.com/github/git-lfs/lfs.doHttpRequest(0xc208028dd0, 0xc20800f9b0, 0x1, 0x2)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:246 +0x215
github.com/github/git-lfs/lfs.doApiRequestWithRedirects(0xc208028dd0, 0xc20800f9b0, 0x2b95186a57e8, 0x0, 0x4, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:261 +0x44
github.com/github/git-lfs/lfs.doApiRequest(0xc208028dd0, 0xc20800f9b0, 0xc20804a33a, 0x40, 0xc208028dd0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:296 +0x8e
github.com/github/git-lfs/lfs.Download(0xc20804a33a, 0x40, 0x0, 0x0, 0x2b95186a5978, 0x2)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/client.go:110 +0xca
github.com/github/git-lfs/lfs.downloadFile(0x2b9518504318, 0xc208036008, 0xc208034080, 0x7fff41e0c8f5, 0x25, 0xc20804a300, 0x7a, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/pointer_smudge.go:45 +0x1e8
github.com/github/git-lfs/lfs.PointerSmudge(0x2b9518504318, 0xc208036008, 0xc208034080, 0x7fff41e0c8f5, 0x25, 0x0, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/pointer_smudge.go:31 +0x300
github.com/github/git-lfs/lfs.(*Pointer).Smudge(0xc208034080, 0x2b9518504318, 0xc208036008, 0x7fff41e0c8f5, 0x25, 0x0, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/lfs/pointer.go:44 +0x73
github.com/github/git-lfs/commands.smudgeCommand(0x98d180, 0xc208000f10, 0x1, 0x1)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/command_smudge.go:59 +0x819
github.com/spf13/cobra.(*Command).execute(0x98d180, 0xc208000f00, 0x1, 0x1, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:355 +0x17c
github.com/spf13/cobra.(*Command).findAndExecute(0x98d780, 0xc20800e010, 0x2, 0x2, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:334 +0xd3
github.com/spf13/cobra.(*Command).Execute(0x98d780, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:408 +0x7b0
github.com/github/git-lfs/commands.Run()
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:80 +0x2a
main.main()
        /Users/rick/github/git-lfs/cmd/git-lfs/git-lfs.go:8 +0x1a
```

The repository uses LFS to manage many huge binaries, but always failed to checkout some binaries.
Any help would be greatly appreciated. Thanks!

**Comment by demonyangyue** [comment]
The current workaround is:

```bash
$ rm <the_missing_binary>
$ git checkout <the_missing_binary>
```

Which will trigger the smudge filter and force LFS to download the binary again. Then the binary will be successfully downloaded, replace the placeholder in work space.

But since this repository is used by all engineers in our company, manually fix the missing binaries after    
each clone would not be acceptable.

**Comment by technoweenie** [comment]
If you're using Git LFS v0.5.2, you can also use `git lfs fetch` to do that.

We're working on improvements to the checkout process. Better error handling is definitely part of that. Thanks for the report!

**Comment by emiilsd** [comment]
Hi,

This issue is still unresolved. Just posting so others can see this. When googling for the error message, only one link was found. :laughing: 

`git checkout feature/some-branch`
`Downloading test/fixtures/images/image_1.jpg (149.29 KB)`
`Error downloading object: test/fixtures/images/image_1.jpg`

OS version  = `3.19.0-49-generic #55~14.04.1-Ubuntu x86_64 x86_64 x86_64 GNU/Linux`
Git version = `2.7.1`
git-lfs version = `1.1.1`

**Comment by technoweenie** [comment]
@emiilsd: Can I get some more info? That's a pretty generic error message that could mean many things. Try running with `GIT_TRACE=1`.

**Comment by emiilsd** [comment]
Well, I did a fresh install so can't check anything
.
Ok, so the first thing - I followed the installation steps and tried installing `git-lfs` with bash script. After that I ran `sudo apt-get update && sudo apt-get install git-lfs` and I get error message `E: Unable to locate package git-lfs`.
So I installed `git-lfs

**Comment by emiilsd** [comment]
Installed `git-lfs` through tar.gz. Went to my project, tried

    $ rm <the_missing_binary>
    $ git checkout <the_missing_binary>

and received this error:

    Downloading image.jpg (149.29 KB)
    Error downloading object: image.jpg (76d83cea369c4160ce08f96d916e3af316920e9fd39dd7ef2478cb88131093ce)

    Errors logged to /home/<user>/<project>/.git/lfs/objects/logs/20160211T100624.481431389.log
    Use `git lfs logs last` to view the log.
    error: external filter git-lfs smudge %f failed 2
    error: external filter git-lfs smudge %f failed
    fatal: image.jpg: smudge filter lfs failed

Log file:
    
    git-lfs/1.1.1 (GitHub; linux amd64; go 1.5.3; git 7de0397)
    git version 2.7.1

    $ git-lfs smudge image.jpg
    Error downloading object: image.jpg (76d83cea369c4160ce08f96d916e3af316920e9fd39dd7ef2478cb88131093ce)

    exit status 1
    goroutine 1 [running]:
    github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/errors.go:557 +0x80
     github.com/github/git-lfs/commands.logPanicToWriter(0x7f395d0c71e8, 0xc820030178, 0x7f395d0c7bc0, 0xc820011f60)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:184 +0xf7f
     github.com/github/git-lfs/commands.logPanic(0x7f395d0c7bc0, 0xc820011f60, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:148 +0x421
     github.com/github/git-lfs/commands.handlePanic(0x7f395d0c7bc0, 0xc820011f60, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:123 +0x4e
     github.com/github/git-lfs/commands.LoggedError(0x7f395d0c7bc0, 0xc820011f60, 0x96a3a0, 0x21, 0xc820127c98, 0x2, 0x2)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:73 +0x82
     github.com/github/git-lfs/commands.smudgeCommand(0xb5cfa0, 0xc820011c30, 0x1, 0x1)
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_smudge.go:77 +0xd89
     github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xb5cfa0, 0xc820011b80, 0x1, 0x1, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x403
      github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xb5dfe0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x46a
      github.com/github/git-lfs/commands.Run()
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:88 +0x23
     main.main()
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:34 +0x12e

     ENV:
     LocalWorkingDir=/home/<user>/<project>
     LocalGitDir=/home/<user>/<project>/.git
     LocalGitStorageDir=/home/<user>/<project>/.git
     LocalMediaDir=/home/<user>/<project>/.git/lfs/objects
     TempDir=/home/<user>/<project>/.git/lfs/tmp
     ConcurrentTransfers=3
     BatchTransfer=true
     GIT_DIR=.git
     GIT_PREFIX=

**Comment by emiilsd** [comment]
OK, so we got it working!

First of all, we're using GitLab and Let's Encrypt CA. Maybe something there is the problem.
Here are the config that worked for me that wasn't set up automatically for me but was for a colleague:

    lfs.batch=true
    lfs.url=https://git.<domain>.<tld>/<group_name>/<project_name>.git/info/lfs/objects/batch
    lfs.url=https://git.<domain>.<tld>/<group_name>/<project_name>.git/info/lfs
    lfs.https://git.<domain>.<tld>/<group_name>/<project_name>.git/info/lfs/objects/batch.access=basic

We think that first and second config line isn't needed but we aren't sure.

**Comment by skakri** [comment]
To summarize, this works with self-hosted GitLab with Let's Encrypt (?):

    git config lfs.batch true
    git config lfs.url https://git.domain.tld/group-name/project-name.git/info/lfs

This may help someone although this seems to be different issue than original one.
