### ISSUE TITLE
[Bug] Repeated asking for username and password under SSH

### ISSUE THREAD

**Issue by tomspilman** [github/git-lfs#474]
I'm running into repeated requests for my password and username even with credential caching enabled.

I'm on Windows.  I've tried both from the dos command line and git bash.  

![capture](https://cloud.githubusercontent.com/assets/103522/8599391/c4a3f1e6-2625-11e5-958e-2b6ff665c2e7.JPG)

Notice the weird wrapping with the `E` on the right side of the command window.  That does not happen normally when i'm using git to commit changes.

Also I tried the same sequence entering wrong information...  wrong password, wrong user name... and it looks almost identical in output.  Doubting myself I fetched from a different git repo and everything worked correctly.

**Comment by tomspilman** [comment]
A few other things I've tried.

I noticed I was running v0.5.1 of LFS and the GitHub email said I should be running v0.5.2.  So i installed from the link provided in the email.  No change in the behavior.

**Comment by technoweenie** [comment]
Do you remember what was different about the first time where the "enter passphrase for key" message doesn't include linebreaks?

**Comment by tomspilman** [comment]
> Do you remember what was different 

Nothing that I could tell.

I did notice when it asked me for my username it would omit the first typed letter... so I would have to type `ttomspilman` and not `tomspilman`.  That made me thing maybe the same is happening for the password, but even repeating the first character of my password didn't seem to change things.

**Comment by tomspilman** [comment]
Also this was a new empty repo I created via the GitHub site.  I cloned using SSH originally... made two local commits, the second of which included the LFS files... then pushed.

So I tried again... this time I cloned using HTTPS.  I made one commit and pushed and things seemed to work correctly.  The credential caching must have worked as it didn't ask me for my password and/or username.

I'll give this all another try tonight with a test repo using SSH again.

**Comment by technoweenie** [comment]
Git credential caching is strictly for HTTP requests. I think it's your ssh agent that handles the passphrase. This is why I asked for a separate issue.

**Comment by tomspilman** [comment]
@technoweenie - Ahh...  that makes more sense now.  Still something that should have worked.

**Comment by tomspilman** [comment]
So now i'm unsure if Git really stored by large binary files using LFS.  

The repo browser looks identical to any other via the GitHub website.  Our billing page says 0% of bandwidth used and 0% of storage space used.

Is there a way to check that for certain that LFS was used for storage?

**Comment by technoweenie** [comment]
> Still something that should have worked.

Definitely agreed.

> Is there a way to check that for certain that LFS was used for storage?

`git lfs ls-files` will list Git LFS tracked files locally. We don't have an admin view on the website now.

**Comment by technoweenie** [comment]
> Our billing page says 0% of bandwidth used and 0% of storage space used.

We have periodic background jobs that scan logs for usage, so it may not be up to date yet. But I'm happy to confirm on our server if you like.  Feel free to hit up support@github.com if you want to take this private.

We can keep discussing the SSH issue here of course. That's a bug of the open source Git LFS client.

**Comment by tomspilman** [comment]
> We don't have an admin view on the website now.

Actually I was able to sort of verify it by looking at the details of the commit on the website.  It shows "Git LFS file not shown" where the diff would normally be.

**Comment by gurugray** [comment]
There is a bug in logic when we are using GH enterprise.

First we authorize for object thru ssh https://github.com/github/git-lfs/blob/release-0.5/lfs/client.go#L553 and getting valid Auth-header. (in `newApiRequest()`)

Then we are going for meta on API-call with this header in `doApiRequest()` https://github.com/github/git-lfs/blob/master/lfs/client.go#L114
And then GH return no headers, but with valid no-credentials required URl (with token GET-parameter)

Then we going to download the object itself, but in https://github.com/github/git-lfs/blob/master/lfs/client.go#L651 we are just check headers and they are empty, so there we have prompt for credentials.

I think we should keep auth-header thru all `object-action` sessions, like [Download()](https://github.com/github/git-lfs/blob/master/lfs/client.go#L108)

Or, might be a better solution, we should ask for credentials only if server response with 401 header with current request.

**Comment by gurugray** [comment]
this bug is really annoying, so please fix it in next version :)

**Comment by shuhrat** [comment]
+1

**Comment by technoweenie** [comment]
> Or, might be a better solution, we should ask for credentials only if server response with 401 header with current request.

Git LFS v0.6.0 will do this with servers that support the new API endpoint. 

Thanks for the report!

**Comment by gurugray** [comment]
It's great, but there are still many GH Enterprise installation.
And I think git-lfs should work with servers which support an old API endpoints.

**Comment by gurugray** [comment]
I think my case is closed by #611 but I didn't check yet.
How about you guys?

**Comment by technoweenie** [comment]
I'm QAing #611 today, hoping to ship Git LFS v0.6.0 this week. Also, I intend to backport our server work to the next enterprise 2.2 and 2.3 releases.

**Comment by gurugray** [comment]
great!

**Comment by technoweenie** [comment]
Hey @gurugray: Did v0.6.0 or v1.0.0 resolve your SSH auth issues?

**Comment by gurugray** [comment]
Yes, it is! Thanks again.
We have new issue on the way of integration git-lfs to our infrastructure, but it's on the GHEnterprise side this time.

**Comment by technoweenie** [comment]
Cool, closing this. Feel free to open a new git-lfs issue or send something to https://github.com/contact or Enterprise Support. Whatever you think is most appropriate :)
