### ISSUE TITLE
Pushing initial big repo error

### ISSUE THREAD

**Issue by topherredden** [github/git-lfs#477]
I get about 90% complete pushing my repo (around 8gb in size) and eventually get this error repeated:

Check that you have proper access to the repository
Authorization error: https://github-cloud.s3.amazonaws.com/alambic/media/1147554
35/6a/c1/6ac1d55906de0237337b1b703e767fef7fe94bdba6b269db239f426a0189b8f1?actor_
id=1283957

**Comment by technoweenie** [comment]
The good news is that if you retry the push, it will pick up where it left off again. The `git lfs pre-push` command will check every file, and skip the upload if it's already on the server.

The bad news is that it looks like you made a request with an expired S3 token. The strange thing is that the client should be making the S3 request almost immediately after getting the token. So I'm not sure how it could be expired. Could you try another push with more detailed logging, and post the deets to a Gist or pastebin?

    $ GIT_CURL_VERBOSE=1 git push origin master

Make sure to scrub any `Authorization` header lines.

**Comment by topherredden** [comment]
I'll give this a try, but it never appears to start where it left off. I tried about 5 times before posting :(

**Comment by topherredden** [comment]
There is quite a lot to paste, what is worth showing?

For example this is in the last couple failed attempts (near the end before the error spam I pasted above):

<Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the current time is too large.</Message><RequestTime>20150710T164330Z</RequestTime><ServerTime>2015-07-10T16:59:13Z</ServerTime><MaxAllowedSkewMilliseconds>900000</MaxAllowedSkewMilliseconds><RequestId>788C471F0F7E12ED</RequestId><HostId>I3ojd7j1ayq09ftEW8o6ASfgXunYVYfiXlTkfg7cy298ub7peGFLx4vNYzCjR0/8</HostId></Error>>

This is after about 55mins pushing.

**Comment by technoweenie** [comment]
@topherredden That's exactly what I'm looking for. I'd like to match that S3 request up with the one that generated the s3 token. The S3 error should be coming from a request like:

    PUT https://github-cloud.s3.amazonaws.com/alambic/media/1147554
35/{OID}?actor_
id=1283957

That 64-char OID value is important. There should be a corresponding request that gets the s3 token. It should look something like:

    POST https://github.com/{user}/{repo}.git/info/lfs/objects

The OID value from the erroring S3 request should be in the JSON request body of a matching POST. I'd like to see what time both requests were made.

Since this is a GitHub.com issue, and not a Git LFS issue necessarily, you're welcome to send the log to support@github.com. I'll be the one helping you there too :)

Also, what does `git lfs env` say? If it doesn't have the Git LFS version, what does `git lfs version` say too?

**Comment by topherredden** [comment]
```
$ git lfs env
git-lfs/0.5.2 (GitHub; windows amd64; go 1.3)
git version 1.9.5.msysgit.1
```

While trying to find the OID value from an error, I noticed this as well:
```
API rate limit exceeded for topherredden.
```

I found this PUT
```
Error for PUT https://github-cloud.s3.amazonaws.com/alambic/media/114755435/2b/f4/2bf486172bc0329a6bbc5a7d1649f78638ec380d43d0a51e243f23b8d82d68ea?actor_id=1283957

Put https://github-cloud.s3.amazonaws.com/alambic/media/114755435/2b/f4/2bf486172bc0329a6bbc5a7d1649f78638ec380d43d0a51e243f23b8d82d68ea?actor_id=1283957: net/http: TLS handshake timeout
```

I'm having trouble finding a POST with "info/lfs/objects" on the end.

**Comment by topherredden** [comment]
I've e-mailed you the log :)

**Comment by technoweenie** [comment]
Okay, I found the problem. The token was generated at 16:18:15 GMT. The token was used at 16:33:41 GMT, which is beyond the token timeout. I didn't expect the time between those requests to differ so much. We're working on new, better API, and a better, more reliable client for Git LFS v0.6.0. But until then, I'm going to extend the timeout to compensate for this issue.

If you want to confirm this in the log you sent, the token was generated with this response header: `X-Github-Request-Id: 97E2A007:7520:D7A987F:559FF046`. The same token was used with this response header: `X-Amz-Id-2: 83EDX4cqbOiAs0KAoKlKjsMCEQFciM97a7yMC0wpxVG/T9BkW38nyZcFWAKjpFSL`. 

> API rate limit exceeded for topherredden.

I'm working this issue now, actually :)

Thanks for going through this with me, and for checking out the Git LFS Early Access!

**Comment by cog-ethz-git** [comment]
Hello, I am having the same (or a similar) problem. I have a lot of logs that report an EOF or a forcibly closed connection, but the first and oldest error is *net/http: TLS handshake timeout*.

I am pushing a 12.4 GB initial repository. Could it be, that the increased timeout counter was not enough for larger repositories?

**Comment by technoweenie** [comment]
Nope, totally different timeout. I think a TLS handshake indicates some bigger problem communicating between your computer and the host of the Git LFS server.

**Comment by cog-ethz-git** [comment]
I saw that the put request expired: I am not sure what that means in this context. It processed all files - but in the end did not complete. If you want to I can open an issue and provide the logs. I switched from a https connection to ssh, but that did not mitigate the problem. Now I am pushing the repo in pieces and it seems to work - but that is an undesirable workflow. But since I am under a time constrain to provide the repository I will continue like this.

**Comment by technoweenie** [comment]
Are you getting the TLS handshake timeout with the S3 urls that GitHub's LFS API returns? I saw another case of that this morning.

**Comment by cog-ethz-git** [comment]
Yes, here is he full line:

Put https://github-cloud.s3.amazonaws.com/alambic/media/115288174/93/a5/93a5a8ec634cde161e404dcabb73027646ea45fede8949115f1064bd57ca569d?actor_id=13062527: net/http: TLS handshake timeout

**Comment by joeblackwaslike** [comment]
hey i'm having this same problem:

net/http: TLS handshake timeout

Only pushing a 160MB file, and only one.

Has anyne looked into this problem at all since July?

**Comment by technoweenie** [comment]
It's a network issue, so there's not a ton we can do at the client level. However, Git LFS v1.1.1 bumped the http client timeouts, with git config settings for increasing them even further: https://github.com/github/git-lfs/blob/05aa87dbf5c6c7feced04bb43c907cc3ba4e1f76/docs/man/git-lfs-config.5.ronn#L35-L49

**Comment by hazzaldo** [comment]
Hi technoweenie, 

When trying to push a large file using LFS tracking I got a similar error:
```
$ git push -u origin master
Git LFS: (0 of 1 files) 113.05 MB / 580.15 MB                                                                                        
LFS: Client error: https://github-cloud.s3.amazonaws.com/alambic/media/134753364/c7/73/c773a6287dec8c0feeb557e8af478b1e7cb2e30f105812718a282f7aaa24d4c6?actor_id=16270718
error: failed to push some refs to 'https://github.com/hazzaldo/Collect_All_Cubes_3D_Game_-iOS-.git'

```
Sorry if my query is a duplicate but I'm not sure if it was the same as the earlier problems posted on this thread.
