### ISSUE TITLE
Inconsistent behaviour with git-lfs track and *.ext when .ext files exist in the current directory

### ISSUE THREAD

**Issue by shana** [github/git-lfs#478]
Doing `git lfs track *.ext` will result in different behaviour depending on whether there are .ext files in the current directory. If there are, `git lfs track *.ext` will add individual entries to .gitattributes for each file. If there aren't, it will add a `*.ext` entry to .gitattributes. The result is that if there are files of the type I'm trying to track, I can't add a global catch-all filter on the command line and have to edit the .gitattributes file directly.

This tripped me earlier because I didn't realize it did this (it does tell that it's tracking individual files, I just didn't notice it because I wasn't expecting it to do that), so the next file I added with the same extension did not get tracked by lfs (which was when I noticed it had added a specific filename instead of *)

Is this expected? I'm not expecting `git lfs *.ext` to actually enumerate all the files that exist and add entries for each one, especially because it doesn't recurse into subdirectories, so it doesn't feel like it's very useful to do this.

**Comment by technoweenie** [comment]
Git LFS isn't doing the expanding, here. We recommend running `git lfs track "*.ext"`, so the shell doesn't expand it before execing git lfs. I wonder if there's something we can do to detect this, such as looking for one or more full filenames?

While I don't necessarily want to remove the ability to track individual files, the `track` command can probably be more strict about it. Users can get around it by modifying `.gitattributes` if they really want.

**Comment by shana** [comment]
@technoweenie ah yes, of course, it's the shell expanding, duh. It's a usability issue then, not really inconsistent behaviour. It would be nice if it warned about it, but it's not a big thing. Feel free to close :)
