### ISSUE TITLE
push failed

### ISSUE THREAD

**Issue by jiandingzhe** [github/git-lfs#479]
I did the following things to perform a simple test, but failed at pushing:

- installed git-lfs.
- created an empty repo by making a directory and run `git init --bare` in it.
- clone the repo into another place, so I have a working place and an upstream repo.
- touch "a.bmp" in the working place.
- run `git lfs track "*.bmp"`, then add a.bmp and commit.
- run `git push`.

It seems the error occurred inside git-lfs executable:

    > git-lfs pre-push origin /home/yangxi/projects/test.git
    LocalWorkingDir=/home/yangxi/test
    LocalGitDir=/home/yangxi/test/.git
    LocalMediaDir=/home/yangxi/test/.git/lfs/objects
    TempDir=/home/yangxi/test/.git/lfs/tmp
    ConcurrentTransfers=3
    BatchTransfer=false
    GIT_PREFIX=
    
    Error for POST /home/yangxi/projects/test.git/info/lfs/objects
    
    Post /home/yangxi/projects/test.git/info/lfs/objects: unsupported protocol scheme ""
    goroutine 16 [running]:
    github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/lfs/errors.go:85 +0x89
    github.com/github/git-lfs/commands.logPanicToWriter(0x7ff3f3ef3318, 0xc20803c188, 0x7ff3f3ef3c98, 0xc20809e750)
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:161 +0x832
    github.com/github/git-lfs/commands.logPanic(0x7ff3f3ef3c98, 0xc20809e750, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:134 +0x387
    github.com/github/git-lfs/commands.handlePanic(0x7ff3f3ef3c98, 0xc20809e750, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:109 +0x67
    github.com/github/git-lfs/commands.LoggedError(0x7ff3f3ef3c98, 0xc20809e750, 0xc20800e080, 0x3e, 0x0, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:66 +0x89
    github.com/github/git-lfs/commands.prePushCommand(0x9aa2a0, 0xc208044960, 0x2, 0x2)
        /Users/rick/go/src/github.com/github/git-lfs/commands/command_pre_push.go:98 +0x63f
    github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0x9aa2a0, 0xc208044940, 0x2, 0x2, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:355 +0x17c
    github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).findAndExecute(0x9aaaa0, 0xc20800e010, 0x3, 0x3, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:334 +0xd3
    github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0x9aaaa0, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:408 +0x7b0
    github.com/github/git-lfs/commands.Run()
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:81 +0x2a
    main.main()
        /Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:9 +0x1a

**Comment by technoweenie** [comment]
Currently the Git LFS APi only works over HTTPS. Pushing to a local directory is interesting, but not the use case we're prioritizing for in v1.

https://github.com/github/git-lfs/blob/master/ROADMAP.md

**Comment by jiandingzhe** [comment]
So, it is designed for pushing to a remote server, I got it.

But is it required for the server to install git-lfs, or it is only needed to be installed on my working machine? And does it need any configurations on the server? I did not find corresponding document for that.

**Comment by technoweenie** [comment]
The server has to be using the [Git LFS API](https://github.com/github/git-lfs/tree/master/docs/api).

**Comment by GeorgeR** [comment]
Oh wow, so those of us sole developers using something like dropbox as a remote are boned?

**Comment by sinbad** [comment]
It's actually fairly easy to create a minimal LFS server which you can either run locally or on an AWS remote to cater for small scale cases. The example Go server at https://github.com/github/lfs-test-server can just run locally for example, and rather than use a DB you could store in a Dropbox folder in a simple structure. The requirement of an API server makes things more flexible (e.g. decoupling authentication from storage so you log in using your Git credentials but store on S3 or something) but minimal local cases are quite easy to cater for too.
