### ISSUE TITLE
operation timed out

### ISSUE THREAD

**Issue by kamoljan** [github/git-lfs#512]
Hi guys

I am getting the following error from `git lfs logs last`:

    Error accessing media: iOS/ShoppingKaki/AdobeCreativeSDKFoundation.framework/AdobeCreativeSDKFoundation (8d980f43eaed253fcf9d71362afd130199508be4f2b0a56f56394834ce3a294e)

    Error buffering media file.
    read tcp 54.231.2.233:443: operation timed out
    goroutine 16 [running]:
    github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
     	/Users/rick/go/src/github.com/github/git-lfs/lfs/errors.go:85 +0x89
     github.com/github/git-lfs/lfs.Errorf(0x6da1c8, 0xc20820e080, 0x3fbb10, 0x1b, 0x0, 0x0, 0x0, 0x6da1c8)
    	/Users/rick/go/src/github.com/github/git-lfs/lfs/errors.go:29 +0x62
     github.com/github/git-lfs/lfs.downloadFile(0x6ce318, 0xc208048008, 0xc20804a700, 0x7fff5fbff6af, 0x50, 0xc208004fc0, 0x57, 0x0, 0x0)
    	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer_smudge.go:138 +0x538
    github.com/github/git-lfs/lfs.PointerSmudge(0x6ce318, 0xc208048008, 0xc20804a700, 0x7fff5fbff6af, 0x50, 0x0, 0x0, 0x0)
     	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer_smudge.go:32 +0x30d
    github.com/github/git-lfs/lfs.(*Pointer).Smudge(0xc20804a700, 0x6ce318, 0xc208048008, 0x7fff5fbff6af, 0x50, 0x0, 0x0, 0x0)
    	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer.go:44 +0x73
    github.com/github/git-lfs/commands.smudgeCommand(0x5b2420, 0xc208044e20, 0x1, 0x1)
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_smudge.go:60 +0x819
    github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0x5b2420, 0xc208044e10, 0x1, 0x1, 0x0, 0x0)
    	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:355 +0x17c
     github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).findAndExecute(0x5b2a20, 0xc20800e010, 0x2, 0x2, 0x0, 0x0)
    	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:334 +0xd3
    github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0x5b2a20, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:408 +0x7b0
    github.com/github/git-lfs/commands.Run()
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:81 +0x2a
    main.main()
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:9 +0x1a

My envoriment:

    ✗ git-lfs version
    git-lfs/0.5.2 (GitHub; darwin amd64; go 1.3)

    ✗ system_profiler SPSoftwareDataType
      System Version: OS X 10.11 (15A225f)
      Kernel Version: Darwin 15.0.0
      Boot Volume: Macintosh HD

What should I do?

**Comment by technoweenie** [comment]
What does `git lfs env` show? What is `54.231.2.233`?

**Comment by kamoljan** [comment]
Hi @technoweenie 

✗ git lfs env
git-lfs/0.5.2 (GitHub; darwin amd64; go 1.3)
git version 2.3.8 (Apple Git-58)

Endpoint=https://github.com/kamoljan/ShoppingXXX.git/info/lfs
  SSH=git@github.com:kamoljan/ShoppingXXX.git
LocalWorkingDir=/Users/kamol/w/ShoppingXXXi
LocalGitDir=/Users/kamol/w/ShoppingXXX/.git
LocalMediaDir=/Users/kamol/w/ShoppingXXX/.git/lfs/objects
TempDir=/Users/kamol/w/ShoppingXXX/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=false

not sure about `54.231.2.233`

**Comment by technoweenie** [comment]
Run `git lfs fsck` to clean up any partial files in `.git/lfs/objects`, and then run `git lfs fetch` to try downloading the object again.

That IP address is S3. So it looks like you had a temporary network issue. If this is something that's happening a lot, can you contact us at https://github.com/contact?
