### ISSUE TITLE
Viewing error logs is confusing if a clone fails

### ISSUE THREAD

**Issue by mgriffin** [github/git-lfs#513]
If there is a problem when you clone a LFS enabled repository, git-lfs very nicely gives you the command to run to read the log file:

```
Errors logged to .git/lfs/objects/logs/20150720T141259.212878623.log
Use `git lfs logs last` to view the log.
```

But, unless you are already in the directory, it returns `No logs to show`, because it doesn't know which repository to look into. This is obvious when you know the reason, but could be confusing if you don't. 

Would it be a good idea to put a note here that you need to `cd` to the directory before running `git lfs logs last`? Is that even possible?

**Comment by technoweenie** [comment]
> Would it be a good idea to put a note here that you need to cd to the directory before running git lfs logs last? Is that even possible?

That's tough. I don't think git lfs even knows if its in a repo. I suppose the best thing to do is compare the current working directory to `GIT_DIR`, which is probably the cloned repo directory.

**Comment by technoweenie** [comment]
Added to the roadmap in #1438.
