### ISSUE TITLE
I'd like a local mirror/proxy/cache to improve performance.

### ISSUE THREAD

**Issue by jsh** [github/git-lfs#515]
Instead of having to pull down every object from the remote server, every time, I'd like to have local copies without having to maintain and rely on my own server.

I can imagine several flavors of solutions that provide this, but an example would be a local cache: when I request an object during a clone, git-lfs could look in the cache and, if the object is there, return it immediately. If not, it would pull from the server and puts a copy in the cache, too.

We have projects where lots of developers are using a single server, and all of them pull hundreds of megs of files from the server on every clone. It'd be nice to make those clone operations lighter-weight and faster.

**Comment by technoweenie** [comment]
So, the easy option is to spin up a LFS server, and manually configure it in `lfs.url` for your repo. This will require some additional config:

* Extra user/name pass for local LFS server.
* Some mapping so the LFS server knows what auth token to use for the remote LFS server (whether that's GitHub or whatever).

Oh yeah, someone needs to write this intelligent LFS cache server :)

Another idea would be a way to configure some proxy/cache in Git LFS somehow. I'm not totally sure how this would work, but it's something I'm interested in.
