### ISSUE TITLE
I'd like a way to migrate all objects from one server to another.

### ISSUE THREAD

**Issue by jsh** [github/git-lfs#516]
The spec for the server has encouraged development of at least three implementations: the sample server on GitHub, GitHub's own git-lfs server, which is built on S3, and a git-lfs plugin for Artifactory.

Right now, there's vendor lock-in: if I put a pile of large files onto Artifactory, there's no easy way to migrate them to GitHub, or vice versa. 

If there were a migration path, I could move the lfs objects, call "git config lfs.url <new-server>", and the pointers to the lfs objects, in the "real" git repo, should just work again. Uh, I think. :-)

Solutions to permit such a migration could be anything from a server-server transfer protocol, to permit mirroring, to a simple pair of commands that bundle and unbundle collections of objects under .git/lfs/objects.

**Comment by technoweenie** [comment]
This shouldn't be that difficult. https://github.com/github/git-lfs/issues/490#issuecomment-124026748 brings up the idea of an `-all` switch on `git lfs fetch` to download all the objects. Then, you should be push your objects with `git lfs push`. It's the `pre-push` command that only pushes the LFS objects contained in the range of commits that are about to be pushed to the Git server.

This workflow should be documented well once all the pieces are in place.

**Comment by sinbad** [comment]
This should be catered for in 0.6.0 - use `git lfs fetch --all <remote>` to download all objects, then `git lfs push --all <remote>` to upload them somewhere else.

**Comment by samrocketman** [comment]
Will this ever be a feature?  Currently, I can't, in good conscience, ever recommend `git lfs` to anyone while there's no ability to migrate out of an artifact store.  At the very least, I am sure to sternly warn about this missing capability so as to keep the user informed.

**Comment by sinbad** [comment]
The answer is in the comment before yours:

> This should be catered for in 0.6.0 - use git lfs fetch --all <remote> to download all objects, then git lfs push --all <remote> to upload them somewhere else.

This did indeed ship several versions ago.

**Comment by samrocketman** [comment]
Ok great.  It wasn't clear because documentation on git lfs seems to be lacking on the subject.  All web searches for git lfs migrations seem to refer to migrating a git repository to _use git lfs_ rather than migrate from datastore to datastore.

**Comment by samrocketman** [comment]
Correction, I find it documented now that you point it out.  I guess it's just not easily found web searching.  Not really a git lfs problem.

References

* https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-fetch.1.ronn
* https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-push.1.ronn
