### ISSUE TITLE
git lfs uninit does not completely remove its traces from ~/.gitconfig

### ISSUE THREAD

**Issue by psibre** [github/git-lfs#529]
After running `git lfs init`, my `~/.gitconfig` ends like this:
```
[filter "lfs"]
	clean = git-lfs clean %f
	smudge = git-lfs smudge %f
	required = true
```
If I subsequently run `git lfs uninit`, my `~/.gitconfig` still ends with the line:
```
[filter "lfs"]
```
Running `git lfs init`, followed by `git lfs uninit`, repeatedly will result in another appended filter section line surviving each time:
```
[filter "lfs"]
[filter "lfs"]
[filter "lfs"]
```
[etc.]

**Comment by psibre** [comment]
I realize it's a super-trivial cosmetic issue, but I wanted to reported it nonetheless.

**Comment by psibre** [comment]
This is with v0.5.3 installed from Homebrew, on OSX 10.9.5.

**Comment by technoweenie** [comment]
Thanks for the report. We may have to remove the `filter.lfs` key manually, instead of just [each sub key](https://github.com/github/git-lfs/blob/2ebafdaa0da6e3c86c2617c5dd7a6fed05a37539/lfs/setup.go#L118-L126).
