### ISSUE TITLE
Client prompts for username/password auth after obtaining a token via SSH

### ISSUE THREAD

**Issue by jatoben** [github/git-lfs#533]
`newApiRequest()` calls [`sshAuthenticate()`](https://github.com/github/git-lfs/blob/master/lfs/client.go#L557) to retrieve a token with git-lfs-authenticate, but the following [`newClientRequest()` call](https://github.com/github/git-lfs/blob/master/lfs/client.go#L573) always [invokes `getCreds()`](https://github.com/github/git-lfs/blob/master/lfs/client.go#L595). This results in a password prompt if a Git credential cacher isn't configured.

**Comment by technoweenie** [comment]
I figured out why I couldn't replicate this:

```
trace git-lfs: ssh: git@github.com git-lfs-authenticate github/git-lfs-test.git download d1c8fab51418ef587fcf5dd8e73c60b9700704e2f8f5292ea12ec27c285b23a3
trace git-lfs: res header: map[Authorization:RemoteAuth BOOYA]
trace git-lfs: req header before getCreds(): map[User-Agent:[git-lfs/0.5.3 (GitHub; darwin amd64; go 1.3)]]
trace git-lfs: req.URL: https://api.github.com/lfs/github/git-lfs-test/objects/d1c8fab51418ef587fcf5dd8e73c60b9700704e2f8f5292ea12ec27c285b23a3, apiUrl: https://github.com/github/git-lfs-test.git/info/lfs/objects
trace git-lfs: Skip creds because of host/scheme mismatch
trace git-lfs: req header after getCreds(): map[User-Agent:[git-lfs/0.5.3 (GitHub; darwin amd64; go 1.3)]]
trace git-lfs: req header after res header: map[Accept:[application/vnd.git-lfs+json; charset=utf-8] Authorization:[RemoteAuth BOOYA] User-Agent:[git-lfs/0.5.3 (GitHub; darwin amd64; go 1.3)]]
trace git-lfs: HTTP: GET https://api.github.com/lfs/github/git-lfs-test/objects/d1c8fab51418ef587fcf5dd8e73c60b9700704e2f8f5292ea12ec27c285b23a3
trace git-lfs: HTTP: 200
```

The reason it's not triggering is because Git LFS doesn't bother trying to get the credentials if the configured Git LFS endpoint and the current endpoint don't agree on the host or scheme. That happens to affect GitHub.com, but not GitHub Enterprise.

**Comment by gurugray** [comment]
:+1:

**Comment by shuhrat** [comment]
+1
