### ISSUE TITLE
Investigate Git LFS and Git worktrees

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#545]
Git v2.5.0 was [just released](https://github.com/blog/2042-git-2-5-including-multiple-worktrees-and-triangular-workflows), and contains initial support for worktrees:

> It's not very difficult to switch a single Git repository between multiple branches, or to create a second local clone of a repository. This lets you work on two branches simultaneously, or start long-running tests in one clone while continuing development in the other. However, maintaining multiple clones of a repository means extra work to keep the clones in sync with each other and with any remote repositories.
>
> The new Git subcommand `git worktree` creates additional working trees connected to an existing Git repository [1]. Each linked working tree is a pseudo-repository with its own checked-out working copy. Its `.git` is actually a file that refers to the history and references from the main repository.

Based on UXR interviews and feedback I've seen, this could be useful to Git LFS users. Now would be a good time to play around with it so we can make changes, or even influence the design of Git worktrees if necessary. Here's how Michael replied when I brought this up:

> But you have a good point that Git LFS might have to be slightly aware of worktrees, mainly the distinction between $GIT_DIR (containing worktree-specific files) and $GIT_COMMON_DIR (containing files shared among all worktrees). You will have to decide where Git LFS files need to be stored.
See [git-worktree(1)](http://git-scm.com/docs/git-worktree) and [gitrepository-layout(5)](http://git-scm.com/docs/gitrepository-layout) for more details.

**Comment by sinbad** [comment]
I believe I've resolved this: https://github.com/github/git-lfs/pull/546

**Comment by technoweenie** [comment]
Yup, nice work.
