### ISSUE TITLE
Can't build on homebrew CI

### ISSUE THREAD

**Issue by gurugray** [github/git-lfs#548]
There is an uninformative error when builds on Brew Jankins farm.
```
tar xf /Library/Caches/Homebrew/git-lfs-0.5.4.tar.gz
==> ./script/bootstrap
panic: exit status 128

goroutine 1 [running]:
main.mainBuild()
	/private/tmp/git-lfs20150731-31872-fyr904/git-lfs-0.5.4/script/build.go:40 +0x249
main.main()
	/private/tmp/git-lfs20150731-31872-fyr904/git-lfs-0.5.4/script/script.go:19 +0x8c
exit status 2
```
http://bot.brew.sh/job/Homebrew%20Pull%20Requests/30547/version=mavericks/testReport/junit/brew-test-bot/mavericks/install_git_lfs/

I'm not Go developer, so can't figured what happens.

**Comment by gurugray** [comment]
@technoweenie 
I think it fails on this method https://github.com/github/git-lfs/commit/0cf7c479e403deee9f8e0cdafa9b6597d22fab71#diff-5a4f2bb696a202bd86a822f59d36318aR38

**Comment by gurugray** [comment]
https://github.com/Homebrew/homebrew/pull/42295

**Comment by rubyist** [comment]
Yep, it's that check. The build script will panic if it's not in a git repo. We can add a check for that.

**Comment by technoweenie** [comment]
Would it be sufficient to push a `v0.5.4-1` tag for homebrew? I don't want to bump the version number and recreate the packages for this.

**Comment by gurugray** [comment]
Thanks,
I think patch version is ok.
