### ISSUE TITLE
git-lfs staged but unstaged changes with 0B tracked file

### ISSUE THREAD

**Issue by kenzierocks** [github/git-lfs#557]
When a zero byte file is tracked by `git-lfs`, it will make `git status` claim there are no changes, but `git rebase -i` will claim there are unstaged changes. This doesn't happen with 1b+ files, as seen on the [1b branch](https://github.com/kenzierocks/0b1can0b/tree/1b).

Test repo: https://github.com/kenzierocks/0b1can0b

**Comment by technoweenie** [comment]
Interesting, thanks for the report.

**Comment by timon-schroeter** [comment]
First of all thank you for all the great work on git-lfs!!!

I just reproduced this bug with the latest release git-lfs/1.1.0 (GitHub; linux 386; go 1.5.1) running on Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-43-generic i686) and distro included git version 1.9.1.

I ran into it with one of by own repos but then I was able to reproduce it with the minimal test repo referenced in the original bug report above by kenzierocks:

```
root@moby:/tmp# git-lfs version
git-lfs/1.1.0 (GitHub; linux 386; go 1.5.1)
root@moby:/tmp# git clone https://github.com/kenzierocks/0b1can0b.git
Cloning into '0b1can0b'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 7 (delta 0), reused 0 (delta 0), pack-reused 5
Unpacking objects: 100% (7/7), done.
Checking connectivity... done.
Downloading 0b.track (0 B)
root@moby:/tmp# ls -l
total 4
drwxr-xr-x 3 root root 4096 Jan 17 23:19 0b1can0b
root@moby:/tmp# cd 0b1can0b/
root@moby:/tmp/0b1can0b# ls
0b.track
root@moby:/tmp/0b1can0b# git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
root@moby:/tmp/0b1can0b# git commit .
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
        modified:   0b.track

no changes added to commit
root@moby:/tmp/0b1can0b# 
```
Is it still there or is it a regression??

**Comment by kenzierocks** [comment]
This was never fixed, so it is still there.

**Comment by technoweenie** [comment]
Fixed by @nathanhi :metal:
