### ISSUE TITLE
How to build v0.5.2 rpm

### ISSUE THREAD

**Issue by cpTpalazzolo** [github/git-lfs#567]
If I checkout tag v0.5.2 and build the rpm, I get v0.5.1. If I goto to v0.5.3, then I get v0.5.3. I need v0.5.2 due to a bug in v0.5.3, how can I install v0.5.2 on CentOS 7? BTW, I was able to build a deb v0.5.2 on Ubuntu.

**Comment by cpTpalazzolo** [comment]
Sorry, that was simple enough to just change the version in the spec file.

**Comment by technoweenie** [comment]
What's the bug in 0.5.3?

**Comment by cpTpalazzolo** [comment]
Sorry, I do not have the details of the actually bug. I was told to use v0.5.2 because v0.5.3 has a bug for our build. I tested v0.5.4 and the same error happens. I get a signal 13 error. I assumed the people who are writing the build environment have already file a bug report, but that would be just a guess. I am too far removed from the inner workings of the build process. Sorry I couldn't be more help.

**Comment by technoweenie** [comment]
No one's filed a bug report about it that I've seen. I'd really appreciate it though, so we can fix it and unblock you from upgrading :)
