### ISSUE TITLE
v0.6.0 hang on push

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#575]
Here's how to replicate against master:

* Create a new repository with 50 LFS objects and push to the server.
* Clone that repository to a new local directory.
* Create a new branch
* Create 50 _new_ files and push again

Here's a `GIT_TRACE` log:

https://gist.github.com/technoweenie/3058ade83b3735b3d4ab

I counted the HTTP response codes in the trace response:

```
$ grep "HTTP: 20" hanging.log -c
150
```

That's 100 API requests + 50 new uploads. So it should be done now.

**Comment by billygor** [comment]
If I understood correctly, this is the issue fixed by:
https://github.com/github/git-lfs/pull/572

**Comment by rubyist** [comment]
Confirm the hand and that #572 fixes it. I've merged that PR into master.

**Comment by technoweenie** [comment]
@billygor Oh rad, thanks! Did you experience that on v0.5.4, or are you running off master?

**Comment by billygor** [comment]
@technoweenie 
I'm running off master, v0.5.4 is not affected.
I bisected this to 94ecd166e424d26d3779f6bb69cad811df842f65
$ git tag --contains 94ecd166e424d26d3779f6bb69cad811df842f65
--nothing--
$ git branch --remotes --contains 94ecd166e424d26d3779f6bb69cad811df842f65
  upstream/index-progress
  upstream/master
  upstream/newbatchapi
$

**Comment by technoweenie** [comment]
Great, thanks for confirming.  Feel free to stop by the [chat room](https://gitter.im/github/git-lfs) if you want to talk in more real time.
