### ISSUE TITLE
Do you plan on releasing a production ready git-lfs server?

### ISSUE THREAD

**Issue by dosire** [github/git-lfs#584]
See https://about.gitlab.com/2015/08/13/towards-a-production-quality-open-source-git-lfs-server/#comment-2191074763 for the request to open an issue here.

Some questions we have, feel free to answer selectively:

1. Do you plan on releasing a production ready git-lfs server?
1. Is this repository based on code you run in production?
1. What would need to be added to this codebase to make it ready for production?
1. Are you accepting pull requests that make this codebase more ready for production?
1. Are you accepting pull requests that optionally bypass the user management that is currently in here or would you rather see us maintaining a fork?

**Comment by dosire** [comment]
Question 5 as prased by https://twitter.com/ethomson/status/631864576422772736 Are you open to adding a pluggable auth model?

**Comment by technoweenie** [comment]
1. No plans at this time.
2. Nope, not even close. It's just a test server with as few dependencies as possible.

We have no intentions of working on the lfs test server, beyond making it protocol compatible with the client. I'd much rather see you start over, or fork it.

I think an oss, production-ready lfs server with a pluggable auth model would be rad though :metal:

**Comment by dosire** [comment]
@technoweenie Thanks for the answers. We'll proceed with a fork that we'll try to wip into production shape over time.

BTW thanks for attachment_fu back in the day, it was such a big improvement over the status quo.

**Comment by technoweenie** [comment]
Cool, thanks for reaching out!

**Comment by blowsie** [comment]
https://github.com/blog/2069-git-large-file-storage-v1-0
