### ISSUE TITLE
Install script fails on OSX

### ISSUE THREAD

**Issue by mindmelting** [github/git-lfs#596]
When running the install script I get the following on OSX (Yosemite)

```
[mindmelting:~/Downloads/git-lfs-0.5.4]$ ./install.sh
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
```

**Comment by technoweenie** [comment]
This was [reported](https://github.com/github/git-lfs/pull/519#issuecomment-131680845) and [backported](https://github.com/github/git-lfs/pull/589) yesterday. You can grab the updated zip from [the v0.5.4 release page](https://github.com/github/git-lfs/releases/tag/v0.5.4).

Also, you should be able to install it with homebrew.

Thanks for the report!

**Comment by mindmelting** [comment]
Thanks!
