### ISSUE TITLE
Using git lfs to pull files down on travis-ci

### ISSUE THREAD

**Issue by lbergelson** [github/git-lfs#598]
We're trying out git lfs to manage some large test files we have.  I'm having trouble getting it set up so that it works with travis-ci though.  

It seems to be having some sort of authentication issue.  

Locally, if I checkout my repo with `git clone git@github.com:broadinstitute/hellbender.git` and then run my [install_git_lfs](https://gist.github.com/lbergelson/4265e5ef3ec8b60dac97) script it works fine.

However, if I clone using the link travis uses

`git clone --depth=50 --branch=lb_travis_lfs git://github.com/broadinstitute/hellbender.git` 

I get a password and username prompt for every file I'm trying to download.  The [result on travis](https://travis-ci.org/broadinstitute/hellbender/builds/76479127#L92) looks like what happens if I enter nonsense passwords, although it doesn't output any prompt text at all (it's not an interactive terminal so that's not surprising).  It just silently fails to download anything.

Is there a workaround for this?  I tried following something I saw @mnapoli doing to work around the same issue by resetting the git remote to use and https: remote instead, but I couldn't get that to work either.

**Comment by mnapoli** [comment]
Hi! Migrating Piwik to git-lfs is still work in progress, currently git-lfs seems to fail to download the screenshots correctly so it's not working: https://github.com/piwik/piwik/pull/8392 (tried different versions, including master… hopefully you won't meet this issue)

Regarding your problem, have a look at the Travis script: https://github.com/piwik/travis-scripts/pull/1 In there I change the remote url: `git remote set-url origin "https://$GITHUB_USER_TOKEN:@github.com/$TRAVIS_REPO_SLUG.git"`

I tried removing the `$GITHUB_USER_TOKEN` but IIRC it didn't work.

Good luck!

**Comment by technoweenie** [comment]
So unfortunately, the current LFS API requires authentication. Make sure the token has no oauth access.

The new batch API for Git LFS v0.6.0 will work without authentication, so this won't be an issue anymore.

**Comment by lbergelson** [comment]
Thanks for the replies!
 @mnapoli that's what I tried but it blew up at me.  It sounds like it's not exactly working for you either?

@technoweenie 
I'm not sure I understand what you mean by 
>make sure the token has no oath access.

I can provide a valid username/password to log into my repo if it needs it.  Is there a way I can have git lfs read it from an environment variable?  

Or should I just wait for  v0.6.0? What's the eta?

**Comment by technoweenie** [comment]
@lbergelson When generating the token, uncheck everything at https://github.com/settings/tokens/new. The token will authenticate, but still only gives you readonly access.

Git LFS v0.6.0 is pretty close. I'd say within a few weeks.

**Comment by lbergelson** [comment]
0.6.0 solve the problem

**Comment by technoweenie** [comment]
@lbergelson Awesome, thanks for following up!
