### ISSUE TITLE
Push on non-current branches produces incorrect results

### ISSUE THREAD

**Issue by sinbad** [github/git-lfs#606]
I'm just dumping this one here so I don't lose it, I spotted this while trying test my 'fetch recent' feature.

If you create a secondary branch which includes a modification of an existing file, then try to push it from a different branch, it doesn't push the last update to the object but still updates the remote branch pointer.

I demonstrated this by adding the oid to the --dry-run output and running against a simple repo with this setup:

```
steve@Stevens-MacBook-Pro ~/p/G/s/g/g/g/t/t/fetch-recent> git branch
* master
  other_branch
steve@Stevens-MacBook-Pro ~/p/G/s/g/g/g/t/t/fetch-recent> git lfs push --dry-run origin other_branch
push file1.dat (ec3a53b52eb11808d59d29ffd01568edf2d62cdc9c02def84d0a11704d552de2)
push file2.dat (495e32a1c5615c5cf236d99c1ec53903086630eddcba51a1f8b543bf5f2275be)
push file1.dat (d9929b4e48b6ab5d9c5e0da4a5b9bf89f5c63dd0a08c7ebcd2afbbe19436bfdb)
push file1.dat (1a526e57eddca261e4da323bf7b8ca468d27aedf019884e30dfc3cd7342706e1)
steve@Stevens-MacBook-Pro ~/p/G/s/g/g/g/t/t/fetch-recent> git checkout other_branch
Switched to branch 'other_branch'
steve@Stevens-MacBook-Pro ~/p/G/s/g/g/g/t/t/fetch-recent> git lfs push --dry-run origin other_branch
push file1.dat (7bf3771066357ae85beb19c246d6177c5d8183f4fd8ee20eaae3fe54dffa0a72)
push file1.dat (d9929b4e48b6ab5d9c5e0da4a5b9bf89f5c63dd0a08c7ebcd2afbbe19436bfdb)
push file1.dat (1a526e57eddca261e4da323bf7b8ca468d27aedf019884e30dfc3cd7342706e1)
steve@Stevens-MacBook-Pro ~/p/G/s/g/g/g/t/t/fetch-recent>
```

`7bf3771066357ae85beb19c246d6177c5d8183f4fd8ee20eaae3fe54dffa0a72` is the final change on other_branch:

```
steve@Stevens-MacBook-Pro ~/p/G/s/g/g/g/t/t/fetch-recent> git checkout other_branch
Switched to branch 'other_branch'
steve@Stevens-MacBook-Pro ~/p/G/s/g/g/g/t/t/fetch-recent> git show
commit 4cf53058040a9a453668e26d1c797e402ff325db
Author: Git LFS Tests <git-lfs@example.com>
Date:   Tue Aug 25 16:39:47 2015 +0100

    Test commit 2

diff --git a/file1.dat b/file1.dat
index d5a0899..0f0f1a4 100644
--- a/file1.dat
+++ b/file1.dat
@@ -1,3 +1,3 @@
 version https://git-lfs.github.com/spec/v1
-oid sha256:d9929b4e48b6ab5d9c5e0da4a5b9bf89f5c63dd0a08c7ebcd2afbbe19436bfdb
+oid sha256:7bf3771066357ae85beb19c246d6177c5d8183f4fd8ee20eaae3fe54dffa0a72
 size 12
```

I can reproduce this failure to push using `git lfs push` and `git push` (I've noticed the ref scan is different for `push` and `pre-push`, we should probably unify that).

**Comment by sinbad** [comment]
I can't attach a zipped repo example but the fetch integration test here reproduces it: https://github.com/sinbad/git-lfs/commit/aba8f6dd10c32750ab78d0341f5ae74f87894b17

**Comment by sinbad** [comment]
You can assign this to me if you want, I'm in a decent position to test it now I have the tools to create non-trivial test repos in my branch, and it's getting in my way anyway.

**Comment by sinbad** [comment]
There are a couple of problems with the `push` command as currently implemented:
# it always uses the current ref as the 'left' param to ScanRefs. This doesn't work for non-current branches (including the case of a detached HEAD on a previous commit of the 'current' branch)
# it always compares with the ref of the same name on the remote (via git.LsRemote), which assumes push.default=current/simple/matching. While this is typical, if push.default=upstream the remote branch can have a different name.

None of this would be noticeable when pushing the current branch to a branch of the same name, but it produces unexpected results in other setups. What the push command *should* be doing when a ref is supplied is using the argument as the 'left' param to ScanRefs and either correctly derive the right remote branch to use for 'right' (supporting push.default=upstream) or using the ScanLeftToRemote option to exclude all remote branches (probably more efficient so will try that).

**Comment by sinbad** [comment]
Fixed. I'm also not sure why the `push` command and the `pre-push` command are **both** set up to handle being used in the pre-push hook. My feeling is that the implementation should be removed from `push` because it's not used anymore but I haven't done this in this PR in case it's there for a reason.

**Comment by rubyist** [comment]
> I'm also not sure why the push command and the pre-push command are both set up to handle being used in the pre-push hook.

Probably legacy behavior. There used to be only a `lfs push`, then we went to hooks, then changes made to both, and so on. It's probably worth looking at, but in a different PR.
