### ISSUE TITLE
getCreds incorrectly compares a requests URL scheme when against localhost

### ISSUE THREAD

**Issue by WillHipschman** [github/git-lfs#612]
In client.go in getCreds if we make a request against mymachinename but the remote is localhost then we will not authenticate correctly.

	if req.URL.Scheme != apiUrl.Scheme ||
		req.URL.Host != apiUrl.Host {

**Comment by whoisj** [comment]
Git allows for just about anything in the host and scheme values. Ideally, git-lfs would as well and then just report the failure if no method for utilizing the scheme exists, or it is unable to reach the host.

**Comment by technoweenie** [comment]
This should be solved in https://github.com/github/git-lfs/commit/f71969d965aaab8d2d0664818fb2bf1350c33af1 from #611

**Comment by technoweenie** [comment]
#611 has been merged. Let me know if you still have issues.
