### ISSUE TITLE
push does not resume after failure

### ISSUE THREAD

**Issue by psibre** [github/git-lfs#621]
After a canceled or failed `git push`, the transfer should resume where it left off, but it starts all over again. As I'm trying to push dozens of GB, this is of course a problem.

**Comment by psibre** [comment]
@technoweenie thanks for the feedback! I had a feeling it would be a known issue, but could find anything.

**Comment by technoweenie** [comment]
FWIW Git LFS doesn't re-upload entire objects if they've been successfully uploaded. It just can't resume partial uploads.

**Comment by psibre** [comment]
Indeed, I just realized that upon running `git push` again after failure, I immediately get the HTTP 413 reported in #622, so the first 10 objects must have been transferred successfully.

**Comment by jamestalmage** [comment]
@technoweenie 
What about manually splitting the upload into chunks, and just uploading as multiple smaller files? Perhaps just as a fallback option for services without supported multipart upload implementations?

**Comment by technoweenie** [comment]
@jamestalmage That _is_ a multipart upload implementation :) That would need extra server logic that can somehow re-assemble the file, so that a Git LFS fetch will download it properly. 

Personally, I really like [tus.io](http://tus.io/), which is as close to a sane, open standard that I've seen. But we'd likely need to support S3 multipart uploads too, and other common implementations that other cloud servers may use.

**Comment by jamestalmage** [comment]
Maybe I wasn't being clear. I meant giving each part a different file name and uploading using the current server API. The server doesnt need to know the chunks are related. The client would also have to be responsible for reassembly.

**Comment by technoweenie** [comment]
Ah, do you mean doing the chunking locally? It'd have to keep track of what chunks a file has locally too so it knows what chunks to request from the server. I do like that idea, so we can keep the server dumb.

**Comment by jamestalmage** [comment]
Yep, that is what I was thinking. 

Could you just incorporate a chunking size in the local record?

```js
{
  base_oid: '111111',
  size: 50000,
  chunking_size: 5000
}
// Apologies - I have no idea what the local record looks like
```

You could determine the exact number of required chunks just from that info

Then just suffix the oid with a chunk number when uploading:

```js
{
  operation: 'upload',
  objects: [
    {
      oid: '111111-00',
      size: 10000
    },
    {
      oid: '111111-00',
      size: 10000
    },
    // ....
  ]
}
```

Will suffixes like that cause problems for current server implementations?

**Comment by technoweenie** [comment]
Suffixes will, but there's no reason an extra property couldn't be added to the JSON in the batch API.

**Comment by jamestalmage** [comment]
Sure, that makes sense. Servers could then append/prepend that extra property to the upload/download url.

My only concern with the extra property would be current server implementations that are not validating the JSON. They might tell the client to upload all 10 chunks to the same URL. It might be simple enough to check that client side.

It might be wise to introduce `GET /apiVersion` as a line of defense against these types of breaking changes?

**Comment by jamestalmage** [comment]
Why the close?

**Comment by technoweenie** [comment]
Because there are no plans to change this any time soon.

There is an experimental resumable upload adapter in master now using the tus.io API, as well.
