### ISSUE TITLE
Client error HTTP 413 when pushing

### ISSUE THREAD

**Issue by psibre** [github/git-lfs#622]
Trying to push a large amount of data through LFS I can upload a significant portion of it, but then I get an HTTP error 413 ("Request entity too large").
```
$ git lfs version
git-lfs/0.5.4 (GitHub; darwin amd64; go 1.4.2)
$ git lfs status
On branch lfs
Git LFS objects to be pushed to origin/lfs:

[ 28 files totalling ~ 37 GB ]

Git LFS objects to be committed:


Git LFS objects not staged for commit:


$ git push
(10 of 28 files) 5.01 GB 13m29s                                                                                                                                                    
Validation Failed
Docs: https://help.github.com/enterprise
Validation Failed
Docs: https://help.github.com/enterprise
Validation Failed
Docs: https://help.github.com/enterprise
Validation Failed
Docs: https://help.github.com/enterprise
Validation Failed
Docs: https://help.github.com/enterprise
Validation Failed
Docs: https://help.github.com/enterprise
Validation Failed
Docs: https://help.github.com/enterprise
Client error: https://GH_DOMAIN/files/media/GH_USER/REPO/object/SOME_HASH from HTTP 413
error: failed to push some refs to 'git@GH_DOMAIN:GH_USER/REPO.git'
```
(where `GH_DOMAIN` is our GitHub Enterprise instance, `GH_USER` and `REPO` are my user account and the repository there, respectively, and `SOME_HASH` appears to refer to a file stored under `.git/lfs/objects/SO/ME/SOME_HASH` that is 1.4 GB in size.)

**Comment by technoweenie** [comment]
There's a 1GB limit for single objects in GitHub Enterprise. We plan to increase this to 2GB in the next 2.2/2.3/2.4 releases. Closing this since it has nothing to do with the OSS project.  Please hit up support@github.com (or go through your normal Enterprise support procedure) if you want to talk further about it.

**Comment by psibre** [comment]
I see, thanks for the explanation!
