### ISSUE TITLE
Installation fails on Raspbian 

### ISSUE THREAD

**Issue by klcodanr** [github/git-lfs#623]
The installation on Raspbian fails with the message:

    can't load package: package github.com/github/git-lfs/commands: cannot find package "github.com/github/git-lfs/commands" in any of:
	/root/.gvm/gos/go1.4.2/src/github.com/github/git-lfs/commands (from $GOROOT)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/github/git-lfs/commands (from $GOPATH)
    can't load package: package github.com/github/git-lfs/lfs: cannot find package "github.com/github/git-lfs/lfs" in any of:
	/root/.gvm/gos/go1.4.2/src/github.com/github/git-lfs/lfs (from $GOROOT)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/github/git-lfs/lfs (from $GOPATH)
    script/build.go:13:2: cannot find package "github.com/github/git-lfs/lfs" in any of:
	/root/.gvm/gos/go1.4.2/src/github.com/github/git-lfs/lfs (from $GOROOT)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/github/git-lfs/lfs (from $GOPATH)
    
  ++ echo FAIL

**Comment by klcodanr** [comment]
Complete logs:

+ trap 'echo FAIL' ERR
+ apt-get -y update
Hit http://mirrordirector.raspbian.org wheezy Release.gpg
Hit http://archive.raspberrypi.org wheezy Release.gpg
Hit http://raspberrypi.collabora.com wheezy Release.gpg
Hit http://mirrordirector.raspbian.org wheezy Release
Hit http://raspberrypi.collabora.com wheezy Release
Hit http://archive.raspberrypi.org wheezy Release
Hit http://raspberrypi.collabora.com wheezy/rpi armhf Packages
Get:1 http://archive.raspberrypi.org wheezy/main armhf Packages [133 kB]
Ign http://raspberrypi.collabora.com wheezy/rpi Translation-en_GB
Ign http://raspberrypi.collabora.com wheezy/rpi Translation-en
Get:2 http://mirrordirector.raspbian.org wheezy/main armhf Packages [6,905 kB]
Ign http://archive.raspberrypi.org wheezy/main Translation-en_GB
Ign http://archive.raspberrypi.org wheezy/main Translation-en
Get:3 http://mirrordirector.raspbian.org wheezy/contrib armhf Packages [23.6 kB]
Get:4 http://mirrordirector.raspbian.org wheezy/non-free armhf Packages [49.3 kB]
Get:5 http://mirrordirector.raspbian.org wheezy/rpi armhf Packages [592 B]
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-en_GB
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-en
Ign http://mirrordirector.raspbian.org wheezy/main Translation-en_GB
Ign http://mirrordirector.raspbian.org wheezy/main Translation-en
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-en_GB
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-en
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-en_GB
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-en
Fetched 7,112 kB in 23s (300 kB/s)
Reading package lists...
+ apt-get -y install binutils bison curl gcc git golang-go make
Reading package lists...
Building dependency tree...
Reading state information...
bison is already the newest version.
curl is already the newest version.
gcc is already the newest version.
git is already the newest version.
golang-go is already the newest version.
binutils is already the newest version.
make is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 32 not upgraded.
++ go version
++ sed 's/go version go//; s/ .*//'
+ go_version=1.0.2
+ [[ 1.0.2 < 1.3.1 ]]
+ [[ -r /root/.gvm/scripts/gvm ]]
+ set +u
+ source /root/.gvm/scripts/gvm
++ export GVM_ROOT=/root/.gvm
++ GVM_ROOT=/root/.gvm
++ . /root/.gvm/scripts/gvm-default
+++ unset GOROOT
+++ unset GOARCH
+++ unset GOOS
+++ unset GOPATH
+++ unset GOBIN
+++ unset gvm_go_name
+++ unset gvm_pkgset_name
+++ mkdir -p /root/.gvm/logs
+++ mkdir -p /root/.gvm/gos
+++ mkdir -p /root/.gvm/archive
+++ mkdir -p /root/.gvm/archive/package
+++ mkdir -p /root/.gvm/environments
++++ cat /root/.gvm/VERSION
+++ export GVM_VERSION=1.0.22
+++ GVM_VERSION=1.0.22
+++ export PATH=/root/.gvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+++ PATH=/root/.gvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+++ export GVM_PATH_BACKUP=/root/.gvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+++ GVM_PATH_BACKUP=/root/.gvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+++ '[' -f /root/.gvm/environments/default ']'
+++ . /root/.gvm/scripts/env/gvm
++++ . /root/.gvm/scripts/functions
+++++ for function in '$GVM_ROOT/scripts/function/*'
+++++ . /root/.gvm/scripts/function/display_error
+++++ for function in '$GVM_ROOT/scripts/function/*'
+++++ . /root/.gvm/scripts/function/display_fatal
+++++ for function in '$GVM_ROOT/scripts/function/*'
+++++ . /root/.gvm/scripts/function/display_message
+++++ for function in '$GVM_ROOT/scripts/function/*'
+++++ . /root/.gvm/scripts/function/display_warning
+++++ for function in '$GVM_ROOT/scripts/function/*'
+++++ . /root/.gvm/scripts/function/find_local_pkgset
+++++ for function in '$GVM_ROOT/scripts/function/*'
+++++ . /root/.gvm/scripts/function/gvm_export_path
+++++ for function in '$GVM_ROOT/scripts/function/*'
+++++ . /root/.gvm/scripts/function/tools
++++++ LS_ERROR='GVM couldn'\''t find ls'
++++++ GREP_ERROR='GVM couldn'\''t find grep'
++++++ SORT_ERROR='GVM couldn'\''t find sort'
++++++ HEAD_ERROR='GVM couldn'\''t find head'
+++++++ unalias ls
+++++++ which ls
++++++ LS_PATH=/bin/ls
+++++++ unalias grep
+++++++ which grep
++++++ GREP_PATH=/bin/grep
+++++++ unalias sort
+++++++ which sort
++++++ SORT_PATH=/usr/bin/sort
+++++++ unalias head
+++++++ which head
++++++ HEAD_PATH=/usr/bin/head
+ gvm install go1.4.2
+ [[ /root/.gvm == '' ]]
+ [[ -d /root/.gvm/.git ]]
+ [[ ! -d /root/.gvm ]]
+ mkdir -p /root/.gvm/logs
+ mkdir -p /root/.gvm/gos
+ mkdir -p /root/.gvm/archive
+ mkdir -p /root/.gvm/archive/package
+ mkdir -p /root/.gvm/environments
+ [[ install == \u\s\e ]]
+ [[ install == \i\m\p\l\o\d\e ]]
+ [[ install == \p\k\g\s\e\t ]]
+ /root/.gvm/bin/gvm install go1.4.2
Already installed!
+ gvm use go1.4.2
+ [[ /root/.gvm == '' ]]
+ [[ -d /root/.gvm/.git ]]
+ [[ ! -d /root/.gvm ]]
+ mkdir -p /root/.gvm/logs
+ mkdir -p /root/.gvm/gos
+ mkdir -p /root/.gvm/archive
+ mkdir -p /root/.gvm/archive/package
+ mkdir -p /root/.gvm/environments
+ [[ use == \u\s\e ]]
+ . /root/.gvm/scripts/env/use
+ shift
+ gvm_use go1.4.2
+ [[ go1.4.2 != '' ]]
+ local VERSION=go1.4.2
++ /bin/ls /root/.gvm/gos
++ /usr/bin/sort
++ /bin/grep go1.4.2
++ /usr/bin/head -n 1
++ /bin/grep go1.4.2
+ fuzzy_match=go1.4.2
+ [[ 0 != \0 ]]
+ gvm_export_path
++ echo /root/.gvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ tr : '\n'
++ grep -v '^$'
++ sed 's/:*$//'
++ egrep -v '/root/.gvm/(pkgsets|gos|bin)'
++ tr '\n' :
+ export PATH=/root/.gvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ PATH=/root/.gvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ export GVM_PATH_BACKUP=/root/.gvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ GVM_PATH_BACKUP=/root/.gvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ . /root/.gvm/environments/go1.4.2
+ [[ '' == \-\-\d\e\f\a\u\l\t ]]
+ display_message 'Now using version go1.4.2'
+ which tput
+ [[ 0 == \0 ]]
+ [[ xterm-256color == \x\t\e\r\m ]]
+ echo 'Now using version go1.4.2'
Now using version go1.4.2
+ set -u
++ dirname ./debian-build
+ cd .
+ git rev-parse
++ git rev-parse --show-toplevel
+ cd /opt/git-lfs
+ ./script/bootstrap
can't load package: package github.com/github/git-lfs/commands: cannot find package "github.com/github/git-lfs/commands" in any of:
	/root/.gvm/gos/go1.4.2/src/github.com/github/git-lfs/commands (from $GOROOT)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/github/git-lfs/commands (from $GOPATH)
can't load package: package github.com/github/git-lfs/lfs: cannot find package "github.com/github/git-lfs/lfs" in any of:
	/root/.gvm/gos/go1.4.2/src/github.com/github/git-lfs/lfs (from $GOROOT)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/github/git-lfs/lfs (from $GOPATH)
script/build.go:13:2: cannot find package "github.com/github/git-lfs/lfs" in any of:
	/root/.gvm/gos/go1.4.2/src/github.com/github/git-lfs/lfs (from $GOROOT)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/github/git-lfs/lfs (from $GOPATH)
++ echo FAIL
FAIL

**Comment by technoweenie** [comment]
That's a normal go issue if your go environment isn't setup properly. Have you tried installing the Debian package from https://github.com/github/git-lfs/releases/tag/v0.5.4 ? That's the recommended route for Git LFS users on Debian platforms.

**Comment by klcodanr** [comment]
@technoweenie Since this is on a Raspberry PI which .deb would be appropriate?  It seems like the pre-built ones are geared towards x86 platforms.

**Comment by technoweenie** [comment]
Ah yeah, good point. I haven't even tried compiling this for ARM processors. 

Go likes to keep its packages in its `$GOPATH`. The easiest way to do this is to run `go get github.com/github/git-lfs`. This will clone the repository to `$GOPATH/src/github.com/github/git-lfs`. From there you should be able to run `script/bootstrap` to build the project.

Just curious: what are you doing with Git LFS on a raspberry pi? Is it hooked up to a USB drive or something?

**Comment by klcodanr** [comment]
Good question. I'm using it as a basic internal fileserver. I was hoping to set it up where files could be committed to Git and automatically pulled down onto the server.

When I called the command above I got the following message:

root@raspberrypi:~# go get github.com/github/git-lfs
# github.com/github/git-lfs/git
/usr/lib/go/src/pkg/github.com/github/git-lfs/git/git.go:196: undefined: bufio.NewScanner
# github.com/github/git-lfs/vendor/_nuts/github.com/cheggaaa/pb
/usr/lib/go/src/pkg/github.com/github/git-lfs/vendor/_nuts/github.com/cheggaaa/pb/format.go:19: function ends without a return statement
# github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra
/usr/lib/go/src/pkg/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:106: function ends without a return statement
/usr/lib/go/src/pkg/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:169: function ends without a return statement
/usr/lib/go/src/pkg/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:183: function ends without a return statement
/usr/lib/go/src/pkg/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:215: function ends without a return statement
/usr/lib/go/src/pkg/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:226: function ends without a return statement
/usr/lib/go/src/pkg/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:236: function ends without a return statement
/usr/lib/go/src/pkg/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:244: function ends without a return statement
/usr/lib/go/src/pkg/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:281: function ends without a return statement
/usr/lib/go/src/pkg/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:434: function ends without a return statement
/usr/lib/go/src/pkg/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:498: function ends without a return statement
/usr/lib/go/src/pkg/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:434: too many errors

**Comment by technoweenie** [comment]
What version of Go are you using? Something in your previous output mentioned Go 1.4.2 , but those errors look like they come from Go 1.0. Git LFS requires Go 1.3+.

**Comment by timon-schroeter** [comment]
I think you have a good chance to get it to work:

git lfs runs perfectly on my Olinuxino micro board with A20 ARM CPU and Ubunty Trusty (Armbian variant) as OS.

This is how I installed it:

1. I looked for a Go 1.5 backport for Ubunty Trusty (ARM) and found a suitable one in ppa:ubuntu-lxc/lxd-stable
2. I compiled form source as descried in https://github.com/github/git-lfs/blob/master/CONTRIBUTING.md#building , i.e.
```
mkdir /root/gocode
export GOPATH=/root/gocode
go get github.com/github/git-lfs
cp gocode/bin/git-lfs /usr/bin
```
The whole process of downloading and compiling via "go get" took exactly 80 seconds and git lfs itself performs beautifully.

**Comment by technoweenie** [comment]
Closing this, Go 1.6+ should support ARM builds. I don't plan on building official ARM releases, since I don't think too many people will be working with LARGE FILES on a raspbian :)

**Comment by roeles** [comment]
I'm using raspbian on a Pi3 to log aircraft parameters (pressures, acceleration, gyro, magneto) at 600Hz. This produces 6MB per minute. 
I'd like to use git-lfs to push the resulting files to git, allowing others to process them further. 
The Git-lfs repository the bash script adds to sources.list does not exist anymore.
What solution is suggested to add git-lfs support to raspbian?

**Comment by ttaylorr** [comment]
@roeles: if I'm understanding your question correctly, you're trying to build git-lfs for Raspbian? To do this:

```sh
./script/bootstrap -arch arm -os linux
```

**Comment by vervaekejonathan** [comment]
@ttaylorr 

Trying your suggestion, this is the error I get
 
> pi@raspberrypi:~/git-lfs $ ./script/bootstrap -arch arm -os linux
> can't load package: package github.com/ThomsonReutersEikon/go-ntlm/ntlm: cannot find package "github.com/ThomsonReutersEikon/go-ntlm/ntlm" in any of:
> 	/usr/lib/go/src/pkg/github.com/ThomsonReutersEikon/go-ntlm/ntlm (from $GOROOT)
> 	/home/pi/git-lfs/src/github.com/ThomsonReutersEikon/go-ntlm/ntlm (from $GOPATH)
> can't load package: package github.com/bgentry/go-netrc/netrc: cannot find package "github.com/bgentry/go-netrc/netrc" in any of:
> 	/usr/lib/go/src/pkg/github.com/bgentry/go-netrc/netrc (from $GOROOT)
> 	/home/pi/git-lfs/src/github.com/bgentry/go-netrc/netrc (from $GOPATH)
> can't load package: package github.com/cheggaaa/pb: cannot find package "github.com/cheggaaa/pb" in any of:
> 	/usr/lib/go/src/pkg/github.com/cheggaaa/pb (from $GOROOT)
> 	/home/pi/git-lfs/src/github.com/cheggaaa/pb (from $GOPATH)
> can't load package: src/github.com/git-lfs/git-lfs/subprocess/pty_nix.go:9:2: cannot find package "github.com/kr/pty" in any of:
> 	/usr/lib/go/src/pkg/github.com/kr/pty (from $GOROOT)
> 	/home/pi/git-lfs/src/github.com/kr/pty (from $GOPATH)
> can't load package: src/github.com/git-lfs/git-lfs/progress/meter.go:12:2: cannot find package "github.com/olekukonko/ts" in any of:
> 	/usr/lib/go/src/pkg/github.com/olekukonko/ts (from $GOROOT)
> 	/home/pi/git-lfs/src/github.com/olekukonko/ts (from $GOPATH)
> can't load package: src/github.com/git-lfs/git-lfs/errors/errors.go:56:2: cannot find package "github.com/pkg/errors" in any of:
> 	/usr/lib/go/src/pkg/github.com/pkg/errors (from $GOROOT)
> 	/home/pi/git-lfs/src/github.com/pkg/errors (from $GOPATH)
> can't load package: src/github.com/git-lfs/git-lfs/subprocess/subprocess.go:13:2: cannot find package "github.com/rubyist/tracerx" in any of:
> 	/usr/lib/go/src/pkg/github.com/rubyist/tracerx (from $GOROOT)
> 	/home/pi/git-lfs/src/github.com/rubyist/tracerx (from $GOPATH)
> can't load package: src/github.com/git-lfs/git-lfs/commands/command_checkout.go:8:2: cannot find package "github.com/spf13/cobra" in any of:
> 	/usr/lib/go/src/pkg/github.com/spf13/cobra (from $GOROOT)
> 	/home/pi/git-lfs/src/github.com/spf13/cobra (from $GOPATH)
> src/github.com/git-lfs/git-lfs/lfsapi/lfsapi.go:13:2: cannot find package "github.com/ThomsonReutersEikon/go-ntlm/ntlm" in any of:
> 	/usr/lib/go/src/pkg/github.com/ThomsonReutersEikon/go-ntlm/ntlm (from $GOROOT)
> 	/home/pi/git-lfs/src/github.com/ThomsonReutersEikon/go-ntlm/ntlm (from $GOPATH)
> src/github.com/git-lfs/git-lfs/config/config_netrc.go:7:2: cannot find package "github.com/bgentry/go-netrc/netrc" in any of:
> 	/usr/lib/go/src/pkg/github.com/bgentry/go-netrc/netrc (from $GOROOT)
> 	/home/pi/git-lfs/src/github.com/bgentry/go-netrc/netrc (from $GOPATH)
> src/github.com/git-lfs/git-lfs/subprocess/pty_nix.go:9:2: cannot find package "github.com/kr/pty" in any of:
> 	/usr/lib/go/src/pkg/github.com/kr/pty (from $GOROOT)
> 	/home/pi/git-lfs/src/github.com/kr/pty (from $GOPATH)
> src/github.com/git-lfs/git-lfs/progress/meter.go:12:2: cannot find package "github.com/olekukonko/ts" in any of:
> 	/usr/lib/go/src/pkg/github.com/olekukonko/ts (from $GOROOT)
> 	/home/pi/git-lfs/src/github.com/olekukonko/ts (from $GOPATH)
> src/github.com/git-lfs/git-lfs/errors/errors.go:56:2: cannot find package "github.com/pkg/errors" in any of:
> 	/usr/lib/go/src/pkg/github.com/pkg/errors (from $GOROOT)
> 	/home/pi/git-lfs/src/github.com/pkg/errors (from $GOPATH)
> src/github.com/git-lfs/git-lfs/subprocess/subprocess.go:13:2: cannot find package "github.com/rubyist/tracerx" in any of:
> 	/usr/lib/go/src/pkg/github.com/rubyist/tracerx (from $GOROOT)
> 	/home/pi/git-lfs/src/github.com/rubyist/tracerx (from $GOPATH)
>

**Comment by Gergosz2** [comment]
@fiddike 's answer does the trick.

First of all you need go version 1.8. On raspbian the  `sudo apt-get install golang` installs the version 1.3.3, which is not suitable to get and also to build the source. 

So these are the steps you need to do:
1, remove the previous golang package
2, get the latest one from  [here](https://storage.googleapis.com/golang/go1.8.linux-armv6l.tar.gz) for  arm based machines
3,  extract it into /usr/local (it is the default) using `tar -C /usr/local -xzf go1.8.linux-armv6l.tar.gz` 
4, add it to your path using `echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.bashrc`
5, reboot
6, check the go version using `go version`. It should be go1.8 linux\arm
7, then 
```
mkdir /root/gocode
export GOPATH=/root/gocode
go get github.com/github/git-lfs
cp gocode/bin/git-lfs /usr/bin
```


And you are ready.

**Comment by vervaekejonathan** [comment]
@Gergosz2 
That takes me further, but now i'm receiving the following error

> root@raspberrypi:~# go get github.com/github/git-lfs
> # runtime
> /usr/local/go/src/runtime/os_linux.go:27: _FUTEX_WAIT redeclared in this block
> 	previous declaration at /usr/local/go/src/runtime/os1_linux.go:22
> /usr/local/go/src/runtime/os_linux.go:28: _FUTEX_WAKE redeclared in this block
> 	previous declaration at /usr/local/go/src/runtime/os1_linux.go:23
> /usr/local/go/src/runtime/os_linux.go:36: futexsleep redeclared in this block
> 	previous declaration at /usr/local/go/src/runtime/os1_linux.go:31
> /usr/local/go/src/runtime/os_linux.go:67: futexwakeup redeclared in this block
> 	previous declaration at /usr/local/go/src/runtime/os1_linux.go:62
> /usr/local/go/src/runtime/os_linux.go:83: getproccount redeclared in this block
> 	previous declaration at /usr/local/go/src/runtime/os1_linux.go:78
> /usr/local/go/src/runtime/os_linux.go:112: _CLONE_VM redeclared in this block
> 	previous declaration at /usr/local/go/src/runtime/os1_linux.go:104
> /usr/local/go/src/runtime/os_linux.go:113: _CLONE_FS redeclared in this block
> 	previous declaration at /usr/local/go/src/runtime/os1_linux.go:105
> /usr/local/go/src/runtime/os_linux.go:114: _CLONE_FILES redeclared in this block
> 	previous declaration at /usr/local/go/src/runtime/os1_linux.go:106
> /usr/local/go/src/runtime/os_linux.go:115: _CLONE_SIGHAND redeclared in this block
> 	previous declaration at /usr/local/go/src/runtime/os1_linux.go:107
> /usr/local/go/src/runtime/os_linux.go:116: _CLONE_PTRACE redeclared in this block
> 	previous declaration at /usr/local/go/src/runtime/os1_linux.go:108
> /usr/local/go/src/runtime/os_linux.go:116: too many errors
> root@raspberrypi:~# go version
> go version go1.8 linux/arm
>

**Comment by vervaekejonathan** [comment]
Removing /usr/local/go and reinstalling Go did the trick, thanks!
