### ISSUE TITLE
Integration tests randomly fail with Go 1.5 (batch related)

### ISSUE THREAD

**Issue by sinbad** [github/git-lfs#625]
I've been getting random failures in any one of a handful of batch-related integration tests recently and I've realised that they only seem to happen when using Go 1.5. I can't reproduce them when switching back to 1.4.

Adopting Go 1.5 is important not only for the vast performance improvements in the GC but because 1.4 has a bug which prevents using LFS API URLs which include a username (https://github.com/golang/go/issues/11399). 

The errors can occur even when you're using GIT_LFS_TEST_MAXPROCS=1 so it's not a race condition between tests. It is however always in one of the batch tests (not the same one, and not always in the same command), the common response is:

```
1 of 1 files) 11 B / 11 B                                                     Error uploading file common1.dat (2bc27d3512c2b3ab35b75244a7c5a7508610096aed67d64d65b11b5574b897d9)

    Errors logged to /Users/steve/projects/Go/src/github.com/github/git-lfs/tmp/test-pre-push.sh-63176/missing-but-on-server-batch/.git/lfs/objects/logs/20150902T101809.825928472.log
```

Repeating just the single test doesn't reproduce it. Since GIT_LFS_TEST_MAXPROCS=1 still does, I suspect it might be some some leftover state issue on the test server in batch mode, although I don't know why Go 1.5 would trigger it.

**Comment by sinbad** [comment]
I'll be looking into this further myself when I get the chance, just recording it here in case anyone else starts to see it.

**Comment by technoweenie** [comment]
I noticed this yesterday too when I setup a travis build with go 1.5: https://travis-ci.org/github/git-lfs/builds/78316038

**Comment by sinbad** [comment]
Current working theory is that it's because Go 1.5 is now genuinely using multiple cores all the time and not just using co-operative multitasking on one core when hitting syscalls etc. I've found one specific instance I think is dodgy, in TransferQueue.transferWorker:

```
func (q *TransferQueue) transferWorker() {
	for transfer := range q.transferc {
		cb := func(total, read int64, current int) error {
			q.meter.TransferBytes(q.transferKind, transfer.Name(), read, total, current)
			return nil
		}

		if err := transfer.Transfer(cb); err != nil {
			q.errorc <- err
		} else {
			oid := transfer.Oid()
			for _, c := range q.watchers {
				c <- oid // <------- A. RECEIVER DOESN'T NECESSARILY HAPPEN BEFORE B.
			}
		}

		q.meter.FinishTransfer(transfer.Name())

		q.wait.Done() // <------- B.
	}
}
```

Therefore watchers on the transfer channel which then Wait() cannot be certain that all transfer notifications are delivered before q.Wait() exits, when multiple cores are involved.  Example:

```
	transferc := checkQueue.Watch()
	go func() {
		for oid := range transferc {
			fmt.Fprintf(os.Stderr, "EXISTSONSERVER: |%v|\n", oid)
			skipObjects[oid] = struct{}{}
		}
	}()
	checkQueue.Wait()
```
skipObjects may not be complete after Wait() in a multicore runtime. I can fix this instance of it, I think the others may have been caused by what I fixed in #627 but I'll have to check.

In general the queue's Wait() may no longer really make sense any more, instead a user of the queue needs to sync on the close of the transfer channel.

**Comment by rubyist** [comment]
Yep that makes sense, especially when using the Watch stuff with an extra goroutine.

**Comment by sinbad** [comment]
I've updated #627, both fixes together now resolve this issue.

**Comment by sinbad** [comment]
Fixed by https://github.com/github/git-lfs/commit/9f58bced4ff42babff52c4376bc7385aac209041
