### ISSUE TITLE
Git Clone of LFS repo seems very slow due to single-file pulling

### ISSUE THREAD

**Issue by SubtGames-GoCD** [github/git-lfs#639]
I've been using Git LFS for the past couple of months and loving it so far - Fantastic job.

I've been doing a lot of cloning of our internal LFS-enabled repo recently and I've noticed that one of the key bottlenecks on first clone is that it appears that Git is downloading each LFS'd file individually, which is incredibly slow when you start to build up 1000+ ~1MB files.

Is there an improvement for this on the current roadmap?

**Comment by technoweenie** [comment]
We've been kicking around some ideas here: https://github.com/github/git-lfs/issues/616.  The bad news is there's no easy solution without requiring special Git LFS commands or changing how Git works. We have an idea for an interim solution involving wrapped commands like `git lfs clone`.

**Comment by SubtGames-GoCD** [comment]
Hrm, I like that idea. I'll close this ticket and focus on the linked one, thanks.
