### ISSUE TITLE
Question: How to revert tracked pointer files?

### ISSUE THREAD

**Issue by Vdragon** [github/git-lfs#641]
Hi, I've tried Git LFS on [my GitBook project](https://github.com/Vdragon/Hello_Git_World_) and found that GitBook can't access all pictures I tracked using Git LFS, I tried to stop using Git LFS, but found no way to revert my previous tracked pointer files using `git lfs uninit` `git lfs untrack` `git rm`... after I move those files back it still lists as tracked by Git LFS with `git lfs ls-files`, how can I opt out the whole Git LFS stuff from my repo?

**Comment by technoweenie** [comment]
1. Remove all `filter.lfs.*` git config entries with `git lfs uninit`.
2. Clear any any attributes that use the lfs filter in `.gitattributes` by running `git lfs untrack` for each file type, or deleting `.gitattributes` if LFS is all you ever used it for.

After this, any added files will go straight to git.

**Comment by Vdragon** [comment]
@technoweenie 
I later end up LFS pointer files in my working directory and have to recover all my pictures from .git/lfs using the sha1 hash stored in those pointers manually.

However thanks for helping, I will try this out when I know better about Git LFS

**Comment by yustiks** [comment]
Is there any way I can return my files back from pointers?

**Comment by ggrrll** [comment]
to answer question  by @yustiks , what would be the workflow , to be able to work with (few) specific files? 

@technoweenie  would `git lfs migrate export` be a good option?  
thanks

https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-migrate.adoc#migrate-from-git-lfs

**Comment by ggrrll** [comment]
related to #957  #910

**Comment by ggrrll** [comment]
wrote a little script, in case 'nothing' works -- given you still have data in .git/lfs

https://github.com/git-lfs/git-lfs/issues/5463#issuecomment-1674511319
