### ISSUE TITLE
Install Git LFS for all users on Windows

### ISSUE THREAD

**Issue by larsxschneider** [github/git-lfs#643]
It looks like as Git LFS is installed only per user on Windows. Could you add a install switch to make Git LFS available to all users on a system?

I am no Windows user, but with a little hint I might be able to create the appropriate PR.

/CC @joshvera

**Comment by technoweenie** [comment]
We're working on a gui installer: https://github.com/github/git-lfs/pull/642

Now, i'm not sure how this will affect multiple users on the same computer. Both the current `install.bat` script and the gui uploader install stuff to `c:\program files`. So it should be available to everyone. We could try changing `git lfs init` to use `--system` instead of `--global`. Is that what you're asking about?

**Comment by larsxschneider** [comment]
Great to hear you are working on a installer! I am no Windows expert, but I don't think you install into `c:\program files`. [You are using `%LOCALAPPDATA%`](https://github.com/github/git-lfs/blob/60eba2d3b0aed23c0b132ba6fe27dc639b016143/script/install.bat.example#L34) which installs into ` C:\Users\<user-name>\AppData\Local`. More info [here](https://msdn.microsoft.com/en-us/library/aa369768(v=vs.85).aspx). In addition I think we need to add the Git LFS to the system PATH.

**Comment by technoweenie** [comment]
The installer [attempts to detect common locations for Git](https://github.com/github/git-lfs/blob/nsis/script/nsis/installer.nsi#L19-L33). I figure if they have git setup, I can install `git-lfs.exe` next to it and not worry about the PATH.

**Comment by technoweenie** [comment]
How's this work? https://github.com/github/git-lfs/releases/download/v0.6.0/git-lfs-windows-0.6.0.zip

**Comment by larsxschneider** [comment]
The installer worked for me! I also wait for feedback from my team members with more Windows experience :smile: !

One minor thing: I noticed that README.md and CHANGELOG.md have Unix line endings... consequently the files look weird if someone opens them on Windows using Notepad. :scream: :smile:

**Comment by technoweenie** [comment]
> I noticed that README.md and CHANGELOG.md have Unix line endings...

That sucks. I'm not going to change them in the repo. Git LFS contributors should be using some unix shell. I think "Git Bash" on Windows doesn't have this problem.

However, I think you're referring to the readme and changelog files that are included in the zips. I think we should _at least_ fix those line endings. We could even convert the markdown to HTML...

**Comment by larsxschneider** [comment]
Yes, I am referring to the zip file. BTW: Why do you zip up the content anyways? Why not just distributing the nsi installer exe file? Then the users can install it right away. Git for Windows does the same:
https://github.com/git-for-windows/git/releases/download/v2.5.2.windows.2/Git-2.5.2.2-64-bit.exe

**Comment by technoweenie** [comment]
No good reason. I can try that next.

**Comment by davidbernard04** [comment]
@technoweenie, so what's the status of this issue? Because I'm trying to setup a Windows build agent with LFS support and I think having a `git lfs install` that use **--system** instead of **--global** would help a lot. Because the LFS hooks are installed from my account only, and does not affect all other accounts (like the one used by my build agent).

**Comment by technoweenie** [comment]
@davidbernard04: Currently still an open issue without any PRs. However, it's just using `git config`. You can workaround it by using:

```
$ git config --system filter.lfs.required "true"
$ git config --system filter.lfs.clean "git-lfs clean %f"
$ git config --system filter.lfs.smudge "git-lfs smudge %f"
```

Also, I'd appreciate you starting new discussions in new issues, and not in an unrelated thread. Thanks!

**Comment by davidbernard04** [comment]
@technoweenie thanks a lot for the workaround! I thought this was related to the current thread, as "Install Git LFS for all users on Windows" applies for the "git lfs install" too no?

**Comment by technoweenie** [comment]
It's more about the windows specific install process. This 3 month old thread was before there was any kind of git lfs installer gui for windows, and installation was a mess.

**Comment by davidbernard04** [comment]
@technoweenie, OK I see! Then I have a question about your current Windows installer, which installs git-lfs.exe under `C:\Program Files (x86)\Git\bin` alongside the other git binaries, but for some reason only `C:\Program Files (x86)\Git\cmd` is in the path "by default", which also contain a git.exe (don't know why).

In other words, even using your installer, I still have to manually update the PATH or copy the git-lfs.exe under the "cmd" folder.

**Comment by technoweenie** [comment]
The installer goes with the most common settings. If your isn't setup like that, you'll have to put it in the right place and change the system path yourself. There is a PR for a new windows installer: #875. I don't use Windows, so I'm relying on help from windows developers to get the installer in decent shape.

**Comment by technoweenie** [comment]
Things should be much better now with the current installer.
