### ISSUE TITLE
[v0.60] Git LFS Pull on newly cloned repo causes 'Error for POST objects/batch' error

### ISSUE THREAD

**Issue by strich** [github/git-lfs#660]
[Running Git LFS v0.60]

I have a Git LFS active repo that I have cloned using non-git-lfs commands due to Jenkins CI plugin limitations. After this is done I had planned to run *git lfs pull* to download the LFS-managed files. However in doing so I get the following error:

> (0 of 534 files) 0 B / 446.51
> Error for POST objects/batch
> Error for POST objects/batch
> Error for POST objects/batch
> Error for POST objects/batch
> Error for POST objects/batch
> Error for POST objects/batch

After clearing the git lfs logs and trying git lfs pull again the logs were empty.

I'm using a GitHub private repo.

I'm not sure how to debug this further. Happy to dig deeper given a few pointers (How does one enable verbose logging for Git in Windows?).

**Comment by strich** [comment]
I tried git lfs init and received:

> PS C:\Jenkins\workspace\Star Wards Build\Star-Wards-Prototype> git lfs init
The filter.lfs.clean attribute should be "git-lfs clean %f" but is "git lfs clean %f"
Run `git lfs init --force` to reset git config.

Running git lfs init --force worked but didn't resolve the initial issue.

**Comment by strich** [comment]
Okay. I've sort of resolved the problem - The way the Jenkins Git plugin works causes the repo to have no 'origin' remote setup - It sets up a remote under another name. Renaming the remote to origin resolved this mysterious error.

I'm going to leave this issue open for the moment and ask that error reporting be improved in future - This should really return like the normal git pull command does under these conditions.

In addition to this, does git lfs pull take arguments like git pull does? Eg the remote name or URL?

**Comment by technoweenie** [comment]
Yes, `git lfs pull other-remote` should work.

**Comment by technoweenie** [comment]
I think there are two things at play here:

1. fetch/pull don't seem to respect the tracking graph.
2. Error messages should suggest that the remote is wrong. Maybe even specify what remote they're accessing.

```bash
$ git lfs fetch
Fetching some-branch
(2 of 4 files) 50.85 KB / 136.40 KB                                                                                                                                                                                                                                                                                                                                        
Not Found
Docs: https://github.com/contact
Not Found
Docs: https://github.com/contact

# explicit remote
$ git lfs fetch other-remote
Fetching some-branch
(2 of 4 files) 62.76 KB / 136.40 KB         
```

**Comment by sinbad** [comment]
> fetch/pull don't seem to respect the tracking graph.

They actually do, see their use of git.CurrentRemote, which I altered specifically to reflect the tracking remote. My suspicion is that Jenkins doesn't configure a tracking branch OR origin.

**Comment by strich** [comment]
> My suspicion is that Jenkins doesn't configure a tracking branch OR origin.
This is correct. The Jenkins git plugin checks out a specific commit to be left in a detached state, and the remote it does create is not 'origin' and not a default.

**Comment by sinbad** [comment]
Proposed alternate behaviour for 1.0.1; if not on a branch which is tracking a remote branch, and there is no `origin` remote:

* If there is only 1 remote defined, use that
* If there is >1 remote defined, exit with a clearer error

**Comment by strich** [comment]
That sounds ideal to me. Agreed.
