### ISSUE TITLE
All of the git lfs man pages use 'git-lfs' commands rather than 'git lfs'

### ISSUE THREAD

**Issue by strich** [github/git-lfs#661]
I assume this has something to do with platform differences, but in Windows all Git LFS commands are run with `git lfs [command]`, not `git-lfs [command]`.

**Comment by strich** [comment]
In addition to the above, it looks like the help text in Windows is outdated. The Git lfs pull command, for example, does not show that it is possible to supply the remote name argument, whereas the man page does.

**Comment by technoweenie** [comment]
Blah, thanks for the report :)

**Comment by technoweenie** [comment]
So, the problem here was that we were relying on the CLI framework's built-in help output. While the tool IS technically called `git-lfs`, most users will interact with `git lfs` instead. #665 replaces the help output with tweaked man pages. Thanks for the report!
