### ISSUE TITLE
Git LFS pull doesn't download all of the files, and no errors reported

### ISSUE THREAD

**Issue by strich** [github/git-lfs#663]
I'm really struggling to figure this one out - I'm running a build via Jenkins and its Git plugin performs a repo clone/update in a very specific way that cannot be modified greatly (I cannot make it use `git clone`, for example).

It doesn't support Git LFS at all, which is fine. It basically leaves the repo in a detached state (This is fine) and all files managed under Git LFS are still only link files.

This is its process:
>Started by user blah
Building remotely on blah Home PC (Windows) in workspace C:\Jenkins\workspace\Repo Build
Cloning the remote Git repository
Using shallow clone
Cloning repository git@github.com:Company/Repo.git
 > git init C:\Jenkins\workspace\Repo Build\Repo-Prototype # timeout=10
Fetching upstream changes from git@github.com:Company/Repo.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git -c core.askpass=true fetch --tags --progress git@github.com:Company/Repo.git +refs/heads/*:refs/remotes/Github-Repo/* --depth=1
 > git config remote.Github-Repo.url git@github.com:Company/Repo.git # timeout=10
 > git config --add remote.Github-Repo.fetch +refs/heads/*:refs/remotes/Github-Repo/* # timeout=10
 > git config remote.Github-Repo.url git@github.com:Company/Repo.git # timeout=10
Fetching upstream changes from git@github.com:Company/Repo.git
using GIT_SSH to set credentials 
 > git -c core.askpass=true fetch --tags --progress git@github.com:Company/Repo.git +refs/heads/*:refs/remotes/Github-Repo/*
 > git rev-parse "refs/remotes/Github-Repo/master^{commit}" # timeout=10
 > git rev-parse "refs/remotes/Github-Repo/Github-Repo/master^{commit}" # timeout=10
Checking out Revision c6c921ecdf76416a4ddd3a835e54c77e60d1a1b0 (refs/remotes/Github-Repo/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f c6c921ecdf76416a4ddd3a835e54c77e60d1a1b0
 > git rev-list c6c921ecdf76416a4ddd3a835e54c77e60d1a1b0 # timeout=10

All good so far. I run the following commands after this:
>git remote add origin git@github.com:Company/Repo.git
git lfs pull

It seems to complete successfully with:
> (534 of 534 files) 443.10 MB / 446.51 MB

However a large number of the files are not replaced with their link files. Some are. But definitely not all.

This only occurs if I let Jenkins clone the repo the way it does above. If I do it manually via `git clone` & `git lfs pull` it properly gets all the files.

**Comment by strich** [comment]
Interestingly, during the Jenkins-run `git checkout` I can see all of the lfs files failing to download with:
> PS C:\Jenkins\workspace\Repo Build\Repo> git lfs logs last
git-lfs/0.6.0 (GitHub; windows amd64; go 1.5.1; git 183bdc8)
git version 1.9.5.msysgit.1

> $ git-lfs.exe smudge Repo/Assets/TileWorldCreator/_Documentation/img/doc/saveloadmap.png
Error accessing media: Repo/Assets/TileWorldCreator/_Documentation/img/doc/saveloadmap.png (8f9b8fb73df7
5d4a3bdcc7c9611ebfe19f7e96f33277c6121bbbae75db051162)

> Error for GET objects/8f9b8fb73df75d4a3bdcc7c9611ebfe19f7e96f33277c6121bbbae75db051162
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/lfs/errors.go:525 +0x87
github.com/github/git-lfs/commands.logPanicToWriter(0x26941e8, 0xc082130010, 0x2ab02c0, 0xc082120260)
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:181 +0xf86
github.com/github/git-lfs/commands.logPanic(0x2ab02c0, 0xc082120260, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:145 +0x428
github.com/github/git-lfs/commands.handlePanic(0x2ab02c0, 0xc082120260, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:120 +0x55
github.com/github/git-lfs/commands.LoggedError(0x2ab02c0, 0xc082120260, 0x8e4b40, 0x1e, 0xc082069ce0, 0x2, 0x2)
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:70 +0x89
github.com/github/git-lfs/commands.smudgeCommand(0xab1da0, 0xc082007780, 0x1, 0x1)
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/command_smudge.go:69 +0xd18
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xab1da0, 0xc0820076d0, 0x1, 0x1, 0x0,
0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x40a
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xab2aa0, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x59a
github.com/github/git-lfs/commands.Run()
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:85 +0x2a
main.main()
        C:/Users/techn/go/src/github.com/github/git-lfs/git-lfs.go:9 +0x1b

I'm wondering under what conditions it causes that to fail?

**Comment by strich** [comment]
Okay a little bit more info - I did another couple of rounds of testing and I've found that I can get the repo to fully sync. But only after I do `get lfs pull` twice:

>PS C:\Jenkins\workspace\Repo Build\Repo> git remote add origin
ar-Wards-Prototype.git
PS C:\Jenkins\workspace\Repo Build\Repo> git lfs pull
(534 of 534 files) 435.88 MB / 446.51 MB
Error buffering media file.
Error buffering media file.
Error buffering media file.
PS C:\Jenkins\workspace\Repo Build\Repo> git lfs logs last
No logs to show
PS C:\Jenkins\workspace\Repo Build\Repo> git lfs pull
(3 of 534 files) 12.91 MB / 446.51 MB
PS C:\Jenkins\workspace\Repo Build\Repo> git lfs logs last
No logs to show

Note that way more files than the 3 `Error buffering media file` errors suggest might be broken. I also only saw those errors on the last test I did.

I'm not sure if any of this information allows you to reproduce and resolve. I'm happy to perform more complex debugging if I could get some pointers on how to do so.

**Comment by technoweenie** [comment]
> But I am led to understand that a git checkout, even without git lfs init should still download lfs files?

`git checkout` only downloads the files automatically if the smudge filter is setup by `git lfs init`. This only needs to be run once on the server to get in the global config though. However, you're better off relying on `git lfs pull` because it will download the files in a single command, with some concurrency. Well, when whatever bug you're running into here is fixed :)

**Comment by strich** [comment]
>Well, when whatever bug you're running into here is fixed :)

Oh? How so?

**Comment by strich** [comment]
Well the odd thing here is that the `git checkout` run by Jenkins is still running the smudge filter, but it is failing horribly, as per the above errors. If I do it manually in the console it downloads the files just fine.

Something I've failed to note too - The Jenkins agent all this is run on is my Windows dev machine at the moment. So its using all the same global git config I do.

**Comment by technoweenie** [comment]
So `fetch` or `pull` should only be downloading what's in the current checkout. Do you really have 534 files in the checkout?

    # try this in "Git Bash"
    $ git lfs ls-files | wc -l

Also, what does the pointer have for "Repo/Assets/TileWorldCreator/_Documentation/img/doc/saveloadmap.png" at that commit?  Is it OID 8f9b8fb73df75d4a3bdcc7c9611ebfe19f7e96f33277c6121bbbae75db051162?

I noticed that the stack trace of the "Error accessing media" error in the second post points to [the smudge command](https://github.com/github/git-lfs/blob/ccbc6f60692180ff345327d352525a38d5f88b1f/commands/command_smudge.go#L69). We need to make sure that the stack trace is captured deeper in the stack. Probably inside `ptr.Smudge()` call a few lines above.  I think the true error is being swallowed up. I can cut you a custom release to get more details about it.

Also, it looks like you're on windows. How was the new installer? 

>> Well, when whatever bug you're running into here is fixed :)
>
> Oh? How so?

Are you asking specifically why `git lfs pull` is preferable to letting the the smudge filter runs? I was just saying that what you're doing _should_ work. And I'm trying to figure out why it's not.

> Something I've failed to note too - The Jenkins agent all this is run on is my Windows dev machine at the moment. So its using all the same global git config I do.

Hmm, can you get Jenkins to run as a separate user? That would at least match a more standard Jenkins setup.

**Comment by strich** [comment]
Do you really have 534 files in the checkout?
Yep.

>Is it OID 8f9b8fb73df75d4a3bdcc7c9611ebfe19f7e96f33277c6121bbbae75db051162?
Yep.

>I can cut you a custom release to get more details about it.
Happy to assist.

>How was the new installer?
Seemed fine. :)

>Are you asking specifically why...
I misread your comment. Ignore. :)

>Hmm, can you get Jenkins to run as a separate user? That would at least match a more standard Jenkins setup
I could. It'd be terribly annoying to do right now though. I won't be doing this once it's all working - It'll have its own dedicated machine at some point.

**Comment by DanielRose** [comment]
I'm running into the same bug (and "resolution" by calling `git lfs pull` twice). In my case this is on a TeamCity 9.1.5, connected to a GitLab 8.5.8. It uses similar steps to the Jenkins run above:

[16:54:57]revision: 838a69bd6e23021fd725da38e517abe2d5d11e73
[16:54:58][C:\TeamCity_BuildAgent_1\system\git\git-52DEED56.git]: "C:\Program Files\Git\bin\git.exe" show-ref
[16:54:58][C:\TeamCity_BuildAgent_1\system\git\git-52DEED56.git]: "C:\Program Files\Git\bin\git.exe" -c core.askpass=C:\TeamCity_BuildAgent_1\temp\buildTmp\pass2664196739912727160.bat ls-remote origin
[16:54:58][C:\TeamCity_BuildAgent_1\system\git\git-52DEED56.git]: "C:\Program Files\Git\bin\git.exe" show-ref refs/heads/master
[16:54:58][C:\TeamCity_BuildAgent_1\system\git\git-52DEED56.git]: "C:\Program Files\Git\bin\git.exe" show-ref refs/heads/master
[16:54:58][C:\TeamCity_BuildAgent_1\work\86c85a94c8eb2058]: "C:\Program Files\Git\bin\git.exe" config remote.origin.url
[16:54:58][C:\TeamCity_BuildAgent_1\system\git\git-52DEED56.git]: "C:\Program Files\Git\bin\git.exe" pack-refs --all
[16:54:58][C:\TeamCity_BuildAgent_1\work\86c85a94c8eb2058]: "C:\Program Files\Git\bin\git.exe" config core.sparseCheckout false
[16:54:58][C:\TeamCity_BuildAgent_1\work\86c85a94c8eb2058]: "C:\Program Files\Git\bin\git.exe" show-ref
[16:54:59][C:\TeamCity_BuildAgent_1\work\86c85a94c8eb2058]: "C:\Program Files\Git\bin\git.exe" -c core.askpass=C:\TeamCity_BuildAgent_1\temp\buildTmp\pass4802293131856411253.bat ls-remote origin
[16:54:59][C:\TeamCity_BuildAgent_1\work\86c85a94c8eb2058]: "C:\Program Files\Git\bin\git.exe" show-ref refs/remotes/origin/master
[16:54:59][C:\TeamCity_BuildAgent_1\work\86c85a94c8eb2058]: "C:\Program Files\Git\bin\git.exe" log -n1 --pretty=format:%H%x20%s 838a69bd6e23021fd725da38e517abe2d5d11e73 --
[16:54:59][C:\TeamCity_BuildAgent_1\work\86c85a94c8eb2058]: "C:\Program Files\Git\bin\git.exe" branch
[16:54:59][C:\TeamCity_BuildAgent_1\work\86c85a94c8eb2058]: "C:\Program Files\Git\bin\git.exe" reset --hard 838a69bd6e23021fd725da38e517abe2d5d11e73
[16:55:00][C:\TeamCity_BuildAgent_1\work\86c85a94c8eb2058]: "C:\Program Files\Git\bin\git.exe" branch --set-upstream-to=refs/remotes/origin/master

The output from git lfs env:
[16:55:01]git-lfs/1.1.0 (GitHub; windows amd64; go 1.5.1; git 258acf1)
[16:55:01]git version 2.7.0.windows.1
[16:55:01]
[16:55:01]Endpoint=https://drose@gs2-git.inform-ac.com/gui/tools.git/info/lfs (auth=none)
[16:55:01]LocalWorkingDir=C:\TeamCity_BuildAgent_1\work\86c85a94c8eb2058
[16:55:01]LocalGitDir=C:\TeamCity_BuildAgent_1\work\86c85a94c8eb2058\.git
[16:55:01]LocalGitStorageDir=C:\TeamCity_BuildAgent_1\work\86c85a94c8eb2058\.git
[16:55:01]LocalMediaDir=C:\TeamCity_BuildAgent_1\work\86c85a94c8eb2058\.git\lfs\objects
[16:55:01]TempDir=C:\TeamCity_BuildAgent_1\work\86c85a94c8eb2058\.git\lfs\tmp
[16:55:01]ConcurrentTransfers=3
[16:55:01]BatchTransfer=true
[16:55:01]TEAMCITY_GIT_PATH=C:\Program Files\Git\bin\git.exe
[16:55:01]git config filter.lfs.smudge = ""
[16:55:01]git config filter.lfs.clean = ""

First git lfs pull:
[16:55:16]Git LFS: (0 of 432 files) 0 B / 207.92 MB
...
[16:55:16]Git LFS: (432 of 432 files) 205.24 MB / 207.92 MB  

Second git lfs pull:
[16:55:18]Git LFS: (0 of 432 files) 0 B / 207.92 MB
[16:55:18]Git LFS: (0 of 432 files) 0 B / 207.92 MB

**Comment by technoweenie** [comment]
@DanielRose Try the latest version, v1.1.2. There was a race condition fixed in v1.1.1.

**Comment by DanielRose** [comment]
@technoweenie Thanks. Once I'm back at work (in a week) I'll contact the admins to update the software.

**Comment by DanielRose** [comment]
@technoweenie I've upgraded to 1.1.2, and now it works fine after the first pull. Can you mark this issue as fixed?

**Comment by technoweenie** [comment]
Booya!  Thanks for reporting back :)

**Comment by technoweenie** [comment]
Hey @strich, are we good to close? Forgot this was your issue originally.

**Comment by strich** [comment]
Yeah.

**Comment by technoweenie** [comment]
Oh good, so I didn't completely leave you hanging. Thanks!

**Comment by MarkEWaite** [comment]
Jenkins [git plugin 3.1.0](https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin#GitPlugin-ChangeLog) released 4 Mar 2017 includes support for git large files.  Git lfs must be installed on each agent which will work with large files, and command line git (the default) needs to be used (rather than JGit).
