### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by zoeweidz** [github/git-lfs#667]
An old colleague sent me the following email:

> At River Studios, we're doing quite a bit of Virtual Reality development, and help support a Virtual Reality accelerator program, River. VR requires quite a bit of large files and I was wondering if you could help point me in the right direction to get on the Large File Storage beta. (which was announced here: https://github.com/early_access/git-lfs ) I signed up on the page using my hardcoded2 account, but have not seen any movement.   We're looking to switch from bitbucket, but without large file support, some of our repositories will not fit under the 1GB limit of github.   Thanks a million!  Alex  

No idea what to tell him, can someone help provide some guidance?

Thanks!

**Comment by technoweenie** [comment]
Hey @zoeweidz, send them to https://github.com/contact for all GitHub Support related questions.

**Comment by zoeweidz** [comment]
Thanks @technoweenie will do
