### ISSUE TITLE
Broken download link

### ISSUE THREAD

**Issue by allejo** [github/git-lfs#688]
I can't seem to find the repository for the LFS website, so I'll leave this here to bring it to your attention. But the giant download button for Windows uses the wrong link. It links to a nonexistent .zip file where it should link to the .exe file listed in the release.

![broken link](https://cloud.githubusercontent.com/assets/1246453/10231341/0e082b2e-6837-11e5-8155-314346459c64.PNG)

**Comment by nuclearsandwich** [comment]
Thanks for the report. I've opened an internal issue on the Git LFS website.

**Comment by nuclearsandwich** [comment]
In the meantime you can grab the release from https://github.com/github/git-lfs/releases/tag/v1.0.0

**Comment by leereilly** [comment]
Thanks, @allejo. It should be working now :metal:

**Comment by jblotus** [comment]
link is broken for me

**Comment by technoweenie** [comment]
@jblotus What OS? What's the exact broken link?

**Comment by jblotus** [comment]
@technoweenie sorry for the drive by report. i am on windows 7. the broken link is the "Install the client to get started" link.

![image](https://cloud.githubusercontent.com/assets/382230/13330608/8f5afd24-dbc7-11e5-9bcb-30d4aacaef89.png)

**Comment by jblotus** [comment]
the broken link is linking to https://github.com/github/git-lfs/releases/download/v1.1.1/git-lfs-windows-amd64-1.1.1.exe

the working link on the download button links to this:
https://github.com/github/git-lfs/releases/download/v1.1.1/git-lfs-windows-1.1.1.exe

**Comment by technoweenie** [comment]
Ah, thanks. Apparently I updated **big download button**, but not the linked text.

**Comment by itsho** [comment]
Currently, the link is NOT broken, but it is directed to **2.9.1** and not directed to the latest version **2.9.2**

**Comment by bk2204** [comment]
Thanks for pointing this out.  I've pushed a fix, and it should update in the next few minutes.
