### ISSUE TITLE
Doesn't work if remote URL contains shorthands

### ISSUE THREAD

**Issue by williamboman** [github/git-lfs#693]
For example, I've got this shorthand in my `.gitconfig`,

```
[url "git@github.com:williamboman/"]
    insteadOf = "me@gh";
```

`git-lfs` will not expand shorthands at all;

```sh
$ git config --local --get remote.origin.url
me@gh:test

$ git push
(0 of 1 files) 0 B / 130.26 MB
Post https://gh/test.git/info/lfs/objects/batch: dial tcp: lookup gh: no such host
error: failed to push some refs to 'git@github.com:williamboman/test'
```

**Comment by technoweenie** [comment]
Hi, I'm going through old issues I missed and responding to them. There is a fix for this in https://github.com/github/git-lfs/pull/1117, but it still needs some work.
