### ISSUE TITLE
dial tcp/ i/o timeout and EOF errors on pushing 1GB repo?

### ISSUE THREAD

**Issue by AndrewJDR** [github/git-lfs#695]
When doing an initial push of a repo with 1GB worth of large files, I can't successfully 'git push' the whole thing in one go. I always end up with errors like this:
```
Post https://api.github.com/..../verify: dial tcp: i/o timeout
Post https://api.github.com/..../verify: dial tcp: i/o timeout
Post https://api.github.com/..../verify: EOF
```
After retrying the 'git push' a couple more times, it eventually succeeds. I've tried this initial push a few times now, and I always end up needing to run 'git push' several times.
Any tips for debugging this?

**Comment by hf2186** [comment]
I have had a similar issue and did the same thing. Took me a few pushes.

**Comment by technoweenie** [comment]
Git LFS uses what I thought was a pretty generous 5s timeout for tcp connections. Is it always that `/verify` endpoint, or are there other affected URLs too?

**Comment by hf2186** [comment]
4e3edc9c88faa76de10edfbf23de46d9b6b76edb8/verify: dial tcp: i/o timeout

yeah always on verify for me.

**Comment by hons82** [comment]
I get only the EOF, but when I try to send a Put to .../objects/{oid}: EOF
Is there a way to change the timeout in a config?

**Comment by technoweenie** [comment]
@hons82: https://github.com/github/git-lfs/blob/3671987c9b346cb7e453d2ad07a0493152487239/docs/man/git-lfs-config.5.ronn#L35-L49. It needs v1.1.1+.

**Comment by hons82** [comment]
THX
I'll try with that

**Comment by bretonics** [comment]
I get the same errors, and it makes my internet go down
`Post https://api.github.com/..../verify: dial tcp: i/o timeout`
`Post https://api.github.com/..../verify: dial tcp: i/o timeout`

**Comment by jaredmharris** [comment]
I'm also getting this error that @bretonics mentioned. Any update on this? I have Git LFS 1.2.1 and Git 2.9.2 installed.

**Comment by ttaylorr** [comment]
@jaredmharris Did you configure with https://github.com/github/git-lfs/blob/3671987c9b346cb7e453d2ad07a0493152487239/docs/man/git-lfs-config.5.ronn#L35-L49?

**Comment by kevincantu** [comment]
@ttaylorr @technoweenie do those timeouts have anything to do with SSH instead of HTTPS connections?

**Comment by technoweenie** [comment]
A timeout error like this is from LFS's HTTP client:

> Post https://api.github.com/..../verify: dial tcp: i/o timeout

However, there is an SSH timeout issue related to a long running `pre-push` hook, as discussed in #2428.
