### ISSUE TITLE
building with gccgo

### ISSUE THREAD

**Issue by zeldin** [github/git-lfs#696]
A build script to build this with only gccgo would be appreciated.

The portability of Google's go implementation is rather lacking...

**Comment by Tqelung** [comment]
A build script to build this with only gccgo would be appreciated.
The portability of Google's go implementation is rather lacking

**Comment by technoweenie** [comment]
Thanks for the request. I haven't seen any other requests for this, but I'd accept a patch that implements it.

**Comment by dankegel** [comment]
https://github.com/github/git-lfs/pull/1222 was merged... maybe you got your wish.
