### ISSUE TITLE
Cant push - error 403

### ISSUE THREAD

**Issue by pointcache** [github/git-lfs#697]
![image](https://cloud.githubusercontent.com/assets/5315202/10261166/48db23a6-6958-11e5-9bc2-a7627a546057.png)
I spend 6 hours already.
I managed to push one commit to branch without lfs enabled.
Installed lfs, now im stuck on this message 
```
git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags origin master:master
Pushing to https://pointcache@github.com/RaginBear/CaelDominis.git

Invalid status for POST https://pointcache@github.com/RaginBear/CaelDominis.git/info/lfs/objects/batch: 403
Invalid status for POST https://pointcache@github.com/RaginBear/CaelDominis.git/info/lfs/objects/batch: 403
Invalid status for POST https://pointcache@github.com/RaginBear/CaelDominis.git/info/lfs/objects/batch: 403




(0 of 246 files) 0 B / 235.20 MB                                               


error: failed to push some refs to 'https://pointcache@github.com/RaginBear/CaelDominis.git'

Completed with errors, see above.
```

Nothing helps. Every password everywhere is fine, i send emails to support but it seems they are sleeping (4 hours i wait response)

http://prntscr.com/8n4rph

i dont know what to do.

**Comment by theSoenke** [comment]
Same problem here

**Comment by irazasyed** [comment]
Same here!

Using Git version: `2.6.0`

**Comment by pointcache** [comment]
Pushing with lfs disabled just fine

**Comment by technoweenie** [comment]
Please send details to https://github.com/contact. Run the push like this:

```bash
# add 'GIT_CURL_VERBOSE=1' before your git command
$ GIT_CURL_VERBOSE=1 git push origin master
```

Before sending it to us, replace any "Authorization" lines:

```
# BAD
Authorization: Basic ZGaSFlajsdf;ljkasdf.asdf.as.d.....

# REPLACED
Authorization: Basic ...
```

**Comment by technoweenie** [comment]
I think the problem has to do with git remotes with the username in them. So if you're seeing a message like this:

    Invalid status for POST https://pointcache@github.com/RaginBear/CaelDominis.git/info/lfs/objects/batch: 403

Run this to fix it:

```bash
$ git remote rm origin
$ git remote add origin https://github.com/RaginBear/CaelDominis
```

The functionality was added in #626, but apparently breaks somewhere. We still need to dig into the exact cause. For now, just remove the username from the Git remote URL.

**Comment by pointcache** [comment]
thank you

**Comment by hartbit** [comment]
:+1: and @technoweenie 's suggestion does not help

**Comment by theSoenke** [comment]
also tried @technoweenie suggestion and it did not help

**Comment by technoweenie** [comment]
Did you try https://github.com/github/git-lfs/issues/697#issuecomment-145598782 ?

**Comment by technoweenie** [comment]
Actually, I'm closing this issue. If you need help with github.com, try these directions: https://github.com/github/git-lfs/issues/697#issuecomment-145598782

Otherwise, don't send stuff to GitHub support about other LFS servers. I'd suggest checking [chat](https://gitter.im/github/git-lfs) or spinning up [an issue](/github/git-lfs/issues/new) for your specific problem. Having multiple problems in a single thread will get confusing really quickly. Keep in mind that I can only provide help with the open source client, or the GitHub LFS server. 

If you don't know where to turn, feel free to post an issue with details, and we'll do our best.

**Comment by brianmingus** [comment]
also tried @technoweenie suggestion and it did not help

**Comment by cchamberlain** [comment]
@technoweenie solution fixed for me.

**Comment by nkatre** [comment]
@technoweenie solution DID NOT work for me.

**Comment by pointcache** [comment]
@nkatre if you are on windows try doing this 
$git config --global credential.helper wincred

**Comment by technoweenie** [comment]
Hey all, my workaround above was for a very specific API issue on GitHub. It's all fixed now on our server, so any 403 issues will not be solved by my suggestion. If you have other 403-related issues, please send details to a new Git LFS issue or https://github.com/contact if you want to keep it private. Though @pointcache is correct, having a functioning git credential helper will go a long way.

I'm locking this issue, it is not a catch-all to debug everyone's specific 403 issues. Things can get confusing when an issue has multiple people asking for different things. I'd prefer separate issues instead.

**Comment by samv** [comment]
I experienced this and landed on this issue.  For me, I got it to work by changing my git remote URL from rsh-style host/path ``github:username/project`` to the more verbose ``ssh://git@github.com/username/project``:

```
$ git lfs track peter\ gibbons\ hardhat.jpg
Tracking peter gibbons hardhat.jpg
$ git add peter\ gibbons\ hardhat.jpg
$ git commit -m 'Add a picture of relevance to our project'
[master c553eb1] Add a picture of relevance to our project
 1 file changed, 3 insertions(+)
 create mode 100644 peter gibbons hardhat.jpg
$ git ls-tree HEAD|grep peter
100644 blob 46f0d6e1dc5e1bef923f198305ce401ea9bf2424	peter gibbons hardhat.jpg
$ git cat-file blob 46f0d6e1dc5e1bef923f198305ce401ea9bf2424
version https://git-lfs.github.com/spec/v1
oid sha256:0cd23607e7828dec1fb7ef421b8041a7a6938f2e76755386521ad268bbffbabf
size 23318
$ git push origin HEAD:refs/heads/peter
(0 of 1 files) 0 B / 22.77 KB
Error for POST github:wearableintelligence/design-docs.git/info/lfs
error: failed to push some refs to 'github:wearableintelligence/design-docs'
$ git remote show origin
* remote origin
  Fetch URL: github:wearableintelligence/design-docs
  Push  URL: github:wearableintelligence/design-docs
  HEAD branch: master
  Remote branch:
    master tracked
  Local ref configured for 'git push':
    master pushes to master (fast-forwardable)
$ git config remote.origin.url ssh://git@github.com/wearableintelligence/design-docs
$ git push origin HEAD:refs/heads/peter
(1 of 1 files) 22.77 KB / 22.77 KB
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 466 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To ssh://git@github.com/wearableintelligence/design-docs
 * [new branch]      HEAD -> peter
$
```

**Comment by shriharistark** [comment]
I had a duplicate entry in my keychain access for git. Removed the one invalid one and everything seems to work fine now.
