### ISSUE TITLE
Push Fails on 1.0

### ISSUE THREAD

**Issue by OptimisticMonkey** [github/git-lfs#698]
I have existing repo using 0.53 and git-lfs-s3 that works.

I tried upgrading to the 1.0 release, and the push just hangs in the middle - no error.

Any ideas on how to troubleshoot?

Is 1.0 compatible with git-lfs-s3, or are changes needed?

**Comment by rubyist** [comment]
You can set the GIT_TRACE environment variable to get some debugging info. E.g. `GIT_TRACE=1 git push origin master`. 

If 0.6.x worked with git-lfs-s3, then 1.0 should. If it doesn't that's probably a bug.

**Comment by WillHipschman** [comment]
Is this your first push in the repo?

#687 will hang indefinitely on the first push in a repo and is in 0.6 and 1.0.  There's a pending fix at #690

**Comment by WillHipschman** [comment]
I think the first push after 0.53 in an existing repo will hang indefinitely because of #687 which has a pending fix in #690. You can verify if GIT_TRACE shows infinite 401s.

**Comment by AlicanC** [comment]
@WillHipschman, that is the exact problem I'm having.

**Comment by WillHipschman** [comment]
@AlicanC The fix is in and tested. Just waiting for them to merge it :smile:

**Comment by AlicanC** [comment]
What happened to this? Still not fixed (or merged)?

**Comment by technoweenie** [comment]
It made it into [v1.0.1](https://github.com/github/git-lfs/releases/tag/v1.0.1).

**Comment by AlicanC** [comment]
Great news.
