### ISSUE TITLE
Repeated request for credentials on https clone

### ISSUE THREAD

**Issue by rcorre** [github/git-lfs#701]
A https clone requests credentials for each blob of content.

I'm trying to authenticate with a personal access token, and I can get the clone to succeed if I paste the PAT into every credential request. Putting the PAT into my .netrc does not help (though it is used for non-lfs authentication).

This happens on both Github and VSO.

For contrast, SSH clone downloads all content without a single manual auth request.

Possibly related: #523, #533
version:
```git-lfs/1.0.0 (GitHub; linux amd64; go 1.5.1; git 7379fa9)```

**Comment by technoweenie** [comment]
I think the problem is that your URLs have capital letters, and that's messing up the git config code. #690 should fix this.

#171 is open to support netrc.

**Comment by rcorre** [comment]
Ah, I didn't realize .netrc was unsupported. #171 pretty much sums up my problem, so I'll close this.
I don't think the capitals were related though (the github url has all lowercase).
Fortunately lfs seems to respect `credential.helper = cache`, which relieves most of the pain.
