### ISSUE TITLE
Recommended best practices?

### ISSUE THREAD

**Issue by linojon** [github/git-lfs#703]
I was thinking one strategy would be to put all binary files in LFS, regardless of size.
Or lets say I have a lot of small binary files of a specific type, but a couple that are huge, should i just track the specific file name? That seems like a very manual curation process.
Or do I wait till github complains that a file is too big before tracking it? 
If not, how big a file makes sense? greater than 10mb? 1mb? 100k? 
If I'm not tracking a file type in LFS and then add it to .gitattributes, what happens to the history of that file, are older versions still on github but newer ones are on LFS? 
if so how to purge the history?
I use this command to find my large files in a project:
```git ls-files -z | xargs -0 ls -l -h -S -r```

**Comment by technoweenie** [comment]
Hi, I'm going through and replying to old issues that I've missed.

The `.gitattributes` file doesn't support tracking files by size. You can track files by extension, by directory, or by individual file name. 

> If I'm not tracking a file type in LFS and then add it to .gitattributes, what happens to the history of that file, are older versions still on github but newer ones are on LFS? 

Correct. You can't change the history of a git repository without rewriting all of the commits. If you're interested in that, I'd look at https://github.com/bozaro/git-lfs-migrate.
