### ISSUE TITLE
Question about fetchexclude usage

### ISSUE THREAD

**Issue by maxogden** [github/git-lfs#706]
I'm curious about the intended workflow for fetchinclude/fetchexclude. According to the `git-lfs-fetch` manpage (https://github.com/github/git-lfs/blob/f32da15913e838c1f50ae4aca9191a3390541ade/docs/man/git-lfs-fetch.1.ronn#L55-L58) you use gitconfig to set up paths to exclude when fetching. I have some questions about its usage:

1. Is there any way to check in the fetchexclude settings to the repo, so that people cloning a repo can avoid fetching certain files at clone-time? (And also without setting global git config paths that could mess up other repos)
2. If not, would it make sense to use gitattributes for this? Since its already used to declare which files are supposed to be managed by `gif-lfs`, wouldn't it also be nice to declare which files should/should not be fetched (all in one place)?
3. I couldn't get fetchexclude to work... I made a test repo (https://github.com/maxogden/lfs-test), made a 2nd local clone, added a new file into the original inside the `donotfetch` folder, pushed it, then on the 2nd local clone ran `git config lfs.fetchexclude "donotfetch"` and then pulled, but it still downloaded the new file inside `donotfetch`. Am I doing it wrong?

Thanks!

**Comment by technoweenie** [comment]
1. Git LFS supports a `.gitconfig` file in the root of the repository working directory. Git itself will ignore this, of course. You can add to it like so:

        $ git config --file .gitconfig lfs.fetchexclude "donotfetch"

2. The problem with using `.gitattributes` is this behavior is default for everyone. Git config values can be overridden or customized per user or even local clone.
3. It worked for me:

```bash
$ GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/maxogden/lfs-test
Cloning into 'lfs-test'...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 16 (delta 4), reused 13 (delta 1), pack-reused 0
Unpacking objects: 100% (16/16), done.
Checking connectivity... done.

$ cd lfs-test
$ ls -l
total 8
-rw-r--r--  1 rick  staff  132 Oct  5 13:15 Archive.zip
drwxr-xr-x  5 rick  staff  170 Oct  5 13:15 donotfetch

$ ls -l donotfetch
total 24
-rw-r--r--  1 rick  staff  131 Oct  5 13:15 marios.zip
-rw-r--r--  1 rick  staff  131 Oct  5 13:15 marios2.zip
-rw-r--r--  1 rick  staff  131 Oct  5 13:15 marios3.zip

$ git config lfs.fetchexclude "donotfetch"
$ git lfs pull
(1 of 3 files) 3.14 MB / 4.10 MB          

$ ls -l
total 6432
-rw-r--r--  1 rick  staff  3292005 Oct  5 13:17 Archive.zip
drwxr-xr-x  5 rick  staff      170 Oct  5 13:15 donotfetch

$ ls -l donotfetch 
total 24
-rw-r--r--  1 rick  staff  131 Oct  5 13:15 marios.zip
-rw-r--r--  1 rick  staff  131 Oct  5 13:15 marios2.zip
-rw-r--r--  1 rick  staff  131 Oct  5 13:15 marios3.zip
```

The `GIT_LFS_SKIP_SMUDGE` env var turns off the automatic downloading on clones so I could test this out.

Make sure you're on Git LFS v0.6.0 or v1.0. Maybe even do a `git config -l` just before `git lfs pull` to make sure the value was set correctly.

**Comment by maxogden** [comment]
@technoweenie thanks for the reply!

1. ah excellent, didn't realize `git-lfs` looked for a local `.gitconfig` file! 
2. Gotcha. I see that as a potential feature personally, to support a use case where you have a repo containing metadata for a potentially large set of files, and you want the default to be that none of the files get downloaded by default but can be selectively downloaded later as they are needed
3. Figured it out by running `git config -l`, my `~/.gitconfig` had `fetchexclude = Archive.zip` in it (from earlier testing I was doing) and it was overriding the local setting I had set from the CLI

**Comment by technoweenie** [comment]
> Figured it out by running git config -l, my ~/.gitconfig had fetchexclude = Archive.zip in it (from earlier testing I was doing) and it was overriding the local setting I had set from the CLI

Weird! I'd think local git config would override your user config. Mystery solved, at least :)
