### ISSUE TITLE
Client still depends on legacy API

### ISSUE THREAD

**Issue by benhumphreys** [github/git-lfs#708]
The [*Git LFS v1 Original API*](https://github.com/github/git-lfs/blob/v1.0.0/docs/api/http-v1-original.md) says:

> This describes the original API for Git LFS v0.5.x. It's already deprecated by the batch API.

and the [*Git LFS v1 Batch API*](https://github.com/github/git-lfs/blob/v1.0.0/docs/api/http-v1-batch.md) says:

> This is a newer API introduced in Git LFS v0.5.2, and made the default in Git LFS v0.6.0. The client automatically detects if the server does not implement the API yet, and falls back to the legacy API.

However v1.0.0 of the client still depends on the legacy API for clone operations. During **git clone**, GETing LFS objects will fail with the following error where the legacy API is not available:

```
Repository or object not found: http://localhost/scm/test/lfsrepo.git/info/lfs/objects/1b88b71728388427ca7c6df0948add966bb0799b6a2dbb669145e84526fa81b4
```

**Comment by technoweenie** [comment]
Blah, you're right! Looks like the smudge command is still using the old API for some reason:

```
trace git-lfs: HTTP: 200
17:22:07.449748 run-command.c:351       trace: run_command: 'git-lfs smudge '\''gif/droidtocat.gif'\'''
17:22:07.450162 run-command.c:199       trace: exec: '/bin/sh' '-c' 'git-lfs smudge '\''gif/droidtocat.gif'\''' 'git-lfs smudge '\''gif/droidtocat.gif'\'''
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: 'git' config -l -f .git/config
Downloading gif/droidtocat.gif (24.65 KB)
trace git-lfs: HTTP: GET https://github.com/github/git-lfs-test.git/info/lfs/objects/d1c8fab51418ef587fcf5dd8e73c60b9700704e2f8f5292ea12ec27c285b23a3
trace git-lfs: HTTP: 200
trace git-lfs: HTTP: GET https://github-cloud.s3.amazonaws.com/alambic/media/111976139/d1/c8/d1c8fab51418ef587fcf5dd8e73c60b9700704e2f8f5292ea12ec27c285b23a3?actor_id=21
trace git-lfs: HTTP: 200
```

We'll get that fixed up in 1.0.1. Thanks for the report!
