### ISSUE TITLE
Intermittently failures when running git add and commit

### ISSUE THREAD

**Issue by oyvindh** [github/git-lfs#709]
I keep on hitting issues like this:

git lfs env:
**git-lfs/0.6.0 (GitHub; windows amd64; go 1.5.1; git 183bdc8)**
**git version 2.5.0.windows.1**

Endpoint=https://....git/info/lfs (auth=..)
ConcurrentTransfers=3
BatchTransfer=false

*panic: Error listing git config: fork/exec C:\Git\mingw64\libexec\git-core\git.exe: Access is denied.*

goroutine 1 [running]:
github.com/github/git-lfs/lfs.(*Configuration).loadGitConfig(0xc082076780, 0x410800)
        /Users/rick/go/src/github.com/github/git-lfs/lfs/config.go:312 +0x35d
github.com/github/git-lfs/lfs.(*Configuration).Extensions(0xc082076780, 0x10)
        /Users/rick/go/src/github.com/github/git-lfs/lfs/config.go:226 +0x28
github.com/github/git-lfs/lfs.PointerClean(0x2f4780, 0xc08202a008, 0xc082054000, 0x7f, 0x4a36, 0x0, 0x0, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/lfs/pointer_clean.go:17 +0x4b
github.com/github/git-lfs/commands.cleanCommand(0xab2060, 0xc08200b790, 0x1, 0x1)
        /Users/rick/go/src/github.com/github/git-lfs/commands/command_clean.go:43 +0x267
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xab2060, 0xc08200b6c0, 0x1, 0x1, 0x0,
0x0)
        /Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x40a
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xab4aa0, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x59a
github.com/github/git-lfs/commands.Run()
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:85 +0x2a
main.main()
        /Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:9 +0x1b
error: cannot feed the input to external filter git-lfs clean %f
error: external filter git-lfs clean %f failed 2
error: external filter git-lfs clean %f failed

I have worked around them by doing smaller adds in a script and retrying upon failure

**Comment by technoweenie** [comment]
> Error listing git config: fork/exec C:\Git\mingw64\libexec\git-core\git.exe: Access is denied.

Does that file exist? Do you have access to it? Git LFS relies on the "git.exe" it finds in your system path. That needs to be correct for Git LFS to function.
