### ISSUE TITLE
How to track files with no extensions?

### ISSUE THREAD

**Issue by Tomu3** [github/git-lfs#712]
Since I have to specify a file extension when using ````git lfs track```` how would I go about adding extensionless files to LFS?

**Comment by nuclearsandwich** [comment]
You can specify any filename or path in your repository. You aren't limited to using file extensions. You could also track a specific directory with `git lfs track 'assets/*'` or an entire directory tree with `git lfs track 'assets/**/*'`. You could also track individual files specifically with `git lfs track path/to/file` which will track only that file.

Let me know if that answers your question.

**Comment by Tomu3** [comment]
Thanks very much, that worked just fine. :+1:

**Comment by kilianc** [comment]
I get 

```
$ git lfs track 'native/**/*'
native/**/* is outside repository
```

When trying to track an entire folder

**Comment by technoweenie** [comment]
@kilianc What version of Git LFS? This is what I get on v1.1.1:

```bash
~g/git-lfs-test git:(master) ✗$ git lfs track "native/**/*"
Tracking native/**/*
```

**Comment by kilianc** [comment]
@technoweenie `git-lfs/1.1.0 (GitHub; darwin amd64; go 1.5.1)` let me update and try again.

Just to be clear, manually writing to `.gitattributes` works, it's just `track`.

**Comment by kilianc** [comment]
$ git lfs version
    git-lfs/1.1.1 (GitHub; darwin amd64; go 1.5.3)
    $ git lfs track 'native/**/*'
    Tracking native/**/*

@technoweenie ^ :+1:

**Comment by technoweenie** [comment]
The `track` command changed in 1.1.1: #975. Glad it worked :)
