### ISSUE TITLE
`git lfs pull` asks for username and password when using deploy key

### ISSUE THREAD

**Issue by Bam4d** [github/git-lfs#716]
I am using a deploy key on a server to pull my git repo. This works fine:

```
git pull origin master
From github.com:import-io/marvin
 * branch            master     -> FETCH_HEAD
Already up-to-date.
```

However when I try to pull the files stored using lfs. it asks me for a username and password:
```
git lfs pull
Username for 'https://github.com':
```

This is only happening on the server side where I am using the deploy key. locally it works fine using ssh.

I have also noticed that these two lines keep being added to my `.git/config`
```
[lfs "https://github.com/import-io/marvin.git/info/lfs"]
        access = basic
```

**Comment by technoweenie** [comment]
Ah, it turns out we don't actually support deploy keys right now. Can you contact https://github.com/contact about this, since it's not an issue with the Git LFS client?

**Comment by swolfish** [comment]
It would be nice to use ssh key for the Git repo and LFS. In this moment is not so intuitive to use double credentials for the same project.
Note: I'm using lfs-test-server for storing assets.

**Comment by Bam4d** [comment]
Sure, thanks for the quick reply

**Comment by atyndall** [comment]
This also happened to me with one of my projects. I'll contact Github.

**Comment by pedrocarmona** [comment]
Is it possible or not?

**Comment by technoweenie** [comment]
Deploy keys aren't supported right now.

**Comment by chytreg** [comment]
@technoweenie When do you plan to add support for deploy keys?

**Comment by technoweenie** [comment]
Today's the day! Deploy keys should work on github.com now. If not, send me details at https://github.com/contact so I can look into it. Or contact me there if you're interested in GitHub Enterprise.

**Comment by brutuscat** [comment]
@technoweenie `git-lfs-authenticate` still not working with deploy keys, I sent u details using the contact form. Thanks
