### ISSUE TITLE
`git lfs init` should detect absence of `.git`

### ISSUE THREAD

**Issue by wkoszek** [github/git-lfs#717]
Looks like `git lfs init` doesn't detect the lack of `git` correctly:
```
wk:~> cd /tmp/
wk:/tmp> mkdir lfs-exp1
wk:/tmp> cd lfs-exp1
wk:/tmp/lfs-exp1> git lfs init
Git LFS initialized.
wk:/tmp/lfs-exp1> ls -la
total 0
drwxr-xr-x   2 wk    wheel    68  7 paź 23:03 .
drwxrwxrwt  59 root  wheel  2006  7 paź 23:03 ..
wk:/tmp/lfs-exp1> git init
Initialized empty Git repository in /private/tmp/lfs-exp1/.git/
wk:/tmp/lfs-exp1> git lfs init
Updated pre-push hook.
Git LFS initialized.
wk:/tmp/lfs-exp1> la
total 0
drwxr-xr-x   3 wk    wheel   102  7 paź 23:04 .
drwxrwxrwt  59 root  wheel  2006  7 paź 23:03 ..
drwxr-xr-x  10 wk    wheel   340  7 paź 23:04 .git
```

I'd expect it to complain.

**Comment by technoweenie** [comment]
Its primary purpose is to setup the global clean and smudge filters. IF it's inside a repository, it also installs the pre-push hook. Other commands will do that too, like the "track" command.

**Comment by wkoszek** [comment]
@technoweenie can you confirm that the observed behavior is suboptimal and that we're agreeing that `git lfs init` reports success without actually doing anything?

**Comment by technoweenie** [comment]
It sets the global clean and smudge filters:

```bash
$ git config --global --list | grep lfs
filter.lfs.clean=git-lfs clean %f
filter.lfs.smudge=git-lfs smudge %f
filter.lfs.required=true
```

**Comment by AlicanC** [comment]
> Its primary purpose is to setup the global clean and smudge filters. IF it's inside a repository, it also installs the pre-push hook. Other commands will do that too, like the "track" command.

@technoweenie, it installs the pre-push hook even when it's not in a repository:
```
C:\Users\redacted\not-a-repository> ls -Name
C:\Users\redacted\not-a-repository> git lfs init
Updated pre-push hook.
Git LFS initialized.
C:\Users\redacted\not-a-repository> ls -Name
hooks
C:\Users\redacted\not-a-repository> ls hooks -Name
pre-push
```

```
Microsoft Windows Server 2012 R2 Datacenter 6.3.9600.0
git version 2.6.1.windows.1
git-lfs/1.0.0 (GitHub; windows amd64; go 1.5.1; git 7379fa9)
```

**Comment by technoweenie** [comment]
AH, that makes more sense. Sorry, I totally missed that important detail.
