### ISSUE TITLE
Debian package 1.0.0 for jessie 64bit is broken

### ISSUE THREAD

**Issue by megies** [github/git-lfs#719]
Man pages in `usr/share/man/man1/` inside the package are all just empty gzip files.

**Comment by technoweenie** [comment]
Thanks for the report. We'll look into it.

**Comment by megies** [comment]
I bet you're aware of this, just to make double-sure (and since your deb packages don't have a debversion part). Please use an incremented debversion suffix (e.g. `..._1.0.0-1_...`) to make sure updated packages of same software version get installed (semi-)automatically by package management.

**Comment by ssgelm** [comment]
@megies I'll take a look at this.  Thanks for the heads up!

**Comment by ssgelm** [comment]
Sorry for the delay in looking at this.  Something definitely changed between 0.6.0 and 1.0.  Still looking into it.

**Comment by ssgelm** [comment]
According to the git bisect I did this was broken in e970264f007f77384c03a4d5913a1948e83001fd.  For some reason dh_installman seems to be picking up that go file.  I will track it down.

**Comment by brbsix** [comment]
I just got the update to 1.1.0 on Jessie 64bit and noticed man pages are still empty gzip files.

**Comment by ssgelm** [comment]
Sorry I have not fixed it yet. I will try to do so asap!

**Comment by carsten-AEI** [comment]
When I tried to rebuild the 1.1.0 Debian packages from the release tarball I got stuck with 
```
[...]
make[1]: Entering directory `/tmp/git-lfs-1.1.0'
mkdir -p debian/git-lfs/usr/bin
cp obj-x86_64-linux-gnu/bin/git-lfs debian/git-lfs/usr/bin/
make[1]: Leaving directory `/tmp/git-lfs-1.1.0'
   dh_install -O--buildsystem=golang
   dh_installdocs -O--buildsystem=golang
   dh_installchangelogs -O--buildsystem=golang
   dh_installexamples -O--buildsystem=golang
   dh_installman -O--buildsystem=golang
Converting man pages into code...
Failed to create go file: open ../commands/mancontent_gen.go: no such
file or directory
Converting man pages into code...
Failed to open man dir: <nil>
dh_installman: man --recode UTF-8 ./git\-lfs\-checkout\.1 >
git\-lfs\-checkout\.1\.new returned exit code 2
make: *** [binary] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2
```
where `man` seems to be contained in the tarball.

Maybe this may be related to the man pages never showed up in the first place.

**Comment by brbsix** [comment]
I just looked into the *.deb* that was released today, *git-lfs_1.2.0_amd64.deb*. 24 out of 25 man pages are intact (in man1). There's one missing, */usr/share/man/man5/git-lfs-config.5.gz*

**Comment by javabrett** [comment]
@brbsix well spotted.  Same here:

```
$ ls -las /usr/share/man/man1/git-lfs* | wc -l
24
$ [ -f /usr/share/man/man1/git-lfs-config* ] || echo missing
missing
```

And same in local build.  I think I see where this happens.
