### ISSUE TITLE
Download LFS assets automatically or not

### ISSUE THREAD

**Issue by swolfish** [github/git-lfs#720]
Can it be LFS configured in some way to choose between automatically and manually download assets by cloning git repo?
In my case, by cloning project git repo it starts to download LFS assets immediately and the problem is if user has't configured credentials caching before so download prompts username and password for each asset specifically.
After clone, I want to execute bash script first (to cache credentials) then git lfs pull to download assets.
Also, maybe I want option to checkout only the project code if don't need assets in the moment (maybe they are too large and wasting of resources).

**Comment by sinbad** [comment]
Yes, define `GIT_LFS_SKIP_SMUDGE=1` at clone time and downloading LFS files will be skipped. You can then use `git lfs pull` to download LFS files.

**Comment by swolfish** [comment]
OK, thanks, this works fine. But it would be great that some default LFS properties are inside project itself (like lfs url in .gitconfig) and then the end user shouldn't use some non intuitive commands by cloning the project. Is that maybe gonna be possible in some future releases?

**Comment by sinbad** [comment]
You can set this option globally by doing `git lfs init --skip-smudge` which means the smudge filter is turned off completely and you have to always use `git lfs pull` to download & check out large files. We're also discussing the option of having wrapper commands for operations like `git clone` where we can optimise the download and provide more options.

**Comment by lbergelson** [comment]
I agree with @swolfish that it would be very useful to be able to define this within the project itself.

**Comment by technoweenie** [comment]
Git doesn't read `.gitconfig` by default, so this is something you'll have to do manually with `git config`.

```bash
# from your repository working directory:
$ git config filter.lfs.smudge "git-lfs smudge --skip %f"
```

This will save it to `.git/config`.

**Comment by technoweenie** [comment]
You can now run `git lfs install --local` to do this.
