### ISSUE TITLE
Basic tutorials miss key point about `git lfs init`

### ISSUE THREAD

**Issue by megies** [github/git-lfs#721]
Both basic tutorial pages ([page1](https://git-lfs.github.com/), [page2](https://help.github.com/articles/configuring-git-large-file-storage/#platform-all)) and the prominently advertised [youtube video](https://www.youtube.com/watch?v=uLR1RNqJ1Mw) I first encountered when searching how to get started with LFS lack one key information: They **by no word mention the need for `git lfs init` before doing anything else**. If this was omitted intentionally to revel in simplicity this is counterproductive and leads to people (at least command line people installing via the offered packages for e.g. debian) getting frustrated and trying to find the problem. I only found that piece of information when downloading a different binary in the included `README.md`.

This command should be mentioned in those intro pages.

**Comment by ajohnson23** [comment]
+1

**Comment by technoweenie** [comment]
Those guides all assume you've installed the project, which includes "git lfs init". I've also noticed that including this in quick start guides leads people to running "git lfs init" everywhere, when it only needs to be run once on a computer. Thanks for the feedback though, you definitely bring up some good points.

**Comment by megies** [comment]
Is it more harmful to your project if some people run `git lfs init` once more (not changing anything i presume, and taking maybe a second or two) or if some people get annoyed by spending half an hour trying to find out why it's not working as advertised in starter tutorials?
Don't get me wrong. Your project, your call. I don't mind, I got it running. Just reported this for the sake of others.


P.S.:
If it's a thing that's supposed to be run once on the computer, it should be done during install of packages as a post-install. But then again I guess you mean "once per user"? Anyway, something should be done in post-install of packages, a simple message showing up would help, setting up package install hooks (e.g. in debian) would be the best thing (if it's possible and going to some global place as opposed to some user place).

**Comment by technoweenie** [comment]
@megies How'd you install Git LFS? Was it through a RPM or Deb package?

**Comment by megies** [comment]
Debian package, see #719.

**Comment by AlicanC** [comment]
> Those guides all assume you've installed the project, which includes "git lfs init". I've also noticed that including this in quick start guides leads people to running "git lfs init" everywhere, when it only needs to be run once on a computer.

@technoweenie, don't we have to run `git lfs init` every time we create a new repo or clone a repo that uses Git LFS so the pre-push hook gets installed?

**Comment by technoweenie** [comment]
@AlicanC It doesn't _hurt_. But other commands like "git lfs track" will add it for you automatically too.

**Comment by megies** [comment]
> @AlicanC It doesn't hurt. But other commands like "git lfs track" will add it for you automatically too.

Nope, sorry, but that's not correct. (At least it isn't for the 1.0.0 deb package installation via aptitude.)
I went exactly like in your tutorial..
```
# cd to existing git repo
git lfs track *.buf
git add *
git commit
git push
```
.. and `git lfs track` most certainly *did not* run `git lfs init` for me. I would've never opened this ticket if it did.

**Comment by technoweenie** [comment]
@megies Other commands like `track`, `clean`, `smudge`, etc will add the pre-push hook without requiring you to run `git lfs init`.

**Comment by megies** [comment]
> Other commands like track, clean, smudge, etc will add the pre-push hook without requiring you to run git lfs init.

Were you reading my last comment? Or do you think I'm stupid? After installing git-lfs by means of the debian package I made a test git repo, ran a `git lfs track` and `git-lfs` was not intercepting the binaries I designated for tracking when I commited them. After my first manual `git lfs init` this is working as you describe, but it certainly wasn't before that.

Whatever, I'm really getting tired of this. Just wanted to let you know of some glitch in the installation/configuration procedure. I really don't care anymore if you'll do anything about it.

**Comment by technoweenie** [comment]
@megies I was answering this question from @AlicanC:

> don't we have to run git lfs init every time we create a new repo or clone a repo that uses Git LFS so the pre-push hook gets installed?

I appreciate your feedback, and will update docs accordingly. Thanks for reporting it.

**Comment by megies** [comment]
Alright, sorry about the harsh tone then but how could I have know you're answering some other comment if you precede it with @megies?

**Comment by technoweenie** [comment]
@megies I was replying to your reply replying to my reply to @AlicanC. This thread is really confusing :)

> QUESTION: don't we have to run git lfs init every time we create a new repo or clone a repo that uses Git LFS so the pre-push hook gets installed?

> REPLY: It doesn't _hurt_. But other commands like "git lfs track" will add it for you automatically too.

I'm referring to other commands adding your pre-push hook for you.
