### ISSUE TITLE
autocrlf is not applied to files before they are added to the LFS object store.

### ISSUE THREAD

**Issue by tvandijck** [github/git-lfs#723]
also the sha256 is calculated based on the file on disk on the platform where it is committed, leading to differences between an LFS repository that is created on linux vs windows.

**Comment by technoweenie** [comment]
Hey all, I'm going through all the old issues that haven't been triaged, and replying to them.

I've labeled this as a bug. I would like to see a steps to replicate this issue so we can investigate further.

**Comment by technoweenie** [comment]
Adding to our roadmap in #1438.
