### ISSUE TITLE
GIT LFS not pushing files

### ISSUE THREAD

**Issue by hf2186** [github/git-lfs#728]
Try listing the files... (nothing is outputted)
$ git lfs ls-files

Try doing a push...(nothing is outputted)
$ git lfs push origin master

Making sure things are being tracked...
$ git lfs track
Listing tracked paths
    *.so (.gitattributes)
    *.jar (.gitattributes)

This is my git version
$ git --version
git version 2.3.8 (Apple Git-58)

Any ideas?

**Comment by technoweenie** [comment]
Have you added any `*.so` or `*.jar` files since tracking them? Git LFS won't rewrite your repository history to add files with Git LFS. The BFG Repo Cleaner is a repository history rewriting tool with Git LFS support though:

https://github.com/rtyley/bfg-repo-cleaner/releases/tag/v1.12.5

**Comment by hf2186** [comment]
@technoweenie Thanks for that info. The git LFS documentation is very simplistic. They should probably mention a bit more about how things are suppose to be setup and work.

I followed the BFG tools steps. I had an EOF error but i pushed again and it worked. Weird.

How do I know if a file is now in LFS mode? I don't see anything indicating that in github

Thanks!

**Comment by hf2186** [comment]
Here is another issue I am having: I did a clean checkout of the repo and all the LFS files were pointers.

so i did:

git lfs fetch
git lfs checkout

Now I got all my LFS files. GREAT!

Now I make some changes and do a new build but I want to commit those changed LFS files... they get committed as binary and not an LFS pointer and they are removed from tracking. Any Ideas on what the issue is?

**Comment by technoweenie** [comment]
> How do I know if a file is now in LFS mode? I don't see anything indicating that in github

We're working on something for that, actually.

> If I delete the Repo...will the LFS files be deleted as well?

Yes, but there we can recover them them.

> Here is another issue I am having:

Did you commit your `.gitattributes` file? If cloning didn't replace any pointers, and adding files to commit adds them to git, it sounds like you didn't. Check this out with `git lfs track`.

> so i did:
>
> git lfs fetch
> git lfs checkout

Run `git lfs pull` to do that in a single command.

**Comment by hf2186** [comment]
My .gitattributes has been committed.

I think I found the problem. When doing a checkout through eclipse, Xcode, or any IDE, the files aren't pulled. Is this a known issue?

**Comment by technoweenie** [comment]
Yes, any tool that doesn't use `git` will have to add support manually for things like gitattributes and clean/smudge filters.

**Comment by hf2186** [comment]
@technoweenie Thank you for your help. It would be nice if the git LFS site was updated with some of the info above.

**Comment by technoweenie** [comment]
We're trying to keep the Git LFS site focused on the client, and not how servers are implemented. There's no guarantee that GitHub's LFS implementation will work the same as any other LFS server. Some servers may delete files immediately with no chance for undo, for example.

The issue about non-git tools not working with git lfs is legit though. I'll see if we can work that into the docs somewhere.
