### ISSUE TITLE
Following the directions doesn't work

### ISSUE THREAD

**Issue by brianmingus** [github/git-lfs#729]
I checked out my 'cognatory' repository, added a data directory to it, asked git-lfs to track all the filetypes in it, and added the directory to the repository. Upon push I get many:

Invalid status for POST https://github.com/brianmingus/cognatory.git/info/lfs/objects/batch: 403

Followed by:

error: failed to push some refs to 'https://github.com/brianmingus/cognatory'

Apparently this is happening to many people, and the attempted workaround posted in this issue doesn't work for everyone: https://github.com/github/git-lfs/issues/697

cc @technoweenie

**Comment by technoweenie** [comment]
Hey @brianmingus, check out my reply on sending us some help. That error message means you're not authenticating with GitHub properly. So I just need some details on your setup to determine what the issue is.  https://github.com/github/git-lfs/issues/697#issuecomment-145598782

**Comment by brianmingus** [comment]
Hi @technoweenie  I sent you guys a contact e-mail with a link to a gist that contains that log file.

**Comment by brianmingus** [comment]
@technoweenie - out of pure coincidence, I was walking down Walnut tonight to the Sundown Saloon and saw the GitHub office sign :+1:

**Comment by tuxbox** [comment]
This seems to be related to this issue as well https://github.com/github/git-lfs/issues/726
maybe the output of the logs there does help too

**Comment by technoweenie** [comment]
@brianmingus you should be good to go now :+1:

**Comment by brianmingus** [comment]
@technoweenie there is seemingly still some issues with this. First, it asks for my username/password twice every time. Second, it typically doesn't transfer any data. Once it transferred one file and then froze. If I press enter, I can see that it is still asking for my username / password. 

~/Projects/Cognatory> git push --set-upstream origin master
Username for 'https://github.com': brianmingus
Password for 'https://brianmingus@github.com': 
Username for 'https://github.com': brianmingus
Password for 'https://brianmingus@github.com': 
(0 of 9090 files, 100 skipped) 0 B / 56.09 GB, 283.04 MB skipped                                                                                    U(0 of 9090 files, 100 skipped) 0 B / 56.09 GB, 283.04 MB skipped                                                                                    
(0 of 9090 files, 100 skipped) 0 B / 56.09 GB, 283.04 MB skipped                                                                                    
(0 of 9090 files, 100 skipped) 0 B / 56.09 GB, 283.04 MB skipped                                                                                    U(0 of 9090 files, 100 skipped) 0 B / 56.09 GB, 283.04 MB skipped                                                                                    P(0 of 9090 files, 100 skipped) 0 B / 56.09 GB, 283.04 MB skipped                                                                                    n(0 of 9090 files, 100 skipped) 0 B / 56.09 GB, 283.04 MB skipped                                                                                    d(0 of 9090 files, 100 skipped) 0 B / 56.09 GB, 283.04 MB skipped                                                                                    e(0 of 9090 files, 100 skipped) 0 B / 56.09 GB, 283.04 MB skipped                                                                                    r(0 of 9090 files, 100 skipped) 0 B / 56.09 GB, 283.04 MB skipped                                                                                    !
(0 of 9090 files, 100 skipped) 0 B / 56.09 GB, 283.04 MB skipped                                                                                    
(0 of 9090 files, 100 skipped) 0 B / 56.09 GB, 283.04 MB skipped                                                                                    
Password for 'https://github.com': 
(0 of 9090 files, 100 skipped) 0 B / 56.09 GB, 283.04 MB skipped                                                                                    Username for 'https://github.com': 
(0 of 9090 files, 100 skipped) 0 B / 56.09 GB, 283.04 MB skipped                                                                                    
(0 of 9090 files, 100 skipped) 0 B / 56.09 GB, 283.04 MB skipped                                                                                    
(0 of 9090 files, 100 skipped) 0 B / 56.09 GB, 283.04 MB skipped

**Comment by brianmingus** [comment]
There is some additional evidence that it repeatedly asks for the user and password, which is that this fixed the problem (for at least five minutes...)

git config credential.helper cache

**Comment by technoweenie** [comment]
Git LFS uses the same mechanism that Git does for storing passwords: https://help.github.com/articles/caching-your-github-password-in-git/

If you have any more problems, please open a new issue with details. Thanks!
