### ISSUE TITLE
Windows installer location

### ISSUE THREAD

**Issue by andyneff** [github/git-lfs#736]
I told the windows installer to install into `D:\Program Files (x86)\Git\bin` and it correctly put the uninstaller there, but not git-lfs.

1. I downloaded https://github.com/github/git-lfs/releases/download/v1.0.0/git-lfs-windows-amd64-1.0.0.exe to `C:\Users\Me\Desktop\`

I have git for windows on my computer, but do not have it in any standard location, furthermore, it probably wasn't installed, but just unzipped. So it correctly didn't detect and git installed location if it was supposed to. This is how I like my setup. That part is good. All I see is a prompt for install location. So I choose `D:\Program Files (x86)\Git\bin` and tell it to install there.

![image](https://cloud.githubusercontent.com/assets/7596961/10461963/f090621a-71a9-11e5-82b6-78ec886b543a.png)

`git-lfs.exe` is installed to `C:\Users\Me\Desktop\git-lfs.exe` while `git-lfs-uninstaller.exe` is installed in `D:\Program Files (x86)\Git\bin\git-lfs-uninstaller.exe`

I was expecting `git-lfs.exe` to go into `D:\Program Files (x86)\Git\bin\` too.

Also, since git-lfs wasn't in the same dir, the uninstaller only removed itself, not the git-lfs left on my desktop. If I moved `git-lfs.exe` into the same directory, the uninstaller successfully removes it.

**Comment by awayken** [comment]
:+1: I had issues with this, too.

**Comment by technoweenie** [comment]
I'd really love help from someone that _uses_ Windows on this :) We're using an nsis script, but I've been thinking about moving to wix. I'll take a look this weekend.

**Comment by whoisj** [comment]
> I'd really love help from someone that uses Windows on this :) We're using an nsis script, but I've been thinking about moving to wix. I'll take a look this weekend.

Big fan of Inno Setup myself. Git for Windows uses it as well.

WIX is a special kind of painful.

**Comment by technoweenie** [comment]
Cool, I'll look into that. I originally went with NSIS because I saw a `makensis` command in homebrew, meaning I could (in theory) do the build from my mac. Of course, I later discovered I should sign the exe, so I'm stuck using my Windows VM :/

**Comment by brabil** [comment]
I was trying to build on windows and I was stuck at missing zip command on my windows running git bash using MINGW64. What type of zip you are using on your windows VM to build the windows installer ?

**Comment by technoweenie** [comment]
@brabil Can you try unzipping it in Windows Explorer? It should have zip capabilities built-in. However, the installer is not in the zip, just the compiled binary. You can get the installer [here](https://github.com/github/git-lfs/releases/download/v1.1.0/git-lfs-windows-amd64-1.1.0.exe).

Also, I'd appreciate it if you start discussions in a new issue to reduce the chance of derailing the main issue. Thanks!

Also for everyone else in this thread... This specific issue will be fixed by #875, in time for the next Git LFS release.

**Comment by brabil** [comment]
Thanks @technoweenie.

**Comment by technoweenie** [comment]
Should be fixed now in #875.
