### ISSUE TITLE
Git Lfs Status Doesn't List Files that are Duplicates

### ISSUE THREAD

**Issue by WillHipschman** [github/git-lfs#738]
Git Lfs Status on the following changes only lists a.txt and d.txt as objects to be pushed, even though I added b.txt and c.txt, which are identical to a.txt behind the scenes.

This is confusing. The wording "Git LFS objects to be pushed to origin/master" is wrong, because lfs objects have oids, not file names. The lfs object to be pushed to master really matches 3 files, not one.

E:\dev\project2>git lfs track
15:50:59.642019 git.c:558               trace: exec: 'git-lfs' 'track'
15:50:59.643018 run-command.c:347       trace: run_command: 'git-lfs' 'track'
Listing tracked paths
    *.txt (.gitattributes)

E:\dev\project2>echo a > a.txt
E:\dev\project2>echo a > b.txt
E:\dev\project2>echo a > c.txt
E:\dev\project2>echo d > d.txt
E:\dev\project2>git add *
E:\dev\project2>git commit -m "a"

E:\dev\project2>git lfs status
15:51:30.689638 git.c:558               trace: exec: 'git-lfs' 'status'
15:51:30.690638 run-command.c:347       trace: run_command: 'git-lfs' 'status'
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: git diff-index -M HEAD
trace git-lfs: run_command: git diff-index -M --cached HEAD
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: run_command: 'git' rev-parse --abbrev-ref HEAD
On branch master
trace git-lfs: run_command: 'git' rev-parse --abbrev-ref HEAD
trace git-lfs: run_command: 'git' config branch.master.remote
trace git-lfs: run_command: 'git' rev-parse origin/master --symbolic-full-name origin/master
trace git-lfs: run_command: git rev-list --objects --do-walk a2866ec09a6b61c9eb9ffbecf2c04f1a2c1f2657 ^90e63e342a338c1f882987e6ca076a92606da679
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: run_command: 'git' rev-parse --abbrev-ref HEAD
trace git-lfs: run_command: 'git' config branch.master.remote
Git LFS objects to be pushed to origin/master:

        a.txt (4 B)
        d.txt (4 B)

Git LFS objects to be committed:

Git LFS objects not staged for commit:

**Comment by technoweenie** [comment]
Is this still a problem? I seem to recall this being fixed. I could be thinking of `git lfs ls-files` though.
