### ISSUE TITLE
windows git thinks all files are modifed after git lfs pull.

### ISSUE THREAD

**Issue by bunnybones1** [github/git-lfs#740]
This happens on 2 different windows 8 machines with git bash running git 1.9.4.msysgit.0
Is this normal?
Is there any way to fix this?

**Comment by bunnybones1** [comment]
I've updated to git 2.6.1.windows.1 and the problem has gone away.
Long live git lfs.

**Comment by technoweenie** [comment]
If you run into this, it'd be awesome if you could create a tiny test repo that has the problem, so we can take a look.  Do you actually see the git lfs pointer changing in the diff? The only thing off the top of my head is line ending changes, but that'd only affect large text files like csv.

**Comment by bunnybones1** [comment]
I haven't seen it again but I'll provide a repo if I do.
