### ISSUE TITLE
Provide an archive containing Windows binaries for portable installation

### ISSUE THREAD

**Issue by anurse** [github/git-lfs#743]
Can you provide an official Windows release containing a simple compressed archive (`.zip`, `.7z`, something fairly standard) with just the binaries? I'd like to make a manifest for this app to use with [Scoop](http://scoop.sh/) (a kind of Homebrew for Windows) and getting it to extract files from the NSIS installer is a bit of a pain. It would be :sparkles: and :rocket: if I could just download, unpack and PATH-ify a ZIP of binaries.

**Comment by technoweenie** [comment]
Is there any kind of directory layout that you'd like? Or do you just want git-lfs.exe at the root?

**Comment by anurse** [comment]
Just a pile-o-files with no directory layout is just fine with me :). If there's a directory layout that's easier for you though, go for it, I can easily make it work!

**Comment by technoweenie** [comment]
v1.0.1 has a windows zip file now (the "Windows AMD64" release): https://github.com/github/git-lfs/releases/tag/v1.0.1. Does that work?

**Comment by anurse** [comment]
Looks perfect! Thanks!
