### ISSUE TITLE
Can't fetch file by API: "message": "Not Acceptable"

### ISSUE THREAD

**Issue by petek** [github/git-lfs#744]
I can't download an LFS file on EC2, although I can on my local machine, and I'm getting an odd response from GitHub when I try to debug it.

I have a build server running on EC2.  When I do a fresh clone and checkout of my repository, the one file I have stored in LFS is not retrieved, and I get this message:
```
$ git checkout develop
Downloading ***.zip (55.87 MB)
Error accessing media: ***.zip (<long hash value>)

Errors logged to .git/lfs/objects/logs/20151015T174546.361886396.log
Use `git lfs logs last` to view the log.
Branch develop set up to track remote branch develop from origin.
Switched to a new branch 'develop'
```
When I check the `git lfs logs last` log, I get the following snippet that leaves a clue:
```
git-lfs/1.0.0 (GitHub; linux 386; go 1.5.1; git 7379fa9)
git version 2.4.3

$ git-lfs smudge ***.zip
Error accessing media: ***.zip (<long hash value>)

Unable to parse HTTP response for GET https://api.github.com/lfs/fairbanksllc/fairbanks-ltss-v2/objects/<long hash value>
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/errors.go:557 +0x80
<cut for brevity>
```
When I attempt to retrieve that URL, I get the following JSON document:
```
{"message":"Not Acceptable","documentation_url":"https://github.com/contact"}
```
I don't have this same problem from my local machine, so I'm not sure where the problem is.

**Comment by technoweenie** [comment]
This is a server problem, and has nothing to do with the OSS Git LFS client. That URL doesn't work because you're not following the API spec. Just missing an Accept header.

https://github.com/github/git-lfs/tree/master/docs/api

Also, check your email, I have a more detailed response there :)

**Comment by petek** [comment]
Thanks to @technoweenie, I have tracked this down a bit further, and I'm getting the following debug information in the log:
```
$ GIT_TRACE=1 GIT_TRACE_PACKET=1 git lfs fetch
18:41:53.891958 git.c:557               trace: exec: 'git-lfs' 'fetch'
18:41:53.892098 run-command.c:347       trace: run_command: 'git-lfs' 'fetch'
trace git-lfs: run_command: 'git' rev-parse --abbrev-ref HEAD
trace git-lfs: run_command: 'git' config branch.develop.remote
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: 'git' config -l -f /home/***/.git/config
Fetching develop
trace git-lfs: run_command: git rev-list --objects --no-walk ***
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: tq: starting 3 transfer workers
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: fetch ***.zip [<long hash value>]
trace git-lfs: tq: sending batch of size 1
trace git-lfs: ssh: git@github.com git-lfs-authenticate ***.git download
trace git-lfs: api: batch 1 files
trace git-lfs: HTTP: POST https://api.github.com/lfs/***/***/objects/batch
trace git-lfs: HTTP: 200
trace git-lfs: api error: Unable to parse HTTP response for POST https://api.github.com/lfs/***/***/objects/batch
(0 of 1 files) 0 B / 55.87 MB        
```
It appears the git-lfs-authenticate over ssh is not working in my case.

**Comment by technoweenie** [comment]
Weird. If there was an authentication error, you should see something about getting a 403. Can you run that with:

```
$ GIT_CURL_VERBOSE=1 git lfs fetch
```

Feel free to send the log to our github support email, unless you want to do this here.  This isn't an issue with the OSS client though. The curl verbose log will include your authorization header too. Look for any lines with "Authorization: Basic".

**Comment by WillHipschman** [comment]
If you set ```GIT_CURL_VERBOSE=1```it should show you the http response so you can figure out what's wrong with it.

**Comment by petek** [comment]
Log sent in; I will not post a sanitized version here, except to note that the authorization both ways was successful, and a valid JSON document containing the objects to be downloaded - and the authorization to do that (via AWS4-HMAC-SHA256) - was received by the client.

**Comment by technoweenie** [comment]
Closing this, as it's a temporary issue on our server. Thanks for the report!

**Comment by petek** [comment]
Confirmed the issue is resolved.
