### ISSUE TITLE
git lfs init: Access denied

### ISSUE THREAD

**Issue by csrvermaak** [github/git-lfs#745]
Hi - I just downloaded and installed git lfs from the installer:

After the installer finished, I got a messagebox from the installed to open a Git Bash and run "git lfs init"

Here is what I got:

```
$ git lfs init
mkdir hooks: Access is denied.
Run `git lfs update --force` to overwrite this hook.
Git LFS initialized.
```

Please advise?

**Comment by csrvermaak** [comment]
How do I know if LFS is now active on my repo?

**Comment by technoweenie** [comment]
@csrvermaak Git LFS needs to setup global git hooks to function properly. You can verify they are set by:

```
# look for filter.lfs settings
$ git config --global --list
filter.lfs.clean=git-lfs clean %f
filter.lfs.smudge=git-lfs smudge --skip %f
filter.lfs.required=true
```

According to [the git-config docs](https://git-scm.com/docs/git-config), it needs access to `~/.gitconfig`. It seems weird that you don't have access to a file in your home directory.

> For writing options: write to global ~/.gitconfig file rather than the repository .git/config, write to $XDG_CONFIG_HOME/git/config file if this file exists and the ~/.gitconfig file doesn’t.

I'm not sure how this translates to a Windows environment. Did you install Git for Windows, or just GitHub Desktop? If someone else with Windows experience doesn't chime in, I'll check it out on my Windows VM when I get home.

> How do I know if LFS is now active on my repo?

All GitHub and VSO repositories have Git LFS enabled for everyone.

**Comment by csrvermaak** [comment]
@technoweenie - I installed git lfs v1.0 for windows, from the link:

https://github.com/github/git-lfs/releases/download/v1.0.0/git-lfs-windows-amd64-1.0.0.exe


I'll check the hooks now. Will let you know. Thanks for your help.

**Comment by technoweenie** [comment]
@csrvermaak Ah, I was trying to ask how you installed Git itself.

**Comment by csrvermaak** [comment]
I see - I installed Git itself via TortoiseGit first.

**Comment by technoweenie** [comment]
Ah ok. I'm really new to Git on Windows, so I'll probably setup a VM with just TortoiseGit for future tests of our installer. Thanks :)

**Comment by csrvermaak** [comment]
No probs - glad to help flag some possible issues :)

**Comment by csrvermaak** [comment]
Here is what I get when I run --config --settings:

```
$ git config --global --list
gui.recentrepo=C:/Git
user.email=xxxtmail.com
user.name=xxx
merge.tool=winmerge
filter.lfs.clean=git-lfs clean %f
filter.lfs.smudge=git-lfs smudge %f
filter.lfs.required=true
core.autocrlf=true
core.excludesfile=C:\Users\xxx\Documents\gitignore_global.txt
```

Looks like it's all fine? Thanks for your help.

**Comment by csrvermaak** [comment]
Here is the contents of my .gitattributes:

```
*.csv filter=lfs diff=lfs merge=lfs -text
*.xlsx filter=lfs diff=lfs merge=lfs -text
*.xlsm filter=lfs diff=lfs merge=lfs -text
*.xls filter=lfs diff=lfs merge=lfs -text
*.pdf filter=lfs diff=lfs merge=lfs -text
*.odg filter=lfs diff=lfs merge=lfs -text
```

I'm guessing the .xlsx should be -binary? Please advise? Sorry for all the questions, I'm new to LFS, still figuring it out.

**Comment by csrvermaak** [comment]
Final question - assuming all is fine, if I now commit, the above mentioned files will now be stored in LFS.... For the organisation repo, as well as my and my colleagues forks?

**Comment by technoweenie** [comment]
Gah, I'm dumb. Here's your original message:

> mkdir hooks: Access is denied.

That means Git LFS was not able to create a `.git/hooks` directory in your local repository. Again, it's weird that you wouldn't have access to create it on your own. You'll need that so that Git LFS will push large objects _before_ Git pushes your commits. If you can't add any Git hooks, you'll have to push with an extra command:

```
$ git lfs push origin master
$ git push origin master
```

> I'm guessing the .xlsx should be -binary?

Not really. Git LFS stores the binary files outside of the actual Git repository. As far as Git can tell, you're just committing tiny text files.

> Final question - assuming all is fine, if I now commit, the above mentioned files will now be stored in LFS.... For the organisation repo, as well as my and my colleagues forks?

Git LFS does not rewrite any existing repository history. It only stores files in the LFS server for _new_ commits that were added after you ran `git lfs track`. But yes, you and your colleagues will see the same options.

You can confirm that files are stored in LFS after you do `git commit` with `git lfs ls-files`.

**Comment by csrvermaak** [comment]
@technoweenie - thanks, I've just confirmed the files that are in LFS. Thanks for your help.
