### ISSUE TITLE
Receiving "Error accessing media"

### ISSUE THREAD

**Issue by jtsadlerjr** [github/git-lfs#746]
With 2 different repositories on multiple machines since about 10am PST this morning I can no longer download any files. I can still submit files but receive "Error accessing media" when downloading anything stored in LFS.

**Comment by technoweenie** [comment]
Hi @jtsadlerjr I think we resolved this. Are you still having problems?

**Comment by nbazzeghin** [comment]
I am also getting this when a repo i just setup.

    git-lfs/1.0.1 (GitHub; windows amd64; go 1.5.1; git 2182d86)
    git version 1.9.5.msysgit.0

**Comment by technoweenie** [comment]
Sorry for the hassles. This was a bug caught just a bit too late for 1.0.1, but is fixed in master:

https://github.com/github/git-lfs/pull/795

You can either go back to v1.0, or run `git lfs pull` from inside the repo directory. We should have a fixed v1.0.2 out tomorrow. :angel:
