### ISSUE TITLE
Please add pointer size upper limit to specification

### ISSUE THREAD

**Issue by bozaro** [github/git-lfs#747]
It would be great to add pointer size upper limit to specification: https://github.com/github/git-lfs/blob/master/docs/spec.md

Currentry I can create correct pointer with unlimited size. I think a good idea to limit pointer size (for example: 4096 bytes).

Currentry pointer size is 130-140 bytes.

**Comment by technoweenie** [comment]
We should definitely document it. There's an unofficial size that we use when scanning blobs to filter any over a certain size. We used to use 200, but now have to deal with [extensions](https://github.com/github/git-lfs/blob/master/docs/extensions.md). I thought we added a limit to the number of extensions a repository could have, but apparently not.

I agree there should be a well known, documented size limit. I want to set the extension limit to 10 (probably more than generous), with a reasonable size and extension name length limit.

```
version https://git-lfs.github.com/spec/v1
ext-0-foo sha256:{original hash}
ext-1-bar sha256:{hash after foo}
oid sha256:{hash after bar}
size 123
```

FWIW some of my previous thoughts on this are in #524.

**Comment by bozaro** [comment]
> I want to set the extension limit to 10 

Extension limit is not good idea: one extension may have unlimited size.

I think total size limit like N kilobytes is good enought.

**Comment by technoweenie** [comment]
I'm just saying we should send extension limits in addition to a byte size limit.

**Comment by technoweenie** [comment]
Added to the roadmap in #1438.
