### ISSUE TITLE
problems using git-lfs in an Xcode Bot

### ISSUE THREAD

**Issue by szigetics** [github/git-lfs#748]
I installed git-lfs on my Xcode Server instance.
I added my hosting server's url to my global gitconfig :
 
cat ~/.gitconfig
```
[filter "lfs"]  
  clean = git-lfs clean %f  
  smudge = git-lfs smudge %f  
  required = true  
[lfs]  
  url = https://artifactory.myCompany.net/artifactory/api/lfs/git-lfs  
```
 
 
I added git-lfs to my pre-build trigger :
 
```
#!/bin/bash  
echo "Initializing dependencies"  
export PATH="$PATH:/opt/local/bin:/opt/local/sbin:/usr/local/bin"  
git lfs init  
#here I run my own git command which pulls my git sources which are using git-lfs  
[[ $? -eq 0 ]] || exit 1  
  
cat "$XCS_SOURCE_DIR/Components/OpenSSL/lib/Device/libssl.a"  
cat "$XCS_SOURCE_DIR/Components/OpenSSL/lib/Simulator/libssl.a"  
 ```
 
The result is :

``` 
version https:/
oid sha256:123fb53535365ede0f7b95aaa8cb4be3c38c5f4bac30cd74d4fbe3e283903f54
size 4529280
 
version https:/
oid sha256:99b51ad7bc89d3f870140644f21c088ebcf6f9627996d9eb9b16c47437a6edfe
size 3153456
```
 
So it seems that it is not using git-lfs at all, just pulling down the real file content (the pointers).
 
Do you know how can this issue be fixed?
 
Thanks!

**Comment by technoweenie** [comment]
If your own git command is not fetching the Git LFS content, you can run "git lfs pull" to fetch and replace the pointer files.

**Comment by szigetics** [comment]
Running "git lfs pull" fixed my problem. Thank you! :)

![ThumbsUp](http://cdn.meme.am/images/300x/4742169.jpg)
