### ISSUE TITLE
git lfs track fails with "Not a git repository." in /

### ISSUE THREAD

**Issue by krichter722** [github/git-lfs#753]
Invoking `cd / && git lfs init && git lfs track .` (as user `root`) fails with `Not a git repository.` and returncode 128. I have created a repository at `/` with `git init`.

experienced with 1.0.0 on Ubuntu 15.04

**Comment by technoweenie** [comment]
Do you have a git repository at `/`? `git lfs track` requires a git repository.

**Comment by krichter722** [comment]
> Do you have a git repository at /?

Yes.

**Comment by leecade** [comment]
:+1: OSX 10.11.2

```sh
❯ git lfs init
Git LFS initialized.

~/tmp/lfs
❯ git lfs track .
Not a git repository.
```

**Comment by technoweenie** [comment]
I don't think tracking `.` is what you want, but this works in the current version of LFS:

```bash
$ git lfs track .
Tracking .

$ cat .gitattributes
. filter=lfs diff=lfs merge=lfs -text
```
