### ISSUE TITLE
Documentation about the internal format.

### ISSUE THREAD

**Issue by ytrezq** [github/git-lfs#757]
Hello,

This project is good for dealing with large files manually, however it seems it’s not the best choice for code integration into other projects and/or language.
So does the exact changes in objects are documented outside the source code ?

**Comment by technoweenie** [comment]
Here are some internal docs:

* [Specification](https://github.com/github/git-lfs/blob/master/docs/spec.md)
* [Server API](https://github.com/github/git-lfs/tree/master/docs/api)
