### ISSUE TITLE
see

### ISSUE THREAD

**Issue by chiefkme60** [github/git-lfs#764]
Your welcome you know I think that's what everybody was doing you know it's kind of like speeds everybody's doing differently so the issues that people are worth having is generally eat it going to snow on a downloader do it too fast is very common man

**Comment by familyfaithlove1** [comment]
On Oct 20, 2015 2:56 PM, "chiefkme60" <notifications@github.com> wrote:

>

> Closed #764 <https://github.com/github/git-lfs/issues/764>.
>
> —
> Reply to this email directly or view it on GitHub
<https://github.com/github/git-lfs/issues/764#event-440881493>.
