### ISSUE TITLE
Git LFS broken with organizations?

### ISSUE THREAD

**Issue by megastep** [github/git-lfs#773]
I've been trying to switch fully to LFS, which would work great with some of the repositories I work with that include large binary files. However I have been at a loss as to why it has been failing to upload the files to LFS on my repo that is owned by an organization.

I am currently using git on the command line on OS X El Capitan, with the git-lfs binary installed from the current Github Desktop app. The version is the following:

`git-lfs/0.6.0 (GitHub; darwin amd64; go 1.5.1; git 183bdc8)`

To try to figure out what might be the cause of this, I did a simple test today by creating a simple empty repo in my own account, then adding a simple JPEG image that was supposed to be handled by LFS.
The repo in question is at `https://github.com/megastep/test-lfs`. I created the repo, added a tracking rule for *.jpg, added the image, did a git push and everything worked just fine. The image shows up in the Github web interface with proper annotations and this seems seamless (as it should be). I can clone the repo and the image is downloaded properly.

I then proceeded to fork the above repo on an organization, at `https://github.com/catloafsoft/test-lfs`. The repo appears just fine there too, with the image being visible, etc. But if I try to clone the repo from the command line, things start going wrong.

```
Cloning into 'test-lfs'...
X11 forwarding request failed on channel 0
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 7 (delta 0), reused 7 (delta 0), pack-reused 0
Receiving objects: 100% (7/7), done.
Checking connectivity... done.
Downloading TeamAmerica1.jpg (213.05 KB)
Username for 'https://github.com': megastep
Password for 'https://megastep@github.com': 
Error accessing media: TeamAmerica1.jpg (40581dceff39e349ca659f1a1d9f345390d7bfe1dc5670d7da00b8a18b994b16)

Errors logged to .git/lfs/objects/logs/20151022T201905.734782058.log
```

The password prompt was rather unexpected (I also use 2-factor auth), and I have setup the osxkeychain credential helper. I created an API token that I used as the password here.

Looking at the log that is produced, I get this:

```
git-lfs/0.6.0 (GitHub; darwin amd64; go 1.5.1; git 183bdc8)
git version 2.4.9 (Apple Git-60)

$ git-lfs smudge TeamAmerica1.jpg
Error accessing media: TeamAmerica1.jpg (40581dceff39e349ca659f1a1d9f345390d7bfe1dc5670d7da00b8a18b994b16)

Git LFS objects can not be uploaded to public repository forks at this time.
Docs: https://github.com/contact
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/errors.go:525 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0xc641e8, 0xc8200ea0b0, 0xcae280, 0xc8205a8410)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:181 +0xf7f
github.com/github/git-lfs/commands.logPanic(0xcae280, 0xc8205a8410, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:145 +0x421
github.com/github/git-lfs/commands.handlePanic(0xcae280, 0xc8205a8410, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:120 +0x4e
github.com/github/git-lfs/commands.LoggedError(0xcae280, 0xc8205a8410, 0x4d7e00, 0x1e, 0xc8200cfd00, 0x2, 0x2)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:70 +0x82
github.com/github/git-lfs/commands.smudgeCommand(0x6a4ec0, 0xc820013890, 0x1, 0x1)
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_smudge.go:69 +0xd11
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0x6a4ec0, 0xc8200137e0, 0x1, 0x1, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x403
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0x6a5bc0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x46a
github.com/github/git-lfs/commands.Run()
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:85 +0x23
main.main()
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:9 +0x14

ENV:
LocalWorkingDir=/private/tmp/test-lfs
LocalGitDir=.git
LocalGitStorageDir=.git
LocalMediaDir=.git/lfs/objects
TempDir=.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
GIT_DIR=.git
```

I am particularly wondering about the `Git LFS objects can not be uploaded to public repository forks at this time.` message. This makes no sense to me as Github itself handles the fork just fine (and what is Github without the ability to use forks?). Also, since the original repo was public you would think there wouldn't need any special authentication to access what is essentially a public file being stored on LFS somewhere.

So what am I doing wrong and how can I fix this? Or are things still broken on Github's side?

**Comment by technoweenie** [comment]
Correct, Git LFS on GitHub isn't supported on public forks right now. Feel free to contact us about it at https://github.com/contact. This isn't an issue with the OSS client though.

**Comment by megastep** [comment]
Is there an ETA for actually implementing this? This just blows my mind, are we supposed to just give up on the ability to fork if we want to use LFS in the meantime? 

This is a major part of using Github that just gets broken with no advance warning when trying to use LFS. At the very least there should be something said when attempting to fork a project using LFS until this actually works.

**Comment by technoweenie** [comment]
Forking works great for private projects. We don't want to charge owners for things they have no control over in a public project, though. There are a lot of places where LFS can still integrate better with GitHub, and hopefully it gets better over time.

**Comment by megastep** [comment]
I figured it probably had something to do with the way Github charges for bandwidth. I think this is an incredibly shortsighted decision as it pretty much makes it impossible to use this with an Open Source project. Completely breaking the social aspects of using GitHub for the sake of greed, woohoo!

Nice going, Github! Could you at least mention anywhere in the LFS pages that this only works properly with private projects? Or how about just giving up on charging for bandwidth, I'm sure that would solve that issue. Who the hell still does that for file hosting in this day and age? Just charge for storage like everybody else and make everybody happy.

Sorry about the rant, I'm sure you have nothing to do with this personally. :)

**Comment by technoweenie** [comment]
I'm the lead on this project at GitHub, so I had everything to do with this, and had to make some tough choices. Unfortunately, bandwidth charges are typically much higher than storage charges, so it's tough for us to ignore. I decided to err on the side of caution (and keep public repo owners from being hit with a large bill) for now, but am considering some creative solutions to the issue. Anyways, thanks for the feedback!

**Comment by megastep** [comment]
It is nice to be able to talk to the project lead over here, but to me this is not a technical problem as much as it is a big flaw in the associated business model, which just gets in the way of getting this stuff to work right. So unless you had a hand in establishing the completely bonkers pricing model for bandwidth with regards to LFS, I wouldn't be so quick to pin the responsibility for this on you. ;)

Really, if bandwidth was out of the picture, this would be a non issue and this would work for everybody involved without sacrificing the entire open-source community for the sake of squeezing out a bit of cash.

Github doesn't charge for bandwidth usage anywhere else that I know of. Not even for Github Pages. Not if I just stick the huge files in the repo and then just go about my regular business, consuming even more bandwidth. None of the cloud file providers out there charge for bandwidth. Not Google, not DropBox, not even Microsoft.

You said this is not a problem with the OSS client and you're right - this is entirely a problem with the crazy model adopted on the server side, and that is solely Github's responsibility.

As an open-source developer I may just be forced out of Github entirely and may have to move some projects to friendlier hosts, unless this changes.

**Comment by technoweenie** [comment]
You're not wrong. Git LFS is a new product, and things will change in the future. Locking this to keep this repository focused on the repository at hand. You can send me more feedback at https://github.com/contact (if you mention LFS somewhere, it'll show up in my inbox). Thanks.
