### ISSUE TITLE
Use .lfsconfig instead of .gitconfig

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#780]
This change would make it clear that the file is used for lfs configuration only. Though we'd want to keep supporting `.gitconfig`, and just print a warning asking them to change it to `.lfsconfig`.

**Comment by sinbad** [comment]
:-1: Amen to this. I only just realised there was support for a `.gitconfig` file in the working copy root, I misread it previously as meaning one of the other standard `.gitconfig` files.
