### ISSUE TITLE
Rename "init" command

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#781]
The `git lfs init` command mirrors `git init` by name, which is leading some confusion about how often you need to run it. @nuclearsandwich proposed renaming it to `git lfs install`, to indicate that it's a command you only run ONCE per computer. Maybe even update the messages to let you know when you ran it again and didn't need to.

**Comment by sinbad** [comment]
:+1:

**Comment by shiftkey** [comment]
:thumbsup:

**Comment by autious** [comment]
I know this is a little stale, but i'd like clarification in case more like me stumble in here.

According to the manual:

## DESCRIPTION

Perform the following actions to ensure that Git LFS is setup properly:

* Set up the clean and smudge filters under the name "lfs" in the global Git
  config.
* Install a pre-push hook to run git-lfs-pre-push(1) for the current repository,
  if run from inside one.

Doesn't bullet point two indicate that git lfs init needs to be run once for each repo aswell?

**Comment by technoweenie** [comment]
@autious: That's more of a convenience thing. Maybe I should rip that out then if it's causing confusion. Other commands like "track", "smudge", "clean", etc will install the pre-push hook too. Ideally you don't have to worry about setting up the pre-push hook yourself, because Git LFS should have already added it for you in your normal git+lfs workflow.

**Comment by autious** [comment]
Oh, ok, i see, so it's "lazily" initialized.

That clears some confusion up for me, thanks!
