### ISSUE TITLE
Clone fails with GitHub Desktop

### ISSUE THREAD

**Issue by hellkama** [github/git-lfs#785]
Hi,

I migrated a repository to use LFS for some file types using the https://github.com/bozaro/git-lfs-migrate.

It went without problems and i was able to clone the migrated repository with git and git-lfs 1.0.0.

However trying to clone the same repository with GitHub Desktop fails for some reason.

I also tried adding the local repository I cloned earlier successfully to the GitHub Desktop. It seemed to work normally until I modified existing LFS tracked file. Then GitHub Desktop would just crash before I even had chance to commit.

I tried cloning the repository using Github Desktop from multiple machines without success.

Any help would be greatly appreciated as we have people using GitHub Desktop.

You can find GitHubLog file of the client here for the failed clone:
http://pastebin.com/34fExtc1

**Comment by technoweenie** [comment]
Your best bet is sending the details to https://github.com/contact, as this repository is for the open source git-lfs client.

**Comment by anarulaaamgroup** [comment]
Any solution found?
