### ISSUE TITLE
GitHub Enterprise in private mode sends a 403 for info/lfs/objects/batch

### ISSUE THREAD

**Issue by cjs** [github/git-lfs#787]
When a GitHub Enterprise instance is configured in private mode, it returns 403 when a POST to https://[hostname]/testuser/testrepo.git/info/lfs/objects/batch is sent.

This causes the error:

```
Invalid status for POST https://[hostname]/testuser/testrepo.git/info/lfs/objects/batch: 403
error: failed to push some refs to 'https://[hostname]/testuser/testrepo.git'
```
Version tested is:

git-lfs/1.0.0 (GitHub; darwin amd64; go 1.5.1)
git version 2.4.9 (Apple Git-60)

Possible workarounds:

1) use a remote URL with a username:token in it (however, this is bad security practice)
2) manually set ``git config lfs.batch false``
3) Set the remote to SSH instead of HTTP(S)

**Comment by technoweenie** [comment]
Unfortunately, 403 is a typical response that means _something_ is there. It'd be really easy to change [here](https://github.com/github/git-lfs/blob/8c655a86cdc030ce809b95e64b42ecdc811de9ea/lfs/client.go#L244-L247), but would also disable the batch api in GHE 2.4+ because those also return 403 for the batch API.

I don't see how we can support this custom (and incorrect IMHO) response code without affecting other LFS servers.

**Comment by cjs** [comment]
Adding another workaround: connecting via SSH instead of HTTPS.

@technoweenie I agree. I think the workaround, while annoying, is better than having one-offs for each server's implementation.

**Comment by boblaublaw** [comment]
Am I correct in reading that one of the workarounds is required for any private gitub repo?

**Comment by technoweenie** [comment]
Enterprise 2.4 returns 401 instead of 403, so it supports the auth workflow properly. It means public repositories still require a login, but that's the whole point of Enterprise's private mode feature.

**Comment by boblaublaw** [comment]
I see.  Apologies as I'm not as familiar with the Enterprise product line.

Our organization is currently not using Enterprise, but we are using paid private repos - does this mean a workaround is required?

**Comment by technoweenie** [comment]
@boblaublaw Nope. GitHub Enterprise ships with a "private mode" feature that wraps all requests (even to public repositories or gh pages) behind authentication. Before GitHub Enterprise 2.4, private mode would return 403 responses if no authentication was passed. I changed it to 401, which is semantically correct.
