### ISSUE TITLE
Silent installation option for git-lfs Windows installer

### ISSUE THREAD

**Issue by FeodorFitsner** [github/git-lfs#789]
Hello,

Windows installer is made with NSIS however it doesn't respect `/S` (silent) option for unattended installation ([this](https://github.com/github/git-lfs/blob/master/script/nsis/installer.nsi#L41) should be avoided in silent mode too). That would be especially useful for headless CI environment such as AppVeyor.

Thank you!

**Comment by technoweenie** [comment]
Would it help to have a zip of just `git-lfs.exe`? I'm thinking about ditching nsis in a future release (maybe v1.1).

**Comment by FeodorFitsner** [comment]
Sure, zip could be a great addition to MSI for "advanced" installations (when you know where to unpack the zip and what to do next).

**Comment by technoweenie** [comment]
Just merged https://github.com/github/git-lfs/pull/812. Should work better for Git LFS 1.1.0.
