### ISSUE TITLE
GitHub pages won’t load files tracked using git-lfs

### ISSUE THREAD

**Issue by exalted** [github/git-lfs#791]
Say `/foo.png` is **NOT** tracked using `git-lfs` in repository `username.github.io`, then if you access to `http://username.github.io/foo.png` you see image just fine.

If you were to track `/foo.png` using `git-lfs` (i.e., `git lfs track foo.png`), then if you access to `http://username.github.io/foo.png` the image is not available.

This may be related to GitHub pages rather than https://github.com/github/git-lfs/, but I wouldn’t know where to report.

Am I missing something?

Thank you.

**Comment by technoweenie** [comment]
GitHub Pages does not support Git LFS. Contact us at https://github.com/contact to talk further about it.

**Comment by exalted** [comment]
:+1:

**Comment by rajrsingh** [comment]
+1
