### ISSUE TITLE
Can't track already commited files

### ISSUE THREAD

**Issue by sshillo** [github/git-lfs#796]
From the docs seems like you have to commit a file after you track it, but what am I supposed to do if the file is already committed. Doing ```git lfs track file``` doesn't seem to work in this case

**Comment by technoweenie** [comment]
First, you don't need to track individual files. Tracking file types and/or directories should be fine:

```bash
$ git lfs track "*.zip" # all zips
$ git lfs track "archives/*" # all files in ./archives/
$ git lfs track "archives/*.zip" # all zip files in ./archives/
```

Second, Git LFS has no control over when Git runs its filters. You'll have to wait until the file changes before it runs it through the `clean` filter again.

Here's a repo where I was testing this:

```bash
$ git lfs track "*.txt"
Tracking *.txt

$ git add abc.txt
$ git status
## master
?? .gitattributes
```

No change for "abc.txt" even though I added it again explicitly. Updating the file works though:

```bash
$ echo "abcd" > abc.txt
$ git add abc.txt
$ git status
## master
M  abc.txt
?? .gitattributes
$ git commmit -m "update"
[master b348d85] update abc
 1 file changed, 3 insertions(+), 1 deletion(-)

$ git show
commit b348d8569398765816c81b6f291bd31851297dd9
Author: risk danger olson <technoweenie@gmail.com>
Date:   Tue Oct 27 12:36:56 2015 -0600

    update abc

diff --git a/abc.txt b/abc.txt
index 8baef1b..e4b517c 100644
--- a/abc.txt
+++ b/abc.txt
@@ -1 +1,3 @@
-abc
+version https://git-lfs.github.com/spec/v1
+oid sha256:fc4b5fd6816f75a7c81fc8eaa9499d6a299bd803397166e8c4cf9280b801d62c
+size 5
```

Notice how the diff shows the file changing into the LFS pointer.

**Comment by sshillo** [comment]
Okay got it thanks
