### ISSUE TITLE
API rate limit exceeded for ... Authenticated requests get a higher rate limit

### ISSUE THREAD

**Issue by boblaublaw** [github/git-lfs#797]
Hi all, I suspect I'm dealing with a misunderstanding here, but when attempting to clone/fetch a repo with a lot of LFS content, I'm now encountering an error:

"API rate limit exceeded for $(MY_IP). (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation..."

My confusion here is that I was prompted for my credentials on the initial clone, but i suspect (and hope) those are not saved to .git/config in the [lfs] section.

How can I provide credentials to "git lfs fetch" to avoid the rate limit problem?

**Comment by boblaublaw** [comment]
HTTP remote URLs seem to encounter this rate limit error, but by changing my remote to "git@github.com:/Team-Name/Repo-Name" I am now able to clone, but the clone speed is about 40Kbps, which for a 2GB repo is problematic.

**Comment by technoweenie** [comment]
> My confusion here is that I was prompted for my credentials on the initial clone, but i suspect (and hope) those are not saved to .git/config in the [lfs] section.

Interesting. While separate, Git LFS uses the same git credential stuff that is configured for git. If your Git LFS server is hosted by your Git host, it _should_ only require one https password for Git and Git LFS.

> How can I provide credentials to "git lfs fetch" to avoid the rate limit problem?

This is kind of gross:

    # run this in your local repo. the config key should be all lowercase.
    $ git config lfs.https://github.com/github/git-lfs-test.git/info/lfs.access basic

We should probably add a simple command for this that just accepts the remote name.

Here's why this is needed: By default, Git LFS assumes repositories are public. It makes the initial request with no auth. If the server returns 401, it sets `access=basic`, so future attempts will always send a password (prompting as necessary to fill your local git credential cache).

Also, I can look at the API rate limits on our server (though this is unrelated to Git LFS of course).

**Comment by Kwizatz** [comment]
I am getting the same issue but when trying to do a push on a re-lfs created repository. I get prompted for my username and password by git, but I don't get prompted again for CURL. The process tries to push the files over and over without authentication until the rate limit is reached, here is what gets repeated over and over with GIT_CURL_VERBOSE=1:

< Content-Length: 86
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-
RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes,
 X-Poll-Interval
< Content-Security-Policy: default-src 'none'
< Content-Type: application/json; charset=utf-8
< Date: Thu, 29 Oct 2015 01:40:52 GMT
< Lfs-Authenticate: Basic realm="GitHub"
< Server: GitHub.com
< Status: 401 Unauthorized
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Github-Media-Type: unknown
< X-Github-Request-Id: BAB0131E:798B:C5B28C5:56317924
< X-Ratelimit-Limit: 100
< X-Ratelimit-Remaining: 7
< X-Ratelimit-Reset: 1446082882
< X-Xss-Protection: 1; mode=block
<
{"message":"Requires authentication","documentation_url":"https://github.com/con
tact"}> POST /AeonGames/runtime.git/info/lfs/objects/batch HTTP/1.1
> Host: github.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/1.0.1 (GitHub; windows amd64; go 1.5.1; git 2182d86)
>
{"objects":[{"oid":"f5a78da18fa548f6ef325edfbd91d3088c010d896b21863beec5a7ab3418
8d2c","size":2272462},{"oid":"36658cb768a54c1d4dec43c3116c27ed893e88b02ecfcb44f2
166f9c0b7f2a0d","size":571091}],"operation":"upload"}< HTTP/1.1 401 Unauthorized

Let me know what can I provide to further diagnose the problem.

**Comment by Leviathan1753** [comment]
I'm getting similar errors.  I tried to checkout my partners branch in order to do a merge, and I'm getting git lfs errors related to API rate limit exceeded.    

D:\Repos\Black Ink Studios\Black-Ink>git lfs version
git-lfs/1.0.2 (GitHub; windows amd64; go 1.5.1; git 0566698)

D:\Repos\Black Ink Studios\Black-Ink>git lfs fetch
Fetching Justin-PC
(0 of 2309 files) 0 B / 4.42 GB
API rate limit exceeded for 50.129.162.48. (But here's the good news: Authentica
ted requests get a higher rate limit. Check out the documentation for more detai
ls.)
Docs: https://developer.github.com/v3/#rate-limiting
Warning: errors occurred

**Comment by Leviathan1753** [comment]
Something I've noticed a lot since I started using gitlfs, is that the GitHub Desktop powershell is way more reliable than any other system I've used.  I've repeatedly had trouble doing certain tasks via SourceTree, and even GitHub Desktop, but pop open that powershell, and it always seems to work like a charm.

Yet again, doing this checkout via the powershell worked wonders.

Is there some major difference between the powershell and GitHub Desktop that allows powershell to work so well?  I'd think GitHub Desktop would be doing the same things under the hood..

**Comment by Vochsel** [comment]
I also had this problem when trying to push a repo with a new file tracked with lfs, everything seemed setup correctly, but yet still received the API rate limit exceeded errors. The problem even existed on multiple machines, and multiple new repo's. However I just installed the github desktop client and synced and it worked correctly and uploaded it to my repo on github. I'm now able to push and clone the repo from command line. 

Is it possible the desktop client could have done some back end commands for setting it all up?

**Comment by technoweenie** [comment]
@Vochsel: yes, I believe GitHub Desktop sets up your Git credential cachers for you. Every case I've seen with this issue stems from a lack of Git credentials, causing git lfs to go into a loop until the API rate limit is reached.

**Comment by shiftkey** [comment]
@Vochsel what @technoweenie said is correct - GitHub Desktop acts as it's own credential provider - if you've authenticated with the app, those credentials will flow through when you launch Git Shell to do anything command-line related.
