### ISSUE TITLE
Git LFS installers should run 'git lfs init' as part of installation

### ISSUE THREAD

**Issue by strich** [github/git-lfs#799]
Given that `git lfs init` is a global command I figure it might make sense to do this as part of the installation script on any platforms that have it (Windows).

It would obviously still need to be in the installation documentation for any methods where the user is simply extracting the package on to the computer.

**Comment by technoweenie** [comment]
Totally. We use the nsis installer for windows, but I've been thinking about switching to [another one](http://www.jrsoftware.org/isinfo.php) for v1.1. I haven't had much windows experience, so any help here is appreciated.

**Comment by strich** [comment]
Yeah I saw that. I had planned to take a look at implementing that task myself soon if no one else picks it up.

**Comment by technoweenie** [comment]
@strich We have an [Installation chat room](https://gitter.im/github/git-lfs/installation) (in addition to the main lfs chat) if you want to rap about it in more real time :)

**Comment by dg9ngf** [comment]
I guess it shouldn't update the global config but the system config instead. The LFS setup is a systemwide thing and all users of the computer can use it. The global config only applies to a single user. So if one user installs this package and another one uses it, this part of the installation would be missing is only the global config was updated.

Instead of calling `git config --global ...`, it should be `git config --system ...`. If your installer writes to the files directly, act accordingly.

And including this step would remove a lot of the confusion people have around getting LFS to work. Having to install something twice that isn't obviously documented (and otherwise it would fail with very strange error messages or simply not do anything at all) is a bad user experience and leads to either support load or frustration and abandonment. (Actually LFS needs to be installed three times, with the third time being the repository-local config. This obviously isn't covered by the application installer.)

**Comment by strich** [comment]
Hey @dg9ngf - Yep this is clearly an issue I had not thought of. It would be trivial to change this to a system-wide config change. @technoweenie do you foresee any issues with this? If not, I'll make the change and submit the PR.

**Comment by technoweenie** [comment]
These config settings shouldn't affect any repositories that aren't using LFS, unless they happen to have their own separate LFS filter setting. Without `--force`, `git lfs install` won't overwrite an existing setting that it doesn't recognize.

I agree that the system config is a more appropriate default. I think both the `install` and `uninstall` commands should get `--system` and `--global` options, to go with `--local` as well for parity with `git config`. The windows installer is probably fine as-is.

@dg9ngf: thanks for the feedback!

**Comment by dg9ngf** [comment]
Well, you should retest your setup. I have just installed the following components into a brand new Windows 10.0 system:

* TortoiseGit 2.1
* Git 2.8.0
* Git LFS 1.1.2

And LFS was not registered anywhere visible in the system. I didn't check its function, just its configuration. It's not in the local config of newly created repositories (either with TGit or git.exe), nor in the two system-wide configs (there seem to be files in ProgramData\Git and ProgramFiles\Git\mingw64\etc). The global file in my user profile doesn't even exist yet.

The installer log (`git-lfs-windows-1.1.2.exe /log=c:\tmp\lfs-install.log`) doesn't say anything about running the external process. I'm not sure though whether it would be included here. I'm not regularly reading InnoSetup log files.

**Comment by strich** [comment]
And the installer appears to run to completion? You _should_ find Git LFS in `%programfiles%\Git LFS\`. Is this not so?

**Comment by dg9ngf** [comment]
The program files are installed and the installer seems to have finished successfully. At least there was no error message and I got the license confirmation, install path and finished page. But `git lfs install` wasn't run. I always need to do that manually once after running the graphical installer on a new computer. (And I need to include this only manual step in the installation guide for my colleagues.)

**Comment by strich** [comment]
I assume this is because you're installing Git LFS as a different user to the one you need to run `git lfs install` on manually?

**Comment by dg9ngf** [comment]
No, just one interactive user. The default case. Anybody should experience this issue. But I can retry it with different environments to check how widespread the issue is. But you basically say that if I run the LFS Windows installer, I should find the LFS filter entries in any of my Git configuration files (outside of repositories), is that correct? Because that's what I don't see.

**Comment by strich** [comment]
Any further tests would be great, as I've had this tested on a number of machines at work with no issues. How are you checking git config? If you run `git config -l` before and after installation you should see the new LFS config.

**Comment by dg9ngf** [comment]
On a machine that has never seen Git, I assume there is no Git configuration anywhere. Unless Windows 10 comes with one out of the box... Then after installation I can run `git config -l` as well as open each config file from the TortoiseGit UI. None contained LFS. I'm doing more tests. I have clean Windows 10 and 7 VMs around.

**Comment by strich** [comment]
Ah! Well yes, of course Git LFS won't install correctly if Git itself hasn't been installed yet. Git LFS is, after all, just an extension for Git.

**Comment by dg9ngf** [comment]
That's what I did, see my comment above. First TortoiseGit (optional), then Git, then LFS.

Windows 10.1511 and Windows 8.1 have just failed the test.

**Comment by dg9ngf** [comment]
Windows 7 SP1 also failed. All show the following identical output of `git config -l`:

```
core.symlinks=false
core.autocrlf=false
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
rebase.autosquash=true
credential.helper=manager
```

Can you describe the environment that passed your tests?

**Comment by dg9ngf** [comment]
This is a CMD session from the Windows 10 machine, running `git lfs install` manually the very first time:

```
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Testaffe>git config -l
core.symlinks=false
core.autocrlf=false
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
rebase.autosquash=true
credential.helper=manager

C:\Users\Testaffe>git lfs install
Git LFS initialized.

C:\Users\Testaffe>git config -l
core.symlinks=false
core.autocrlf=false
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
rebase.autosquash=true
credential.helper=manager
filter.lfs.clean=git-lfs clean %f
filter.lfs.smudge=git-lfs smudge %f
filter.lfs.required=true

C:\Users\Testaffe>
```

**Comment by strich** [comment]
We've had it tested on both Windows 8 and 10. This is also the first time this issue has been reported, and I'd think it'd be pretty quickly reported that LFS doesn't work at all after installation if it was a common case.

I'm really scratching my head as to what could be going wrong on your end - The installer should do this already, but can you try right-clicking the installer and running as admin?

**Comment by dg9ngf** [comment]
I think it requested admin elevation at the start but I'm going to check that. If it helps I might also be able to give you RDP, VNC or TeamViewer access to a VM where I tested it.

**Comment by dg9ngf** [comment]
Your installer always runs with admin privileges by design.

**Comment by technoweenie** [comment]
Weird, it shouldn't require admin privileges to run `git lfs install`, since it writes to the git config in your user directory. The proposed change to use `--system` that I mentioned above would probably require admin privs.

**Comment by dg9ngf** [comment]
I have the impression we're no longer in sync. The installer for me is the git-lfs-windows-1.1.2.exe file that I download from your website. I assume that this installer is supposed to start off `git lfs install` as part of the installation. Actually, that "install" command isn't really an installation, it's a configuration. This configuration as I call it does not happen. I can do it manually but I shouldn't need to.
