### ISSUE TITLE
Can not delete Large Files from repo again.

### ISSUE THREAD

**Issue by benelot** [github/git-lfs#804]
I have some large files that I checked into the original repo before I was forced to upload to LFS. Now that I want to remove them with the newest commit, I can not do it because the lfs-hook tells me that it detects large files.

How to reproduce:
-Upload a too large file into a github repository (I can not tell you how, as this was done pre git-lfs)
-Try to delete it again with another commit.
-You get that message that it does not work.

**Comment by technoweenie** [comment]
You need to rewrite your commits before pushing. If you've already pushed commits with big files, you'll need to do a migration that involves a force push at the end. This GitHub help article is a good start:

https://help.github.com/articles/removing-files-from-a-repository-s-history/
