### ISSUE TITLE
how do you make git-lfs play nicely with herkoku?

### ISSUE THREAD

**Issue by hayesmaker** [github/git-lfs#805]
Since installing git-lfs in my github repo, my deploys to heroku fail like this:
```
Repository or object not found: https://git.heroku.com/thrust-engine.git/info/lfs/objects
```
How do you make lfs play nicely with heroku deploys?

I tried removing .gitattributes, and the folder with lfs assets inside, and git ignoring them from my deploy branch before pushing to heroku, but this error persists.

**Comment by technoweenie** [comment]
Try removing the `.git/hooks/pre-push` hook. However, if you keep using Git LFS, it'll re-install that hook automatically.

We can look at setting up a no-hook mode if you need to work with LFS repos, but also deploy through Heroku (or any similar git interface for deployments). It would just require you to manually specify `git lfs pull` and `git lfs push` when working out of your origin git remote.

**Comment by hayesmaker** [comment]
removing that file fixed the problem for now... I'll add `rm .git/hooks/pre-push` to my deploy script. :dancer:

**Comment by EmilStenstrom** [comment]
Is removing that file actually a fix for how to use Git LFS with heroku?

**Comment by hayesmaker** [comment]
it's not a fix, currently heroku doesn't support git lfs.

**Comment by allthesignals** [comment]
Seems a little strange that having any trace of LFS disqualifies Heroku as a deploy option...

**Comment by ferrix** [comment]
Add --no-verify to the push command line to ignore the hook once.
