### ISSUE TITLE
Powershell succeeds when others don't

### ISSUE THREAD

**Issue by Leviathan1753** [github/git-lfs#808]
I've noticed this since I started using GitLFS.. but the powershell from GitHub Desktop will work and succeed at tasks when all other methods crash and burn.

Typically I'll do my work in SourceTree, but some major tasks that seems to suck/fail on.  So I'll switch to GitHub Desktop, and sometimes that'll do it better, sometimes not.  However, going to the powershell in GitHub Desktop seems to -always- work when the others fail.   Is there a reason for this?   Also, is there a reason GitHub Desktop itself would fail when its powershell succeeds?  Wouldn't it be doing the same commands under the hood?

Just trying to understand, as I think a lot of the "bugs" i experience using GitLFS might just be some config issue that powershell configs better when its doing things.  If i can figure that out, the whole experience overall might be bettter

**Comment by shiftkey** [comment]
>  So I'll switch to GitHub Desktop, and sometimes that'll do it better, sometimes not

@Leviathan1753 there's a log file found at `%LOCALAPPDATA%\GitHub\TheLog.txt` that will have some extra details around what might be occurring.

Also, we published an update to Git LFS 1.0.2 during the week. This might be related, but I'd love to understand what differences there are between the GUI and running commands in PowerShell.

**Comment by Leviathan1753** [comment]
Sorry about the delay, somehow missed this notification.   I'll see if I can trigger the difference again and report back.  Unfortunately, it's not always a surefire way that I've found to trigger the difference.  Usually is apparent when we're doing major merges or other messy work.  I've yet to find a truly repeatable case, which is why I was a bit hesitant making this report in the first place.  I'll let you know what I find with some logs.

**Comment by technoweenie** [comment]
Hi, I'm going through old issues that I've missed. I'm closing this until I can see some specific details.

However, there is some recent discussion in https://github.com/github/git-lfs/issues/1195 about similar issues. Git LFS provides better ways to download objects by bypassing git's internal filters, but it means there are manual commands you have to type, or that 3rd party tools like GH Desktop have to support.
