### ISSUE TITLE
Collaborators without Git LFS produce errors when merging upstream changes

### ISSUE THREAD

**Issue by seymour1** [github/git-lfs#809]
According to https://help.github.com/articles/collaboration-with-git-large-file-storage/, it seems that collaborators should be able to contribute without forcing install of Git LFS, but they just won't have access to the large files- only the pointer files.

This is fine for my purpose- I want to be able to let contributors generate the large files and PR them back into the original repo, and they don't need the actual files that have already been generated, the pointer files suffice. I'd actually prefer to periodically move the new large files over to Git LFS, so that I can check certain aspects of the file as it's being PR'ed.

However, when attempting to merge upstream changes without Git LFS, collaborators without Git LFS receive `git: 'lfs' is not a git command. See 'git --help'.`

Is there a best practice for dealing with forks and PRs when it comes to Git LFS?

**Comment by technoweenie** [comment]
That command is likely coming from some git config left over from uninstalling Git LFS. If you've never installed it, Git will be completely oblivious about LFS.

1. Clear any `filter.lfs` config settings.

    ```
$ git config --global --unset "filter.lfs.clean"
$ git config --global --unset "filter.lfs.smudge"
$ git config --global --unset "filter.lfs.required"
```

2. Remove any LFS pre-push hooks:

        $ rm .git/hooks/pre-push

> Is there a best practice for dealing with forks and PRs when it comes to Git LFS?

Every user and collaborator should be using Git LFS to be effective. You won't be able to make PRs changing LFS content without it.

**Comment by seymour1** [comment]
Hi again!
So, there's very little chance that Git LFS was installed on the machine previously. If it helps, the collaborator was using Mac OSX- so maybe this should just be documentation of a possible issue for the future. If this crops up again, I'll try those commands and see if the issue continues.

As for the all users having Git LFS- my particular use case (distributing work units) doesn't require that :-)

Anyway, I guess this issue can be closed for now, and I'll just ask for it to be reopened if I can reproduce the issue reliably.

**Comment by technoweenie** [comment]
BTW If you install Git LFS and want to remove it, running "git lfs uninit" will remove those config settings too.
