### ISSUE TITLE
Tiny local lfs files; remote says they're big

### ISSUE THREAD

**Issue by rBatt** [github/git-lfs#815]
I have files being tracked by git-lfs that locally are tiny:
<img width="569" alt="screen shot 2015-11-04 at 2 31 29 pm" src="https://cloud.githubusercontent.com/assets/5630847/10949429/c82370a2-8300-11e5-816e-3a728f1e84b1.png">

However, on GitHub it says they are much larger (appropriate size); for example, `newf.zip` is 6.64 MB, and GitHub says it's being tracked by lfs.

If I do a `git pull`, it says I'm up to date. If I try to open the file, I get one of those infinite zip file scenarios (unzipping yields a `.zip.cpgz` file ... ugh).

So I have a bit of a problem where all these local files are apparently useless to me. How did I get myself in this situation? How do I avoid it, and fix it?

**Comment by rBatt** [comment]
Also, and possibly related, I remember at one point reading that I might need to do a `git lfs pull` to pull in the larger versions of files from a remote instead of the pointer only (pardon if my language is incorrect here); however, I can't seem to find any documentation on that now. 

Furthermore, apparently `git lfs pull` is no longer a command. Was it replaced by something else?

**Comment by technoweenie** [comment]
What does `git lfs env` say?

**Comment by rBatt** [comment]
```
git-lfs/0.5.4 (GitHub; darwin amd64; go 1.4.2)
git version 2.6.2

Endpoint=https://github.com/rBatt/trawlData.git/info/lfs
LocalWorkingDir=/Users/Battrd/Documents/School&Work/pinskyPost/trawlData
LocalGitDir=/Users/Battrd/Documents/School&Work/pinskyPost/trawlData/.git
LocalMediaDir=/Users/Battrd/Documents/School&Work/pinskyPost/trawlData/.git/lfs/objects
TempDir=/Users/Battrd/Documents/School&Work/pinskyPost/trawlData/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=false
```

So apparently it has me on the old version of `git-lfs` again. I have 1.0.2 installed through Homebrew. My `echo $PATH` is 

```
/usr/texbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/opt/ImageMagick/bin:/Library/TeX/texbin
```

How do I delete that old `git-lfs`? Is that the problem?

**Comment by technoweenie** [comment]
Run `which git-lfs` to see where the old version is being referenced from. You can safely delete that one, so hopefully the homebrew one will take precedence.

**Comment by rBatt** [comment]
Also, it might be worth pointing out that I have this directory sync'd among 3 computers using BitTorrentSync. I don't know if you're familiar with it, but I've used BTS to sync directories managed by Git for a couple years w/o problems.

I'm a git novice, though.

My computer at home is new, and I've only ever installed git lfs 1.0.2 on it. For that machine, the current `git lfs env` is:

```
git-lfs/1.0.2 (GitHub; darwin amd64; go 1.5.1)
git version 2.6.2

Endpoint=https://github.com/rBatt/trawlData.git/info/lfs (auth=basic)
LocalWorkingDir=/Users/battrd/Documents/School&Work/pinskyPost/trawlData
LocalGitDir=/Users/battrd/Documents/School&Work/pinskyPost/trawlData/.git
LocalGitStorageDir=/Users/battrd/Documents/School&Work/pinskyPost/trawlData/.git
LocalMediaDir=/Users/battrd/Documents/School&Work/pinskyPost/trawlData/.git/lfs/objects
TempDir=/Users/battrd/Documents/School&Work/pinskyPost/trawlData/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""
```

I've been noticing problems where the changes on one machine aren't properly being reflected on the other machine (1 will say the directory is clean, while the other reports I have numerous uncommitted changes). I can talk more about that if you think it's relevant. Maybe related to different versions of `git lfs`.

**Comment by rBatt** [comment]
`which git-lfs` on my current (outdated) machine reads `/usr/local/bin/git-lfs`.

But that's the homebrew directory, right?

**Comment by rBatt** [comment]
I just went in an deleted the old Homebrew versions of `git-lfs` in the `/usr/local/Cellar/git-lfs`. Now only 1.0.2 is left there.

**Comment by technoweenie** [comment]
> git config filter.lfs.smudge = ""

You need to run `git lfs init` on every computer that you have git lfs installed. That will set the `filter.lfs.*` config values globally. This is why your git clones are not downloading the files for you. Running `git lfs pull` should not be necessary.

Also, without the `filter.lfs.clean` setting, you won't be able to add files through LFS, even if they're tracked.

> But that's the homebrew directory, right?

By default, yes. You can run `brew --prefix` to get the prefix for installed packages. Add "/bin" to get the path. 

```
$ brew --prefix
/usr/local
# my stuff is installed to /usr/local
```

You can run `brew info git-lfs` to see what version it has installed. However, if you replace `/usr/local/bin/git-lfs` manually (I do this sometimes to test new builds), homebrew will report the wrong version. If that's the case, you may want to do something like:

```
$ brew unlink git-lfs
$ brew install git-lfs # gets the LATEST version
```

**Comment by technoweenie** [comment]
Ok now that you have v1.0.2, run:

```
$ git lfs init

# go to your repo with the tiny lfs pointer files
$ git lfs pull

# now show me the new env 
$ git lfs env
```

**Comment by rBatt** [comment]
Do `git lfs init` on all machines? I've done it on my current machine. The files are sync'd between them all, so even if I never explicitly typed `git lfs init` all files in the directory are the same. But I'll go through and type it everywhere.

**Comment by technoweenie** [comment]
Yes, it sets up `filter.lfs.*` settings in the global git config for each machine. This config cannot be shared, unless you're syncing `~/.gitconfig` between all your computers.

**Comment by rBatt** [comment]
After typing `git lfs init` on the 3 machines, these are the results:

Local Machine:
```
Updated pre-push hook.
Git LFS initialized.
```

Remote Machine 1 (the new one):
```
Updated pre-push hook.
Git LFS initialized.
```

On one Remote Machine 2 I got:
```
The filter.lfs.clean attribute should be "git-lfs clean %f" but is "git lfs clean %f"
Run `git lfs init --force` to reset git config.
```


Thanks for you comment about `filter.lfs.*` and `~/.gitconfig`. I did not know about that.

Should I force the `git lfs init --force` on the Remote Machine 2?

**Comment by technoweenie** [comment]
> Should I force the git lfs init --force on the Remote Machine 2?

Yup. Changing `git lfs clean` to `git-lfs clean` is a tiny micro optimization, but it doesn't hurt.

**Comment by rBatt** [comment]
Ah, brilliant! I just did the `git lfs pull` on my Local Machine, and all my big files are back.

Related note: If I started collaborating with people who had forgotten to install `git lfs`, would they experience issues similar to what I just encountered? I.e., if they pulled down the repo, they would see tiny files? I'm trying to get our whole group to start using `git lfs`, and I haven't been sure of what will happen if they forget to do the `git lfs` on accident.

**Comment by rBatt** [comment]
And just to be clear, I'm not syncing `~/.gitconfig` among computers, so that was at least part of the problem.

It seems that my first mistake was improperly updating (`upgrade`) git-lfs through Homebrew; version 0.5.4 was still being used. The second mistake was not doing `git lfs init` on each machine, because even though the repo is syncd between computers, there is a file `~/.gitconfig` that is outside the repo, and thus wouldn't be sync'd.

In the future, do I need to do `git lfs init` on all new repos, or do I just do that whenever I upgrade git-lfs? Also, should I always do a `git lfs pull` when I want to pull down the large binaries, or does a normal `git pull` give me the full big file?

**Comment by rBatt** [comment]
Oh, and as you requested, post-`git lfs pull`, a `git lfs env` gives the following:

```
git-lfs/1.0.2 (GitHub; darwin amd64; go 1.5.1)
git version 2.6.2

Endpoint=https://github.com/rBatt/trawlData.git/info/lfs (auth=basic)
LocalWorkingDir=/Users/Battrd/Documents/School&Work/pinskyPost/trawlData
LocalGitDir=/Users/Battrd/Documents/School&Work/pinskyPost/trawlData/.git
LocalGitStorageDir=/Users/Battrd/Documents/School&Work/pinskyPost/trawlData/.git
LocalMediaDir=/Users/Battrd/Documents/School&Work/pinskyPost/trawlData/.git/lfs/objects
TempDir=/Users/Battrd/Documents/School&Work/pinskyPost/trawlData/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
git config filter.lfs.smudge = "git-lfs smudge %f"
git config filter.lfs.clean = "git-lfs clean %f"
```

**Comment by technoweenie** [comment]
Yup. Git LFS works by inserting itself into some low-level Git hooks (the `filter.lfs.*` setting). Without Git LFS installed, git clones will just happen like normal, just like your experience in the original post.

> In the future, do I need to do git lfs init on all new repos, or do I just do that whenever I upgrade git-lfs?

Only once for each computer. You don't need to run it after upgrades or with new repos.

> Also, should I always do a git lfs pull when I want to pull down the large binaries, or does a normal git pull give me the full big file?

By default, git lfs (using the `filter.lfs.smudge` setting) will automatically download everything for you.

**Comment by rBatt** [comment]
>>Also, should I always do a git lfs pull when I want to pull down the large binaries, or does a normal git pull give me the full big file?

>By default, git lfs (using the filter.lfs.smudge setting) will automatically download everything for you.

To be clear, you're saying that I only need to do `git pull` in the future? Such that `git lfs pull` is entirely redundant with `git pull`?

Thanks so much for your help. Very cool product, and surprisingly easy to troubleshoot when I have run into a problem (the problems reflect on me, not git-lfs, btw!).

**Comment by technoweenie** [comment]
> To be clear, you're saying that I only need to do git pull in the future? Such that git lfs pull is entirely redundant with git pull?

Yes.

> Thanks so much for your help. Very cool product, and surprisingly easy to troubleshoot when I have run into a problem (the problems reflect on me, not git-lfs, btw!).

While there are some common unix/git concepts that lead to your problems, I think the Git LFS documentation should be able to help you out a LOT more too. Thanks for checking it out, and your patience getting to the bottom of this!
