### ISSUE TITLE
git lfs push not working

### ISSUE THREAD

**Issue by sepastian** [github/git-lfs#833]
After searching around for hours, i'm opening a new issue.

I have created an empty, private repository at github.com. I have added and pushed a `README.md`, `.gitattributes` and `.gitignore`.

Now I try to add files to LFS.

```
git lfs track
Listing tracked paths
    *png (.gitattributes)
    *blend (.gitattributes)
    *ttf (.gitattributes)
    *jpg (.gitattributes)
    *mov (.gitattributes)
    *avi (.gitattributes)
    *mpg (.gitattributes)
    *mpeg (.gitattributes)
    *wav (.gitattributes)
```

```
git lfs ls-files
f71da2c579 - live/arrow/PARTICLES/particles0001.png
da2377825e - live/arrow/PARTICLES/particles0002.png
d582e7d8b8 - live/arrow/PARTICLES/particles0003.png
:
622d33b5e5 - live/arrow/lightrays/lightrays_00071.png
26978b2315 - live/arrow/previews/test0001-0431.avi
bd9d530055 - live/arrow/template.blend
```

Then, when i try to push, I get:

```
$ git push 
live/arrow/PARTICLES/particles0001.png is an LFS pointer to f71da2c579ee3aac0e046953e393d8ad53e26bce2bb27065e3351d8c1cf97dd8, which does not exist in .git/lfs/objects.

Run 'git lfs fsck' to verify Git LFS objects.
error: failed to push some refs to 'git@github.com:***/templates.git'
```

No objects seem to have been created for my LFS tracked files:

```
$ tree .git/lfs/objects/
.git/lfs/objects/
├── f7
│   └── 1d
└── logs
```

Why??

**Comment by technoweenie** [comment]
Looks like one of two things:

1. The repository was cloned from somewhere without downloading LFS objects. Run `git lfs fetch [remote]` to download them.
2. Something outside of Git LFS removed those files. Git LFS itself doesn't have any code to remove these files (as of v1.0.2).

Also, you may have better luck using patterns like `*.png` instead of `*png` when tracking files through LFS.

**Comment by sepastian** [comment]
Thanks.

I changed `.gitattributes` to use `*.png` instead if `*png` (for other extensions, too).

When running `git lfs fetch`, I get

```
Fetching master
(0 of 308 files) 0 B / 58.59 MB                                                                                                      
Git LFS is disabled for this repository.
Docs: https://github.com/contact
Git LFS is disabled for this repository.
Docs: https://github.com/contact
Git LFS is disabled for this repository.
Docs: https://github.com/contact
Git LFS is disabled for this repository.
Docs: https://github.com/contact
Warning: errors occurred
```

Here's the output of `git lfs env`

```
git-lfs/1.0.2 (GitHub; linux 386; go 1.5.1; git 0566698)
git version 2.6.2

Endpoint=https://github.com/viddyozeapp/templates.git/info/lfs (auth=none)
  SSH=git@github.com:viddyozeapp/templates.git
LocalWorkingDir=/home/sebastian/Code/viddyoze-templates
LocalGitDir=/home/sebastian/Code/viddyoze-templates/.git
LocalGitStorageDir=/home/sebastian/Code/viddyoze-templates/.git
LocalMediaDir=/home/sebastian/Code/viddyoze-templates/.git/lfs/objects
TempDir=/home/sebastian/Code/viddyoze-templates/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""
```

The repository was not cloned. I started with a directory containing my data, I ran `git init`, then set `git remote add origin ...`. I set `.gitattributes`, added some files to LFS, `git lfs ls-files` is showing these files. When doing `git lfs push origin master` gives a `Clean pointer error`, `git lfs fetch origin master` gives the error above.

What am I doing wrong?

**Comment by technoweenie** [comment]
> Git LFS is disabled for this repository.

You've run over your quota for storage and bandwidth on GitHub.

> Clean pointer error

I'd have to see details of the error. But I think this means you added a Git LFS pointer file, and not the actual file.

**Comment by sepastian** [comment]
OK, given I am over my quota, your explanation for the _Clean pointer error_ makes sense. A pointer has been created, but uploading the actual file failed because of the quota.

However, in the organization settings, it doesn't look as if any of my quota was used up.

![billing](https://cloud.githubusercontent.com/assets/14915/11206211/b6a9aa50-8d0d-11e5-8cdd-640dc7b22928.png)

I need this working, urgently. What can be done?

**Comment by technoweenie** [comment]
@sepastian I confirmed your organization's usage and turned Git LFS on for you. You should be good to go now.

**Comment by sepastian** [comment]
Sorry, still no luck, nothing changed.

```
$ git lfs track
Listing tracked paths
    *.png (../.gitattributes)
    *.blend (../.gitattributes)
    *.ttf (../.gitattributes)
    *.jpg (../.gitattributes)
    *.mov (../.gitattributes)
    *.avi (../.gitattributes)
    *.mpg (../.gitattributes)
    *.mpeg (../.gitattributes)
    *.wav (../.gitattributes)
$ git lfs push origin master
Clean pointer error
$ git push 
live/arrow/PARTICLES/particles0001.png is an LFS pointer to f71da2c579ee3aac0e046953e393d8ad53e26bce2bb27065e3351d8c1cf97dd8, which does not exist in .git/lfs/objects.

Run 'git lfs fsck' to verify Git LFS objects.
error: failed to push some refs to 'git@github.com:XXXX/templates.git'
$ git remote show origin 
* remote origin
  Fetch URL: git@github.com:XXXX/templates.git
  Push  URL: git@github.com:XXXX/templates.git
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (fast-forwardable)
$ git lfs fsck
Object live/arrow/arrowmask/arrow_00000.png (941750c8337e89883c9843d2eded9d4f32c9826e032a9cbe18db7cd0978b7a5b) could not be checked: no such file or directory
Object live/arrow/arrowmask/arrow_00040.png (dc430adaa9dc48241b0fec5ec90384d01efb07f352a93ca93bf3d45058c7c0ec) could not be checked: no such file or directory
Object live/arrow/arrowmask/arrow_00131.png (1c6f41f2fc9c881315de8241aa2a25755bab5036b1551dc68bd391659ecb57a2) could not be checked: no such file or directory
Object new/Cave Wall Carvings/textures/vignette.png (6bb2fa0dd4c1abd10cd30a4a7123536dd459b41f17e4fc9fc9ec726ac2888a78) could not be checked: no such file or directory
Object live/arrow/PARTICLES/particles0028.png (f86fca3ed47d465e30e5f3d823766bfdec76b91781e28d98db666f663ba6be1b) could not be checked: no such file or directory
Object live/arrow/lightrays/lightrays_00005.png (6037185caaec866205f9483f5ffa19342afd39f5de794a217f14781230530b6d) could not be checked: no such file or directory
:
```

**Comment by sepastian** [comment]
Can I try something different? Such as creating a new repo from scratch? Could you tell me how to do this exactly? Then we know, whether I am doing something wrong or there is an issues somewhere else...

**Comment by sepastian** [comment]
Hello again, appears to be working no - maybe it just took some time for the _reset_ to propagate through...

Thanks for your help!

**Comment by technoweenie** [comment]
Blah, sorry I left this hanging. Glad you got it working though.

**Comment by mlbright** [comment]
What do the "object could not be found" errors mean?

**Comment by wooden-utensil** [comment]
Commit and try 
```bash
$ git lfs track
$ git lfs track *.foo
$ git lfs push remote branch
```
<sup>(I've got the same issue too.)</sup>

**Comment by wooden-utensil** [comment]
Could be a duplicate of #994

**Comment by wooden-utensil** [comment]
Make sure your `.gitattributes` file has `lfs` for the `file.ext`s.
Make sure `git lfs ls-files` returns the files you want to treat as large.

**Comment by soerendip** [comment]
It does not.
