### ISSUE TITLE
global/local email config clash

### ISSUE THREAD

**Issue by pearswj** [github/git-lfs#859]
I'm getting the following warning after upgrading to v1.1.0.

```
WARNING: These git config values clash:
  git config "user.email" = "<personal email in ~/.gitconfig>"
  git config "user.email" = "<work email in .git/config>"
```

Is there any reason why my personal/work/global/local email configuration wouldn't work with git-lfs?

`git-lfs/1.1.0 (GitHub; darwin amd64; go 1.5.1)`

\cc @technoweenie

**Comment by technoweenie** [comment]
Nope, that warning isn't a very strong warning. I'm going to change that up so it only warns about config keys important to LFS. Sorry for the extra noise!

**Comment by technoweenie** [comment]
I hacked up a fix: #861. Should make it in the next release.

Also if I wasn't super clear, you can totally ignore that warning.

**Comment by pearswj** [comment]
Just built #861 and the warnings have disappeared. Thanks for the quick turnaround!

**Comment by andre487** [comment]
+1
