### ISSUE TITLE
git lfs track "/somedir/*" error

### ISSUE THREAD

**Issue by larsxschneider** [github/git-lfs#870]
I think a slash at the beginning of a pattern is valid and indicates the root of the repository. This is explicitly stated in [.gitignore](https://github.com/git/git/blob/f5b6079871904ba5b0a8548f91545f126caf898b/Documentation/gitignore.txt#L112-L114) but seems to work in the same way for .gitattributes.

git-lfs 1.1.0 returns " is outside repository" in that case.

**Comment by technoweenie** [comment]
This was put in to prevent people from referencing absolute paths outside of the repository. You can update `.gitattributes` and add whatever you want though. Is there some reason you can't use just "somedir/*"?

**Comment by larsxschneider** [comment]
Yes, I edited `.gitattributes` manually. I think the difference is:

"somedir/*" will match:
```
somedir/*
foo/bar/somedir/*
...
```

whereas "/somedir/*" will match only:
```
somedir/*
```

no?

**Comment by technoweenie** [comment]
Ok, seems legit :+1:

**Comment by larsxschneider** [comment]
thanks :-) ... I am a bit busy right now but maybe I can provide a patch next week or so...

**Comment by technoweenie** [comment]
Cool. I added it to the v1.2 checklist. Though being a bug, it could technically go towards v1.1.1 if we need it.
