### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by jleppert** [github/git-lfs#873]
I followed the example directions precisely and it's failed to track any files. Just plain doesn't work. No files are listed as tracked, although I have added the files to be tracked.

my attributes file:
```
local/lib.new/libgdal.so.1 filter=lfs diff=lfs merge=lfs -text
bundle.zip filter=lfs diff=lfs merge=lfs -text
*.zip filter=lfs diff=lfs merge=lfs -text
local/lib filter=lfs diff=lfs merge=lfs -text
local/lib.new filter=lfs diff=lfs merge=lfs -text
local/bin filter=lfs diff=lfs merge=lfs -text
local/bin.new filter=lfs diff=lfs merge=lfs -text
local/lib64 filter=lfs diff=lfs merge=lfs -text
local/lib/libgdal.a filter=lfs diff=lfs merge=lfs -text

now:

git lfs status
On branch master
Git LFS objects to be pushed to origin/master:


Git LFS objects to be committed:


Git LFS objects not staged for commit:

git lfs track
Listing tracked paths
    local/lib.new/libgdal.so.1 (.gitattributes)
    bundle.zip (.gitattributes)
    *.zip (.gitattributes)
    local/lib (.gitattributes)
    local/lib.new (.gitattributes)
    local/bin (.gitattributes)
    local/bin.new (.gitattributes)
    local/lib64 (.gitattributes)
    local/lib/libgdal.a (.gitattributes)
    bundle.zip (local/.gitattributes)
    local/lib.new/libgdal.so.1 (local/.gitattributes)

git lfs ls-files
```

what gives? it doesn't do anything..

**Comment by technoweenie** [comment]
Git LFS only works on new things that you add or change. It can't go through existing repository history and update the repository. Check out the [BFG Repo Cleaner](https://github.com/rtyley/bfg-repo-cleaner/releases) for migrating repositories with existing data.

If this doesn't help, can you be more specific about what's wrong?

**Comment by timini** [comment]
I think you could do with more in depth tutorial / documentation. It might help to explain a little how lfs works too. It is very confusing starting a repository using lfs.

**Comment by jleppert** [comment]
I figured it out; but had to create a new repository. It might be worth noting that the github is advertising git-lfs as a potential solution when you try to push large files -- there's actually a URL in the banner that comes back from the server on the pre-commit hook with a link to the web site.

Upon further examination, it appears git-lfs is ill-suited for existing repos. It would be nice if there was an easy way to just go through a repo and somehow re-create files over a size n as git-lfs files; that's what I was looking for and I'd imagine is the pain point many others are trying to solve as well.

**Comment by technoweenie** [comment]
> It would be nice if there was an easy way to just go through a repo and somehow re-create files over a size n as git-lfs files

Check out the [BFG Repo Cleaner](https://github.com/rtyley/bfg-repo-cleaner/releases) for this.
