### ISSUE TITLE
Git lfs with files in repo that are already committed

### ISSUE THREAD

**Issue by joshterrill** [github/git-lfs#874]
I have a repo that has a folder of files that should be managed under git-lfs. I've done `git lfs track` for each of the files, it created the `.gitattributes` file. But when I did a `git status`, it only showed the attributes file as being added, nothing changed. I did a check in, and nothing seemed to change. Is there any way that I can manage already committed files using git lfs?

**Comment by technoweenie** [comment]
While I'd like Git LFS to support existing data natively, it's not a trivial task. Check out [BFG Repo Cleaner](https://github.com/rtyley/bfg-repo-cleaner/releases).

**Comment by Diogo-Rossi** [comment]
I'm trying to learn how to use git-lfs and found this topic in 2021. It seems it now supports existing data, right?
If I do ```git lfs track``` the files, then the ```git status``` show me that the files have been modified, even if nothing has been updated inside the files. Am I right?

**Comment by bk2204** [comment]
If you want to track existing files, you need to either use `git lfs migrate import --no-rewrite` with an appropriate pattern or use `git add --renormalize .` after `git lfs track` (and then commit).

**Comment by Diogo-Rossi** [comment]
> If you want to track existing files, you need to either use `git lfs migrate import --no-rewrite` with an appropriate pattern or use `git add --renormalize .` after `git lfs track` (and then commit).

What happens if I just do `git lfs track` the existing files and then commit?

**Comment by bk2204** [comment]
Then your repository will show the files as modified whenever you check them out, and will continue to do so until you run `git add --renormalize .` and commit.

**Comment by Diogo-Rossi** [comment]
Sorry, I didn't made myself clear: I did `git lfs track` the existing files, then did `git add .` to add all the files to the index (without the option `--renormalize`). Only then I committed the files.

In this way, will the files continue to show as modified? Why do I have to use `--renormalize`?

Thanks for the answers.

**Comment by bk2204** [comment]
Yes, they will continue to show as modified.  The way that Git works is that Git LFS is a smudge and clean filter, and tracking a file tells Git to enable Git LFS on the file.  Once Git LFS is enabled on the file, Git will clean the files through Git LFS so that your large files are turned into pointer files.  When it does that, the data in the repository (the large file) differs from the version that Git got when it ran the code through the clean filter (the pointer file) and so it shows it as modified.

This is required almost anytime you change the `.gitattributes` file for a particular path with Git, whether it's for Git LFS, a working tree encoding, or line endings.

**Comment by Diogo-Rossi** [comment]
Thank you so mush.
So, it is right to say that [this answer](https://stackoverflow.com/a/47200501) is incomplete?

**Comment by bk2204** [comment]
If you `git add` the file manually after `git lfs track`, it will _probably_ work, but I haven't tested.  I don't know if that answer is correct or not, but if you want to be certain, you should use `--renormalize` or use `git lfs migrate import --no-rewrite` instead.

**Comment by puravpanchal** [comment]
How to move an non-lfs repo to lfs if I have a custom .gitattributes file? The migrate import no rewrite needs all files as input argument and I cannot enter all filenames as there are n number and also with different extensions. Also if there are different branches, do we have to perform --renormalize on all the branches?

**Comment by bk2204** [comment]
You can use the same technique of using your custom `.gitattributes` file and then `git add --renormalize`, then commit.  `git lfs migrate import --no-rewrite` is simply a different way of doing the same thing.  And yes, you need to do the renormalize on all branches.

**Comment by puravpanchal** [comment]
Oh thanks, after I do this on my pc. Does every other user has to perform reclone or they can also just fetch and prune and then checkout?

**Comment by bk2204** [comment]
No, a reclone is not necessary.  However, users do need to update their branches to ones that contain the proper `.gitattributes` and have had `git add --renormalize` done on them.

**Comment by puravpanchal** [comment]
They need to do the renormalize too? There are 30 users and I think most of them have no clue how this works. If 30 users do renormalize and commit, then it will mess up the history. Isn't there any other option where they won't have to do much?

**Comment by bk2204** [comment]
Every user must end up with an appropriate `.gitattributes` file on which `git add --renormalize` has been done if you don't want to rewrite history totally.  Users can rebase on the main branch if you've handled it already, but if they've updated the files which are now LFS files, then the rebase may or may not make them into LFS files, and if it doesn't, then you'll end up with perpetually modified files.  If they haven't modified the new LFS files, then there's no need to do anything but rebase onto the main branch.

**Comment by puravpanchal** [comment]
Can they not simply fetch the branch from origin (so they will get the new .gitattribute file on which --renormalize has been done). Or will it work if they simply delete the repo locally and reclone? Because this would be an easy option to explain.

**Comment by bk2204** [comment]
They can fetch the branch and rebase any in-progress work, or re-clone as they like.

The rule is that they cannot modify any files that are newly LFS files without having the correct `.gitattributes` file where `--renormalize` has been done.  See [the FAQ entry for “Why do I end up with some of my working tree files constantly showing as modified?”](https://github.com/git-lfs/git-lfs/wiki/FAQ) to see what will happen if they break this rule.

**Comment by puravpanchal** [comment]
I have an another question, if I don't want to track the existing files, can I just add .gitattributes to main branch and then cherry pick this commit on all other branches. Then whenever there is a new commit with mentioned extension, will lfs track it? or is it necessary to perform renormalize no matter what?

**Comment by bk2204** [comment]
Adding a pattern to `.gitattributes` is considered tracking that file with Git LFS.  If no patterns match any existing files, then you don't need to renormalize.  If the patterns match any existing files, then you must renormalize.
