### ISSUE TITLE
README.md doesn't mention git lfs init

### ISSUE THREAD

**Issue by mnot** [github/git-lfs#881]
README.md gives a short demo of lfs, but fails to mention that its necessary to `git lfs init` first. 

This is confusing and leads to much brokenness.

**Comment by technoweenie** [comment]
The command is called `git lfs install` as of Git LFS v1.1, and it's mentioned in the [Getting Started](https://github.com/github/git-lfs#getting-started) section.  I have a big revision of the readme coming up, so I'll pull it out into a separate code block to make it stand out more.

**Comment by technoweenie** [comment]
How's [this](https://github.com/github/git-lfs/blob/readme-updates/README.md#getting-started) look? I went ahead and pushed up my changes: #882

**Comment by mnot** [comment]
Awesome.
