### ISSUE TITLE
Question: How to configure the lfs storage location?

### ISSUE THREAD

**Issue by crydalch** [github/git-lfs#886]
I'm new to git lfs, and am wondering how to configure where the files are stored? When I run `git lfs env`, I see **LocalMediaDir** is setup; is there supposed to be a **RemoteMediaDir**, or something along those lines? So far, I haven't seen anything alluded to in any docs or man pages I've found so far...

It'd be great to be able to change the default location where git lfs is sending/retrieving the files.

Thanks in advance!

**Comment by dseeker** [comment]
I've been looking for where the binaries are stored after a github push but can't find this info so far.

**Comment by technoweenie** [comment]
Hi, I'm going through old issues I missed and replying to them.

LFS requires a server, there is no "remote media directory".  The [spec](https://github.com/github/git-lfs/blob/master/docs/spec.md#the-server) describes how to configure where the server lives.
