### ISSUE TITLE
The first command in the Git-LFS is wrong

### ISSUE THREAD

**Issue by pditommaso** [github/git-lfs#888]
In the [Git-LFS](https://git-lfs.github.com/) page is written: 

    1. Download and install the Git command line extension. You only have to set up Git LFS once.

        git lfs install 

However install is not an available command: 

    $ git lfs install
    Error: unknown command "install" for "git-lfs"
    Run 'git-lfs --help' for usage. 

I guess you mean `git lfs init`

**Comment by technoweenie** [comment]
The command name changed in Git LFS v1.1.0 (though `git lfs init` will continue to work for awhile). You can substitute `git lfs init` for `git lfs install`, and `git lfs uninit` for `git lfs uninstall`.

**Comment by chrisfree** [comment]
I just ran into this same issue. Running `git lfs init` fixed it.
