### ISSUE TITLE
Retry (or resume) when encountering download errors

### ISSUE THREAD

**Issue by rubyist** [github/git-lfs#89]
When the git media client receives an unexpected EOF from the server, it will panic and abort the clone/push. It should retry (or resume) the download.

**Comment by feldan** [comment]
@technoweenie @rubyist , I'd just like to add it seems like a bug to me - writing the pointer file (which has the exact name as the file itself) can be misleading:  i.e. I expect the file to be there and it is - but the content is wrong, now I have to backtrack and understand what messed up  (think about a CI server failing a build over this or worse - packaging a release with bad content).
you should not write the pointer if the get failed in my opinion.

**Comment by technoweenie** [comment]
We have some retries now.
