### ISSUE TITLE
v1.1.0 Does not support passwords with spaces

### ISSUE THREAD

**Issue by stemid** [github/git-lfs#890]
I have not tried a later version but I can't see this being fixed in #844. 

Steps to reproduce:
  1. Set a password with spaces on the server end, for example "horse battery staple"
  2. git push -u origin master

Expected results: Login to HTTP service

Actual results: git lfs will not accept the password and continues asking for it

Workaround: Changed password to have no spaces, for example "misrecollect9001"

**Comment by larsxschneider** [comment]
Maybe this is connected to the base64 encoding issue mentioned [here](https://github.com/github/git-lfs/issues/938#issuecomment-180625818), too?

**Comment by stemid** [comment]
I'm afraid someone else will have to check the encoding to compare if the issues match because I've moved to a different solution.

**Comment by ttaylorr** [comment]
Should be fixed in https://github.com/github/git-lfs/pull/989, otherwise give v1.2.1 a shot 😄
