### ISSUE TITLE
smudge filter failed?

### ISSUE THREAD

**Issue by jleppert** [github/git-lfs#892]
```
[ec2-user~/lambda (master)]$ git pull
Updating a6cbfb9..e70300c
error: unable to write file dsm2.tif
Error accessing media: dsm_1.tif (9d2afb0bad298a9173d3e38831b340e71dea3c31969e3d0c0b7f0578bd64e8fd)

Errors logged to .git/lfs/objects/logs/20151207T022523.981710529.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge %f failed 2
error: external filter git-lfs smudge %f failed
fatal: dsm_1.tif: smudge filter lfs failed
```

and then I try to look at the logs:
```
[ec2-user~/lambda (master)]$ git lfs logs last
```
(no logs listed)
```
[ec2-user~/lambda (master)]$ git reset HEAD --hard
fatal: Could not write new index file.
```
Trying to figure out what  smudge filter lfs failed means, why there are no logs when it implied there would be logs to help figure out the issue, and why won't resetting to head work? It appears my repo is in a broken state and I'm not sure how to recover it (besides re-cloning)?

```
[ec2-user~/lambda (master)]$ git lfs version
git-lfs/1.1.0 (GitHub; linux amd64; go 1.5.1; git 258acf1)
```

**Comment by technoweenie** [comment]
"error: unable to write file dsm2.tif" is a strange error. You're not out of disk space or anything, are you?

Does `.git/lfs/objects/logs/20151207T022523.981710529.log` exist? If not, try running `GIT_TRACE=1 git pull`.

**Comment by jleppert** [comment]
I deleted the checked out copy and retried and not having this issue. Maybe a problem writing the file system? Have plenty of free space.

**Comment by jleppert** [comment]
Actually, looks like github just killed my repo. Maybe not let me push if I'm over their "quota". Sheesh. How nice of them. What a horrible thing to do to someone!! Requiring me to dig through log files to find their squelched error message and apparently breaking your stuff.

```
git-lfs/1.1.0 (GitHub; linux amd64; go 1.5.1; git 258acf1)
git version 2.4.3

$ git-lfs smudge dsm_1.tif
Error accessing media: dsm_1.tif (9d2afb0bad298a9173d3e38831b340e71dea3c31969e3d0c0b7f0578bd64e8fd)

This repository is over its data quota. Purchase more data packs to restore access.
Docs: https://github.com/contact
goroutine 1 [running]:
```

**Comment by jleppert** [comment]
Can you help me out? There is nowhere to figure out how to purchase more data packs to get my repo back into a workable state.

**Comment by technoweenie** [comment]
Ah, thanks for the feedback. That's definitely a message that the smudge command should be writing to stderr, instead of hiding away in a log file.

As for GitHub data packs:

* https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-an-organization/
* https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-a-personal-account/

If you have questions about GitHub specific stuff, hit me up at [GitHub Support](https://github.com/c).

**Comment by jleppert** [comment]
Thanks. It's really annoying to waste 2 hours of time to pay $5..

**Comment by sqs8866** [comment]
@jleppert I have the same question.The system needs to be cracked before it can be used
