### ISSUE TITLE
Clashing config values

### ISSUE THREAD

**Issue by larsxschneider** [github/git-lfs#894]
Hi,

git-lfs checks (rightly so!) for clashing config values:
https://github.com/github/git-lfs/blob/e467a119b8ca38bbcd1a9f5479e43bdb14d17f70/lfs/config.go#L407

However, in case the clashing configs have exactly the same values (e.g. defined in global git config and in system git config) then we don't have a problem. Should git-lfs still print a warning in that case?

Thanks,
Lars

**Comment by technoweenie** [comment]
Fixed in #861. Just didn't seem important enough for its own patch release.

**Comment by larsxschneider** [comment]
Great! Thanks :+1:
