### ISSUE TITLE
Enhance Git LFS status to show if Git LFS is installed or not

### ISSUE THREAD

**Issue by brabil** [github/git-lfs#901]
It would be more convenient for users to see if git lfs is installed or not in the "git lfs status" command output. 

Right now the only way is to check manually the .git/hooks/pre-push hook and the smudge filter settings in the git configurations using the command: git config --global --list | grep lfs

**Comment by technoweenie** [comment]
You can run `git lfs env` to see if the hooks are setup:

```bash
$ git lfs env
git-lfs/1.1.0 (GitHub; darwin amd64; go 1.5.1; git fbbfd7d)
git version 2.5.4 (Apple Git-61)

Endpoint (heroku)=https://git.heroku.com/technoweenie-lametric.git/info/lfs (auth=none)
LocalWorkingDir=/Users/rick/p/lametric-apps
LocalGitDir=/Users/rick/p/lametric-apps/.git
LocalGitStorageDir=/Users/rick/p/lametric-apps/.git
LocalMediaDir=/Users/rick/p/lametric-apps/.git/lfs/objects
TempDir=/Users/rick/p/lametric-apps/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
GIT_LFS_TEST_DIR=/Users/rick/p/git-lfs-temp
GIT_LFS_TEST_MAXPROCS=4
git config filter.lfs.smudge = "git-lfs smudge --skip %f"
git config filter.lfs.clean = "git-lfs clean %f"
```

The "git config" lines at the bottom show that LFS is setup. Does that cover what you need?

**Comment by PT-Matthewjernigan** [comment]
I'm still confused.  If I run `git lfs uninstall` the output of `git lfs env` does not change.  The `git config` lines are still there.

**Comment by bk2204** [comment]
If you're on Windows or are using the Debian-shipped packages, these are in the system configuration and you need to pass `--system` to `git lfs uninstall`.

**Comment by PT-Matthewjernigan** [comment]
Yes, on Windows.  While `git lfs uninstall --system` returns a different message (system instead of global), it doesn't change any env or config output.  Not even `git config --system --list`.

Anyhow, this is not something critical that must be solved.  I'll just instruct the users to run `git lfs install` regardless.  If they have other needs, they can work that out on their own.  I was just curious was the current state was and what to advise and why.

**Comment by PT-Matthewjernigan** [comment]
Correction: I'm working on two machines at once right now.  One has LFS v2.11.0, the other has v2.13.3.  They behave a bit different with the `--system` switch.  The newer version behaves more as expected with config output.  But, still seeing no changes in the env output.

**Comment by bk2204** [comment]
You can check where the options are set with `git config -l --show-origin`.  It's probably still set somewhere.
