### ISSUE TITLE
"Download zip" button doesn't get lfs files

### ISSUE THREAD

**Issue by explodecomputer** [github/git-lfs#903]
Sorry if this has been addressed already, I did a quick search but couldn't find anything. A repo with LFS data can be cloned with the LFS data being pulled down, but the the 'Download ZIP' button on github doesn't include the large files, only the pointers. e.g. [https://github.com/explodecomputer/Eur1000GenomesAut](https://github.com/explodecomputer/Eur1000GenomesAut).

The main reason I'm interested in this is some programmes rely on it, e.g. `install_github` in this repository: [https://github.com/hadley/devtools/blob/master/R/install-github.r](https://github.com/hadley/devtools/blob/master/R/install-github.r)

**Comment by gregmacfarlane** [comment]
I have the same issue.

**Comment by technoweenie** [comment]
This is an issue with GitHub, and not the open source Git LFS client. You can hit up GitHub support to ask us directly about it: https://github.com/contact

Keep in mind that Git LFS is an extension on top of Git, so it's completely expected that git tools need to be updated to take advantage of it.

**Comment by guillochon** [comment]
@technoweenie Are there any plans to make the zip button LFS-aware? I know it doesn't have to be, but it would be great if it was, and if we knew that was it was coming.

**Comment by javabrett** [comment]
>This is an issue with GitHub, and not the open source Git LFS client. You can hit up GitHub support to ask us directly about it: https://github.com/contact

**Comment by guillochon** [comment]
@javabrett: @techonoweenie is a GitHub employee...why is he directing us to the GitHub contact page? Shouldn't he be directing us to the appropriate GitHub issues page to bring this up officially?

**Comment by technoweenie** [comment]
@guillochon I directed you to the most appropriate spot to bring it up officially: https://github.com/contact. GitHub has a great Support team for handling this kind of stuff. They can put it on the appropriate radars for discussion, or so you can get a response from the correct person.

Clearly you all just want ANSWERS :) I'll do my best to answer these github.com questions in the future, but you'll likely get a more timely response from our support team. They can also bring the appropriate engineers in when necessary. Keep in mind, that I'm just one person, while we have a whole clowder of supportocats looking at the support queue.

> Are there any plans to make the zip button LFS-aware

I'd love to do this, but no plans as of yet. I agree it'd be a good idea, but I really want LFS to be more usable and reliable first ;)

**Comment by javabrett** [comment]
> Are there any plans to make the zip button LFS-aware

If this happens, it would be good if it were opt in/out (default unsure), so that there remains an option to obtain a zip of the lfs-unresolved repository (stored as it is in the git repo, with pointer files), without the large-files.

**Comment by billinghamj** [comment]
Perhaps this is a good sign that GitHub should have a more transparent & open way of receiving/discussing requests :)

**Comment by tareko** [comment]
Hello, I am still running into this issue and was wondering if there's any progress since it's been 18+ months since the last comments.

tarek : )

**Comment by ttaylorr** [comment]
Hi @tareko, thanks for checking in. Nothing yet.

**Comment by FunctionPoint** [comment]
Yes, please implement this feature.
Maybe as a checkbox setting per repository: "Include LFS files in ZIP download file?"  (Y/N)

**Comment by darionyaphet** [comment]
Hi, I'm also run int this problem.  Is there any progress?

**Comment by bk2204** [comment]
We don't have any news to announce on this front. As mentioned above, this is an issue with GitHub, not the Git LFS client, so it's best to reach out to GitHub's support team on this, since this repository is only for the Git LFS client, not GitHub.

**Comment by gnuton** [comment]
has anybody contacted of  github about this? if it's so can somebody link that issue here?

**Comment by Haffon** [comment]
"Download zip" actually download the ".gitattributes" file and you can observe any LFS file type and navigate with web browser to any Stored with Git LFS file in github, then click mouse right button on top of "view raw" link and select "Save link as" item with the popup menu, then you got the real file and not the pointer. May be it can automatic with some shell script.

**Comment by laurentopia** [comment]
if you want github to fix their crappy web code, click this https://support.github.com/contact

**Comment by GadgetAngel** [comment]
select the "Download or clone Button" and mouse right click on the "Download Zip" when the pop up window displays select "Save link as..." and save to you local drive. Now the ZIP file will have the whole repository in the zip file.

**Comment by PsykomantaBrain** [comment]
Adding my +1 to this issue. I wanted to use github to host some tutorial projects, but this is a bit of a dealbreaker, because these tutorials don't (shoudn't) expect the users to know how to work with git... And some of the project files are too large for non-lfs commits.

**Comment by PsykomantaBrain** [comment]
> select the "Download or clone Button" and mouse right click on the "Download Zip" when the pop up window displays select "Save link as..." and save to your local drive. Now the ZIP file will have the whole repository in the zip file. I do not understand why you have to use the "Save link as..." but if you just use the "Download ZIP" withOUT the mouse right click you will only get the pointer to the files in the ZIP file that is downloaded. So I now make it a practice to always mouse right-click on the "Download ZIP" button on git repositories

Tried it, doesn't work unfortunately.

**Comment by chrisd8088** [comment]
FWIW, here are some recent support [docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-git-lfs-objects-in-archives-of-your-repository) from GitHub on how to change your settings so LFS objects are included in Zip archive downloads.

**Comment by GadgetAngel** [comment]
> FWIW, here are some recent support [docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-git-lfs-objects-in-archives-of-your-repository) from GitHub on how to change your settings so LFS objects are included in Zip archive downloads.

Thank you for that information!

**Comment by Denis535** [comment]
> If you choose to include Git LFS objects in archives of your repository, every download of those archives will count towards bandwidth usage for your account
This is fantastic !!!
