### ISSUE TITLE
Git LFS extension command "git lfs install" does not work.

### ISSUE THREAD

**Issue by SlowhandFastfeet** [github/git-lfs#919]
After installing the software, the git extension command is not recognized.

Here is a picture with the error:

http://imgur.com/SjfCDXk

What to do?

Note: My operation system is Windows 7.

**Comment by technoweenie** [comment]
You can do this one of two ways:

1. You need that `C:\Program Files\Git\bin` folder to be in the system path.
2. You need to install `git-lfs.exe` in the directory that `git.exe` is in. Run `which git` to see where it's at.

**Comment by SlowhandFastfeet** [comment]
Did step 1.
Did step 2:
$ which git
/mingw32/bin/git
I removed from a different install location and installed it here. However, the git-lfs.exe did not ended here, but in \Git\cmd folder and in the \Git\bin folder as well.

$ git lfs install
fatal: 'lfs' appears to be a git command, but we were not
able to execute it. Maybe git-lfs is broken?

To try out to fix it manually, I copied the git-lfs.exe to the /mingw32/bin folder as well, but it did not help.

What now?

**Comment by technoweenie** [comment]
What's your system path look like? I think you can check this with `echo %PATH%`.

Unfortunately, this is more of an issue with your windows install, and not Git LFS specifically. Hopefully someone with Windows experience can give you some better help, and help us with the installer.

**Comment by SlowhandFastfeet** [comment]
I think I found the problem, it's that I installed the 64 bit package, and my OS is 32 bits. But that was only for the second problem, the first was solved with your help, ty.

$ git lfs install
Git LFS initialized.

Now it works.

**Comment by technoweenie** [comment]
@SlowhandFastfeet what fixed it, specifically?

**Comment by SlowhandFastfeet** [comment]
Well, there were 2 things:

First, the path needed to be added as you suggested, because after I added the error message changed, see above. (git did not recognize the command)

Second, the error was, that it could not run the command, but now it already recognized it. Once I downloaded the 32 bit version, and I unzipped into the folder, you pointed out using the "$ which git" command, it could execute the command.

The page where the install instructions are, is not detailed enough imo, fresh git users, will fall into the error, as they will try to install the 64bit version, while if they have 32 bit Windows, they should download that version from the download links, on top right. 

 I suggest if you can, add a note about this at the install instructions, for the rare case someone still uses 32bit Windows.

**Comment by Domvel** [comment]
Just reboot Windows. Has solved the problem in my case. 😄 
1. Install Git LFS.
2. Reboot
3. `git lfs install`
4. Be glad.
