### ISSUE TITLE
SUSE Linux Enterprise Server 11 (x86_64) binary

### ISSUE THREAD

**Issue by jpicau** [github/git-lfs#921]
I'm using a SGI NUMA hardware. The binary packages are maintained by SGI.
There is no go 1.5+ compiler available and gcc is only available with
version 'gcc (SUSE Linux) 4.3.4 [gcc-4_3-branch revision 152973]'.

I downloaded the 
https://github.com/github/git-lfs/releases/download/v1.1.0/git-lfs-linux-amd64-1.1.0.tar.gz
file. But I get a fatal error, a panic from (I suppose) the go 1.5 runtime.

jpi@hydra:~> git-lfs 
fatal error: procresize: invalid arg

runtime stack:
runtime.throw(0x954d40, 0x17)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/panic.go:527 +0x90
runtime.procresize(0x240, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/proc1.go:2691 +0xb0f
runtime.schedinit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/proc1.go:72 +0x110
runtime.rt0_go(0x7fffffffe0b8, 0x1, 0x7fffffffe0b8, 0x0, 0x0, 0x1, 0x7fffffffe48b, 0x0, 0x7fffffffe493, 0x7fffffffe4ae, ...)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:109 +0x132

Is there any chance, you could provide a binary package for this SUSE edition?

**Comment by technoweenie** [comment]
I'm afraid without go compilation support, this will be difficult. Does Go even run in this environment?

**Comment by jpicau** [comment]
Yeah, I was afraid you'd say that. I can't tell you if there is any golang support for this distribution.
I will have a look into that, but it will take some time ... 

PS: Git LFS is a great concept and otherwise it works fine. You all are doing a good job. Thanks!

**Comment by jpicau** [comment]
Okay, problem (somehow) solved. See: https://github.com/golang/go/issues/13908#issuecomment-170593790 It was the hard-coded maximum number of processes in the go compiler, which is 256. I changed it to 1024. Then I compiled the go compiler and then I compiled git-lfs. Then it worked.
