### ISSUE TITLE
How to determine the default lfs repo?

### ISSUE THREAD

**Issue by Gfurst** [github/git-lfs#923]
Hey folks, got a working setup with git-lfs and a private lfs-test-server.
It seems that lfs will default to github's hosting for the storage by default.
My question is, is this a hardcoded behavior or does it somehow figure out if the lfs host and git repo is in the same http server?

**Comment by technoweenie** [comment]
It's based on the git remote, but can be customized with `git config`:

https://github.com/github/git-lfs/blob/master/docs/spec.md#the-server

**Comment by Gfurst** [comment]
Ah ok, thanks @technoweenie
First I learned that .gitconfig is not going to be use anymore. I got confused with meaning of .gitconfig, it didn't really get included as configuration for the repo, right?

Still a bit confused as to how the client automates the server. In the example, the same https server serves both the git repo and the lfs host (and the website in this github case), authentication is done with same means. 
Is the .../info/lfs/ path a standard, so that lfs always looks there if no host is previously set up?

I really wish github also paid more attention to the server side and how to implement it on your own.

**Comment by technoweenie** [comment]
> I got confused with meaning of .gitconfig

It's deprecated in favor of `.lfsconfig`, but `.gitconfig` will be supported for the forseeable future (until Git LFS v2.0).

> Is the .../info/lfs/ path a standard, so that lfs always looks there if no host is previously set up?

Yup, inspired by similar `../info/*` urls that the git client uses.

> I really wish github also paid more attention to the server side and how to implement it on your own.

Here are some resources to help you:

* [api spec](https://github.com/github/git-lfs/tree/master/docs/api)
* [test server](https://github.com/github/lfs-test-server)

And some implementations: https://github.com/github/git-lfs/wiki/Implementations
