### ISSUE TITLE
Troubleshooting: git-lfs seems to not find files that it knows about.

### ISSUE THREAD

**Issue by vielmetti** [github/git-lfs#924]
I've installed `git-lfs` and am tracking a file:

```
Edwards-MacBook-Air:issuetracker emv$ git lfs track location.json
location.json already supported
Edwards-MacBook-Air:issuetracker emv$ git lfs track footprints.geojson
footprints.geojson already supported
```

However, when I try to do `git push origin master` I get this error message

```
Edwards-MacBook-Air:issuetracker emv$ git push origin master
Git LFS: (0 of 1 files, 1 skipped) 0 B / 952.08 KB, 952.08 KB skipped             
Counting objects: 57, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (43/43), done.
Writing objects: 100% (57/57), 99.05 MiB | 7.03 MiB/s, done.
Total 57 (delta 21), reused 45 (delta 9)
remote: warning: File maps/footprints.geojson is 98.12 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: e3180e92bbef1c114b6dcf09746de33e
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File a2civictech/aaata/log/location.json is 808.07 MB; this exceeds GitHub's file size limit of 100.00 MB
```

What do I need to do to troubleshoot this? (I'm happy to update the "Troubleshooting" section of the wiki to match suggestions.)

**Comment by technoweenie** [comment]
The `.gitattributes` file that `git lfs track` updates only activates on `git add` or `git checkout`. Did you `git add` those files after running `git lfs track`?  If you did, it's possible that the pattern isn't working like you think it should. This is why the docs suggest using file extensions. Unfortunately, the git docs aren't super clear on here, so we may need to show examples for common use cases.

You're going to have to amend some commits. There's a quick guide [here](https://help.github.com/articles/removing-files-from-a-repository-s-history/), but we should definitely have a guide for LFS users that aren't experienced with Git.

**Comment by vielmetti** [comment]
Thanks @technoweenie - this helped me make progress.

I downloaded the `bfg` tool based on instructions here https://rtyley.github.io/bfg-repo-cleaner/ and was able to clobber the biggest of the big files that had prevented `git push` from working at all (after saving a copy elsewhere). So I'm back to "working".

So `git lfs track` kicks in only when the file is added?

**Comment by technoweenie** [comment]
Yes, `git lfs track` only updates `.gitattributes` for you. We're piggy backing on the extension points that Git gives us. There's no way to replace an existing file without rewriting the repository history. But, changes to existing files will be stored in LFS, even if a previous version added before LFS exists.

**Comment by pmarsceill** [comment]
@technoweenie @vielmetti I ran into a similar scenario and used BFG to to "convert" the file (re-write history) in the repo.

Might be worth noting in the (docs)[https://help.github.com/articles/configuring-git-large-file-storage/] that after installing latest version of BFG all one needs to do is:

`$ bfg --convert-to-git-lfs ‘giant_file’`

**Comment by vielmetti** [comment]
Thanks @pmarsceill that's a super helpful command to know!
