### ISSUE TITLE
Runtime error on running git lfs clean 

### ISSUE THREAD

**Issue by Rudy-Tmc** [github/git-lfs#932]
Hi,

I've installed git lfs on Windows 7, let lfs track .zip files, added some zip files to the repo, pushed it to the server. Created a clone in another dir, there I've checked out the lfs files, and got the zips back.
Now I try to get the pointers back instead of the zips. So I use git-lfs clean, but get a runtime error:

```
D:\git\testrepo2>git-lfs clean mygreat.zip
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x4373b9]

goroutine 16 [running]:
runtime.panic(0x76da00, 0x9afde2)
        /opt/boxen/chgo/versions/1.3/src/pkg/runtime/panic.c:279 +0x11f
github.com/github/git-lfs/commands.requireStdin(0x82e570, 0x34)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:97 +0x49
github.com/github/git-lfs/commands.cleanCommand(0x9ae460, 0xc082000d20, 0x1, 0x1)
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/command_clean.go:18 +0x46
github.com/spf13/cobra.(*Command).execute(0x9ae460, 0xc082000d00, 0x1, 0x1, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:355 +0x183
github.com/spf13/cobra.(*Command).findAndExecute(0x9af660, 0xc082007cf0, 0x2, 0x2, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:334 +0xda
github.com/spf13/cobra.(*Command).Execute(0x9af660, 0x0, 0x0)
        /Users/rick/github/git-lfs/.vendor/src/github.com/spf13/cobra/command.go:408 +0x7b7
github.com/github/git-lfs/commands.Run()
        /Users/rick/github/git-lfs/.vendor/src/github.com/github/git-lfs/commands/commands.go:80 +0x31
main.main()
        /Users/rick/github/git-lfs/cmd/git-lfs/git-lfs.go:8 +0x21

goroutine 19 [finalizer wait]:
runtime.park(0x414b30, 0x9b4a38, 0x9b2ba9)
        /opt/boxen/chgo/versions/1.3/src/pkg/runtime/proc.c:1369 +0xac
runtime.parkunlock(0x9b4a38, 0x9b2ba9)
        /opt/boxen/chgo/versions/1.3/src/pkg/runtime/proc.c:1385 +0x42
runfinq()
        /opt/boxen/chgo/versions/1.3/src/pkg/runtime/mgc0.c:2644 +0xdd
runtime.goexit()
        /opt/boxen/chgo/versions/1.3/src/pkg/runtime/proc.c:1445
```

**Comment by technoweenie** [comment]
What does `git lfs version` say?

If I'm assuming the latest at v1.1.0, the panic is occurring [here](https://github.com/github/git-lfs/blob/cc90378df0387ced99c93aed00cc04850a244ae8/commands/commands.go#L97), which doesn't really make a lot of sense. Maybe it's a weird issue with the windows command prompt...

The main problem with what you're attempting though, is that `git lfs clean` is an internal command that you're using incorrectly. I'm not sure what you want with LFS pointers, but here's a couple ways to get the pointer for a given file:

```cli
# this ONLY outputs the pointer
$ git lfs pointer --file mygreat.zip

# this stores the file in .git/lfs/objects/... and outputs the pointer
# not sure this syntax works in the windows terminal though
$ cat mygreat.zip | git lfs clean
```

**Comment by Rudy-Tmc** [comment]
Hi,

It is indeed that latest v1.1.0 version.
I merely was trying to go back to the state of my workspace when I cloned it.
We have a huge repo, with large binary files, which we do not need all the time. So it might be convenient to be able to get the real file at some point, and also be able to only have a the LFS pointer once we not need the large file anymore. 

Rudy

**Comment by technoweenie** [comment]
You can use the `lfs.fetchinclude` and `lfs.fetchexclude` git options to specify paths you want downloaded by default, or ignored by default. Then you can use `git lfs fetch --include` or `git lfs fetch --exclude` if you do want the real file later.

Docs: https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-pull.1.ronn

**Comment by Rudy-Tmc** [comment]
Thanks
