### ISSUE TITLE
Authorization Error from Amazon Cloud

### ISSUE THREAD

**Issue by SkizzlePig** [github/git-lfs#936]
I'm getting an Authorization Error when pushing with git lfs

Here's a log snippet:

Authorization error: https://github-cloud.s3.amazonaws.com/alambic/media/117879268/62/74/6274a215e085bef1de34ded338fa151c92a2791ff063bf85b74bc3e566cbc99c?actor_id=12548121
Check that you have proper access to the repository

I'm not sure how to ensure I have proper access. It's my repository and git pushes before git lfs worked fine. 

I have paid for additional room from GitHub (50GB), so I'm not out of room.

Thoughts?

**Comment by SkizzlePig** [comment]
Nevermind on this ... I flattened my PSDs, so they fit under 100MB.  Deleted LFS

**Comment by technoweenie** [comment]
It's likely that you had a problem authenticating with Git LFS. I'd ask for `git lfs env` and maybe `git config -l` to see your current environment.
