### ISSUE TITLE
error: external filter git-lfs smudge %f failed

### ISSUE THREAD

**Issue by dkoudela** [github/git-lfs#940]
Hi,

I am getting an error when check-outing a previous revision (see below).

Could you please point me out where the problem is?

Thanks,
David.

$ git checkout efb1c6447f3c49499a87c38298d5ced454d4e34e
Downloading JArchitectOut/MyOwnNewFile.xml (22 B)
Error accessing media: JArchitectOut/MyOwnNewFile.xml (d9b006aa779cad15195d0d248a65550fa68ed372819d42ad444832633f241941)

Errors logged to .git/lfs/objects/logs/20160120T122754.008529717.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge %f failed 2
error: external filter git-lfs smudge %f failed
fatal: JArchitectOut/MyOwnNewFile.xml: smudge filter lfs failed

$ cat .git/lfs/objects/logs/20160120T122754.008529717.log
git-lfs/1.1.0 (GitHub; linux amd64; go 1.5.1; git 258acf1)
git version 2.7.0

$ git-lfs smudge JArchitectOut/MyOwnNewFile.xml
Error accessing media: JArchitectOut/MyOwnNewFile.xml (d9b006aa779cad15195d0d248a65550fa68ed372819d42ad444832633f241941)

relation does not exist
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.1.0/src/github.com/github/git-lfs/lfs/errors.go:557 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0x7fccf35411e8, 0xc8201241b8, 0x7fccf0cc3090, 0xc8203f34a0)
	/tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.1.0/src/github.com/github/git-lfs/commands/commands.go:184 +0xf7f
github.com/github/git-lfs/commands.logPanic(0x7fccf0cc3090, 0xc8203f34a0, 0x0, 0x0)
	/tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.1.0/src/github.com/github/git-lfs/commands/commands.go:148 +0x421
github.com/github/git-lfs/commands.handlePanic(0x7fccf0cc3090, 0xc8203f34a0, 0x0, 0x0)
	/tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.1.0/src/github.com/github/git-lfs/commands/commands.go:123 +0x4e
github.com/github/git-lfs/commands.LoggedError(0x7fccf0cc3090, 0xc8203f34a0, 0x95e2c0, 0x1e, 0xc820139c98, 0x2, 0x2)
	/tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.1.0/src/github.com/github/git-lfs/commands/commands.go:73 +0x82
github.com/github/git-lfs/commands.smudgeCommand(0xb61200, 0xc820011b50, 0x1, 0x1)
	/tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.1.0/src/github.com/github/git-lfs/commands/command_smudge.go:77 +0xd89
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xb61200, 0xc820011aa0, 0x1, 0x1, 0x0, 0x0)
	/tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.1.0/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x403
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xb62240, 0x0, 0x0)
	/tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.1.0/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x46a
github.com/github/git-lfs/commands.Run()
	/tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.1.0/src/github.com/github/git-lfs/commands/commands.go:88 +0x23
main.main()
	/tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.1.0/git-lfs.go:34 +0x12e

ENV:
LocalWorkingDir=.
LocalGitDir=.git
LocalGitStorageDir=.git
LocalMediaDir=.git/lfs/objects
TempDir=.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
GIT_DIR=.git
GIT_WORK_TREE=.
GIT_PREFIX=

**Comment by technoweenie** [comment]
The message, "relation does not exist", means the file doesn't exist on the server. Did you push the file successfully?

**Comment by dkoudela** [comment]
I see.
Not yet. I have a local copy since I just experiment with the lfs.

Does that mean I cannot go back to a previous commit until I push the changes to the remote server?

**Comment by technoweenie** [comment]
> Does that mean I cannot go back to a previous commit until I push the changes to the remote server?

Not necessarily. The smudge command will look in your `.git/lfs/objects` directory before checking the remote server. In your case, the file should be `.git/lfs/objects/d9/b0/d9b006aa779cad15195d0d248a65550fa68ed372819d42ad444832633f241941`.

**Comment by dkoudela** [comment]
Ok.

I have committed the changes and now it is working.
It looks like a bug but I cannot reproduce it now, so, I am closing the issue.

Thanks,
David.
