### ISSUE TITLE
Quiet Mode install on windows doesn't actually install

### ISSUE THREAD

**Issue by sinkingpoint** [github/git-lfs#941]
When running the amd64 installer (git-lfs-windows-amd64-1.1.0.exe) in quiet mode, i.e. `./git-lfs-windows-amd64-1.1.0.exe /S`), the installer doesn't actually seem to install anything. In fact, it seems that it just dumps an uninstaller to the Desktop and exits (The actual location is modifiable with the `/D` command line option of nsis scripts). This uninstaller, when run, gives a debug output which indicates only deleting itself indicating that the git-lfs.exe file is never created. I suspect this is because the installer script (https://github.com/github/git-lfs/blob/master/script/nsis/installer.nsi) only sets the `$INSTDIR` variable in the `onGUIInit` function, which is never called on a quiet installation. 

This logic should be moved out of this function, or at least call `SetOutDir $INSTDIR` inside the Section which outputs the git-lfs.exe file so as to respect the `/D` option properly.

**Comment by sinkingpoint** [comment]
This is possibly fixed by a new installer script in https://github.com/github/git-lfs/pull/875 . Is this going to be used going forwards (i.e. scrapping the nsis script)?

**Comment by technoweenie** [comment]
Yup. It's mostly ready to go, but we're trying to figure out the best way to pick where to install the tool, and set up the environment correctly.

**Comment by strich** [comment]
Yep will have it finished up shortly.

**Comment by technoweenie** [comment]
Should be good now with @strich's new windows installer in v1.1.1: https://github.com/github/git-lfs/releases/tag/v1.1.1

**Comment by sinkingpoint** [comment]
Cool. Just tested on Windows Server 2012 and seems to be working. Thanks for your work @strich and @technoweenie
