### ISSUE TITLE
git-lfs is 64 bit application

### ISSUE THREAD

**Issue by KOLANICH** [github/git-lfs#942]
Why there is no 32 bit version? I have to deal with really old systems without enough ram to tolerate overhead of 64 bit apps and OS.

**Comment by chiefk60** [comment]
Because the processor is not compatible with that 64




Sent from Samsung tablet.


-------- Original message --------

**Comment by chiefk60** [comment]
Oa funny if your pc is 64 don't play with 32 that is to all




Sent from Samsung tablet.


-------- Original message --------

**Comment by KOLANICH** [comment]
???

**Comment by chiefk60** [comment]
Ya you can zip codes for Windows you can run it in zip for mat





Sent from Samsung tablet.


-------- Original message --------

**Comment by chiefk60** [comment]
You don't now about zip windows wow

-------- Original message --------

**Comment by KOLANICH** [comment]
![troll_warning](https://cloud.githubusercontent.com/assets/240344/12478184/8ac169fe-c044-11e5-920f-d5b4e5276d08.jpg)

**Comment by chiefk60** [comment]
Funny still called Windows zip it will work for that working on roku 3 wow cool at this end

Sent from my HTC

----- Reply message -----

**Comment by chiefk60** [comment]
P.s because it is faster for the download

Sent from my HTC

----- Reply message -----

**Comment by chiefk60** [comment]
And read of updates

Sent from my HTC

----- Reply message -----

**Comment by technoweenie** [comment]
@KOLANICH You can pick up a 32-bit version from here: https://github.com/github/git-lfs/releases/tag/v1.1.0. They are the "386" releases.

**Comment by KOLANICH** [comment]
@technoweenie Ok, thanks. But I think that the website should also suggest them.

**Comment by chiefk60** [comment]
Ya no kidding

Sent from my HTC

----- Reply message -----

**Comment by technoweenie** [comment]
@KOLANICH Git LFS v1.1.1 comes with a Windows Installer that should work on 32-bit systems too: https://github.com/github/git-lfs/releases/tag/v1.1.1

**Comment by KOLANICH** [comment]
The website still suggests x64 version for 32bit Windows.
