### ISSUE TITLE
Preventing automatic LFS checkout/pull, etc. on GIT command

### ISSUE THREAD

**Issue by nkoterba** [github/git-lfs#950]
So we're trying to use GIT LFS to track some large data files.

However, the majority of time the file content is not needed and doesn't even need to be downloaded by LFS.  Our servers and network are not very fast, so downloading these files from LFS can take a looooooooong time.

We've noticed that if you `checkout` a branch and it has `LFS-tracked` files, those files will be checked out too and downloaded/fetched.

E.g.
```bash
$ git checkout testing_lfs
Downloading big.lfs.txt (34 B)
Checking out files: 100% (1441/1441), done.
Branch testing_lfs set up to track remote branch testing_lfs from origin.
Switched to a new branch 'testing_lfs'

$ cat big.lfs.txt 
Very big file (WOULD LIKE TO SEE FILE HASH HERE)
```

Is there any way to tell GIT LFS to **not** checkout all the LFS-tracked files but just leave them as pointers unless explicitly obtained by a user using `git lfs checkout`.

**Comment by technoweenie** [comment]
Check out the `lfs.fetchinclude` and `lfs.fetchexclude` git config settings: https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-config.5.ronn#L30.  You can put those in a `.lfsconfig` file so that all users of the repo have the same setup without having to configure anything after they clone.

**Comment by nkoterba** [comment]
@technoweenie :+1: Thanks! I must've skipped over the `lfs.fetchXXX` git config settings or interpreted them as files to exclude from LFS that might normally be tracked.  That should help our issue.

I will try out `lfs.fetchexclue = "*"` and let you know if I encounter any additional issues.

But I'm closing this issue assuming all is good.
