### ISSUE TITLE
Slow checkout on Windows

### ISSUE THREAD

**Issue by ygorlazaro** [github/git-lfs#958]
I am migrating some projects to use git-lfs, but checkouting is extremely slow. I am searching for some solution, like multithreading, but I haven't found any.

My system is a Windows 10 64bits, git 2.7 and git-lfs 1.1.0. It doesn't matter the remote is at GitHub or Visual Studio Online :cry:

**Comment by technoweenie** [comment]
Git LFS, in its default configuration, uses the git smudge filters for downloading. While it means you don't have to execute other commands to clone a repo down, it does mean that downloads happen one at a time. There is a `--skip-smudge` option for the [install command](https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-install.1.ronn). This doesn't download objects automatically, requiring you to run `git lfs pull` manually. The benefit here is that it downloads the files in parallel.

There are some Windows specific perf issues with Git LFS discussed in https://github.com/github/git-lfs/issues/931 as well.

**Comment by ygorlazaro** [comment]
I am trying with `--skip-smudge`, seems a bit better. I'll try at Linux with docker and see whats happens.`

**Comment by technoweenie** [comment]
Cool, closing this. Subscribe to #931 to see windows perf updates.
