### ISSUE TITLE
Can I delete the .git/lfs floder in my local Repository?

### ISSUE THREAD

**Issue by stoneStyle** [github/git-lfs#959]
there are too mush resouces in my repository,(about 50G +), before i push the respoitory to our git server, i track these resource in local, so it take much space, so my question is , after push to server, can i delete the lfs floder in local? or is there a way to save my space?
 
any advice is helpful, thankyou ~

**Comment by technoweenie** [comment]
Yes, you can, but any new git checkouts will require a fresh download. There is a [`prune` command](https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-prune.1.ronn) that can help you manage this directory. It has configurable rules for determining what objects to keep.

**Comment by stoneStyle** [comment]
it works~, thx~
