### ISSUE TITLE
Check that it exists and that you have proper access to it

### ISSUE THREAD

**Issue by adeptofvoltron** [github/git-lfs#961]
Hi. I got on my virtualhost gitlab installed. I try to push some pictures from local

git push origin master
after that I give my credentials

error I got:
Repository or object not found: http://localhost/root/test-lfs.git/info/lfs/objects/batch/objects
Check that it exists and that you have proper access to it

my "localhost" lead to vbox server.

on gitlab conf I have:
## Git LFS
 gitlab_rails['lfs_enabled'] = true
 gitlab_rails['lfs_storage_path'] = "/mnt/storage/lfs-objects"

I gave permission to the path "/mnt/storage/lfs-objects" 777 (yeah, i'm security master-but it's test server)

I will be glad to hear what's wrong.

**Comment by adeptofvoltron** [comment]
before u ask:
git-lfs/1.1.0 (GitHub; linux amd64; go 1.5.1; git 258acf1)

**Comment by technoweenie** [comment]
This repo is for the git-lfs client. You'll have to go to gitlab for help configuring the service.
