### ISSUE TITLE
Adding OSX Application Bundles

### ISSUE THREAD

**Issue by jlewin** [github/git-lfs#968]
What mechanism can be used to track OSX application bundles? I've tried a number of pattern matches and so far have not been able to pickup the .app directory and all its children

**Comment by strich** [comment]
This is probably more to do with Git itself - Git doesn't track folders directly, and technically an App Bundle is just a folder. You should be able to do a `git lfs track 'path/to/myapp.app/*'` to track the entire app bundle directory.

**Comment by technoweenie** [comment]
Yup, that should do it. Re-open if it doesn't work :)
