### ISSUE TITLE
Git smudge error preventing checkout

### ISSUE THREAD

**Issue by adcloeshelle** [github/git-lfs#970]
I have a feature branch that I tried enabling git lfs on. I merged the feature branch back into the main branch and tried to push. That wouldn't work so I just tried reverting everything. I got my main branch back to the latest commit upstream. However, I then tried to switch back to the feature branch but I'm getting the following error. This is preventing checkout of the feature branch and that's scaring me. Any ideas?

Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge %f failed 2
error: external filter git-lfs smudge %f failed
fatal: 3rdParty/GStreamer/gst_ios_init.h: smudge filter lfs failed

When looking at the logs, I see:
git lfs logs last
git-lfs/1.1.0 (GitHub; darwin amd64; go 1.5.1; git 258acf1)
git version 2.5.4 (Apple Git-61)

$ git-lfs smudge 3rdParty/GStreamer/gst_ios_init.h
Error accessing media: 3rdParty/GStreamer/gst_ios_init.h (d6134bc02d737975a403fd80b555afe0088d5e0bce65012cc245f39b99c7e9d7)

relation does not exist
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/errors.go:557 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0xd641c0, 0xc820072020, 0xd64ab0, 0xc8201283a0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:184 +0xf7f
github.com/github/git-lfs/commands.logPanic(0xd64ab0, 0xc8201283a0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:148 +0x421
github.com/github/git-lfs/commands.handlePanic(0xd64ab0, 0xc8201283a0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:123 +0x4e
github.com/github/git-lfs/commands.LoggedError(0xd64ab0, 0xc8201283a0, 0x55a620, 0x1e, 0xc820127c98, 0x2, 0x2)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:73 +0x82
github.com/github/git-lfs/commands.smudgeCommand(0x75d060, 0xc8200659f0, 0x1, 0x1)
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_smudge.go:77 +0xd89
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0x75d060, 0xc820065940, 0x1, 0x1, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x403
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0x75e0a0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x46a
github.com/github/git-lfs/commands.Run()
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:88 +0x23
main.main()
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:34 +0x12e

ENV:
LocalWorkingDir=.
LocalGitDir=.git
LocalGitStorageDir=.git
LocalMediaDir=.git/lfs/objects
TempDir=.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
GIT_DIR=.git
GIT_WORK_TREE=.
GIT_PREFIX=

**Comment by technoweenie** [comment]
That "relation does not exist" error when downloading means the server doesn't have the "d6134bc02d737975a403fd80b555afe0088d5e0bce65012cc245f39b99c7e9d7" object.

**Comment by adcloeshelle** [comment]
Is there a solution to fix this?

**Comment by technoweenie** [comment]
Upload the file. It should happen automatically on `git push`. Otherwise, you can run `git lfs push`. If you happen to be using GitHub.com, I can double check the server to see if it has that object.

**Comment by technoweenie** [comment]
Closing this. Feel free to re-open if you have further questions about this.
