### ISSUE TITLE
git lfs push --all <remote> falls back unexpectedly

### ISSUE THREAD

**Issue by sgoo** [github/git-lfs#973]
I'm not sure if this is like this because of #436 But its very strange an unexpected

When provided a remote URL `git lfs` wont use it. I've had a dig through the code and it seems it only supports configured git remotes.
That might be OK but the fallback in `git lfs push` is very confusing.

```
$ git lfs push --all http://sgoo@git-server.com/sgoo/test.git
```
results in the push happening against `origin`.

I would expect it to behave more like how `git lfs fetch` behaves:
```
$ git lfs fetch http://sgoo@git-server.com/sgoo/test.git --all
Invalid remote name "http://sgoo@git-server.com/sgoo/test.git"
```

**Comment by technoweenie** [comment]
Thanks for the report. You happened to catch me at the perfect time. Got a fix in #974 :)
