### ISSUE TITLE
Tracking folders with spaces in their names doesn't work

### ISSUE THREAD

**Issue by raffomania** [github/git-lfs#979]
Maybe I'm doing something wrong, but tracking folders with spaces in their names doesn't work for me.

e.g.

    git lfs track "Asset Sources"
    git add .

After this, according to `git lfs status`, git lfs still hasn't picked up the files in "Asset Sources".

The `.gitattributes` file seems to contain the correct pattern:

    Asset[[:space:]]Sources filter=lfs diff=lfs merge=lfs -text

Do you have any idea if this is a bug in git-lfs or if it's my fault?

**Comment by technoweenie** [comment]
Is `Asset Sources` a directory?  Try `git lfs track "Asset Sources/*"`. Git LFS is writing to the `.gitattributes` file correctly (yes, even with the `[[:space:]]`), but your pattern just isn't matching anything.

Git Attributes is a core git thing, so we have no control over how it works. However, I'd like to add examples for common things that people try to track besides just file extensions.

**Comment by raffomania** [comment]
Interesting! Adding the wildcard makes it work. Thanks for the hint!

I've already had some problems before with getting the patterns in `.gitattributes` right. If you're interested, I could definitely open a PR explaining the most common examples.

**Comment by technoweenie** [comment]
Yeah, I think even some examples in the `git lfs track` man page would go a long way.
