### ISSUE TITLE
Panic when fetching files from private repo

### ISSUE THREAD

**Issue by bcdonadio** [github/git-lfs#983]
I'm trying to fetch a private repo with some LFS files, but then I'm running in this error:

```
$ git-lfs smudge images/freeing-from-isp/antenna-12dbi.jpg
Error downloading object: images/freeing-from-isp/antenna-12dbi.jpg (1fac16f7e0c1b632e79ddaed0bdbc70958c6de66cf2fdbcbe484f5a11b7e4e36)

exit status 1
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/errors.go:557 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0x7f00906a01e8, 0xc8200262a8, 0x7f00906a0d00, 0xc8200eca30)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:184 +0xf7f
github.com/github/git-lfs/commands.logPanic(0x7f00906a0d00, 0xc8200eca30, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:148 +0x421
github.com/github/git-lfs/commands.handlePanic(0x7f00906a0d00, 0xc8200eca30, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:123 +0x4e
github.com/github/git-lfs/commands.LoggedError(0x7f00906a0d00, 0xc8200eca30, 0x96a3a0, 0x21, 0xc8200f5c98, 0x2, 0x2)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:73 +0x82
github.com/github/git-lfs/commands.smudgeCommand(0xb5cfa0, 0xc82000fbb0, 0x1, 0x1)
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_smudge.go:77 +0xd89
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xb5cfa0, 0xc82000fb00, 0x1, 0x1, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x403
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xb5dfe0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x46a
github.com/github/git-lfs/commands.Run()
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:88 +0x23
main.main()
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:34 +0x12e
```

Here is the clone with trace: http://pastebin.com/db5aiMe7
Here is the log: http://pastebin.com/ycdYErQ8

**Comment by technoweenie** [comment]
Your ssh attempt returned an error. Here's the relevant part from the first trace log:

> trace git-lfs: ssh: git@github.com git-lfs-authenticate bcdonadio/blog.git download 
> trace git-lfs: ssh: download attempted with git@github.com.  Error: exit status 1

What happens when you run ssh manually?

```bash
$ ssh git@github.com git-lfs-authenticate bcdonadio/blog.git download
```

You _should_ get a JSON object with `href` and `header` properties. Don't paste that for me :)

**Comment by bcdonadio** [comment]
Oh. I think I can paste that.
```
$ ssh git@github.com git-lfs-authenticate bcdonadio/blog.git download
Deploy keys can not access Git LFS objects on private repositories
```

I can't have a read-only key with LFS?

**Comment by technoweenie** [comment]
Ah, GitHub deploy keys don't work right now. It's on our list to fix.

**Comment by bcdonadio** [comment]
Ok, not an issue with git-lfs, but with the github deployment, then.
Closing this issue.

**Comment by adambutler** [comment]
@technoweenie Any update on this? I've checked my VCR cassettes into LFS because it was making pull-requests noisy but now I can't use Semaphore or any other CI.

**Comment by technoweenie** [comment]
Not yet.

**Comment by wlindley** [comment]
Are there any workarounds for this? It's a blocking issue for us that prevents us from transitioning to our repos to GitHub.

**Comment by technoweenie** [comment]
The only work around now is using another form of authentication, including user ssh keys, oauth tokens, or personal access tokens.  I'll post in here once deploy key support is active on github.com.

**Comment by wlindley** [comment]
Are there instructions somewhere for using personal access tokens in this way? I've heard that suggested elsewhere, but haven't been able to get it to work. I continue to get error messages about deploy keys.

**Comment by technoweenie** [comment]
Create one at https://github.com/settings/tokens and use it in place of your password.

**Comment by wlindley** [comment]
What about using it from a cloud CI system that would otherwise use a deploy key? I've read the docs on the personal access token page, but am still not able to auth from Travis. Git is still trying to use the deploy key it has rather than the credentials I'm supplying it.

**Comment by technoweenie** [comment]
Ah yes, you'll want to use an HTTPS git remote. Personal access tokens don't work over SSH.

**Comment by wlindley** [comment]
Hmm, that's still not working for me. I opened a support ticket, which might be a better place for this discussion. Although I'm also happy to continue here if that's preferable.

**Comment by technoweenie** [comment]
Deploy keys should work on github.com now. If not, send me details at https://github.com/contact so I can look into it. Or contact me there if you're interested in GitHub Enterprise.
