### ISSUE TITLE
Cannot download release, page lists 404

### ISSUE THREAD

**Issue by daniel-dressler** [github/git-lfs#984]
I am trying to download the git-lfs release from a japan IP but I am getting 404. Did something change about github's binary hosting policy?

**Comment by daniel-dressler** [comment]
This link worked: https://github.com/github/git-lfs/releases/download/v1.1.1/git-lfs-windows-amd64-1.1.1.zip

**Comment by red15** [comment]
:+1:

**Comment by technoweenie** [comment]
I updated the link to point to the new windows installer. Thanks for the report!
