### ISSUE TITLE
git lfs track path matching seems inconsistent

### ISSUE THREAD

**Issue by ashenkin** [github/git-lfs#986]
Hello all,

I want to track all files that match */large_files/* with lfs.  I have set the following with git lfs track:
```
$ git lfs track
Listing tracked paths
    large_files/*.* (.gitattributes)
    */large_files/*.* (.gitattributes)
    *large_files/* (.gitattributes)
    **/large_files/** (.gitattributes)
```

This (should be) overkill.  I would think that the last line `**/large_files/**` would suffice, if git lfs track follows gitignore's syntax (i.e. fnmatch(3), https://git-scm.com/docs/gitignore).  However, when I git add files in large_files subdirectories in different locations in the repo, some files are added whereas others are not.  I couldn't find documentation about git lfs track pattern matching.  I have tried combinations of the lines above, and just singly, but no joy.

Any help would be greatly appreciated.

**Comment by technoweenie** [comment]
All `lfs track` does is writes to `.gitattributes`. The actual file pattern matching is done by Git. I assumed it worked just like `gitignore` too.

In your example, do you have multiple `large_files` directories that you want to check? Do you want a single tracked pattern for the following?

* large_files/foo.zip
* project1/large_files/foo.zip
* project2/large_files/foo.zip

**Comment by ashenkin** [comment]
Hey Risk,

Yep, your example is what I'm after.

**Comment by dportabella** [comment]
I guess this ticket has been closed by mistake. It is not solved yet and I have the same issue.

**Comment by technoweenie** [comment]
`git lfs track "**/large/**/*` should do what you want. You can see the rules for how `gitattributes` interprets patterns in the [gitignore docs](https://git-scm.com/docs/gitignore).

**Comment by dportabella** [comment]
oh, I see thanks.

actually i wanted to track files in the `/files` directory. Adding the pattern `files` to `.gitignore` does ignore those files, so I tried the same pattern in for `git lfs track` but i didn't work. So, it seems that the rules are not exactly the same. However, the pattern `files/**` does work (both in `.gitignore` and `git lfs track`).

**Comment by technoweenie** [comment]
`git lfs track` simply writes the argument to `.gitattributes` with minor changes. Otherwise, Git LFS has no control over how Git interprets gitattributes patterns.  `**/large/**/*` worked on a `large/file.bin` file for me. Maybe it depends on your Git version?

**Comment by dportabella** [comment]
files filter=lfs diff=lfs merge=lfs -text

**Comment by technoweenie** [comment]
Huh, well the [gitattributes docs](https://git-scm.com/docs/gitattributes) are wrong then.

>  The rules how the pattern matches paths are the same as in .gitignore files; see [gitignore[5]](https://git-scm.com/docs/gitignore). Unlike .gitignore, negative patterns are forbidden.

**Comment by dportabella** [comment]
maybe it's just a corner case. my use case is solved, it's fine for me. ;)
thx!

**Comment by salzahrani** [comment]
still having the same problem!

**Comment by libor-m** [comment]
Just hit the same problem - I am used to having `data*` in `.gitignore`, which does not (try to) commit anything in directories starting with `data`, no matter how deep in the tree. Now I wanted to commit this kind of data to lfs, but removing `data*` from `.gitignore` and doing `git lfs track 'data*'` does not help. Neither does `git lfs track '**/data*/**/*'`.
