### ISSUE TITLE
can not push to git large file storage

### ISSUE THREAD

**Issue by PCRTM** [github/git-lfs#991]
I tried to upload big files to my github account utilizing git large file storage. Here are the steps I took:

git init
git lfs install
git lfs track *
git add *
git commit -m 'updated'
git remote add origin https://github.com/PCRTM/INPUTDIR.git
git push -u origin master

then after finishing compressing objects and writing objects, I got the error message:
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.

I think I am using the GIt Large File Storage. The instruction on https://git-lfs.github.com.
Can some one point out what I am doing wrong here?

**Comment by technoweenie** [comment]
Does `git lfs ls-files` show anything? If not, you haven't committed any files through git lfs. It's very possible that `git lfs track *` isn't doing what you want. I'm not sure offhand what you need in `.gitattributes` to run every file through LFS. Maybe `*.*`, or `**/*.*` ?

**Comment by PCRTM** [comment]
Thanks. I finally got it straight. I guess that I can not git lfs track directories. I have to go down the directory and set up .gitattributes there.

**Comment by technoweenie** [comment]
You can, but you'll have to track it like `git lfs track "dir/*"`.

**Comment by xuekunguo** [comment]
to technoweenie and PCRTM:

PCRTM is right. You have to go down the directory and set up .gitattributes there.

**Comment by technoweenie** [comment]
Not necessarily:

```bash
$ cat .gitattributes
dir/* filter=lfs diff=lfs merge=lfs -text
*.bin filter=lfs diff=lfs merge=lfs -text
```

Here's how I triggered it:

```bash
$ echo "not lfs" > not-lfs.txt
$ echo "lfs" > lfs.bin
$ mkdir dir
$ echo "dir lfs" > dir/lfs.txt

# ADD AND COMMIT
$ git add .
$ git status -sb
## master
A  dir/lfs.txt
A  lfs.bin
A  not-lfs.txt

$ git commit -m "lfs"
[master e88bbad] lfs
 3 files changed, 7 insertions(+)
 create mode 100644 dir/lfs.txt
 create mode 100644 lfs.bin
 create mode 100644 not-lfs.txt

$ git show
commit e88bbadabff4bfb21fa8240fd9845ccd640377ae
Author: risk danger olson <technoweenie@gmail.com>
Date:   Thu May 12 07:54:17 2016 -0600

    lfs

diff --git a/dir/lfs.txt b/dir/lfs.txt
new file mode 100644
index 0000000..cfbb6ea
--- /dev/null
+++ b/dir/lfs.txt
@@ -0,0 +1,3 @@
+version https://git-lfs.github.com/spec/v1
+oid sha256:55530932b1b62d81901ed2276458f34abdcc909b99f79929d4b226affb6695d4
+size 8
diff --git a/lfs.bin b/lfs.bin
new file mode 100644
index 0000000..29f92d5
--- /dev/null
+++ b/lfs.bin
@@ -0,0 +1,3 @@
+version https://git-lfs.github.com/spec/v1
+oid sha256:64fc7da9eafea5e011f98d6cce8340fd7e812ce81a92259413d2f8b527c84f8c
+size 4
diff --git a/not-lfs.txt b/not-lfs.txt
new file mode 100644
index 0000000..5015bde
--- /dev/null
+++ b/not-lfs.txt
@@ -0,0 +1 @@
+not lfs
```

You can see the lfs pointers for `lfs.bin` and `dir/lfs.txt`.

**Comment by jfoclpf** [comment]
@technoweenie 

The command `git lfs ls-files` list the files
```
$ git lfs ls-files
77f4c33c28 * test/users_insertions.json
```

but when `git push --force`

```
$ git push --force
Uploading LFS objects: 100% (1/1), 171 MB | 0 B/s, done                                                                                                                                                     
Counting objects: 6325, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (1837/1837), done.
Writing objects: 100% (6325/6325), 27.20 MiB | 305.00 KiB/s, done.
Total 6325 (delta 4540), reused 5429 (delta 4424)
remote: Resolving deltas: 100% (4540/4540), completed with 87 local objects.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: c6c271ac8f5f9a36e744c76c5a80a5a8
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File test/users_insertions.json is 162.92 MB; this exceeds GitHub's file size limit of 100.00 MB
To github.com:jfoclpf/autocosts.git
 ! [remote rejected]   master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@github.com:jfoclpf/autocosts.git'
```

I had already the big file in the history, and added _before_ installed `git lfs` 

And now my repo is a mess :)

**Comment by ttaylorr** [comment]
Hi @jfoclpf I'm sorry that you were having issues and I'm glad that you were able to resolve your issue. I think that what was going on here was a case of having a dangling, should-be-but-isn't-actually a pointer file exceeding 100 MiB in size _somewhere_ in your history.

Git LFS's built-in migration command (`git lfs migrate`) has a built-in (set of) option(s) for this:

```ShellSession
$ git lfs migrate import --fixup --everything
$ git push --all --force
```

With `--fixup`, `git lfs migrate` will read your `.gitattributes` file at each point in history, and determine which files fall into the above bucket: should be pointers, but aren't. `git lfs migrate` will automatically promote your files into the right state, and you can repeat this over all history with `--everything`.

Since this issue is quite old, and has been stale/closed recently, I'll suggest that if you have any issues or questions in the future that you open a new issue; we'd be more than happy to help you there. Thanks!

**Comment by jfoclpf** [comment]
Thank you very much
