### ISSUE TITLE
How to let other people download large files on the git large file storage?

### ISSUE THREAD

**Issue by PCRTM** [github/git-lfs#992]
How to let other people download large files on the git large file storage?  

By using 'Donwload zip', you can only get pointer files.

**Comment by technoweenie** [comment]
You can't. This GitHub feature doesn't support LFS. Also, this repository is for the open source git lfs project. 

Feel free to contact us at https://github.com/contact if you want to talk further. But the short answer is that this is something we'd like to do, but there are some considerable technical challenges to solve.
