### ISSUE TITLE
Tracking a single file doesn't work.

### ISSUE THREAD

**Issue by glebkuznetsov** [github/git-lfs#994]
Hello, I want to track a single large file > 100 Mb. However git lfs doesn't seem to be recognizing it.

1. Tell lfs to track my large file:

        $ git lfs track mylargefile.txt
        
        Tracking mylargefile.txt

2. See what lfs is actually tracking. This fails.

        $ git lfs ls-files

        (nothing)

I then tried commiting and pushing anyway:

    $ git add mylargefile.txt
    $ git add .gitattributes
    $ git commit -m "My large file"
    $ git push origin master

        (0 of 0 files) 0 B 0                                                                                                                                                                 
    Counting objects: 4, done.
    Delta compression using up to 4 threads.
    Compressing objects: 100% (4/4), done.
    Writing objects: 100% (4/4), 5.48 MiB | 1.36 MiB/s, done.
    Total 4 (delta 2), reused 0 (delta 0)
    remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
    remote: error: Trace: 385b97b5a926c5bc7d2ff1eef860d3b1
    remote: error: See http://git.io/iEPt8g for more information.
    remote: error: File mylargefile.txt is 100.94 MB; this exceeds GitHub's file size limit of 100.00 MB
    To git@github.com:churchlab/fix-recoli-1.git
     ! [remote rejected] master -> master (pre-receive hook declined)
    error: failed to push some refs to 'git@github.com:churchlab/fix-recoli-1.git'

It's likely my mental model of how this should work is wrong. Any advice?

**Comment by technoweenie** [comment]
I think your mental model may be wrong here, due to the current state of lfs docs. The `track` command simply adds an entry to `.gitattributes`. LFS has no control over when or how git attributes works though. Basically, it will tell git to run files through `git lfs clean` when they are _added to the git repository_. So if you previously added a file before tracking it, it is still added as a regular git file, and not an LFS file.

Here's an annotated transcript of me adding a file by name using Git LFS:

```bash
$ git init
Initialized empty Git repository in /Users/rick/lfs-test/.git/
$ git lfs track "foo.dat"
Tracking foo.dat
$ echo "hi" > foo.dat

# `git lfs ls-files` shows nothing because nothing is committed yet
# `git lfs status` shows nothing because nothing is added to the git index

$ git add .gitattributes foo.dat

# now `git lfs status` will show the file, but not `git lfs ls-files`

$ git commit -m "initial"
[master (root-commit) 0b07136] initial
...

# `git lfs status` shows nothing because the working directory is clean and committed
# `git lfs ls-files` will show the file now that it's committed
```

**Comment by glebkuznetsov** [comment]
Hmm.. I tried reproducing and it didn't work for me:

    gleb@glebs-mbp:~/Desktop$ mkdir lfstest
    gleb@glebs-mbp:~/Desktop$ cd lfstest/
    gleb@glebs-mbp:~/Desktop/lfstest$ git init
    Initialized empty Git repository in /Users/gleb/Desktop/lfstest/.git/
    gleb@glebs-mbp:~/Desktop/lfstest$ git lfs track "foo.dat"
    Tracking foo.dat
    gleb@glebs-mbp:~/Desktop/lfstest$ echo "hi" > foo.dat
    gleb@glebs-mbp:~/Desktop/lfstest$ git add .gitattributes foo.dat
    gleb@glebs-mbp:~/Desktop/lfstest$ git lfs status
    On branch 

    Git LFS objects to be committed:


    Git LFS objects not staged for commit:


    gleb@glebs-mbp:~/Desktop/lfstest$ git lfs ls-files`
    > 
    gleb@glebs-mbp:~/Desktop/lfstest$ git lfs ls-files
    gleb@glebs-mbp:~/Desktop/lfstest$ git commit -m "initial"
    [master (root-commit) 83e2e53] initial
     2 files changed, 2 insertions(+)
     create mode 100644 .gitattributes
     create mode 100644 foo.dat
    gleb@glebs-mbp:~/Desktop/lfstest$ git lfs ls-files
    gleb@glebs-mbp:~/Desktop/lfstest$ 

I'm running

    gleb@glebs-mbp:~/Desktop/lfstest$ git version
    git version 2.1.2

**Comment by technoweenie** [comment]
First, Git LFS v0.5.4 is _ancient_. You should upgrade :) What does `git lfs env` say? Or `git config -l | grep lfs`? If you don't have the git filters setup globally (done through `git lfs init`, or `git lfs install` in current versions of LFS), then none of this will work.

**Comment by glebkuznetsov** [comment]
Brilliant.

I updated my version of Git LFS. I had installed using `brew install git-lfs` earlier today and assumed it gave me the latest version, but I guess my sources were out of date, so I ran `brew upgrade git-lfs` to fix that.

Then I ran `git lfs install`. Somehow missed that in the docs and didn't think it was a problem since git lfs commands were not throwing errors (even though they were not working correctly).

Now everything works as expected!

Thanks a lot for your help. I tried finding a thread like this earlier, but was unable to.

**Comment by Mehul-Mobiquity** [comment]
@technoweenie I have tried your suggestion but If I add only filename instead of path for file I got the file listed in git-lfs. But not again after several tries. Can you help me here?

**Comment by ttaylorr** [comment]
@Mehul-Mobiquity Can you post the steps that you took in order to make this happen? I'd be more than happy to help out 😄

**Comment by Mehul-Mobiquity** [comment]
@ttaylorr I following the steps provided by @technoweenie here and at https://github.com/github/git-lfs.  
```1. When I use the command $ git lfs track "ArcGIS.framework" or "Path/To/File.framework" it add them to track-list. 
2. After that used $ git add .gitattributes "ArcGIS.framework" it failed to do that but succeed if I add $ git add .gitattributes "Path/To/File.framework". 
- But as @technoweenie mentioned it will show you on use of below command but not displaying any tracked object.
# now `git lfs status` will show the file, but not `git lfs ls-files` ```

I'm running

```
*git lfs version*
git-lfs/1.0.2 (GitHub; darwin amd64; go 1.5.1; git 0566698)
git version 2.7.4 (Apple Git-66)
```

Can you help out where I am making mistakes?

**Comment by larsblumberg** [comment]
@Mehul-Mobiquity I also couldn't get it to work with your version of git-lfs 1.0.2. What helped for me was first updating brew:

`brew update`

and then update `git-lfs`

`brew upgrade git-lfs`

Finally, after updated to git-lfs version `1.3.1` I was able to use it.
