### ISSUE TITLE
Doesn't work on Linux, but works fine on OS X

### ISSUE THREAD

**Issue by cjbottaro** [github/git-lfs#997]
Sorry in advance if this is just a user type question, but after a couple of hours of digging around...

On OS X, I installed git-lfs, tracked some binaries on some branch, checked them in, pushed, all is good.  If I do a fresh clone of the repo, then checkout the branch that has the binaries, git-lfs automatically downloads them and all is good.

Great, time to deploy to a Linux host.  It doesn't work.  Fresh clone of the repo, checkout the branch with the binaries, git-lfs *does not* download them.  Fine, I'll do `git lfs pull` manually.  That works, _but_ now git considers them "modified":  http://d.pr/i/AOfa  and that breaks my deployment process.

That's my story.  Here's some technical info:

```
$ git lfs env
git-lfs/1.1.1 (GitHub; linux amd64; go 1.5.3; git 7de0397)
git version 2.7.1

Endpoint=https://github.com/AcademicWorks/user_app.git/info/lfs (auth=none)
  SSH=git@github.com:AcademicWorks/user_app.git
LocalWorkingDir=/home/rails/user_app2
LocalGitDir=/home/rails/user_app2/.git
LocalGitStorageDir=/home/rails/user_app2/.git
LocalMediaDir=/home/rails/user_app2/.git/lfs/objects
TempDir=/home/rails/user_app2/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
git config filter.lfs.smudge = "git-lfs smudge %f"
git config filter.lfs.clean = "git-lfs clean %f"
```

```
$ git lfs env
git-lfs/1.1.1 (GitHub; darwin amd64; go 1.5.3)
git version 2.7.0

Endpoint=https://github.com/AcademicWorks/user_app.git/info/lfs (auth=none)
  SSH=git@github.com:AcademicWorks/user_app.git
LocalWorkingDir=/Users/cjbottaro/Work/overlord/user_app
LocalGitDir=/Users/cjbottaro/Work/overlord/user_app/.git
LocalGitStorageDir=/Users/cjbottaro/Work/overlord/user_app/.git
LocalMediaDir=/Users/cjbottaro/Work/overlord/user_app/.git/lfs/objects
TempDir=/Users/cjbottaro/Work/overlord/user_app/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
git config filter.lfs.smudge = "git-lfs smudge %f"
git config filter.lfs.clean = "git-lfs clean %f"
```

**Comment by jekriske-lilly** [comment]
:+1:  Exact same issue here.

**Comment by technoweenie** [comment]
Gah, sorry for the missed reply. It sounds like your repo isn't tracking the files properly. I need more info to help though. 

* What does `.gitattributes` look like? LFS will only automatically download files if Git matches the file path to a pattern in `.gitattributes`. 
* If files show up modified with no visible changes in `git diff`, it's likely that the change is simply going from a normal git blob with binary data, to a git blob with an LFS text pointer.

Can you replicate this in a dummy repository so I can take a look?

**Comment by cjbottaro** [comment]
Shoot, I figured out my issue and forgot to post here.

I think it's due to some change in git and/or git lfs version.  Previously, having `vendor/cache` in `.gitattributes` was working, but now I have to say something like `vendor/cache/*` or `vendor/cache/*.gem`.

**Comment by cjbottaro** [comment]
Some more info, updating git/git-lfs on my Mac caused the same issue to happen as was happening in Linux.  Thus I don't think this is a Linux vs OS X issue at all, but rather a version compatibility issue with git.

**Comment by technoweenie** [comment]
Well, LFS has nothing to do with how `.gitattributes` is parsed. But we can sure do better about helping people use `lfs track` better :) Thanks for replying!

**Comment by jekriske-lilly** [comment]
for me the .gitattributes file is correct and I can't reproduce it with new repos (exact same .gitattributes). On the repo in question, there's no pre-push hook so maybe there's something else going on or other items are missing. Like the above post, it pulls automatically just fine on the mac but not on Linux. However, a brand new repo works fine.

**Comment by technoweenie** [comment]
@jekriske-lilly What's in your `.gitattributes`? What file paths are not downloading stuff properly? What are the errors? Have you confirmed that the server is storing the files properly?

Git hooks (like pre-push) have to be installed per local repository. Git LFS will automatically check for and add it when commands like `git lfs track` are run. If it's not there, you can run `git lfs update` to add it.  A pre-push hook ensures that LFS files have been successfully uploaded before any Git commits have been pushed.

**Comment by jekriske-lilly** [comment]
gitattributes contains:
*.Rdata filter=lfs diff=lfs merge=lfs -text

I've confirmed the file uploaded correctly because a git lfs pull results in downloading a file with identical sha256sum

the gitattributes is in the project root directory and the file not downloading is in ./data/filename.Rdata

There are no errors on git clone. It simply thinks that it's complete and doesn't pull the lfs file until I manually type git lfs pull.

**Comment by technoweenie** [comment]
Is it possible that the filesystems on your mac and linux systems treat mixed-case filenames differently? Maybe this is an issue with how Git uses `.gitattributes` to filter filenames. I'd recommend using the `skip-smudge` option of [`git lfs install`](https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-install.1.ronn), which disables the smudge hook. It does mean you'll have to run `git lfs pull` manually, though. You will see a noticeable speed boost for large download operations.

**Comment by jekriske-lilly** [comment]
I'll try this out, thanks!

**Comment by jekriske-lilly** [comment]
Ahh, you were absolutely correct about the mixed case. The file extension is actually RData not Rdata. Making that change in the gitattributes file fixed everything.
